import {Text,useTheme,Palette} from "../theme";
import React,{useEffect,useRef,useState} from 'react';
import {Modal,View,TextInput,Pressable,ScrollView,KeyboardAvoidingView,Platform,Image,StyleSheet} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {router,useLocalSearchParams} from 'expo-router';
import * as Crypto from 'expo-crypto';
import {api,imageUrl} from '../api';
import documents from '../help-documents.json';
export default function Help(){
 const {colors}=useTheme(); const s=styles(colors);
 const {topic='contact',orderReference='',request='',name='',email=''}=useLocalSearchParams<{topic:string;orderReference:string;request:string;name:string;email:string}>();
 const [settings,setSettings]=useState<Record<string,string>>({}),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[reference,setReference]=useState('');
 const [form,setForm]=useState({name,email,phone:'',orderReference,category:'order',subject:request==='cancellation'?'Cancellation request':'',message:request==='cancellation'?`Please cancel order ${orderReference}. Reason: `:''});
 const requestId=useRef(Crypto.randomUUID());
 useEffect(()=>{api<{checkout:Record<string,string>}>('/api/catalog').then(r=>setSettings(r.checkout)).catch(()=>setStatus('Could not load the latest delivery policy. Please retry.'));},[]);
 const close=()=>router.back();
 const titles:Record<string,string>={about:'About Vanta Noir',contact:'Here to help','shipping-returns':'Shipping & returns','privacy-policy':'Your privacy','terms-of-service':'Shopping with Vanta Noir'};
 const field=(key:'name'|'email'|'phone'|'orderReference'|'subject'|'message',label:string)=><View style={{gap:7}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={form[key]} onChangeText={v=>setForm(f=>({...f,[key]:v}))} autoCapitalize={key==='email'?'none':'sentences'} keyboardType={key==='email'?'email-address':key==='phone'?'phone-pad':'default'} multiline={key==='message'} maxLength={key==='message'?4000:160} style={[s.input,key==='message'&&{height:150,textAlignVertical:'top'}]}/></View>;
 const submit=async()=>{if(busy)return;if(form.name.trim().length<2||!/^\S+@\S+\.\S+$/.test(form.email.trim())||form.subject.trim().length<3||form.message.trim().length<10){setStatus('Enter your name, valid email, subject and a message of at least 10 characters.');return;}setBusy(true);setStatus('');try{const r=await api<{reference:string}>('/api/support',{...form,requestId:requestId.current,website:'',serious:false});setReference(r.reference);}catch(e){setStatus(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
 const sections=documents[topic as keyof typeof documents]||[];
 return <Modal visible animationType="slide" onRequestClose={close}><SafeAreaProvider><SafeAreaView style={s.page}><View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={close} style={s.back}><Text style={s.title}>‹</Text></Pressable><Text style={s.title}>{titles[topic]||'Here to help'}</Text></View><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>
 <Text style={s.brand}>VANTA NOIR</Text>
 {status!==''&&<Text accessibilityLiveRegion="polite" style={s.notice}>{status}</Text>}
 {topic==='about'&&<Image source={{uri:imageUrl('/images/vanta-noir-emblem-960.webp')}} style={{width:180,height:180,alignSelf:'center',borderRadius:90}}/>}
 {sections.map((section,i)=><View style={s.card} key={i}><Text style={s.title}>{section.title}</Text><Text style={s.body}>{section.body}</Text></View>)}
 {topic==='shipping-returns'&&[['Preparation',settings.processingNote],['Collection',settings.dispatchNote],['Delivery estimates',settings.deliveryNote],['Delivery policy',settings.deliveryPolicy],['Returns, exchanges & refunds',settings.returnPolicy]].map(([title,body])=>body?<View style={s.card} key={title}><Text style={s.title}>{title}</Text><Text style={s.body}>{body}</Text></View>:null)}
 {topic==='contact'&&(reference?<View style={s.card}><Text style={s.title}>Message received</Text><Text style={s.body}>Your enquiry is in our customer-care inbox. Our team will reply by email.</Text><Text selectable style={s.label}>{reference}</Text><Pressable style={s.button} onPress={close}><Text style={s.label}>Back to the app</Text></Pressable></View>:<View style={s.card}><Text style={s.title}>How can we help?</Text><Text style={s.body}>{request==="cancellation"?"Tell us why you want to cancel. Customer care will confirm whether cancellation is still possible and arrange any applicable refund. Sending this request does not cancel the order immediately.":"Send your question here. Include your order reference if you have one."}</Text>{field('name','Your name')}{field('email','Email address')}{field('phone','Phone (optional)')}{field('orderReference','Order reference (optional)')}<Text style={s.label}>Topic</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{['order','delivery','payment','return','sizing','product','privacy','other'].map(category=><Pressable accessibilityRole="button" accessibilityState={{selected:form.category===category}} key={category} style={[s.chip,form.category===category&&{backgroundColor:colors.selected}]} onPress={()=>setForm(f=>({...f,category}))}><Text style={s.label}>{category.charAt(0).toUpperCase()+category.slice(1)}</Text></Pressable>)}</View>{field('subject','Subject')}{field('message','Message')}<Text style={s.body}>Please don’t include card details, passwords or sign-in codes.</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()} style={s.button}><Text style={[s.label,{color:"#182214"}]}>{busy?'Sending…':'Send message'}</Text></Pressable></View>)}
 {topic!=='contact'&&<Pressable style={s.button} onPress={()=>router.setParams({topic:'contact'})}><Text style={s.label}>Contact customer care →</Text></Pressable>}
 </ScrollView></KeyboardAvoidingView></SafeAreaView></SafeAreaProvider></Modal>;
}
const styles=(colors:Palette)=>StyleSheet.create({page:{flex:1,backgroundColor:colors.page},header:{flexDirection:'row',alignItems:'center',gap:12,padding:12,backgroundColor:colors.surface,borderBottomWidth:1,borderColor:colors.border},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontSize:21,fontWeight:'600',color:colors.text},brand:{letterSpacing:4,fontSize:13,color:colors.muted},content:{padding:20,gap:18,paddingBottom:40,maxWidth:760,width:'100%',alignSelf:'center'},card:{padding:20,gap:14,backgroundColor:colors.glass,borderRadius:24,borderWidth:1,borderColor:colors.border,boxShadow:'0 8px 24px rgba(35,51,29,0.07)'},body:{fontSize:15,lineHeight:24,color:colors.muted},label:{fontSize:14,fontWeight:'600',color:colors.text},input:{borderWidth:1,borderColor:colors.border,borderRadius:15,padding:14,fontSize:16,minHeight:50,color:colors.text,backgroundColor:colors.input},chip:{padding:12,borderRadius:16,backgroundColor:colors.secondary,minHeight:44},button:{backgroundColor:'#c9f774',padding:17,borderRadius:25,minHeight:50,alignItems:'center'},notice:{padding:15,backgroundColor:colors.notice,borderRadius:15,color:colors.text}});
