const {spawn}=require('node:child_process');const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--config','portable/vite.config.ts','--host','127.0.0.1','--port','5186']);let browser;try{
 await new Promise((resolve,reject)=>{server.stdout.on('data',b=>{if(b.toString().includes('127.0.0.1:'))resolve();});server.on('exit',c=>reject(Error('server '+c)));});
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox']});
 for(const width of [390,820,1180]){const page=await browser.newPage({viewport:{width,height:900},colorScheme:'dark'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5186/tests/browser/admin-editing.html');
 await page.getByRole('button',{name:'Edit',exact:true}).waitFor();assert.equal(await page.getByLabel('Pickup city').count(),0);
 await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Pickup city').fill('Zaria');assert.equal(await page.evaluate(()=>window.__writes.length),0);
 await page.getByRole('button',{name:'exit',exact:true}).click();await page.evaluate(()=>window.__fail=true);await page.getByRole('button',{name:'Save and exit',exact:true}).click();await page.getByRole('alertdialog').getByRole('alert').waitFor();assert.equal(await page.getByRole('heading',{name:'Exited'}).count(),0);
 await page.evaluate(()=>window.__fail=false);await page.getByRole('button',{name:'Save and exit',exact:true}).click();await page.getByRole('heading',{name:'Exited'}).waitFor();await page.getByRole('button',{name:'pickup',exact:true}).click();await page.getByRole('button',{name:'Edit',exact:true}).click();assert.equal(await page.getByLabel('Pickup city').inputValue(),'Zaria');await page.getByLabel('Pickup city').fill('Kaduna');await page.getByRole('button',{name:'Save pickup details'}).click();await page.getByLabel('Pickup city').waitFor({state:'detached'});
 await page.getByRole('button',{name:'settings',exact:true}).click();const support=page.getByRole('textbox',{name:'Customer support email'});await support.waitFor();assert(await support.isDisabled());await page.getByRole('button',{name:'Edit',exact:true}).click();await support.fill('new@example.com');await page.getByRole('button',{name:'Save',exact:true}).first().click();await page.getByRole('button',{name:'Edit',exact:true}).waitFor();assert(await support.isDisabled());
 await page.getByRole('button',{name:'prices',exact:true}).click();const price=page.getByRole('spinbutton',{name:'Price for Test garment'});await price.waitFor();assert(await price.evaluate(e=>e.readOnly));await page.getByRole('button',{name:'Edit',exact:true}).click();await price.fill('20000');await page.getByRole('button',{name:'exit',exact:true}).click();await page.getByRole('button',{name:'Save and exit',exact:true}).click();await page.getByRole('heading',{name:'Exited'}).waitFor();
 assert.deepEqual(errors,[]);console.log('PASS editing, failed save retention, save-and-exit and collapsed pickup at',width);await page.close();}
 }finally{await browser?.close();server.kill('SIGTERM');}})().catch(e=>{console.error(e);process.exitCode=1;});
