const {assertGlass,assertLime}=require('./glass-assertions.cjs');
const{spawn}=require('node:child_process'),{chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const s=spawn(process.execPath,['node_modules/vite/bin/vite.js','--config','portable/vite.config.ts','--host','127.0.0.1','--strictPort','--port','5203']);let b;try{await new Promise((r,j)=>{s.stdout.on('data',d=>{if(String(d).includes('127.0.0.1:'))r()});s.on('exit',j)});b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox']});let errors=[];const p=await b.newPage();p.on('pageerror',e=>errors.push(e.message));await p.route('**/images/**',r=>{let path='public'+new URL(r.request().url()).pathname;return fs.existsSync(path)?r.fulfill({path}):r.abort()});
for(const role of ['owner','sales','support','fulfilment','catalogue','analyst']){await p.setViewportSize({width:1440,height:1000});await p.goto('http://127.0.0.1:5203/tests/browser/portal-audit.html?role='+role);await p.waitForTimeout(700);assert.equal(await p.locator('.vn-control-center').first().evaluate(e=>getComputedStyle(e).colorScheme),'light',role+' colour scheme');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),role+' desktop overflow');if(role==='owner'){
 await assertGlass(p.locator('.vn-workspace-bar'),'Admin toolbar');
 await assertGlass(p.locator('.vn-control-sidebar'),'Admin sidebar');
 await assertLime(p.locator('.vn-control-primary'),'Admin primary action');
 assert.equal(await p.locator('.vn-control-center').first().evaluate(e=>getComputedStyle(e).color),'rgb(23, 26, 28)','neutral admin text');
 assert.equal(await p.locator('.vn-control-center').first().evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(245, 247, 247)','neutral pearl admin foundation');
}
await p.screenshot({path:`work/portal-${role}-desktop.png`});await p.setViewportSize({width:390,height:844});await p.waitForTimeout(200);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),role+' mobile overflow');await p.screenshot({path:`work/portal-${role}-mobile.png`});if(role==='owner')assert.deepEqual(await p.locator('.vn-menu-toggle,.vn-chart-mobile-actions button').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width>0).filter(e=>Number(getComputedStyle(e).backgroundColor.match(/\d+/)[0])<70).map(e=>e.className)),[],'no dark mobile controls');await p.getByRole('button',{name:/Team chat/}).click();await p.getByRole('button',{name:'Skip welcome'}).click();await p.getByRole('button',{name:'Guides',exact:true}).click();await p.locator('.vn-workspace-help').waitFor();assert.equal(await p.getByRole('button',{name:'Lookup',exact:true}).count(),['owner','support'].includes(role)?1:0,role+' lookup permission');await p.keyboard.press('Escape');}
await p.goto('http://127.0.0.1:5203/tests/browser/portal-audit.html?role=support');await p.getByRole('button',{name:/Team chat/}).click();await p.locator('.vn-chat-intro[data-phase=hero]').waitFor();await p.locator('.vn-chat-intro[data-phase=emblem]').waitFor();await p.locator('.vn-chat-intro').waitFor({state:'detached'});await p.getByRole('button',{name:'Replay welcome'}).click();await p.getByRole('button',{name:'Skip welcome'}).click();await p.screenshot({path:'work/staff-portal-mobile.png'});await p.setViewportSize({width:1440,height:1000});await assertGlass(p.locator('.vn-staff-portal'),'Staff workspace');await assertLime(p.locator('.vn-staff-portal nav button[aria-pressed=true]'),'Staff active channel');await p.screenshot({path:'work/staff-portal-desktop.png'});await p.emulateMedia({contrast:'more'});await p.waitForFunction(()=>matchMedia('(prefers-contrast: more)').matches);await p.waitForFunction(()=>getComputedStyle(document.querySelector('.vn-staff-portal')).backdropFilter==='none');assert.equal(await p.locator('.vn-staff-portal').evaluate(e=>getComputedStyle(e).backdropFilter),'none','Accessible solid staff material');assert.equal(await p.locator('.vn-staff-portal').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');await p.emulateMedia({contrast:'no-preference'});await p.emulateMedia({reducedMotion:'reduce'});await p.getByRole('button',{name:'Replay welcome'}).click();await p.locator('.vn-chat-intro[data-phase=emblem][data-reduced=true]').waitFor();await p.getByRole('button',{name:'Enter workspace'}).click();await p.emulateMedia({reducedMotion:'no-preference'});await p.route('**/images/vanta-hero-960.webp',r=>r.abort());await p.getByRole('button',{name:'Replay welcome'}).click();await p.locator('.vn-chat-intro[data-phase=emblem]').waitFor();await p.locator('.vn-chat-intro').waitFor({state:'detached'});assert.equal(await p.getByRole('button',{name:'Replay welcome'}).evaluate(e=>document.activeElement===e),true);assert.deepEqual(errors,[]);console.log('PASS six roles: pearl theme, mobile/desktop bounds, shared portal, guides and lookup visibility; no runtime errors');}finally{if(b)await b.close();s.kill()}})().catch(e=>{console.error(e);process.exitCode=1});

