const {spawn}=require('node:child_process'),{chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','--config','portable/vite.config.ts','--host','127.0.0.1','--port','5192']);let browser;try{
 await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{if(String(d).includes('127.0.0.1:'))resolve()});server.on('exit',reject)});
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||chromium.executablePath(),args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:5192/tests/browser/sales-desk.html');await p.getByLabel('Garment · colour · size').selectOption('v1');await p.getByLabel('Quantity',{exact:true}).fill('2');await p.getByRole('button',{name:'Add item',exact:true}).click();
 assert.match(await p.locator('aside').innerText(),/180,000/);await p.getByLabel('Payment method').selectOption('transfer');assert.equal(await p.getByRole('button',{name:'Submit for approval'}).isDisabled(),true);await p.getByLabel('Transfer / terminal reference').fill('BANK-123');
 await p.screenshot({path:'work/sales-desk-desktop.png',fullPage:true});await p.evaluate(()=>window.failOnce=true);await p.getByRole('button',{name:'Submit for approval'}).click();await p.getByRole('button',{name:'Retry submission'}).waitFor();assert.equal(await p.getByLabel('Quantity',{exact:true}).isDisabled(),true);await p.getByRole('button',{name:'Retry submission'}).click();await p.getByRole('status').filter({hasText:'Stock reserved'}).waitFor();const calls=await p.evaluate(()=>window.salesCalls);assert.equal(calls.length,2);assert.equal(calls[0].clientId,calls[1].clientId);
 await p.getByRole('button',{name:'Available stock',exact:true}).click();assert.match(await p.locator('tbody').innerText(),/8\s+2\s+6/);
 await p.setViewportSize({width:390,height:844});await p.getByRole('button',{name:'New sale',exact:true}).click();await p.getByLabel('Garment · colour · size').selectOption('v1');await p.getByRole('button',{name:'Add item',exact:true}).click();await p.screenshot({path:'work/sales-desk-mobile.png',fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log('PASS sale selection, totals, payment-reference validation, safe network retry, shared availability, desktop/mobile layout');
 }finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
