const {spawn}=require('child_process');const {chromium}=require('playwright');const assert=require('assert/strict');const fs=require('fs');
(async()=>{const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--config','portable/vite.config.ts','--outDir','outputs/namecheap','--host','127.0.0.1','--port','5185']);try{await new Promise((resolve,reject)=>{server.stdout.on('data',b=>{if(b.toString().includes('Local:'))resolve()});server.on('exit',c=>reject(Error('server '+c)))});const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox']});try{
const policies=JSON.parse(fs.readFileSync('docs/customer-policies-2026-10-05.json','utf8'));
for(const malformed of [false,true]){const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/**',async route=>{const u=route.request().url();const payload=u.includes('/store-settings')?(malformed?{shippingZones:null,hero:null}:{...policies,supportEmail:'care@example.com'}):u.includes('/catalog')?{products:[]}:{};await route.fulfill({json:payload});});await page.goto('http://127.0.0.1:5185/shipping-returns.html');
if(!malformed){await page.getByRole('heading',{name:'Delivery policy',exact:true}).waitFor();assert((await page.locator('article').innerText()).includes(policies.returnPolicy));assert((await page.locator('article').innerText()).includes(policies.deliveryPolicy));}
else await page.getByRole('heading',{name:'Returns, exchanges & refunds',exact:true}).waitFor();
for(const width of [390,820,1180]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'policy overflow '+width);}
assert.deepEqual(errors,[]);console.log('PASS built storefront policy, malformed='+malformed);await page.close();}
}finally{await browser.close()}}finally{server.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
