const {chromium}=require('playwright-core');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let saved=null,fail=false;
await page.route('**/api/admin/terminal-pickup',async route=>{const req=route.request();if(req.method()==='GET')return route.fulfill({json:{pickup:saved}});if(fail)return route.fulfill({status:409,json:{error:'Pickup details changed in another tab.'}});const b=req.postDataJSON();saved={details:b.details,revision:'dc6b4600-7ef1-4f03-b0ad-5926b84fcb40',updatedAt:new Date().toISOString()};return route.fulfill({json:{pickup:saved}});});
await page.goto('http://127.0.0.1:5192');await page.getByText('No business pickup address saved yet.').waitFor();assert.equal(await page.getByLabel('Pickup street address',{exact:true}).inputValue(),'');
for(const [label,value] of [['Pickup street address','Synthetic test location'],['Pickup city','Kaduna'],['Contact first name','Test'],['Contact last name','Owner'],['Contact phone number','08012345678'],['Contact email','test@example.com'],['Pickup postcode','800001']])await page.getByLabel(label,{exact:true}).fill(value);
await page.getByLabel('Pickup state',{exact:true}).selectOption('Kaduna');await page.getByRole('button',{name:'Save pickup details',exact:true}).click();await page.getByText('Pickup details saved ✓',{exact:false}).waitFor();assert.equal(saved.details.city,'Kaduna');await page.reload();await page.getByText('Pickup details saved ✓',{exact:false}).waitFor();assert.equal(await page.getByLabel('Pickup street address',{exact:true}).inputValue(),'Synthetic test location');
fail=true;await page.getByLabel('Pickup city',{exact:true}).fill('Ikeja');await page.getByRole('button',{name:'Save pickup details',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByLabel('Pickup city',{exact:true}).inputValue(),'Ikeja');await page.getByRole('button',{name:'Discard edits'}).click();assert.equal(await page.getByLabel('Pickup city',{exact:true}).inputValue(),'Kaduna');
for(const width of [390,820,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);}assert.deepEqual(errors,[]);console.log('PASS pickup form blank initial state, save, reload persistence, conflict preserves edits, discard and responsive bounds');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
