'use client';
import {useRef,useState} from 'react';
import type {AdminOrder} from '@/lib/store-db';
import {bulkOrderProblem,bulkSourceStatus} from '@/lib/bulk-orders';
import {useUnsavedChanges} from './unsaved-changes';
export function BulkOrders({onChanged,disabled}:{onChanged:()=>void;disabled:boolean}){
 const [target,setTarget]=useState<'processing'|'shipped'|'delivered'>('processing'),[rows,setRows]=useState<AdminOrder[]>([]),[busy,setBusy]=useState(false),[checked,setChecked]=useState(false),[message,setMessage]=useState(''),[review,setReview]=useState(false);
 const lock=useRef(false);useUnsavedChanges({name:'Bulk order review',dirty:review,busy,discard:()=>{setReview(false);setChecked(false);setRows([]);}});
 async function prepare(){if(lock.current)return;lock.current=true;setBusy(true);setReview(false);setChecked(false);setRows([]);setMessage('Loading eligible paid orders…');try{const found:AdminOrder[]=[];for(let page=1;page<=20;page++){const r=await fetch(`/api/admin/orders?status=${bulkSourceStatus[target]}&page=${page}`,{signal:AbortSignal.timeout(20000)});const p=await r.json() as {orders:AdminOrder[];hasMore:boolean;error?:string};if(!r.ok||!Array.isArray(p.orders))throw new Error(p.error||'Could not load orders.');found.push(...p.orders);if(!p.hasMore)break;if(page===20)throw new Error('More than 1,000 orders match. Process smaller batches first.');}const unique=[...new Map(found.map(o=>[o.reference,o])).values()];const ready=unique.filter(o=>!bulkOrderProblem(o,target));setRows(ready);setReview(true);setMessage(`${ready.length} eligible orders. ${unique.length-ready.length} excluded because payment, status or delivery details need attention.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not load orders.');}finally{lock.current=false;setBusy(false);}}
 async function apply(){if(lock.current||!checked||!rows.length)return;lock.current=true;setBusy(true);setChecked(false);let done=0;const failed:AdminOrder[]=[];try{for(const order of rows){try{const r=await fetch('/api/admin/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference:order.reference,status:target,expectedStatus:bulkSourceStatus[target],bulkVerified:true}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error();done++;}catch{failed.push(order);}setMessage(`Updated ${done} of ${rows.length}; ${failed.length} need refreshing and review.`);}setRows(failed);setReview(false);setMessage(`${done} orders updated. ${failed.length} not confirmed—reload the review before retrying. Customer status emails use the normal delivery queue.`);onChanged();}finally{lock.current=false;setBusy(false);}}
 return <div className="vn-studio-form mb-5"><h3>Bulk paid-order update</h3><p>Review all eligible orders across pages. This records fulfilment; it does not arrange a courier. Stock-review, unpaid and cancelled orders are excluded.</p><label>Move orders to <select aria-label="Bulk order stage" className="vn-option-select" disabled={busy||disabled} value={target} onChange={e=>{setTarget(e.target.value as typeof target);setReview(false);setChecked(false);setRows([]);}}><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option></select></label><button type="button" className="vn-pill" disabled={busy||disabled} onClick={prepare}>{busy?'Working…':'Review all eligible paid orders'}</button><p role="status">{message}</p>{review&&rows.length>0&&<><div style={{maxHeight:240,overflow:'auto',overscrollBehavior:'contain'}}><ul>{rows.map(o=><li key={o.reference}>{o.reference} · {o.firstName} {o.lastName} · {o.items.map(i=>`${i.quantity} × ${i.productName} (${i.color}, ${i.size})`).join(', ')} · {o.city}, {o.state} · {o.carrier} {o.trackingNumber}</li>)}</ul></div><label><input type="checkbox" checked={checked} disabled={busy} onChange={e=>setChecked(e.target.checked)}/> {target==='processing'?'I checked every listed order, garment, size, colour, stock and delivery address.':target==='shipped'?'I verified every listed parcel was handed to its courier and its saved tracking details are correct.':'I verified delivery to the customer for every listed order.'}</label><button type="button" className="vn-pill" disabled={!checked||busy||disabled} onClick={apply}>Confirm {rows.length} orders as {target}</button><button type="button" className="vn-pill" disabled={busy} onClick={()=>{setReview(false);setRows([]);setChecked(false);}}>Cancel review</button></>}</div>;
}
