'use client';
import {MeasurementLibrary} from './measurement-library';
import {useState} from 'react';
import {SHOP_SECTIONS} from '@/lib/shop-categories';
import {defaultOptions} from '@/lib/catalog-options';
export function CatalogOptionsEditor({options,onChange}:{options:typeof defaultOptions;onChange:(v:typeof defaultOptions)=>void}){
 const [kind,setKind]=useState<'color'|'category'>('category'),[name,setName]=useState(''),[hex,setHex]=useState('#101112'),[section,setSection]=useState('Tops'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/catalog-options',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,name,hex,section})});const v=await r.json() as typeof defaultOptions & {error?:string};if(!r.ok)throw Error(v.error||'Could not save');onChange(v);setName('');setMessage('Saved. You can now select this option in Product Studio.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save');}finally{setBusy(false)}}
 return <section className="vn-control-panel"><h2>Categories & colours</h2><p>Add a reusable colour or a category. Assign the category to a product and publish it to show it in the storefront menu. Saving an existing name updates its swatch or department.</p><div className="vn-admin-fields"><label>Option type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="category">Category</option><option value="color">Colour</option></select></label><label>Name<input value={name} maxLength={kind==='color'?60:100} onChange={e=>setName(e.target.value)} placeholder={kind==='color'?'e.g. Ice Blue':'e.g. Technical Gilets'}/></label>{kind==='color'?<label>Swatch<input type="color" value={hex} onChange={e=>setHex(e.target.value)}/></label>:<label>Store department<select value={section} onChange={e=>setSection(e.target.value)}>{SHOP_SECTIONS.map(s=><option key={s}>{s}</option>)}</select></label>}</div><button className="vn-pill mt-4" disabled={busy||!name.trim()} onClick={()=>void save()}>{busy?'Saving…':'Save option'}</button><p role="status">{message}</p><details><summary>{options.colors.length} colours · {options.categories.length} categories</summary><div className="vn-option-list">{kind==='color'?options.colors.map(c=><button key={c.name} onClick={()=>{setName(c.name);setHex(c.hex)}}><i style={{background:c.hex}}/>{c.name}</button>):options.categories.map(c=><button key={c.id} onClick={()=>{setName(c.name);setSection(c.section)}}>{c.name} · {c.section}</button>)}</div></details><MeasurementLibrary/></section>;
}
