"use client";
import { useEffect, useRef, useState } from "react";
import { NIGERIA_STATES, type CommerceSettings } from "@/lib/commerce-config";
import { exportCsv } from "./order-tools";
import { formatNaira } from "@/lib/catalog";
import { StoreDesignFields, InternationalShippingFields } from "./store-design-fields";
import { reconcileAdminDraft } from "@/lib/admin-draft";
import {useUnsavedChanges,useOperationDraft} from './unsaved-changes';
import {adminRead} from "@/lib/admin-read";
import { toast } from "sonner";
type ReturnCase={id:string;version:number;reference:string;email:string;kind:string;reason:string;itemsJson:string;status:string;notes:string;refundKobo:number;refundReference:string;refundStatus:string;restocked:number};
type Payload={settings:CommerceSettings;emailConfigured:boolean;paymentsConfigured:boolean;setupIssues:string[];hasMore:boolean;reviews:Array<{id:string;productName:string;displayName:string;rating:number;body:string;status:string}>;returns:ReturnCase[];emails:Array<{id:string;recipient:string;subject:string;status:string;attempts:number;lastError:string}>;subscribers:Array<{id:string;email:string;kind:string;variantId:string;status:string;createdAt:string}>;stock:Array<{id:number;sku:string;old_stock:number;new_stock:number;reason:string;actor:string;created_at:string}>};
export function CommercePanel({onNavigate,onThreshold,view='all'}:{view?:'all'|'settings'|'care';onNavigate?:(t:{section:string;resource?:string})=>void;onThreshold?:(n:number)=>void}={}){
  const [data,setData]=useState<Payload|null>(null),[settings,setSettings]=useState<CommerceSettings|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[page,setPage]=useState(1);
  const serverSettings=useRef<CommerceSettings|null>(null),loadSequence=useRef(0),saving=useRef(false);
  const [loading,setLoading]=useState(false);
  const [lastSavedSettings,setLastSavedSettings]=useState<CommerceSettings|null>(null);
  async function load(){const sequence=++loadSequence.current;setLoading(true);setError("");try{const p=await adminRead<Payload>(`/api/admin/commerce?page=${page}`,v=>!!v?.settings&&['setupIssues','reviews','returns','emails','subscribers','stock'].every(k=>Array.isArray(v[k]))&&['collectionLabels','shippingZones','internationalZones'].every(k=>Array.isArray(v.settings[k])));if(sequence!==loadSequence.current)return;const previous=serverSettings.current;serverSettings.current=p.settings;setData(p);onThreshold?.(p.settings.lowStockThreshold);setLastSavedSettings(p.settings);setSettings(current=>reconcileAdminDraft(current,previous,p.settings));}catch(e){if(sequence===loadSequence.current)setError(e instanceof Error?e.message:"Please try again.");}finally{if(sequence===loadSequence.current)setLoading(false);}}
  useEffect(()=>{void load();return()=>{loadSequence.current++;};},[page]);
  async function action(action:string,input?:unknown){if(saving.current)return false;saving.current=true;setBusy(true);try{const r=await fetch("/api/admin/commerce",{method:"POST",headers:{"Content-Type":"application/json"},signal:AbortSignal.timeout(30000),body:JSON.stringify({action,...(action==="settings"?{settings:input}:{data:input})})});const p=await r.json() as {error?:string;configured?:boolean;settings?:CommerceSettings};if(!r.ok)throw new Error(p.error||"Could not save changes.");if(action==="settings"&&p.settings){const saved=p.settings;setLastSavedSettings(saved);serverSettings.current=saved;setData(current=>current?{...current,settings:saved}:current);setSettings(current=>reconcileAdminDraft(current,input as CommerceSettings,saved));}toast.success(p.configured===false?"Emails remain queued until the sender is configured.":"Saved.");await load();return true;}catch(e){toast.error(e instanceof Error?e.message:"Please try again.");return false;}finally{saving.current=false;setBusy(false);}}
  const settingsDirty=!!settings&&!!serverSettings.current&&JSON.stringify(settings)!==JSON.stringify(serverSettings.current);
  useUnsavedChanges({name:'Store settings',dirty:settingsDirty,busy,save:()=>action('settings',settings),discard:()=>setSettings(serverSettings.current)});
  if(error&&!data)return <section className="vn-admin-panel"><p role="alert">{error}</p><button className="vn-pill" onClick={load}>Retry</button></section>;
  if(!data||!settings)return <section className="vn-admin-panel"><p>Loading customer tools…</p></section>;
  return <section className="vn-admin-panel"><h2>{view==='care'?'Customer care':'Store settings'}</h2>
    {error&&<p role="alert">{error} Your changes remain in this form. <button className="vn-pill" disabled={busy||loading} onClick={load}>Retry refresh</button></p>}
    {view!=='care'&&<>{lastSavedSettings&&<p role="status">{JSON.stringify(settings)===JSON.stringify(lastSavedSettings)?"Settings saved.":"You have unsaved changes. Switches take effect after Save settings."}</p>}
    <div className="vn-launch-status"><h3>{data.settings.acceptingOrders?"Online orders are open":"Prepare your store for orders"}</h3><p>Paystack: {data.paymentsConfigured?"connected":"not connected"} · Order emails: {data.emailConfigured?"configured":"not configured"}</p>
      {data.setupIssues.length?<ul>{data.setupIssues.map(issue=><li key={issue}>{issue}</li>)}</ul>:<p>Your required checkout settings are complete. Use Paystack test mode before switching to live payments.</p>}
      <p>Review every product’s prices, available quantities, photos and size measurements. Publish only information confirmed for the items you will ship.</p>
    </div>
    <fieldset className="vn-admin-fields"><legend>Customer support &amp; order processing</legend><label>Customer support email<input type="email" maxLength={200} value={settings.supportEmail} onChange={e=>setSettings({...settings,supportEmail:e.target.value})}/></label><label>Customer support phone<input type="tel" maxLength={40} placeholder="Include country code" value={settings.supportPhone??""} onChange={e=>setSettings({...settings,supportPhone:e.target.value})}/></label><label>Order processing information<textarea maxLength={500} value={settings.processingNote} onChange={e=>setSettings({...settings,processingNote:e.target.value})}/></label><p>Change these details whenever needed. Saved contacts appear on the contact page and footer. Processing time is separate from dispatch and delivery.</p></fieldset>
    <StoreDesignFields settings={settings} onChange={setSettings} busy={busy} onUploadChange={setBusy}/>
    <InternationalShippingFields settings={settings} onChange={setSettings} busy={busy}/>
    <button className="vn-pill" disabled={busy||!settingsDirty} onClick={()=>action("settings",settings)}>{busy?"Saving…":settingsDirty?"Save settings":"Settings saved ✓"}</button>
    <details className="vn-product-disclosure"><summary>Launch settings, delivery &amp; customer care</summary><div className="vn-admin-fields mt-5"><label>Low-stock threshold<input type="number" min={0} max={100} value={settings.lowStockThreshold} onChange={e=>setSettings({...settings,lowStockThreshold:Number(e.target.value)})}/></label><label>Dispatch timing<input maxLength={240} placeholder="Enter your confirmed dispatch timing" value={settings.dispatchNote} onChange={e=>setSettings({...settings,dispatchNote:e.target.value})}/></label><label>General delivery information<textarea maxLength={500} value={settings.deliveryNote} onChange={e=>setSettings({...settings,deliveryNote:e.target.value})}/></label></div>
      <div className="vn-admin-fields mt-5"><label>Returns, exchanges &amp; refunds policy<textarea rows={8} maxLength={6000} placeholder="Enter your confirmed return window, eligible conditions, return postage responsibility, exchange process and refund timing." value={settings.returnPolicy} onChange={e=>setSettings({...settings,returnPolicy:e.target.value})}/></label></div>
      <label className="vn-launch-check"><input type="checkbox" disabled={busy} checked={settings.inventoryConfirmed} onChange={e=>setSettings({...settings,inventoryConfirmed:e.target.checked})}/>I have checked the product prices and replaced sample stock with actual quantities.</label>
      <label className="vn-launch-check"><input type="checkbox" disabled={busy} checked={settings.acceptingOrders} onChange={e=>setSettings({...settings,acceptingOrders:e.target.checked})}/>Accept online orders (requires Paystack and completed business settings)</label>
      <h3>Delivery zones</h3><p>With no zones, checkout uses your configured standard delivery fee. Once zones are added, only listed states are supported unless you include “All other states”. Enter the full delivery estimate, including dispatch time.</p>
      {settings.shippingZones.map((zone,index)=><div className="vn-admin-fields mt-5" key={index}><label>State<select value={zone.state} onChange={e=>setSettings({...settings,shippingZones:settings.shippingZones.map((z,i)=>i===index?{...z,state:e.target.value}:z)})}><option value="*">All other states</option>{NIGERIA_STATES.map(state=><option key={state}>{state}</option>)}</select></label><label>Fee (₦)<input type="number" min={0} value={zone.feeKobo/100} onChange={e=>setSettings({...settings,shippingZones:settings.shippingZones.map((z,i)=>i===index?{...z,feeKobo:Math.round(Number(e.target.value)*100)}:z)})}/></label><label>Estimated delivery<input maxLength={160} placeholder="Enter your confirmed delivery window" value={zone.estimate} onChange={e=>setSettings({...settings,shippingZones:settings.shippingZones.map((z,i)=>i===index?{...z,estimate:e.target.value}:z)})}/></label><button type="button" onClick={()=>setSettings({...settings,shippingZones:settings.shippingZones.filter((_,i)=>i!==index)})}>Remove zone</button></div>)}
      <button className="vn-pill" onClick={()=>setSettings({...settings,shippingZones:[...settings.shippingZones,{state:NIGERIA_STATES.find(s=>!settings.shippingZones.some(z=>z.state===s))||"*",feeKobo:0,estimate:""}]})}>Add delivery zone</button><button className="vn-pill" disabled={busy||!settingsDirty} onClick={()=>action("settings",settings)}>{busy?"Saving…":settingsDirty?"Save settings":"Settings saved ✓"}</button>
    </details>
    </>}
    {view!=='settings'&&<>
    {onNavigate?<button className="vn-pill" onClick={()=>onNavigate({section:'returns'})}>Manage returns &amp; exchanges →</button>:<details className="vn-product-disclosure"><summary>Returns &amp; exchanges</summary>{data.returns.map(item=><ReturnEditor key={`${item.id}-${item.version}`} item={item} busy={busy} onSave={value=>action("return",value)}/>)}</details>}
    <details className="vn-product-disclosure"><summary>Review moderation</summary><p>Publish genuine customer feedback, including critical reviews. Reject spam, personal information or abusive content.</p>{data.reviews.length?data.reviews.map(review=><article key={review.id}><strong>{review.productName} · {review.rating}/5</strong><p>{review.displayName} · {review.status}</p><p>{review.body}</p>{["published","rejected","pending"].map(status=><button className="vn-pill" disabled={busy||status===review.status} key={status} onClick={()=>action("review",{id:review.id,status})}>{status==="published"?"Publish":status==="rejected"?"Reject":"Keep pending"}</button>)}</article>):<p>No reviews to moderate yet.</p>}</details>
    <details className="vn-product-disclosure"><summary>Subscribers &amp; restock requests</summary><p>Only confirmed subscriptions marked active should receive collection news.</p><button className="vn-pill" onClick={()=>exportCsv("vanta-noir-subscribers.csv",[["Email","Type","Variant","Status","Created"],...data.subscribers.map(s=>[s.email,s.kind,s.variantId,s.status,s.createdAt])])}>Export this page</button><div className="overflow-x-auto"><table className="vn-data-table"><thead><tr><th>Email</th><th>Type</th><th>Variant</th><th>Status</th></tr></thead><tbody>{data.subscribers.map(s=><tr key={s.id}><td>{s.email}</td><td>{s.kind}</td><td>{s.variantId||"—"}</td><td>{s.status}</td></tr>)}</tbody></table></div>{!data.subscribers.length&&<p>No signups yet.</p>}</details>
    <details className="vn-product-disclosure"><summary>Customer email delivery</summary><p>Order confirmations are queued only after verified payment and include the selected garments, colours, sizes, quantities, price breakdown and delivery address. Repeated payment notifications do not create duplicate confirmations.</p><p>{data.emailConfigured?"Email sender configured. Pending messages are processed after store activity and by the scheduled worker when enabled.":"Email delivery needs RESEND_API_KEY and EMAIL_FROM in Cloudflare, using your verified sending domain. Messages stay queued until those are connected."}</p><details><summary>How to activate order emails</summary><ol><li>In Resend, add a sending domain you control and complete its DNS verification.</li><li>Create a sending API key. In your Cloudflare Worker settings, save it as the secret RESEND_API_KEY.</li><li>Set EMAIL_FROM to your verified sender, for example Vanta Noir &lt;orders@vantanoir.store&gt;. Set EMAIL_REPLY_TO to a monitored customer-care inbox.</li><li>Deploy the updated backend and check a test purchase using your own email. Check the email provider’s delivery log as well as the inbox.</li></ol><p>Keep the API key out of GitHub and frontend files. A verified sending address does not automatically create a mailbox for replies.</p></details><p>EMAIL_REPLY_TO can point replies to customer care. “Sent” means the email service accepted the message; it does not confirm arrival in the customer’s inbox. A “review” status means delivery should be checked with the provider before sending again.</p><button className="vn-pill" disabled={busy} onClick={()=>action("process-emails")}>Process queued emails</button>{data.emails.map(email=><article key={email.id}><strong>{email.subject}</strong><p>{email.recipient} · {email.status} · {email.attempts} attempts</p>{email.lastError&&<p>{email.lastError}</p>}</article>)}</details>

    <div className="flex items-center gap-4"><button className="vn-pill" disabled={page===1||busy||loading} onClick={()=>setPage(p=>p-1)}>Previous records</button><span>Page {page}</span><button className="vn-pill" disabled={!data.hasMore||busy||loading} onClick={()=>setPage(p=>p+1)}>Next records</button></div>
    </>}
  </section>;
}
function ReturnEditor({item,busy,onSave}:{item:ReturnCase;busy:boolean;onSave:(value:unknown)=>Promise<boolean>}){
  const [form,setForm]=useState({...item,restock:false}); const items=JSON.parse(item.itemsJson) as Array<{name:string;color:string;size:string;quantity:number}>;
  return <article><h3>{item.reference} · {item.kind}</h3><p>{item.email}</p><p>{item.reason}</p><ul>{items.map((i,n)=><li key={n}>{i.quantity} × {i.name} · {i.color} · {i.size}</li>)}</ul><div className="vn-admin-fields mt-5"><label>Request status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{["requested","approved","received","resolved","declined"].map(status=><option key={status}>{status}</option>)}</select></label><label>Customer-facing instructions / update<textarea value={form.notes} maxLength={2000} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label>Refund amount (₦)<input type="number" min={0} value={form.refundKobo/100} onChange={e=>setForm({...form,refundKobo:Math.round(Number(e.target.value)*100)})}/></label><label>Paystack refund reference<input maxLength={160} value={form.refundReference} onChange={e=>setForm({...form,refundReference:e.target.value})}/></label><label>Refund status<select value={form.refundStatus} onChange={e=>setForm({...form,refundStatus:e.target.value})}>{["none","pending","completed"].map(status=><option key={status}>{status}</option>)}</select></label></div><p>Process the refund in Paystack first, then record its reference and status here. Current recorded amount: {formatNaira(item.refundKobo)}.</p>{!item.restocked?<label className="flex gap-3 my-4"><input type="checkbox" checked={form.restock} onChange={e=>setForm({...form,restock:e.target.checked})}/>I have received and inspected every item above; return these units to stock.</label>:<p>These items have already been restocked.</p>}<button className="vn-pill" disabled={busy} onClick={()=>onSave(form)}>Save return update</button></article>;
}
