"use client";
import {SETTINGS_SECTIONS,type SettingsSection} from "@/lib/settings-sections";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { type CommerceSettings } from "@/lib/commerce-config";
import { exportCsv } from "./order-tools";
import { formatNaira } from "@/lib/catalog";
import { StoreDesignFields, InternationalShippingFields } from "./store-design-fields";
import { reconcileAdminDraft } from "@/lib/admin-draft";
import {useUnsavedChanges,useOperationDraft} from './unsaved-changes';
import {adminRead} from "@/lib/admin-read";
import { toast } from "sonner";
type ReturnCase={id:string;version:number;reference:string;email:string;kind:string;reason:string;itemsJson:string;status:string;notes:string;refundKobo:number;refundReference:string;refundStatus:string;restocked:number};
type Payload={settings:CommerceSettings;emailConfigured:boolean;paymentsConfigured:boolean;setupIssues:string[];hasMore:boolean;reviews:Array<{id:string;productName:string;displayName:string;rating:number;body:string;status:string}>;returns:ReturnCase[];emails:Array<{id:string;recipient:string;subject:string;status:string;attempts:number;lastError:string}>;subscribers:Array<{id:string;email:string;kind:string;variantId:string;status:string;createdAt:string}>;stock:Array<{id:number;sku:string;old_stock:number;new_stock:number;reason:string;actor:string;created_at:string}>};
export function CommercePanel({onNavigate,onThreshold,view='all'}:{view?:'all'|'settings'|'care';onNavigate?:(t:{section:string;resource?:string})=>void;onThreshold?:(n:number)=>void}={}){
  const [data,setData]=useState<Payload|null>(null),[settings,setSettings]=useState<CommerceSettings|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[page,setPage]=useState(1);
  const serverSettings=useRef<CommerceSettings|null>(null),loadSequence=useRef(0),saving=useRef(false);
  const [loading,setLoading]=useState(false),[editing,setEditing]=useState<SettingsSection|null>(null);
  const [lastSavedSettings,setLastSavedSettings]=useState<CommerceSettings|null>(null);
  async function load(){const sequence=++loadSequence.current;setLoading(true);setError("");try{const p=await adminRead<Payload>(`/api/admin/commerce?page=${page}`,v=>!!v?.settings&&['setupIssues','reviews','returns','emails','subscribers','stock'].every(k=>Array.isArray(v[k]))&&['collectionLabels','shippingZones','internationalZones'].every(k=>Array.isArray(v.settings[k])));if(sequence!==loadSequence.current)return;const previous=serverSettings.current;serverSettings.current=p.settings;setData(p);onThreshold?.(p.settings.lowStockThreshold);setLastSavedSettings(p.settings);setSettings(current=>reconcileAdminDraft(current,previous,p.settings));}catch(e){if(sequence===loadSequence.current)setError(e instanceof Error?e.message:"Please try again.");}finally{if(sequence===loadSequence.current)setLoading(false);}}
  useEffect(()=>{void load();return()=>{loadSequence.current++;};},[page]);
  async function action(action:string,input?:unknown){if(saving.current)return false;saving.current=true;setBusy(true);try{const r=await fetch("/api/admin/commerce",{method:"POST",headers:{"Content-Type":"application/json"},signal:AbortSignal.timeout(30000),body:JSON.stringify({action,...(action.startsWith("settings")?{settings:input}:{data:input})})});const p=await r.json() as {error?:string;configured?:boolean;settings?:CommerceSettings};if(!r.ok)throw new Error(p.error||"Could not save changes.");if(action.startsWith("settings")&&p.settings){const saved=p.settings;setLastSavedSettings(saved);serverSettings.current=saved;setData(current=>current?{...current,settings:saved}:current);setSettings(current=>reconcileAdminDraft(current,action==="settings-section"?settings:input as CommerceSettings,saved));}toast.success(p.configured===false?"Emails remain queued until the sender is configured.":"Saved.");await load();return true;}catch(e){toast.error(e instanceof Error?e.message:"Please try again.");return false;}finally{saving.current=false;setBusy(false);}}
  const settingsDirty=!!settings&&!!serverSettings.current&&JSON.stringify(settings)!==JSON.stringify(serverSettings.current);
  async function saveSettings(){if(!editing||!settings)return true;const values=Object.fromEntries(SETTINGS_SECTIONS[editing].map(key=>[key,settings[key]]));const ok=await action('settings-section',{section:editing,values});if(ok)setEditing(null);return ok;}
  useUnsavedChanges({name:'Store settings',dirty:settingsDirty,busy,save:saveSettings,discard:()=>{setSettings(serverSettings.current);setEditing(null);}});
  function section(id:SettingsSection,title:string,children:ReactNode){const active=editing===id;return <article className="vn-settings-section" data-settings-section={id}><header><h3>{title}</h3><div><button className="vn-pill" disabled={busy||Boolean(editing&&!active)} onClick={()=>active?void saveSettings():setEditing(id)}>{active?(busy?'Saving…':'Save'):'Edit'}</button>{active&&<button className="vn-pill" disabled={busy} onClick={()=>{setSettings(serverSettings.current);setEditing(null);}}>Cancel</button>}</div></header><fieldset disabled={!active||busy}>{children}</fieldset></article>;}
  if(error&&!data)return <section className="vn-admin-panel"><p role="alert">{error}</p><button className="vn-pill" onClick={load}>Retry</button></section>;
  if(!data||!settings)return <section className="vn-admin-panel"><p>Loading customer tools…</p></section>;
  return <section className="vn-admin-panel"><h2>{view==='care'?'Customer care':'Store settings'}</h2>
    {error&&<p role="alert">{error} Your changes remain in this form. <button className="vn-pill" disabled={busy||loading} onClick={load}>Retry refresh</button></p>}
    {view!=='care'&&<>{lastSavedSettings&&<p role="status">{JSON.stringify(settings)===JSON.stringify(lastSavedSettings)?"Settings saved.":"You have unsaved changes. Save the section you are editing to apply changes."}</p>}
    <div className="vn-launch-status"><h3>{data.settings.acceptingOrders?"Online orders are open":"Prepare your store for orders"}</h3><p>Paystack: {data.paymentsConfigured?"connected":"not connected"} · Order emails: {data.emailConfigured?"configured":"not configured"}</p>
      {data.setupIssues.length?<ul>{data.setupIssues.map(issue=><li key={issue}>{issue}</li>)}</ul>:<p>Your required checkout settings are complete. Use Paystack test mode before switching to live payments.</p>}
      <p>Review every product’s prices, available quantities, photos and size measurements. Publish only information confirmed for the items you will ship.</p>
    </div>
    {section('support','Customer support & order processing',<div className="vn-admin-fields"><label>Customer support email<input type="email" value={settings.supportEmail} onChange={e=>setSettings({...settings,supportEmail:e.target.value})}/></label><label>Customer support phone<input type="tel" value={settings.supportPhone} onChange={e=>setSettings({...settings,supportPhone:e.target.value})}/></label><label>Order processing information<textarea maxLength={500} value={settings.processingNote} onChange={e=>setSettings({...settings,processingNote:e.target.value})}/></label></div>)}
    {section('design','Storefront design',<StoreDesignFields settings={settings} onChange={setSettings} busy={busy} onUploadChange={setBusy}/>)}
    {section('international','Worldwide shipping',<InternationalShippingFields settings={settings} onChange={setSettings} busy={busy}/>)}
    {section('fulfilment','Dispatch & delivery policy',<div className="vn-admin-fields"><label>Dispatch timing<input maxLength={240} value={settings.dispatchNote} onChange={e=>setSettings({...settings,dispatchNote:e.target.value})}/></label><label>Delivery information<textarea maxLength={500} value={settings.deliveryNote} onChange={e=>setSettings({...settings,deliveryNote:e.target.value})}/></label><label>Delivery policy<textarea rows={6} maxLength={6000} value={settings.deliveryPolicy} onChange={e=>setSettings({...settings,deliveryPolicy:e.target.value})}/></label><p>Shipping uses available courier rates automatically. Manage enabled couriers in Shipbubble. If a service becomes unavailable, use the alternative-courier controls in dispatch.</p></div>)}
    {section('returns','Returns, exchanges & refunds',<label>Returns policy<textarea rows={6} maxLength={6000} value={settings.returnPolicy} onChange={e=>setSettings({...settings,returnPolicy:e.target.value})}/></label>)}
    {section('checkout','Checkout & inventory',<div className="vn-admin-fields"><label>Low-stock threshold<input type="number" min={0} max={100} value={settings.lowStockThreshold} onChange={e=>setSettings({...settings,lowStockThreshold:Number(e.target.value)})}/></label><label className="vn-launch-check"><input type="checkbox" checked={settings.inventoryConfirmed} onChange={e=>setSettings({...settings,inventoryConfirmed:e.target.checked})}/>Prices and stock are confirmed</label><label className="vn-launch-check"><input type="checkbox" checked={settings.acceptingOrders} onChange={e=>setSettings({...settings,acceptingOrders:e.target.checked})}/>Accept online orders</label></div>)}
    </>}
    {view!=='settings'&&<>
    {onNavigate?<button className="vn-pill" onClick={()=>onNavigate({section:'returns'})}>Manage returns &amp; exchanges →</button>:<details className="vn-product-disclosure"><summary>Returns &amp; exchanges</summary>{data.returns.map(item=><ReturnEditor key={`${item.id}-${item.version}`} item={item} busy={busy} onSave={value=>action("return",value)}/>)}</details>}
    <details className="vn-product-disclosure"><summary>Review moderation</summary><p>Publish genuine customer feedback, including critical reviews. Reject spam, personal information or abusive content.</p>{data.reviews.length?data.reviews.map(review=><article key={review.id}><strong>{review.productName} · {review.rating}/5</strong><p>{review.displayName} · {review.status}</p><p>{review.body}</p>{["published","rejected","pending"].map(status=><button className="vn-pill" disabled={busy||status===review.status} key={status} onClick={()=>action("review",{id:review.id,status})}>{status==="published"?"Publish":status==="rejected"?"Reject":"Keep pending"}</button>)}</article>):<p>No reviews to moderate yet.</p>}</details>
    <details className="vn-product-disclosure"><summary>Subscribers &amp; restock requests</summary><p>Only confirmed subscriptions marked active should receive collection news.</p><button className="vn-pill" onClick={()=>exportCsv("vanta-noir-subscribers.csv",[["Email","Type","Variant","Status","Created"],...data.subscribers.map(s=>[s.email,s.kind,s.variantId,s.status,s.createdAt])])}>Export this page</button><div className="overflow-x-auto"><table className="vn-data-table"><thead><tr><th>Email</th><th>Type</th><th>Variant</th><th>Status</th></tr></thead><tbody>{data.subscribers.map(s=><tr key={s.id}><td>{s.email}</td><td>{s.kind}</td><td>{s.variantId||"—"}</td><td>{s.status}</td></tr>)}</tbody></table></div>{!data.subscribers.length&&<p>No signups yet.</p>}</details>
    <details className="vn-product-disclosure"><summary>Customer email delivery</summary><p>Order confirmations are queued only after verified payment and include the selected garments, colours, sizes, quantities, price breakdown and delivery address. Repeated payment notifications do not create duplicate confirmations.</p><p>{data.emailConfigured?"Email sender configured. Pending messages are processed after store activity and by the scheduled worker when enabled.":"Email delivery needs RESEND_API_KEY and EMAIL_FROM in Cloudflare, using your verified sending domain. Messages stay queued until those are connected."}</p><details><summary>How to activate order emails</summary><ol><li>In Resend, add a sending domain you control and complete its DNS verification.</li><li>Create a sending API key. In your Cloudflare Worker settings, save it as the secret RESEND_API_KEY.</li><li>Set EMAIL_FROM to your verified sender, for example Vanta Noir &lt;orders@vantanoir.store&gt;. Set EMAIL_REPLY_TO to a monitored customer-care inbox.</li><li>Deploy the updated backend and check a test purchase using your own email. Check the email provider’s delivery log as well as the inbox.</li></ol><p>Keep the API key out of GitHub and frontend files. A verified sending address does not automatically create a mailbox for replies.</p></details><p>EMAIL_REPLY_TO can point replies to customer care. “Sent” means the email service accepted the message; it does not confirm arrival in the customer’s inbox. A “review” status means delivery should be checked with the provider before sending again.</p><button className="vn-pill" disabled={busy} onClick={()=>action("process-emails")}>Process queued emails</button>{data.emails.map(email=><article key={email.id}><strong>{email.subject}</strong><p>{email.recipient} · {email.status} · {email.attempts} attempts</p>{email.lastError&&<p>{email.lastError}</p>}</article>)}</details>

    <div className="flex items-center gap-4"><button className="vn-pill" disabled={page===1||busy||loading} onClick={()=>setPage(p=>p-1)}>Previous records</button><span>Page {page}</span><button className="vn-pill" disabled={!data.hasMore||busy||loading} onClick={()=>setPage(p=>p+1)}>Next records</button></div>
    </>}
  </section>;
}
function ReturnEditor({item,busy,onSave}:{item:ReturnCase;busy:boolean;onSave:(value:unknown)=>Promise<boolean>}){
  const [form,setForm]=useState({...item,restock:false}); const items=JSON.parse(item.itemsJson) as Array<{name:string;color:string;size:string;quantity:number}>;
  return <article><h3>{item.reference} · {item.kind}</h3><p>{item.email}</p><p>{item.reason}</p><ul>{items.map((i,n)=><li key={n}>{i.quantity} × {i.name} · {i.color} · {i.size}</li>)}</ul><div className="vn-admin-fields mt-5"><label>Request status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{["requested","approved","received","resolved","declined"].map(status=><option key={status}>{status}</option>)}</select></label><label>Customer-facing instructions / update<textarea value={form.notes} maxLength={2000} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label>Refund amount (₦)<input type="number" min={0} value={form.refundKobo/100} onChange={e=>setForm({...form,refundKobo:Math.round(Number(e.target.value)*100)})}/></label><label>Paystack refund reference<input maxLength={160} value={form.refundReference} onChange={e=>setForm({...form,refundReference:e.target.value})}/></label><label>Refund status<select value={form.refundStatus} onChange={e=>setForm({...form,refundStatus:e.target.value})}>{["none","pending","completed"].map(status=><option key={status}>{status}</option>)}</select></label></div><p>Process the refund in Paystack first, then record its reference and status here. Current recorded amount: {formatNaira(item.refundKobo)}.</p>{!item.restocked?<label className="flex gap-3 my-4"><input type="checkbox" checked={form.restock} onChange={e=>setForm({...form,restock:e.target.checked})}/>I have received and inspected every item above; return these units to stock.</label>:<p>These items have already been restocked.</p>}<button className="vn-pill" disabled={busy} onClick={()=>onSave(form)}>Save return update</button></article>;
}
