"use client";
import {useEffect,useState} from 'react';
type Email={id:string;eventKey:string;recipient:string;status:string;deliveryStatus:string|null;lastError:string;createdAt:string;sentAt:string|null};
type Tracking={connected:boolean;state:string;message:string;endpoint:string;lastEventAt:string|null};
type Data={emails:Email[];tracking:Tracking};
const problem=(e:Email)=>['bounced','failed','complained','suppressed','delivery_delayed'].includes(e.deliveryStatus||'')||e.status==='review'||(e.status==='pending'&&!!e.lastError);
const labels:Record<string,string>={delivered:'Delivered to recipient’s mail server',delivery_delayed:'Delivery delayed',bounced:'Bounced — check the address',failed:'Delivery failed',complained:'Marked as spam — contact customer before resending',suppressed:'Blocked by Resend — check suppression details'};
export function EmailDeliveryPanel(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[reload,setReload]=useState(0),[busy,setBusy]=useState(false),[secret,setSecret]=useState('');
 useEffect(()=>{const controller=new AbortController();const load=async()=>{try{const r=await fetch('/api/admin/email-delivery?reference='+encodeURIComponent(filter),{cache:'no-store',signal:controller.signal});const payload=await r.json() as Data&{error?:string};if(!r.ok)throw new Error(payload.error||'Order email status could not load.');setData(payload);setError('');}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Order email status unavailable.');}};void load();const timer=setInterval(()=>{if(!document.hidden)void load();},60000);return()=>{controller.abort();clearInterval(timer);};},[filter,reload]);
 async function setup(body:unknown){setBusy(true);setError('');try{const r=await fetch('/api/admin/email-delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json() as {error?:string};if(!r.ok)throw new Error(p.error||'Connection could not complete.');setSecret('');setReload(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'Connection could not complete.');}finally{setBusy(false);}}
 return <details className="vn-email-panel"><summary>Order emails · {data?data.emails.filter(problem).length:'…'} recent delivery problems</summary>
 <p>Only you can resend confirmations. Delivered means the recipient’s mail server accepted the email; it does not guarantee inbox placement or that it was read.</p>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {data&&<><p>{data.tracking.connected?(data.tracking.lastEventAt?'Delivery tracking is receiving signed Resend updates.':'Tracking is configured; waiting for the first signed Resend update.'):'Delivery tracking needs one connection step. Sending order emails still works.'}</p>
 {!data.tracking.connected&&<details><summary>Connect delivery tracking</summary><p>{data.tracking.message}</p><button disabled={busy} onClick={()=>void setup({action:'connect'})}>Try automatic connection</button><p>If your existing key only allows sending, open <a href="https://resend.com/webhooks" target="_blank" rel="noreferrer">Resend → Webhooks</a>, add this endpoint, and select email.delivered, email.delivery_delayed, email.bounced, email.failed, email.complained and email.suppressed.</p><code>{data.tracking.endpoint||'Endpoint is not configured.'}</code><form onSubmit={e=>{e.preventDefault();void setup({action:'secret',secret});}}><label>Webhook signing secret<input type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="whsec_…" required/></label><button disabled={busy||!secret}>Save signing secret</button></form><p>Use the webhook signing secret here, not your Resend API key. Do not paste it into chat.</p></details>}
 <form onSubmit={e=>{e.preventDefault();setFilter(query.trim().toUpperCase());}}><label>Find order email<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="VN-…"/></label><button>Find</button><button type="button" onClick={()=>{setQuery('');setFilter('');setReload(n=>n+1);}}>Show recent / refresh</button></form>
 {!data.emails.length&&<p>No confirmation emails match. Payment must be verified before a confirmation can be sent.</p>}
 <ul>{data.emails.map(email=><EmailRow key={email.id} email={email} onQueued={()=>{setMessage('Confirmation queued. It will send on the next scheduled email cycle, usually within five minutes.');setReload(n=>n+1);}}/>)}</ul></>}
 </details>;
}
function EmailRow({email:e,onQueued}:{email:Email;onQueued:()=>void}){
 const [editing,setEditing]=useState(false),[recipient,setRecipient]=useState(e.recipient),[confirmed,setConfirmed]=useState(false),[requestId,setRequestId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const reference=e.eventKey.split(':')[1];
 async function resend(){setBusy(true);setError('');try{const r=await fetch('/api/admin/email-delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'resend',reference,recipient,requestId,confirmed})});const p=await r.json() as {error?:string};if(!r.ok)throw new Error(p.error||'Could not queue the confirmation.');setEditing(false);onQueued();}catch(cause){setError(cause instanceof Error?cause.message:'Please retry.');}finally{setBusy(false);}}
 return <li className={problem(e)?'has-problem':''}><strong>{reference}</strong><p>{e.recipient} · {e.deliveryStatus?labels[e.deliveryStatus]:e.status==='sent'?'Accepted by Resend — delivery not confirmed':e.status==='review'?'Sending needs review':e.status==='pending'?'Queued for sending':e.status==='sending'?'Sending':e.status}</p>{e.lastError&&<p>{e.lastError}</p>}<p>{new Date(e.createdAt.replace(' ','T')+'Z').toLocaleString()}</p>
 <button disabled={busy||['pending','sending'].includes(e.status)} onClick={()=>{setEditing(true);setConfirmed(false);setRecipient(e.recipient);setRequestId(crypto.randomUUID());setError('');}}>Resend confirmation</button>
 {editing&&<form onSubmit={event=>{event.preventDefault();void resend();}}><label>Recipient email<input type="email" value={recipient} onChange={event=>setRecipient(event.target.value)} required maxLength={200}/></label><label className="vn-email-confirm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)} required/>I confirmed this address with the customer and they requested another copy.</label><p>This sends order details to the address above. It does not change the checkout address. For a bounce or spam complaint, resolve the delivery problem before sending again.</p>{error&&<p role="alert">{error}</p>}<button disabled={busy||!confirmed}>{busy?'Queueing…':'Send this confirmation'}</button><button type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></form>}
 </li>;
}
