'use client';
import {useEffect,useState,useRef} from 'react';
import {adminRead} from '@/lib/admin-read';
type State={ready:boolean;connected:boolean;property:string;connectedAt:string|null;redirectUri:string};
export function Ga4Connection(){
 const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 const lock=useRef(false);
 useEffect(()=>{const c=new AbortController();setError('');adminRead<State>('/api/admin/ga4',v=>typeof v?.ready==='boolean'&&typeof v?.connected==='boolean',{signal:c.signal}).then(v=>{if(!c.signal.aborted)setData(v);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[refresh]);
 async function action(action:'connect'|'disconnect'){
  if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/ga4',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action}),signal:AbortSignal.timeout(20000)});const p=await r.json() as {error?:string;url?:string;revoked?:boolean};if(!r.ok)throw new Error(p.error||'Connection failed.');if(action==='connect'){if(!p.url)throw new Error('Google authorization URL is missing.');window.location.assign(p.url);return;}setMessage(p.revoked?'Google Analytics disconnected.':'Disconnected locally. Remove this app from your Google account connections to finish revoking Google access.');setRefresh(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{lock.current=false;setBusy(false);}
 }
 return <section className="vn-email-panel" aria-label="Google Analytics connection"><h3>Google Analytics</h3>{error&&<p role="alert">{error} <button disabled={busy} onClick={()=>setRefresh(n=>n+1)}>Retry status</button></p>}{message&&<p role="status">{message}</p>}{data&&<><p>Property {data.property||'not configured'} · {data.connected?'Google authorization saved — check Analytics for current report status':data.ready?'Ready to connect':'One-time Google OAuth setup needed'}</p><p>Connect a Google account with access to this property. We request read-only Analytics reports. Your store-owner login stays the same.</p><button disabled={busy||!data.ready} onClick={()=>void action('connect')}>{data.connected?'Reconnect Google Analytics':'Connect Google Analytics'}</button>{data.connected&&<button disabled={busy} onClick={()=>void action('disconnect')}>Disconnect</button>}<details><summary>Google setup instructions</summary><ol><li>In your Google Cloud project, keep Google Analytics Data API enabled.</li><li>Open Google Auth Platform (OAuth consent screen). Set up Vanta Noir Admin, your support email and contact email. Choose External for a personal Google account. Add your Analytics Google account as a test user.</li><li>Add only the https://www.googleapis.com/auth/analytics.readonly scope under Data Access.</li><li>Create an OAuth client of type Web application. Name it Vanta Noir Admin and add the authorized redirect URI shown below.</li><li>In Cloudflare → vanta-noir-api → Settings → Variables and Secrets, add GA4_OAUTH_CLIENT_ID as text and GA4_OAUTH_CLIENT_SECRET as a secret. Save/deploy, refresh this page, then connect.</li></ol><code>{data.redirectUri}</code><p>The numeric property is configured as {data.property}. A service-account JSON key is not needed. Keep the OAuth client secret out of chat and GitHub.</p><p>Google apps in Testing generally require reconnection after seven days for this scope. For a lasting connection, review Google’s publishing and verification requirements before switching to Production. Keep purchase marked as a key event. Reports reflect consent choices and reporting delays.</p></details></>}</section>;
}
