"use client";
import {useEffect,useRef,useState} from 'react';
import type {AdminProduct} from '@/lib/store-db';
import {isUnlaunched,launchIssues,LAUNCH_CHECKS} from '@/lib/launch-review.mjs';
type Review={product:AdminProduct;revision:string;certification:null|{mode:'in_stock'|'preorder';actor:string;certified_at:string;launched_at:string|null;current:boolean}};
export function LaunchReviewBox({products,onOpen}:{products:AdminProduct[];onOpen:()=>void}){return <button type="button" onClick={onOpen} className="vn-control-panel w-full text-left p-6 my-5"><strong className="text-xl">Launch review →</strong><p className="mt-2">{products.filter(isUnlaunched).length} products not launched · inspect designs, approve readiness, then launch when you choose.</p><small>Includes hidden drafts and every published preview. Prices stay hidden until you launch.</small></button>;}
export function LaunchReview({products,onEdit,onSaved}:{products:AdminProduct[];onEdit:(p:AdminProduct)=>void;onSaved:(p:AdminProduct)=>void}){
 const [query,setQuery]=useState(''),[page,setPage]=useState(1),[id,setId]=useState(''),[review,setReview]=useState<Review|null>(null),[mode,setMode]=useState<'in_stock'|'preorder'>('in_stock'),[checks,setChecks]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const requestId=useRef(0),sending=useRef(false);
 async function load(productId:string){const request=++requestId.current;setReview(null);setChecks({});setError('');setLoading(true);try{const r=await fetch(`/api/admin/launch-review?id=${encodeURIComponent(productId)}`,{cache:'no-store',signal:AbortSignal.timeout(20000)});const d=await r.json() as Review & {error?:string};if(!r.ok)throw Error(d.error||'Could not load review.');if(request!==requestId.current)return;setReview(d);setMode(d.certification?.current?d.certification.mode:d.product.details?.availability==='preorder'?'preorder':'in_stock');}catch(e){if(request===requestId.current)setError(e instanceof Error?e.message:'Could not load review.');}finally{if(request===requestId.current)setLoading(false);}}
 useEffect(()=>{if(id)void load(id);return()=>{requestId.current++;};},[id]);
 const filtered=products.filter(isUnlaunched).filter(p=>`${p.name} ${p.id} ${p.category} ${p.variants.map(v=>v.sku).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const pages=Math.max(1,Math.ceil(filtered.length/12)),currentPage=Math.min(page,pages),p=review?.product,issues=p?launchIssues(p,mode):[];
 const allChecked=Object.keys(LAUNCH_CHECKS).every(key=>checks[key]);
 const certified=review?.certification?.current&&review.certification.mode===mode&&!review.certification.launched_at;
 async function act(action:'certify'|'launch'){
  if(!review||sending.current)return;sending.current=true;setBusy(true);setError('');setMessage('');
  try{const r=await fetch('/api/admin/launch-review',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(20000),body:JSON.stringify({productId:review.product.id,revision:review.revision,mode,checks,action})});const d=await r.json() as {product:AdminProduct;error?:string};if(!r.ok)throw Error(d.error||'Review could not be saved.');onSaved(d.product);setMessage(action==='certify'?'Certified ready. It has not been launched.':'Launched with the approved price. No announcement emails were sent.');await load(review.product.id);}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false);sending.current=false;}
 }
 return <section className="vn-control-panel vn-launch-review p-6"><h2 className="text-2xl">Products awaiting launch</h2><p className="my-3">Publish shows a preview with no price and no ordering. Draft stays hidden. Review one design below, certify it, then use Launch this product when you are ready.</p>
 <label className="block">Find a garment or SKU<input className="block w-full border p-3 my-2" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="Search name, SKU, category or product ID"/></label>
 <p>{filtered.length} products · page {currentPage} of {pages}</p><div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-4">{filtered.slice((currentPage-1)*12,currentPage*12).map(item=><button type="button" disabled={busy} className="vn-launch-card border p-3 text-left" key={item.id} aria-pressed={id===item.id} onClick={()=>{setId(item.id);setMessage('');}}><img src={item.imageUrl} alt={item.imageAlt||item.name} loading="lazy" className="w-full h-48 object-contain"/><strong>{item.name}</strong><p>{item.status==='draft'?'Hidden draft':'Visible preview'} · Price hidden until launch</p><small>{item.id}</small></button>)}</div>
 {!filtered.length&&<p>No products awaiting launch match this search.</p>}<div className="flex gap-3"><button className="vn-pill" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Previous</button><button className="vn-pill" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Next</button></div>
 {loading&&<p role="status">Loading the latest product and stock…</p>}{error&&<p role="alert" className="my-4">{error} {id&&<button disabled={busy} onClick={()=>void load(id)}>Reload review</button>}</p>}{message&&<p role="status" className="my-4">{message}</p>}
 {p&&review&&<div className="border-t mt-6 pt-6"><h3 className="text-xl">Review · {p.name}</h3><p>{p.id} · Selling price: <strong>{new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(p.priceKobo/100)}</strong></p>
 <div className="flex gap-3 my-4"><button className="vn-pill" disabled={busy} onClick={()=>onEdit(p)}>Edit specifications, price &amp; stock</button><a className="vn-pill" target="_blank" rel="noreferrer" href={`/api/admin/tech-packs?id=${encodeURIComponent(p.id)}`}>Open garment tech pack ↗</a></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{p.images.map(i=><figure key={i.id}><img loading="lazy" className="w-full h-48 object-contain" src={i.imageUrl} alt={i.imageAlt}/><figcaption>{i.color} · {i.imageAlt}</figcaption></figure>)}</div>
 <p className="my-3 whitespace-pre-wrap">{p.details?.features}</p><p className="whitespace-pre-wrap">{p.details?.artworkLock}</p>
 <label className="block my-4">Launch as<select disabled={busy} className="block border p-2" value={mode} onChange={e=>{setMode(e.target.value as typeof mode);setChecks({});}}><option value="in_stock">Ready stock</option><option value="preorder">Preorder with confirmed dispatch timing</option></select></label>
 <p>Recorded units / preorder capacity: {p.variants.filter(v=>v.active).reduce((sum,v)=>sum+v.stock,0)}. {p.details?.dispatchNote}</p>
 {issues.length>0?<div className="my-4"><h4>Complete these before certification</h4><ul className="list-disc pl-6">{issues.map((issue:string)=><li key={issue}>{issue}</li>)}</ul></div>:<p className="my-4">Required fields are present. Check the actual content and approved sample before certifying.</p>}
 {review.certification&&<p className="my-4">{review.certification.launched_at?'Previously launched':certified?'Certified ready — awaiting your launch decision':'Previous certificate needs a fresh review'} · {review.certification.actor} · {review.certification.certified_at}</p>}
 <fieldset disabled={busy}><legend>Owner certification · this exact product revision</legend>{Object.entries(LAUNCH_CHECKS).map(([key,label])=><label key={key} className="flex gap-3 my-3"><input type="checkbox" checked={!!checks[key]} onChange={e=>setChecks({...checks,[key]:e.target.checked})}/><span>{String(label)}</span></label>)}</fieldset>
 <div className="flex gap-3 my-4"><button className="vn-pill" disabled={busy||!!issues.length||!allChecked} onClick={()=>void act('certify')}>Certify ready · keep unlaunched</button><button className="vn-pill" disabled={busy||!!issues.length||!allChecked||!certified} onClick={()=>void act('launch')}>Launch this product</button></div><p>Launching publishes this product, approves the displayed price and enables the selected availability. Stock is unchanged. Product or stock changes invalidate certification. This does not send release emails.</p>
 </div>}
 </section>;
}
