'use client';
import {useEffect,useState} from 'react';
import {adminRead,hasArray} from '@/lib/admin-read';
import {Button} from '@/components/ui/button';
export function LegacyRecords(){
 const [table,setTable]=useState('orders'),[page,setPage]=useState(1),[data,setData]=useState<{rows:Record<string,unknown>[];total:number;hasMore:boolean}|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');adminRead<{rows:Record<string,unknown>[];total:number;hasMore:boolean}>(`/api/admin/legacy?table=${table}&page=${page}`,hasArray('rows'),{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setData(value);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[table,page,attempt]);
 return <section className="vn-control-panel"><h2>Earlier backend records</h2><p>Original records retained during the upgrade. These are read-only and excluded from current sales totals. Imported products are drafts until their prices, images and sizes are reviewed.</p><label>Record type <select value={table} onChange={e=>{setTable(e.target.value);setPage(1);}}>{['orders','order_items','products','variants','product_images','product_media','inventory_adjustments','discounts'].map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select></label>{error&&<p role="alert">{error} <button onClick={()=>setAttempt(n=>n+1)}>Retry records</button></p>}{!error&&!data&&<p role="status">Loading…</p>}{data&&<><p>{data.total} preserved records</p><div className="overflow-x-auto"><table><thead><tr>{Object.keys(data.rows[0]||{}).map(k=><th key={k} className="p-3 text-left">{k.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{data.rows.map((row,i)=><tr key={i}>{Object.values(row).map((value,j)=><td key={j} className="p-3">{String(value??'—')}</td>)}</tr>)}</tbody></table></div><div className="vn-control-actions"><Button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page}</span><Button disabled={!data.hasMore} onClick={()=>setPage(page+1)}>Next</Button></div></>}</section>;
}
