'use client';
import {useEffect,useRef,useState} from 'react';
import {Bell,Search} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {AdminProduct} from '@/lib/store-db';
import {formatNaira} from '@/lib/catalog';
import {useAdminNavigation} from './unsaved-changes';
type Row=Record<string,any>;
export type AdminTarget={section:string;query?:string;customerEmail?:string;status?:string;resource?:string;stockFilter?:'low'|'out'|'available';productStatus?:string};
export function AdminSearch({products,onNavigate,onProduct}:{products:AdminProduct[];onNavigate:(target:AdminTarget)=>void;onProduct:(product:AdminProduct)=>void}){
 const [open,setOpen]=useState(false),[q,setQ]=useState(''),[result,setResult]=useState<Row>({}),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(v=>!v);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{setResult({});setError('');if(!open||q.trim().length<2){setLoading(false);return;}const controller=new AbortController();setLoading(true);const timer=setTimeout(async()=>{try{const r=await fetch('/api/admin/management?resource=search&q='+encodeURIComponent(q),{signal:controller.signal});if(!r.ok)throw new Error('Order and customer search unavailable. Try again.');setResult(await r.json());}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{if(!controller.signal.aborted)setLoading(false);}},300);return()=>{clearTimeout(timer);controller.abort();};},[q,open]);
 const matching=q.trim()?products.filter(p=>[p.name,p.category,p.id,...p.variants.map(v=>v.sku)].join(' ').toLowerCase().includes(q.trim().toLowerCase())).slice(0,8):[];
 const links=[['overview','Overview'],['products','Products'],['orders','Orders'],['inventory','Inventory'],['customers','Customers'],['returns','Returns & exchanges'],['delivery','Delivery'],['analytics','Analytics'],['discounts','Discounts'],['settings','Settings'],['staff','Staff access'],['activity','Activity']].filter(([,label])=>label.toLowerCase().includes(q.trim().toLowerCase()));
 function go(target:AdminTarget){setOpen(false);onNavigate(target);}
 return <><button className="vn-global-search" onClick={()=>setOpen(true)}><Search size={16}/><span>Search anything…</span><kbd>⌘ / Ctrl K</kbd></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="vn-management-dialog"><DialogTitle>Search your store</DialogTitle><DialogDescription>Find products, SKUs, orders, customers and management tools.</DialogDescription><input autoFocus aria-label="Search your store" value={q} onChange={e=>setQ(e.target.value)} placeholder="Name, order reference, email or SKU"/><div className="vn-search-results">{links.length>0&&<h3>Go to</h3>}{links.map(([section,label])=><button key={section} onClick={()=>go({section})}>{label}</button>)}{matching.length>0&&<h3>Products</h3>}{matching.map(p=><button key={p.id} onClick={()=>{setOpen(false);onProduct(p);}}>{p.name}<small>{p.status} · {p.category}</small></button>)}{loading&&<p role="status">Searching orders and customers…</p>}{error&&<p role="alert">{error}</p>}{result.orders?.length>0&&<h3>Orders</h3>}{result.orders?.map((o:Row)=><button key={o.reference} onClick={()=>go({section:'orders',query:o.reference})}>{o.reference}<small>{o.firstName} {o.lastName} · {o.status.replaceAll('_',' ')}</small></button>)}{result.customers?.length>0&&<h3>Customers</h3>}{result.customers?.map((c:Row)=><button key={c.email} onClick={()=>go({section:'customers',query:c.email})}>{c.name}<small>{c.email} · {c.orders} orders</small></button>)}{q.trim().length>=2&&!loading&&!error&&!links.length&&!matching.length&&!result.orders?.length&&!result.customers?.length&&<p>No matches. Try another name, email or reference.</p>}</div></DialogContent></Dialog></>;
}
export function NotificationBell({user,lowStock,drafts,onNavigate,onCampaign,onFulfilment,onThreshold}:{onThreshold:(n:number)=>void;onFulfilment:(n:number)=>void;user:string;lowStock:number;drafts:number;onNavigate:(t:AdminTarget)=>void;onCampaign:(id:string)=>void}){
 const [open,setOpen]=useState(false),[data,setData]=useState<Row>({}),[error,setError]=useState(''),[seen,setSeen]=useState('');const campaignCallback=useRef(onCampaign);campaignCallback.current=onCampaign;
 const storageKey='vn-admin-notifications:'+user;
 useEffect(()=>{try{setSeen(localStorage.getItem(storageKey)||'');}catch{}},[storageKey]);
 useEffect(()=>{let active=true;const controller=new AbortController();async function load(){if(document.hidden)return;try{const r=await fetch('/api/admin/management?resource=attention',{signal:controller.signal,cache:'no-store'});if(!r.ok)throw new Error();const value=await r.json() as Row;if(active){setData(value);setError('');campaignCallback.current(value.campaignProductId);onThreshold(value.lowStockThreshold);onFulfilment((value.orders||[]).filter((r:Row)=>['paid','processing'].includes(r.status)).reduce((sum:number,r:Row)=>sum+Number(r.count),0));}}catch{if(active)setError('Alerts could not refresh. Open again to retry.');}}void load();const timer=setInterval(load,60000);const visibility=()=>{if(!document.hidden)void load();};window.addEventListener('visibilitychange',visibility);return()=>{active=false;controller.abort();clearInterval(timer);window.removeEventListener('visibilitychange',visibility);};},[open]);
 const count=(s:string)=>Number(data.orders?.find((r:Row)=>r.status===s)?.count||0);
 const alerts:Array<{id:string;count:number;label:string;target:AdminTarget}>=[{id:'paid',count:count('paid'),label:'paid orders to process',target:{section:'orders',status:'paid'}},{id:'processing',count:count('processing'),label:'orders being processed',target:{section:'orders',status:'processing'}},{id:'review',count:count('paid_stock_review'),label:'paid orders needing stock review',target:{section:'orders',status:'paid_stock_review'}},{id:'low',count:lowStock,label:'variants running low',target:{section:'inventory',stockFilter:'low' as const}},{id:'returns',count:Number(data.returns?.count||0),label:'open returns or exchanges',target:{section:'returns'}},{id:'emails',count:Number(data.emails?.count||0),label:'emails needing delivery review',target:{section:'customers'}},{id:'drafts',count:drafts,label:'draft products',target:{section:'products',productStatus:'draft'}}].filter(a=>a.count>0);
 const signature=JSON.stringify([alerts.map(a=>[a.id,a.count]),data.orders,data.returns?.latest,data.emails?.latest]),unread=alerts.length>0&&signature!==seen;
 return <><button className="vn-notification-trigger" aria-label={unread?'Notifications, unread alerts':'Notifications'} onClick={()=>setOpen(true)}><Bell size={20}/>{unread&&<span/>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="vn-management-dialog"><DialogTitle>Needs your attention</DialogTitle><DialogDescription>Current tasks across your store. Checks every minute while this admin is visible.</DialogDescription>{error&&<p role="alert">{error}</p>}{!data.checkedAt&&!error&&<p>Loading alerts…</p>}{data.checkedAt&&!alerts.length&&<p>No outstanding alerts.</p>}{alerts.map(a=><button className="vn-alert-link" key={a.id} onClick={()=>{setOpen(false);onNavigate(a.target);}}><strong>{a.count}</strong> {a.label} →</button>)}<button className="vn-pill" disabled={!unread} onClick={()=>{setSeen(signature);try{localStorage.setItem(storageKey,signature);}catch{}}}>Mark reviewed on this device</button>{data.checkedAt&&<small>Last checked {new Date(data.checkedAt).toLocaleTimeString()}. Reviewed alerts remain here until resolved.</small>}</DialogContent></Dialog></>;
}
export function CustomersPanel({initialQuery='',onOrders}:{initialQuery?:string;onOrders:(email:string)=>void}){
 const [q,setQ]=useState(initialQuery),[query,setQuery]=useState(initialQuery),[page,setPage]=useState(1),[data,setData]=useState<Row>({}),[error,setError]=useState(''),[loading,setLoading]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setData({});fetch('/api/admin/management?'+new URLSearchParams({resource:'customers',q:query,page:String(page)}),{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Customers could not load.');setData(await r.json());}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[query,page,attempt]);
 return <section className="vn-control-panel"><h2>Customers</h2><p>Customer history grouped by checkout email. Paid totals include delivery and exclude cancelled orders; refunds are available in Sales reports.</p><form className="vn-overview-tools" onSubmit={e=>{e.preventDefault();setQuery(q);setPage(1);setAttempt(a=>a+1);}}><input aria-label="Search customers" placeholder="Customer name or email" value={q} onChange={e=>setQ(e.target.value)}/><button>Search</button></form>{loading&&<p role="status">Loading customers…</p>}{error&&<p role="alert">{error} <button onClick={()=>setAttempt(a=>a+1)}>Retry</button></p>}<div className="vn-ref-table-wrap"><table><thead><tr><th>Customer</th><th>Orders / paid</th><th>Paid total</th><th>Last order</th><th>History</th></tr></thead><tbody>{data.customers?.map((c:Row)=><tr key={c.email}><td>{c.name}<small>{c.email}</small></td><td>{c.orders} / {c.paidOrders}</td><td>{formatNaira(c.paidKobo)}</td><td>{c.lastOrder.slice(0,10)}</td><td><button onClick={()=>onOrders(c.email)}>View orders →</button></td></tr>)}</tbody></table></div>{data.customers?.length===0&&<p>No customers match this search.</p>}<div className="vn-overview-tools"><button disabled={loading||page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page}</span><button disabled={loading||!data.hasMore} onClick={()=>setPage(page+1)}>Next</button></div></section>;
}
export function IntegrationStatus(){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;setError('');fetch('/api/admin/management?resource=integrations').then(async r=>{if(!r.ok)throw new Error('Connection status unavailable.');const v=await r.json() as Row;if(active)setData(v);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[attempt]);
 return <section className="vn-control-panel"><h2>Connections</h2>{error&&<p role="alert">{error}</p>}<button className="vn-pill" onClick={()=>setAttempt(a=>a+1)}>Check connections</button>{data&&<><p>Paystack: {data.paymentsConfigured?'Configured':'Awaiting credentials'} · Order email: {data.emailConfigured?'Configured':'Awaiting credentials'}</p><p>GA4 reporting: {data.ga4Configured?'Credentials configured — check Analytics for report status':'Awaiting reporting credentials'}</p><details><summary>Connect measured conversion</summary><ol><li>Enable the Google Analytics Data API in your Google Cloud project and create a service account.</li><li>Give its email Viewer access to the existing Vanta Noir GA4 property.</li><li>In Cloudflare Worker settings, set GA4_PROPERTY_ID to the numeric property ID, and save GA4_SERVICE_ACCOUNT_JSON as a secret containing that service account’s JSON key.</li><li>Keep purchase marked as a key event in GA4. Refresh Analytics after configuration.</li></ol><p>Your G-29RJ57JB76 measurement ID is already in the storefront; it is not the numeric property ID. Never paste the private key into a product, GitHub or chat. Conversion uses GA4’s reporting timezone and measured sessions; sales use UTC order dates.</p></details><p>Courier: {data.courierReceiverConfigured?'Webhook receiver configured; a courier connection must also be arranged.':'Manual tracking available. Automatic courier updates await a provider connection.'}</p></>}</section>;
}
