'use client';
import {SalesDesk} from './sales-desk';
import {adminRead} from '@/lib/admin-read';
import {useEffect,useState,useRef} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {roleResources,type StaffRole} from '@/lib/operations-permissions';
import {productsFromCSV,csvCell} from '@/lib/catalog-csv';
import {formatNaira} from '@/lib/catalog';
import {allowedOrderStatuses} from '@/lib/order-status';
import './operations.css';
import {useAdminNavigation,useUnsavedChanges,useOperationDraft} from './unsaved-changes';
import {ApprovalsPanel} from './approvals-panel';
import {RewardCampaigns} from './reward-campaigns';
import {StaffAccess} from './staff-access';
type Row=Record<string,any>;
const labels:Record<string,string>={sales:'Sales desk',requests:'My requests',orders:'Orders',bulk:'Bulk catalogue',inventory:'Stock history',returns:'Returns & exchanges',promotions:'Promotions',reports:'Sales reports',courier:'Delivery',staff:'Staff access',activity:'Activity'};
function Choice({value,onChange,values,label}:{value:string;onChange:(v:string)=>void;values:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select>}
function Field({label,value,onChange,type='text'}:{label:string;value:any;onChange:(v:string)=>void;type?:string}){return <Label className="ops-field">{label}<Input type={type} value={value} onChange={e=>onChange(e.target.value)}/></Label>}
function Grid({rows,columns}:{rows:Row[];columns:Array<[string,string]>}){return <div className="ops-table"><Table><TableHeader><TableRow>{columns.map(([key,label])=><TableHead key={key}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={r.id||i}>{columns.map(([key])=><TableCell key={key}>{String(r[key]??'—')}</TableCell>)}</TableRow>)}</TableBody></Table>{!rows.length&&<p className="ops-empty">No records yet.</p>}</div>}
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function OperationsPanel({role,initialSection,onChanged,dedicated=false,supportWorkspace=false}:{supportWorkspace?:boolean;dedicated?:boolean;role:StaffRole;initialSection?:string;onChanged?:()=>Promise<void>}){
 const sections=role==='owner'?roleResources[role]:[...roleResources[role],'requests'], [section,setSection]=useState(initialSection && sections.includes(initialSection as typeof sections[number]) ? initialSection as typeof sections[number] : sections[0]),[data,setData]=useState<Row>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [priceQuery,setPriceQuery]=useState(''),[editingPrices,setEditingPrices]=useState<Record<string,boolean>>({});
 const [csv,setCsv]=useState(''),[preview,setPreview]=useState<Row[]>([]),[result,setResult]=useState<Row[]>([]),[prices,setPrices]=useState<Record<string,string>>({});
 const requestId=useRef(0),savingLock=useRef(false);
 const navigate=useAdminNavigation();
 useUnsavedChanges({name:'Operations save',dirty:false,busy,discard:()=>{}});
 useUnsavedChanges({name:'Bulk prices',dirty:Object.keys(prices).length>0,busy:busy&&Object.keys(prices).length>0,save:()=>savePrices(),discard:()=>{setPrices({});setEditingPrices({});}});
 useUnsavedChanges({name:'CSV import',dirty:csv.length>0,busy:busy&&csv.length>0,discard:()=>{setCsv('');setPreview([]);}});
 async function load(nextPage=page){if(section==='requests'||section==='sales'){setLoading(false);return;}const id=++requestId.current;setLoading(true);setError('');try{const p=new URLSearchParams({resource:section,page:String(nextPage),q,status:status==='all'?'':status});if(from)p.set('from',from);if(to)p.set('to',to);const value=await adminRead<Row>('/api/admin/operations?'+p,v=>!!v&&typeof v==='object'&&!Array.isArray(v));if(id!==requestId.current)return;setData(value);}catch(e){if(id===requestId.current){setError((e instanceof Error?e.message:'Could not load.')+' Existing entries have been kept.');}}finally{if(id===requestId.current)setLoading(false);}}
 useEffect(()=>{void load();return()=>{requestId.current++;};},[section,page,status,from,to]);
 async function save(action:string,values:unknown){if(savingLock.current)return null;savingLock.current=true;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data:values}),signal:AbortSignal.timeout(30000)});const v=await r.json() as Row;if(!r.ok)throw new Error(v.error);if(v.pending){setNotice('Submitted for owner approval. The live store is unchanged. Track it in My requests.');return Array.isArray(values)?values.map((row:Row)=>({...row,ok:true,pending:true})):v;}await load();setNotice(Array.isArray(v.result)&&v.result.some((r:Row)=>!r.ok)?'Some rows need attention. Review the results below.':'Changes saved ✓');try{await onChanged?.();}catch{setNotice('Changes saved. Use Refresh to update the other dashboard figures.');}return v.result;}catch(e){setError(e instanceof Error?e.message:'Could not save.');return null;}finally{savingLock.current=false;setBusy(false);}}

 async function savePrices(id?:string){
  const changed=(data.products||[]).filter((p:Row)=>prices[p.id]!==undefined&&(!id||p.id===id));
  if(changed.some((p:Row)=>!prices[p.id].trim()||!Number.isFinite(Number(prices[p.id]))||Number(prices[p.id])<1)){setError('Enter a valid price of at least ₦1. Your entries have been kept.');return false;}
  const results:Row[]=[];
  for(let offset=0;offset<changed.length;offset+=100){const r=await save('prices',changed.slice(offset,offset+100).map((p:Row)=>({id:p.id,expectedPrice:p.priceKobo,priceKobo:Math.round(Number(prices[p.id])*100)})));if(!r)break;results.push(...r);}
  if(results.length){setEditingPrices(current=>Object.fromEntries(Object.entries(current).filter(([key])=>!results.some(item=>item.id===key&&item.ok))));setResult(results);setPrices(current=>Object.fromEntries(Object.entries(current).filter(([key])=>!results.some(item=>item.id===key&&item.ok))));}
  return changed.every((p:Row)=>results.some(r=>r.id===p.id&&r.ok));
 }

 const products=(data.products||[]) as Row[];
 return <section className="ops-panel" aria-label="Store operations"><div className="ops-heading"><div><p>VANTA NOIR / OPERATIONS</p><h2>Run your store</h2></div><Button variant="outline" onClick={()=>navigate(()=>void load())} disabled={loading||busy}>Refresh</Button></div>
 {role!=='owner'&&<p className="ops-notice">{supportWorkspace?'Your order and return updates require owner approval before taking effect.':'Sales submissions reserve stock immediately; the owner approves the final sale. Other changes require approval before taking effect.'}</p>}
 <Tabs value={section} onValueChange={s=>navigate(()=>{setSection(s);setPage(1);setData({});setNotice('');setError('');})}><TabsList className="ops-tabs">{(dedicated?[section]:sections).map(s=><TabsTrigger key={s} value={s}>{labels[s]}</TabsTrigger>)}</TabsList>
 {error&&<p role="alert" className="ops-error">{error}</p>}{notice&&<p role="status" className="ops-notice">{notice}</p>}{loading&&!Object.keys(data).length?<p className="ops-empty">Loading {labels[section].toLowerCase()}…</p>:<TabsContent value={section} className="ops-content"><fieldset disabled={busy} style={{minWidth:0,border:0,padding:0}}>
 {section==='sales'&&<SalesDesk owner={role==='owner'} onChanged={onChanged}/>}
 {section==='requests'&&<ApprovalsPanel/>}
 {section==='orders'&&<><div className="ops-counts">{(data.counts||[]).map((c:Row)=><button key={c.status} onClick={()=>navigate(()=>{setStatus(c.status);setPage(1);})}><strong>{c.count}</strong>{c.status.replaceAll('_',' ')}</button>)}</div><div className="ops-controls"><Field label="Find an order" value={q} onChange={setQ}/><Button onClick={()=>{navigate(()=>{setPage(1);void load(1);});}}>Search</Button><Choice label="Order status" value={status} onChange={v=>navigate(()=>{setStatus(v);setPage(1);})} values={['all','pending_payment','paid','paid_stock_review','processing','shipped','delivered','cancelled']}/></div>{!(data.orders||[]).length&&<p className="ops-empty">No orders match these filters.</p>}<Pager page={page} setPage={n=>navigate(()=>setPage(n))} more={Boolean(data.hasMore)}/>{(data.orders||[]).map((o:Row)=><OrderCard key={o.id+o.status+o.updatedAt} order={o} role={role} save={save} busy={busy}/>)}</>}
 {section==='bulk'&&<><p>Edit prices in naira. Save one row or use Save edited prices. Stock is managed separately below.</p><div className="vn-price-toolbar"><Field label="Find a product to price" value={priceQuery} onChange={setPriceQuery}/><Button disabled={busy||!Object.keys(prices).length} onClick={()=>void savePrices()}>Save edited prices ({Object.keys(prices).length})</Button><span aria-live="polite">{Object.keys(prices).length?'Unsaved price changes':'All prices saved'}</span></div><div className="ops-table vn-price-table"><Table><TableHeader><TableRow><TableHead>Product</TableHead><TableHead>Price (₦)</TableHead><TableHead>Status</TableHead><TableHead>Save</TableHead></TableRow></TableHeader><TableBody>{products.filter(p=>p.name.toLowerCase().includes(priceQuery.toLowerCase())).map(p=><TableRow key={p.id} onDoubleClick={()=>{if(!busy)setEditingPrices(current=>({...current,[p.id]:true}));}}><TableCell>{p.name}</TableCell><TableCell><Input aria-label={'Price for '+p.name} readOnly={!editingPrices[p.id]} type="number" min="1" step="0.01" value={prices[p.id]??p.priceKobo/100} onChange={e=>setPrices({...prices,[p.id]:e.target.value})}/></TableCell><TableCell>{p.status}</TableCell><TableCell><Button disabled={busy} onClick={()=>{if(editingPrices[p.id]){if(prices[p.id]===undefined)setEditingPrices(current=>({...current,[p.id]:false}));else void savePrices(p.id);}else setEditingPrices(current=>({...current,[p.id]:true}));}}>{busy?'Saving…':editingPrices[p.id]?'Save':'Edit'}</Button></TableCell></TableRow>)}</TableBody></Table></div>

 <details><summary>Variation stock adjustments</summary>{products.map(p=><details key={p.id}><summary>{p.name}</summary>{p.variants.filter((v:Row)=>v.active).map((v:Row)=><StockRow key={v.id+'-'+v.stock} variant={v} busy={busy} save={save}/>)}</details>)}</details>
 <details><summary>Import new designs from CSV</summary><p>One row per size and colour. Repeat the slug to group variations. Separate multiple image URLs with |. All imported products start as drafts.</p><Button variant="outline" onClick={()=>download('vanta-noir-product-template.csv','slug,name,category,description,priceNaira,imageUrl,size,color,colorHex,sku,stock\n')}>Download blank template</Button><Label className="ops-field">Choose CSV<Input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(f){setPreview([]);setCsv(await f.text());}}}/></Label><Textarea aria-label="Product CSV" value={csv} onChange={e=>{setCsv(e.target.value);setPreview([]);}}/><Button onClick={()=>{try{setPreview(productsFromCSV(csv));setError('');}catch(e){setError((e as Error).message);}}}>Review import</Button>{preview.length>0&&<><Grid rows={preview.map(p=>({name:p.name,variations:p.variants.length,price:formatNaira(p.priceKobo)}))} columns={[["name","Design"],["variations","Variations"],["price","Price"]]}/><Button disabled={busy} onClick={async()=>{const r=await save('import',preview);if(r){setResult(r);if(r.every((item:Row)=>item.ok)){setPreview([]);setCsv('');}}}}>Import {preview.length} draft designs</Button></>}</details>
 {!!result.length&&<Grid rows={result.map(r=>({...r,outcome:r.pending?'Awaiting owner approval':r.ok?'Saved':r.error||'Changed elsewhere; refresh and retry'}))} columns={[["name","Design"],["id","Record"],["outcome","Result"]]}/>}</>}
 {section==='inventory'&&<><p>Stock movements recorded from this upgrade include sales and exchanges, alongside existing adjustments and returns. Earlier sales are not reconstructed.</p><div className="ops-controls"><Field label="Search product, colour, size, SKU or reason" value={q} onChange={setQ}/><Button onClick={()=>{navigate(()=>{setPage(1);void load(1);});}}>Search</Button></div><Pager page={page} setPage={n=>navigate(()=>setPage(n))} more={(data.rows||[]).length>50}/><Grid rows={(data.rows||[]).slice(0,50)} columns={[["created_at","Date"],["name","Product"],["color","Colour"],["size","Size"],["sku","SKU"],["old_stock","Before"],["new_stock","After"],["reason","Reason"],["actor","Changed by"]]}/></>}
 {section==='returns'&&<><Pager page={page} setPage={n=>navigate(()=>setPage(n))} more={(data.returns||[]).length>50}/>{!(data.returns||[]).length&&<p className="ops-empty">No return or exchange requests yet.</p>}{(data.returns||[]).slice(0,50).map((r:Row)=><ReturnCard key={r.id+'-'+r.version+'-'+r.exchange_status} row={r} variants={data.variants||[]} role={role} busy={busy} save={save}/>)}</>}
 {section==='promotions'&&<><RewardCampaigns campaigns={data.campaigns||[]} gifts={data.giftVariants||[]} save={save} busy={busy}/><p>Codes are checked on the server at checkout. A quantity requirement creates a bundle offer. Leave product IDs empty to include the whole catalogue.</p><PromotionForm busy={busy} save={save}/>{(data.promotions||[]).map((p:Row)=><details key={p.code+'-'+p.version}><summary>{p.code} · {p.title} · {p.active?'Enabled':'Paused'} · {p.redeemed} paid uses</summary><PromotionForm row={p} busy={busy} save={save}/></details>)}</>}
 {section==='reports'&&<><div className="ops-controls"><Field type="date" label="Paid from" value={from} onChange={setFrom}/><Field type="date" label="Through" value={to} onChange={setTo}/><Button onClick={()=>download('vanta-noir-sales.csv',[['Product','Size','Colour','Units','Gross before discounts/refunds'],...(data.bestsellers||[]).map((r:Row)=>[r.product_name,r.size,r.color,r.units,r.gross/100])].map(r=>r.map(csvCell).join(',')).join('\n'))}>Export report</Button></div><div className="ops-counts">{[['Paid orders',data.sales?.orders||0],['Collected including delivery',formatNaira(data.sales?.revenue||0)],['Discounts applied',formatNaira(data.sales?.discounts||0)],['Refunds recorded in period',formatNaira(data.refunds?.amount||0)]].map(([label,value])=><div key={label}><strong>{value}</strong>{label}</div>)}</div><p>Product totals below are before discounts and refunds. Refund figures use the date the return record was last updated. These are sales summaries, not profit calculations.</p><Grid rows={(data.bestsellers||[]).map((r:Row)=>({...r,gross:formatNaira(r.gross)}))} columns={[["product_name","Product"],["size","Size"],["color","Colour"],["units","Units sold"],["gross","Gross product sales"]]}/></>}
 {section==='courier'&&<><h3>{data.connected?'Tracking receiver configured':'Courier connection pending'}</h3><p>Use Orders to enter a carrier and tracking number now. Automatic updates need a supported courier connection and its signing secret. Configuring the receiver alone does not connect a courier.</p><Grid rows={data.events||[]} columns={[["created_at","Received"],["reference","Order"],["status","Delivery status"]]}/></>}
 {section==='staff'&&<StaffAccess staff={data.staff||[]} busy={busy} save={save}/>}
 {section==='activity'&&<><Pager page={page} setPage={n=>navigate(()=>setPage(n))} more={(data.rows||[]).length>50}/><Grid rows={(data.rows||[]).slice(0,50)} columns={[["created_at","Date"],["actor","Staff member"],["action","Action"],["entity","Record"],["detail","Details"]]}/></>}
 </fieldset></TabsContent>}</Tabs></section>;
}
type Save=(action:string,data:unknown)=>Promise<any>;
function Pager({page,setPage,more}:{page:number;setPage:(n:number)=>void;more:boolean}){return <div className="ops-controls vn-pagination"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page}</span><Button variant="outline" disabled={!more} onClick={()=>setPage(page+1)}>Next</Button></div>}
function StockRow({variant:v,busy,save}:{variant:Row;busy:boolean;save:Save}){
 const [stock,setStock]=useState(String(v.stock)),[reason,setReason]=useState(''),[editing,setEditing]=useState(false);
 const valid=reason.trim().length>=3&&/^\d+$/.test(stock)&&Number(stock)<=100000&&Number(stock)!==v.stock;
 async function commit(){if(!valid)return false;const ok=!!await save('stock',{variantId:v.id,expectedStock:v.stock,stock:Number(stock),reason});if(ok){draft.markSaved();setEditing(false);}return ok;}
 const draft=useOperationDraft('Stock '+v.sku,{stock,reason},x=>{setStock(x.stock);setReason(x.reason);setEditing(false);},busy,commit);
 return <div onDoubleClick={()=>{if(!busy)setEditing(true);}}><div className="vn-editor-heading"><span>{v.sku} · {v.color} / {v.size} · {v.stock} units</span><Button disabled={busy||(editing&&!valid)} onClick={()=>editing?void commit():setEditing(true)}>{editing?'Save':'Edit'}</Button>{editing&&<Button variant="outline" disabled={busy} onClick={()=>{setStock(String(v.stock));setReason('');setEditing(false);}}>Cancel</Button>}</div>{editing&&<fieldset className="ops-stock" disabled={busy}><Field label="Counted stock" type="number" value={stock} onChange={setStock}/><Field label="Reason / receipt reference" value={reason} onChange={setReason}/></fieldset>}</div>;
}
function OrderCard({order:o,role,busy,save}:{order:Row;role:StaffRole;busy:boolean;save:Save}){const [status,setStatus]=useState(o.status),[carrier,setCarrier]=useState(o.carrier),[tracking,setTracking]=useState(o.trackingNumber),[url,setUrl]=useState(o.trackingUrl),[estimate,setEstimate]=useState(o.deliveryEstimate);useOperationDraft('Order '+o.reference,{status,carrier,tracking,url,estimate},x=>{setStatus(x.status);setCarrier(x.carrier);setTracking(x.tracking);setUrl(x.url);setEstimate(x.estimate);},busy);const allowed=allowedOrderStatuses(o.status,o.paymentStatus).filter(s=>role==='owner'||['processing','shipped','delivered'].includes(s));return <details><summary>{o.reference} · {o.firstName} {o.lastName} · {o.status.replaceAll('_',' ')} · {formatNaira(o.totalKobo)}</summary>{o.paymentStatus!=='paid'&&o.providerStatus&&<p>Latest Paystack check: {o.providerStatus}</p>}<p>{o.items.map((i:Row)=>`${i.quantity} × ${i.productName} (${i.color}, ${i.size})`).join(' · ')}</p><p>{[o.addressLine1,o.addressLine2,o.city,o.state].filter(Boolean).join(', ')} · {o.phone}</p><div className="ops-controls"><Choice label="Next order status" value={status} onChange={setStatus} values={[...new Set([o.status,...allowed])]}/><Button disabled={busy||status===o.status||!allowed.includes(status)} onClick={()=>void save('order',{reference:o.reference,status})}>Update status</Button></div><div className="ops-fields"><Field label="Carrier" value={carrier} onChange={setCarrier}/><Field label="Tracking number" value={tracking} onChange={setTracking}/><Field label="HTTPS tracking link" value={url} onChange={setUrl}/><Field label="Delivery estimate" value={estimate} onChange={setEstimate}/></div><Button disabled={busy||o.paymentStatus!=='paid'} onClick={()=>void save('tracking',{reference:o.reference,carrier,trackingNumber:tracking,trackingUrl:url,deliveryEstimate:estimate})}>Save delivery details</Button></details>}
function ReturnCard({row:r,variants,role,busy,save}:{row:Row;variants:Row[];role:StaffRole;busy:boolean;save:Save}){const items=JSON.parse(r.items_json),exchangeItems=Array.from((items as Row[]).reduce<Map<string,Row>>((m,i)=>{const old=m.get(i.variantId);m.set(i.variantId,old?{...old,quantity:old.quantity+i.quantity}:i);return m;},new Map<string,Row>()).values()),[status,setStatus]=useState(r.status),[notes,setNotes]=useState(r.notes),[refund,setRefund]=useState(String(r.refund_kobo/100)),[refundStatus,setRefundStatus]=useState(r.refund_status),[ref,setRef]=useState(r.refund_reference),[replacement,setReplacement]=useState<Record<string,string>>({}),[carrier,setCarrier]=useState(r.exchange_carrier||''),[tracking,setTracking]=useState(r.exchange_tracking||'');useOperationDraft('Return '+r.reference,{status,notes,refund,refundStatus,ref,replacement,carrier,tracking},x=>{setStatus(x.status);setNotes(x.notes);setRefund(x.refund);setRefundStatus(x.refundStatus);setRef(x.ref);setReplacement(x.replacement);setCarrier(x.carrier);setTracking(x.tracking);},busy);return <details><summary>{r.reference} · {r.kind} · {r.status}</summary><p>{r.reason}</p><Grid rows={items} columns={[["name","Item"],["size","Size"],["color","Colour"],["quantity","Quantity"]]}/><div className="ops-fields"><Choice label="Return status" value={status} onChange={setStatus} values={['requested','approved','received','resolved','declined']}/><Field label="Customer update" value={notes} onChange={setNotes}/>{role==='owner'&&<><Field label="Refund amount (₦)" type="number" value={refund} onChange={setRefund}/><Field label="Paystack refund reference" value={ref} onChange={setRef}/><Choice label="Refund status" value={refundStatus} onChange={setRefundStatus} values={['none','pending','completed']}/></>}</div><p>Issue refunds in Paystack, then record their result here. Saving this form does not transfer money.</p><div className="ops-controls"><Button disabled={busy} onClick={()=>void save('return',{id:r.id,version:r.version,status,notes,refundKobo:Math.round(Number(refund)*100),refundReference:ref,refundStatus,restock:false})}>Save request</Button><Button variant="outline" disabled={busy||!!r.restocked||!['received','resolved'].includes(r.status)} onClick={()=>void save('return',{id:r.id,version:r.version,status:r.status,notes,refundKobo:Math.round(Number(refund)*100),refundReference:ref,refundStatus,restock:true})}>{r.restocked?'Already restocked':'Restock inspected items'}</Button></div>
 {r.kind==='exchange'&&!r.replacements&&<><h4>Replacement sizes and colours</h4>{exchangeItems.map((i:Row)=>{const original=variants.find(v=>v.id===i.variantId);return <Label className="ops-field" key={i.variantId}>{i.name} · {i.quantity} replacement(s)<Select value={replacement[i.variantId]||''} onValueChange={v=>setReplacement({...replacement,[i.variantId]:v})}><SelectTrigger><SelectValue placeholder="Choose replacement"/></SelectTrigger><SelectContent>{variants.filter(v=>v.active&&v.product_id===original?.product_id).map(v=><SelectItem key={v.id} value={v.id}>{v.color} / {v.size} · {v.stock} on hand</SelectItem>)}</SelectContent></Select></Label>})}<Button disabled={busy||r.status!=='received'||exchangeItems.some((i:Row)=>!replacement[i.variantId])} onClick={()=>void save('exchange',{returnId:r.id,items:exchangeItems.map((i:Row)=>({originalVariantId:i.variantId,variantId:replacement[i.variantId],quantity:i.quantity}))})}>Allocate replacement stock</Button></>}
 {r.replacements&&<><p>Replacement status: {r.exchange_status}</p><Field label="Replacement carrier" value={carrier} onChange={setCarrier}/><Field label="Replacement tracking number" value={tracking} onChange={setTracking}/><Button disabled={busy||r.exchange_status==='delivered'} onClick={()=>void save('exchange-tracking',{returnId:r.id,carrier,trackingNumber:tracking,status:r.exchange_status==='allocated'?'shipped':'delivered'})}>{r.exchange_status==='allocated'?'Dispatch replacements':'Confirm replacement delivery'}</Button></>}</details>}
function PromotionForm({row,busy,save}:{row?:Row;busy:boolean;save:Save}){const [v,setV]=useState({code:row?.code||'',title:row?.title||'',kind:row?.kind||'percent',value:row?String(row.kind==='fixed'?row.value/100:row.value):'10',minimumKobo:row?String(row.minimum_kobo/100):'0',minimumQuantity:String(row?.minimum_quantity||1),productIds:row?JSON.parse(row.product_ids).join(', '):'',maxUses:String(row?.max_uses||0),startsAt:row?.starts_at?.slice(0,16)||'',endsAt:row?.ends_at?.slice(0,16)||'',active:row?.active?'enabled':'paused'});const [editing,setEditing]=useState(!row);const draft=useOperationDraft('Promotion '+(row?.code||'new'),v,x=>{setV(x);setEditing(!row);},busy,commit);const field=(key:keyof typeof v,label:string,type='text')=><Field label={label} type={type} value={v[key]} onChange={x=>setV({...v,[key]:x})}/>;async function commit(){if(!v.startsAt||!v.endsAt)return false;const result=await save('promotion',{...v,value:Math.round(Number(v.value)*(v.kind==='fixed'?100:1)),minimumKobo:Math.round(Number(v.minimumKobo)*100),minimumQuantity:Number(v.minimumQuantity),maxUses:Number(v.maxUses),productIds:v.productIds.split(',').map((x:string)=>x.trim()).filter(Boolean),startsAt:new Date(v.startsAt+'Z').toISOString(),endsAt:new Date(v.endsAt+'Z').toISOString(),active:v.active==='enabled',version:row?.version||0});if(result){draft.markSaved();setEditing(false);}return !!result;} return <form className="ops-form" onSubmit={e=>{e.preventDefault();void commit();}}><div className="vn-editor-heading"><Button type="button" disabled={busy} onClick={()=>editing?void commit():setEditing(true)}>{editing?'Save':'Edit'}</Button></div><fieldset className="vn-settings-editor" disabled={!editing||busy}><div className="ops-fields">{row?<p>Code: {v.code}</p>:field('code','Code')}{field('title','Offer name')}<Choice label="Discount type" value={v.kind} onChange={x=>setV({...v,kind:x})} values={['percent','fixed']}/>{field('value',v.kind==='percent'?'Percentage off':'Amount off (₦)','number')}{field('minimumKobo','Minimum eligible subtotal (₦)','number')}{field('minimumQuantity','Minimum eligible items','number')}{field('productIds','Eligible product IDs, comma-separated')}{field('maxUses','Usage limit (0 = unlimited)','number')}{field('startsAt','Starts (UTC)','datetime-local')}{field('endsAt','Ends (UTC)','datetime-local')}<Choice label="Promotion enabled" value={v.active} onChange={x=>setV({...v,active:x})} values={['paused','enabled']}/></div></fieldset></form>}
