'use client';
import {useEffect,useState,useRef} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {roleResources,type StaffRole} from '@/lib/operations-permissions';
import {productsFromCSV,csvCell} from '@/lib/catalog-csv';
import {formatNaira} from '@/lib/catalog';
import {allowedOrderStatuses} from '@/lib/order-status';
import './operations.css';
type Row=Record<string,any>;
const labels:Record<string,string>={orders:'Orders',bulk:'Bulk catalogue',inventory:'Stock history',returns:'Returns & exchanges',promotions:'Promotions',reports:'Sales reports',courier:'Delivery',staff:'Staff access',activity:'Activity'};
function Choice({value,onChange,values,label}:{value:string;onChange:(v:string)=>void;values:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v.replaceAll('_',' ')}</SelectItem>)}</SelectContent></Select>}
function Field({label,value,onChange,type='text'}:{label:string;value:any;onChange:(v:string)=>void;type?:string}){return <Label className="ops-field">{label}<Input type={type} value={value} onChange={e=>onChange(e.target.value)}/></Label>}
function Grid({rows,columns}:{rows:Row[];columns:Array<[string,string]>}){return <div className="ops-table"><Table><TableHeader><TableRow>{columns.map(([key,label])=><TableHead key={key}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={r.id||i}>{columns.map(([key])=><TableCell key={key}>{String(r[key]??'—')}</TableCell>)}</TableRow>)}</TableBody></Table>{!rows.length&&<p className="ops-empty">No records yet.</p>}</div>}
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function OperationsPanel({role,initialSection}:{role:StaffRole;initialSection?:string}){
 const sections=roleResources[role], [section,setSection]=useState(initialSection && sections.includes(initialSection as typeof sections[number]) ? initialSection as typeof sections[number] : sections[0]),[data,setData]=useState<Row>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [csv,setCsv]=useState(''),[preview,setPreview]=useState<Row[]>([]),[result,setResult]=useState<Row[]>([]),[prices,setPrices]=useState<Record<string,string>>({});
 const requestId=useRef(0);
 async function load(){const id=++requestId.current;setLoading(true);setError('');try{const p=new URLSearchParams({resource:section,page:String(page),q,status:status==='all'?'':status});if(from)p.set('from',from);if(to)p.set('to',to);const r=await fetch('/api/admin/operations?'+p);const value=await r.json() as Row;if(id!==requestId.current)return;if(!r.ok)throw new Error(value.error);setData(value);}catch(e){if(id===requestId.current){setError(e instanceof Error?e.message:'Could not load.');setData({});}}finally{if(id===requestId.current)setLoading(false);}}
 useEffect(()=>{void load();},[section,page,status,from,to]);
 async function save(action:string,values:unknown){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data:values})});const v=await r.json() as Row;if(!r.ok)throw new Error(v.error);await load();setNotice('Changes saved.');return v.result;}catch(e){setError(e instanceof Error?e.message:'Could not save.');return null;}finally{setBusy(false);}}
 const products=(data.products||[]) as Row[];
 return <section className="ops-panel" aria-label="Store operations"><div className="ops-heading"><div><p>VANTA NOIR / OPERATIONS</p><h2>Run your store</h2></div><Button variant="outline" onClick={()=>void load()} disabled={loading}>Refresh</Button></div>
 <Tabs value={section} onValueChange={s=>{setSection(s);setPage(1);setData({});setNotice('');setError('');}}><TabsList className="ops-tabs">{sections.map(s=><TabsTrigger key={s} value={s}>{labels[s]}</TabsTrigger>)}</TabsList>
 {error&&<p role="alert" className="ops-error">{error}</p>}{notice&&<p role="status" className="ops-notice">{notice}</p>}{loading?<p className="ops-empty">Loading {labels[section].toLowerCase()}…</p>:<TabsContent value={section} className="ops-content">
 {section==='orders'&&<><div className="ops-counts">{(data.counts||[]).map((c:Row)=><button key={c.status} onClick={()=>{setStatus(c.status);setPage(1);}}><strong>{c.count}</strong>{c.status.replaceAll('_',' ')}</button>)}</div><div className="ops-controls"><Field label="Find an order" value={q} onChange={setQ}/><Button onClick={()=>{setPage(1);void load();}}>Search</Button><Choice label="Order status" value={status} onChange={v=>{setStatus(v);setPage(1);}} values={['all','pending_payment','paid','paid_stock_review','processing','shipped','delivered','cancelled']}/></div>{!(data.orders||[]).length&&<p className="ops-empty">No orders match these filters.</p>}{(data.orders||[]).map((o:Row)=><OrderCard key={o.id+o.status+o.updatedAt} order={o} role={role} save={save} busy={busy}/>)}<Pager page={page} setPage={setPage} more={(data.orders||[]).length===50}/></>}
 {section==='bulk'&&<><p>Edit prices here, adjust variation stock with a reason, or import up to 25 new designs as drafts. Use Product studio for descriptions and galleries.</p><div className="ops-table"><Table><TableHeader><TableRow><TableHead>Product</TableHead><TableHead>Price (₦)</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{products.map(p=><TableRow key={p.id}><TableCell>{p.name}</TableCell><TableCell><Input aria-label={'Price for '+p.name} type="number" min="1" value={prices[p.id]??p.priceKobo/100} onChange={e=>setPrices({...prices,[p.id]:e.target.value})}/></TableCell><TableCell>{p.status}</TableCell></TableRow>)}</TableBody></Table></div><Button disabled={busy||!Object.keys(prices).length} onClick={async()=>{const r=await save('prices',products.filter(p=>prices[p.id]!==undefined).map(p=>({id:p.id,expectedPrice:p.priceKobo,priceKobo:Math.round(Number(prices[p.id])*100)})));if(r){setResult(r);setPrices({});}}}>Save edited prices</Button>
 <details><summary>Variation stock adjustments</summary>{products.map(p=><details key={p.id}><summary>{p.name}</summary>{p.variants.filter((v:Row)=>v.active).map((v:Row)=><StockRow key={v.id+'-'+v.stock} variant={v} busy={busy} save={save}/>)}</details>)}</details>
 <details><summary>Import new designs from CSV</summary><p>One row per size and colour. Repeat the slug to group variations. Separate multiple image URLs with |. All imported products start as drafts.</p><Button variant="outline" onClick={()=>download('vanta-noir-product-template.csv','slug,name,category,description,priceNaira,imageUrl,size,color,colorHex,sku,stock\n')}>Download blank template</Button><Label className="ops-field">Choose CSV<Input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(f){setPreview([]);setCsv(await f.text());}}}/></Label><Textarea aria-label="Product CSV" value={csv} onChange={e=>{setCsv(e.target.value);setPreview([]);}}/><Button onClick={()=>{try{setPreview(productsFromCSV(csv));setError('');}catch(e){setError((e as Error).message);}}}>Review import</Button>{preview.length>0&&<><Grid rows={preview.map(p=>({name:p.name,variations:p.variants.length,price:formatNaira(p.priceKobo)}))} columns={[["name","Design"],["variations","Variations"],["price","Price"]]}/><Button disabled={busy} onClick={async()=>{const r=await save('import',preview);if(r){setResult(r);setPreview([]);}}}>Import {preview.length} draft designs</Button></>}</details>
 {!!result.length&&<Grid rows={result.map(r=>({...r,outcome:r.ok?'Saved':r.error||'Changed elsewhere; refresh and retry'}))} columns={[["name","Design"],["id","Record"],["outcome","Result"]]}/>}</>}
 {section==='inventory'&&<><p>Stock movements recorded from this upgrade include sales and exchanges, alongside existing adjustments and returns. Earlier sales are not reconstructed.</p><div className="ops-controls"><Field label="Search SKU or reason" value={q} onChange={setQ}/><Button onClick={()=>{setPage(1);void load();}}>Search</Button></div><Grid rows={(data.rows||[]).slice(0,50)} columns={[["created_at","Date"],["sku","SKU"],["old_stock","Before"],["new_stock","After"],["reason","Reason"],["actor","Changed by"]]}/><Pager page={page} setPage={setPage} more={(data.rows||[]).length>50}/></>}
 {section==='returns'&&<>{!(data.returns||[]).length&&<p className="ops-empty">No return or exchange requests yet.</p>}{(data.returns||[]).slice(0,50).map((r:Row)=><ReturnCard key={r.id+'-'+r.version+'-'+r.exchange_status} row={r} variants={data.variants||[]} role={role} busy={busy} save={save}/>)}<Pager page={page} setPage={setPage} more={(data.returns||[]).length>50}/></>}
 {section==='promotions'&&<><p>Codes are checked on the server at checkout. A quantity requirement creates a bundle offer. Leave product IDs empty to include the whole catalogue.</p><PromotionForm busy={busy} save={save}/>{(data.promotions||[]).map((p:Row)=><details key={p.code+'-'+p.version}><summary>{p.code} · {p.title} · {p.active?'Enabled':'Paused'} · {p.redeemed} paid uses</summary><PromotionForm row={p} busy={busy} save={save}/></details>)}</>}
 {section==='reports'&&<><div className="ops-controls"><Field type="date" label="Paid from" value={from} onChange={setFrom}/><Field type="date" label="Through" value={to} onChange={setTo}/><Button onClick={()=>download('vanta-noir-sales.csv',[['Product','Size','Colour','Units','Gross before discounts/refunds'],...(data.bestsellers||[]).map((r:Row)=>[r.product_name,r.size,r.color,r.units,r.gross/100])].map(r=>r.map(csvCell).join(',')).join('\n'))}>Export report</Button></div><div className="ops-counts">{[['Paid orders',data.sales?.orders||0],['Collected including delivery',formatNaira(data.sales?.revenue||0)],['Discounts applied',formatNaira(data.sales?.discounts||0)],['Refunds recorded in period',formatNaira(data.refunds?.amount||0)]].map(([label,value])=><div key={label}><strong>{value}</strong>{label}</div>)}</div><p>Product totals below are before discounts and refunds. Refund figures use the date the return record was last updated. These are sales summaries, not profit calculations.</p><Grid rows={(data.bestsellers||[]).map((r:Row)=>({...r,gross:formatNaira(r.gross)}))} columns={[["product_name","Product"],["size","Size"],["color","Colour"],["units","Units sold"],["gross","Gross product sales"]]}/></>}
 {section==='courier'&&<><h3>{data.connected?'Tracking receiver configured':'Courier connection pending'}</h3><p>Use Orders to enter a carrier and tracking number now. Automatic updates need a supported courier connection and its signing secret. Configuring the receiver alone does not connect a courier.</p><Grid rows={data.events||[]} columns={[["created_at","Received"],["reference","Order"],["status","Delivery status"]]}/></>}
 {section==='staff'&&<><p>Set each person’s role here. They must also be allowed through your site’s sign-in policy. No invitations are sent from this screen.</p><StaffForm busy={busy} save={save}/>{(data.staff||[]).map((s:Row)=><StaffForm key={s.email+'-'+s.role+'-'+s.active} row={s} busy={busy} save={save}/>)}</>}
 {section==='activity'&&<><Grid rows={(data.rows||[]).slice(0,50)} columns={[["created_at","Date"],["actor","Staff member"],["action","Action"],["entity","Record"],["detail","Details"]]}/><Pager page={page} setPage={setPage} more={(data.rows||[]).length>50}/></>}
 </TabsContent>}</Tabs></section>;
}
type Save=(action:string,data:unknown)=>Promise<any>;
function Pager({page,setPage,more}:{page:number;setPage:(n:number)=>void;more:boolean}){return <div className="ops-controls"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page}</span><Button variant="outline" disabled={!more} onClick={()=>setPage(page+1)}>Next</Button></div>}
function StockRow({variant:v,busy,save}:{variant:Row;busy:boolean;save:Save}){const [stock,setStock]=useState(String(v.stock)),[reason,setReason]=useState('');return <div className="ops-stock"><span>{v.sku} · {v.color} / {v.size}</span><Field label="Counted stock" type="number" value={stock} onChange={setStock}/><Field label="Reason / receipt reference" value={reason} onChange={setReason}/><Button disabled={busy||reason.trim().length<3} onClick={()=>void save('stock',{variantId:v.id,expectedStock:v.stock,stock:Number(stock),reason})}>Save stock</Button></div>}
function OrderCard({order:o,role,busy,save}:{order:Row;role:StaffRole;busy:boolean;save:Save}){const [status,setStatus]=useState(o.status),[carrier,setCarrier]=useState(o.carrier),[tracking,setTracking]=useState(o.trackingNumber),[url,setUrl]=useState(o.trackingUrl),[estimate,setEstimate]=useState(o.deliveryEstimate);const allowed=allowedOrderStatuses(o.status,o.paymentStatus).filter(s=>role==='owner'||['processing','shipped','delivered'].includes(s));return <details><summary>{o.reference} · {o.firstName} {o.lastName} · {o.status.replaceAll('_',' ')} · {formatNaira(o.totalKobo)}</summary><p>{o.items.map((i:Row)=>`${i.quantity} × ${i.productName} (${i.color}, ${i.size})`).join(' · ')}</p><p>{[o.addressLine1,o.addressLine2,o.city,o.state].filter(Boolean).join(', ')} · {o.phone}</p><div className="ops-controls"><Choice label="Next order status" value={status} onChange={setStatus} values={[...new Set([o.status,...allowed])]}/><Button disabled={busy||status===o.status||!allowed.includes(status)} onClick={()=>void save('order',{reference:o.reference,status})}>Update status</Button></div><div className="ops-fields"><Field label="Carrier" value={carrier} onChange={setCarrier}/><Field label="Tracking number" value={tracking} onChange={setTracking}/><Field label="HTTPS tracking link" value={url} onChange={setUrl}/><Field label="Delivery estimate" value={estimate} onChange={setEstimate}/></div><Button disabled={busy||o.paymentStatus!=='paid'} onClick={()=>void save('tracking',{reference:o.reference,carrier,trackingNumber:tracking,trackingUrl:url,deliveryEstimate:estimate})}>Save delivery details</Button></details>}
function ReturnCard({row:r,variants,role,busy,save}:{row:Row;variants:Row[];role:StaffRole;busy:boolean;save:Save}){const items=JSON.parse(r.items_json),[status,setStatus]=useState(r.status),[notes,setNotes]=useState(r.notes),[refund,setRefund]=useState(String(r.refund_kobo/100)),[refundStatus,setRefundStatus]=useState(r.refund_status),[ref,setRef]=useState(r.refund_reference),[replacement,setReplacement]=useState<Record<string,string>>({}),[carrier,setCarrier]=useState(r.exchange_carrier||''),[tracking,setTracking]=useState(r.exchange_tracking||'');return <details><summary>{r.reference} · {r.kind} · {r.status}</summary><p>{r.reason}</p><Grid rows={items} columns={[["name","Item"],["size","Size"],["color","Colour"],["quantity","Quantity"]]}/><div className="ops-fields"><Choice label="Return status" value={status} onChange={setStatus} values={['requested','approved','received','resolved','declined']}/><Field label="Customer update" value={notes} onChange={setNotes}/>{role==='owner'&&<><Field label="Refund amount (₦)" type="number" value={refund} onChange={setRefund}/><Field label="Paystack refund reference" value={ref} onChange={setRef}/><Choice label="Refund status" value={refundStatus} onChange={setRefundStatus} values={['none','pending','completed']}/></>}</div><p>Issue refunds in Paystack, then record their result here. Saving this form does not transfer money.</p><div className="ops-controls"><Button disabled={busy} onClick={()=>void save('return',{id:r.id,version:r.version,status,notes,refundKobo:Math.round(Number(refund)*100),refundReference:ref,refundStatus,restock:false})}>Save request</Button><Button variant="outline" disabled={busy||!!r.restocked||!['received','resolved'].includes(r.status)} onClick={()=>void save('return',{id:r.id,version:r.version,status:r.status,notes,refundKobo:Math.round(Number(refund)*100),refundReference:ref,refundStatus,restock:true})}>{r.restocked?'Already restocked':'Restock inspected items'}</Button></div>
 {r.kind==='exchange'&&!r.replacements&&<><h4>Replacement sizes and colours</h4>{items.map((i:Row)=>{const original=variants.find(v=>v.id===i.variantId);return <Label className="ops-field" key={i.variantId}>{i.name} · {i.quantity} replacement(s)<Select value={replacement[i.variantId]||''} onValueChange={v=>setReplacement({...replacement,[i.variantId]:v})}><SelectTrigger><SelectValue placeholder="Choose replacement"/></SelectTrigger><SelectContent>{variants.filter(v=>v.active&&v.product_id===original?.product_id).map(v=><SelectItem key={v.id} value={v.id}>{v.color} / {v.size} · {v.stock} on hand</SelectItem>)}</SelectContent></Select></Label>})}<Button disabled={busy||r.status!=='received'||items.some((i:Row)=>!replacement[i.variantId])} onClick={()=>void save('exchange',{returnId:r.id,items:items.map((i:Row)=>({originalVariantId:i.variantId,variantId:replacement[i.variantId],quantity:i.quantity}))})}>Allocate replacement stock</Button></>}
 {r.replacements&&<><p>Replacement status: {r.exchange_status}</p><Field label="Replacement carrier" value={carrier} onChange={setCarrier}/><Field label="Replacement tracking number" value={tracking} onChange={setTracking}/><Button disabled={busy||r.exchange_status==='delivered'} onClick={()=>void save('exchange-tracking',{returnId:r.id,carrier,trackingNumber:tracking,status:r.exchange_status==='allocated'?'shipped':'delivered'})}>{r.exchange_status==='allocated'?'Dispatch replacements':'Confirm replacement delivery'}</Button></>}</details>}
function PromotionForm({row,busy,save}:{row?:Row;busy:boolean;save:Save}){const [v,setV]=useState({code:row?.code||'',title:row?.title||'',kind:row?.kind||'percent',value:row?String(row.kind==='fixed'?row.value/100:row.value):'10',minimumKobo:row?String(row.minimum_kobo/100):'0',minimumQuantity:String(row?.minimum_quantity||1),productIds:row?JSON.parse(row.product_ids).join(', '):'',maxUses:String(row?.max_uses||0),startsAt:row?.starts_at?.slice(0,16)||'',endsAt:row?.ends_at?.slice(0,16)||'',active:row?.active?'enabled':'paused'});const field=(key:keyof typeof v,label:string,type='text')=><Field label={label} type={type} value={v[key]} onChange={x=>setV({...v,[key]:x})}/>;return <form className="ops-form" onSubmit={async e=>{e.preventDefault();if(!v.startsAt||!v.endsAt)return;await save('promotion',{...v,value:Math.round(Number(v.value)*(v.kind==='fixed'?100:1)),minimumKobo:Math.round(Number(v.minimumKobo)*100),minimumQuantity:Number(v.minimumQuantity),maxUses:Number(v.maxUses),productIds:v.productIds.split(',').map((x:string)=>x.trim()).filter(Boolean),startsAt:new Date(v.startsAt+'Z').toISOString(),endsAt:new Date(v.endsAt+'Z').toISOString(),active:v.active==='enabled',version:row?.version||0});}}><div className="ops-fields">{row?<p>Code: {v.code}</p>:field('code','Code')}{field('title','Offer name')}<Choice label="Discount type" value={v.kind} onChange={x=>setV({...v,kind:x})} values={['percent','fixed']}/>{field('value',v.kind==='percent'?'Percentage off':'Amount off (₦)','number')}{field('minimumKobo','Minimum eligible subtotal (₦)','number')}{field('minimumQuantity','Minimum eligible items','number')}{field('productIds','Eligible product IDs, comma-separated')}{field('maxUses','Usage limit (0 = unlimited)','number')}{field('startsAt','Starts (UTC)','datetime-local')}{field('endsAt','Ends (UTC)','datetime-local')}<Choice label="Promotion enabled" value={v.active} onChange={x=>setV({...v,active:x})} values={['paused','enabled']}/></div><Button disabled={busy||!v.startsAt||!v.endsAt}>Save promotion</Button></form>}
function StaffForm({row,busy,save}:{row?:Row;busy:boolean;save:Save}){const [email,setEmail]=useState(row?.email||''),[role,setRole]=useState(row?.role||'fulfilment'),[active,setActive]=useState(row?.active?'enabled':'disabled');return <form className="ops-controls" onSubmit={e=>{e.preventDefault();void save('staff',{email,role,active:active==='enabled'});}}>{row?<span>{email}</span>:<Field label="Staff email" value={email} onChange={setEmail} type="email"/>}<Choice label="Staff role" value={role} onChange={setRole} values={['catalogue','fulfilment','support','analyst']}/><Choice label="Staff access" value={active} onChange={setActive} values={['disabled','enabled']}/><Button disabled={busy||!email}>Save access</Button></form>}
