'use client';
import {useState} from 'react';
import {Area,ComposedChart,Line,CartesianGrid,XAxis,YAxis,ResponsiveContainer,Tooltip} from 'recharts';
import {Wallet,ShoppingBag,ChartNoAxesCombined,Receipt,ArrowUpRight,Package,Truck,Pencil,Download} from 'lucide-react';
import {formatNaira} from '@/lib/catalog';
import {comparison} from '@/lib/admin-reporting';
import type {AdminAnalytics,AdminOrder,AdminProduct} from '@/lib/store-db';
import type {AdminTarget} from './management-tools';
import StoreImage from '@/components/store-image';
function compactNaira(kobo:number){const naira=kobo/100;return naira>=1000000?'₦'+new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:2}).format(naira):formatNaira(kobo);}
export function ReportControls({analytics,loading,onRange}:{analytics:AdminAnalytics;loading:boolean;onRange:(params:URLSearchParams)=>void}){
 const [period,setPeriod]=useState('30'),[from,setFrom]=useState(analytics.range?.from||''),[to,setTo]=useState(analytics.range?.to||'');
 function exportReport(){const csv='Date UTC,Paid orders,Collected NGN,Previous date UTC,Previous paid orders,Previous collected NGN\n'+analytics.trend.map(p=>[p.date,p.orders,p.revenueKobo/100,p.previousDate,p.previousOrders,(p.previousRevenueKobo||0)/100].join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=`vanta-noir-revenue-${analytics.range?.from}-${analytics.range?.to}.csv`;a.click();URL.revokeObjectURL(u);}
 return <div className="vn-report-controls"><label><span className="sr-only">Reporting period</span><select aria-label="Reporting period" value={period} disabled={loading} onChange={e=>{setPeriod(e.target.value);if(e.target.value!=='custom')onRange(new URLSearchParams({days:e.target.value}));}}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="custom">Custom dates</option></select></label>{period==='custom'&&<form onSubmit={e=>{e.preventDefault();onRange(new URLSearchParams({from,to}));}}><input aria-label="Report from" type="date" required value={from} max={to||new Date().toISOString().slice(0,10)} onChange={e=>setFrom(e.target.value)}/><input aria-label="Report through" type="date" required value={to} min={from} max={new Date().toISOString().slice(0,10)} onChange={e=>setTo(e.target.value)}/><button disabled={loading}>Apply</button></form>}<button disabled={loading} onClick={exportReport}><Download size={16}/> Export report</button></div>;
}
function Sparkline({values}:{values:number[]}){const low=Math.min(...values),high=Math.max(...values),span=high-low||1;return <svg className="vn-sparkline" viewBox="0 0 100 32" aria-hidden="true"><polyline points={values.map((v,i)=>`${i*100/Math.max(1,values.length-1)},${28-(v-low)*24/span}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="1.8" vectorEffect="non-scaling-stroke"/></svg>;}
export function OverviewPanel({analytics,orders,products,lowStock,onNavigate,onProduct,campaignProductId,onCampaignSaved}:{analytics:AdminAnalytics;orders:AdminOrder[];products:AdminProduct[];lowStock:number;onNavigate:(target:AdminTarget)=>void;onProduct:(product:AdminProduct)=>void;campaignProductId:string;onCampaignSaved:(id:string)=>void}){
 const revenue=analytics.trend.reduce((s,p)=>s+p.revenueKobo,0),paid=analytics.trend.reduce((s,p)=>s+p.orders,0),previousRevenue=analytics.trend.reduce((s,p)=>s+(p.previousRevenueKobo||0),0),previousPaid=analytics.trend.reduce((s,p)=>s+(p.previousOrders||0),0),average=paid?revenue/paid:0,previousAverage=previousPaid?previousRevenue/previousPaid:0;
 const conversion=analytics.conversion,best=analytics.bestSellers||[],drafts=products.filter(p=>p.status==='draft').length,fulfil=analytics.fulfilmentCount||0;
 const [editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState('');
 const campaign=products.find(p=>p.id===campaignProductId&&p.status!=='archived');
 const metrics=[{label:'Collected revenue',value:compactNaira(revenue),note:'Paid, non-cancelled orders · includes delivery',delta:comparison(revenue,previousRevenue),values:analytics.trend.map(p=>p.revenueKobo),Icon:Wallet},{label:'Paid orders',value:String(paid),note:'By order creation date',delta:comparison(paid,previousPaid),values:analytics.trend.map(p=>p.orders),Icon:ShoppingBag},{label:'Purchase conversion',value:conversion?.current!=null?conversion.current.toFixed(2)+'%':'—',note:conversion?.status==='connected'?`${conversion.sessions.toLocaleString()} measured sessions · GA4`:conversion?.message||'Awaiting GA4 reporting connection',delta:conversion?.current!=null&&conversion.previous!=null?comparison(conversion.current,conversion.previous):'No previous baseline',values:conversion?.status==='connected'?analytics.trend.map(p=>conversion.daily[p.date||'']||0):[],Icon:ChartNoAxesCombined},{label:'Average order value',value:paid?compactNaira(Math.round(average)):'—',note:'Collected revenue divided by paid orders',delta:comparison(average,previousAverage),values:analytics.trend.map(p=>p.orders?p.revenueKobo/p.orders:0),Icon:Receipt}];
 async function saveCampaign(id:string){setSaving(true);setFeedback('');try{const r=await fetch('/api/admin/management',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaignProductId:id})});if(!r.ok)throw new Error('Artwork could not be saved.');onCampaignSaved(id);setEditing(false);setFeedback('Artwork saved ✓');}catch(e){setFeedback((e as Error).message);}finally{setSaving(false);}}
 return <>
 <p className="vn-report-period">{analytics.range?.from} – {analytics.range?.to} · UTC order dates. Compared with {analytics.range?.previousFrom} – {analytics.range?.previousTo}. Today may be incomplete.</p>
 <section className="vn-ref-metrics" aria-label="Store summary">{metrics.map(({label,value,note,delta,values,Icon})=><article key={label}><div className="vn-ref-metric-label"><Icon size={17}/>{label}<span/></div><div className="vn-metric-value"><strong>{value}</strong>{values.length>0&&<Sparkline values={values}/>}</div><p className={delta.startsWith('-')?'vn-change-down':'vn-change-up'}>{delta} <span className="vn-ref-muted">vs. previous period</span></p><p>{note}</p></article>)}</section>
 <div className="vn-ref-grid">
 <section className="vn-ref-card vn-revenue"><div className="vn-ref-card-head"><h2>Revenue overview</h2><span className="vn-chart-legend">━ This period · ┄ Previous period</span></div><strong className="vn-revenue-total">{formatNaira(revenue)}</strong><p className="vn-ref-muted">{comparison(revenue,previousRevenue)} · From {paid} paid orders · NGN</p><div className="vn-revenue-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={analytics.trend} margin={{top:24,right:10,bottom:0,left:0}}><defs><linearGradient id="vnRevenueFade" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a8d785" stopOpacity={0.24}/><stop offset="100%" stopColor="#a8d785" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#293128" strokeDasharray="3 7"/><XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={40} tick={{fill:'#929d93',fontSize:12}}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#929d93',fontSize:12}} tickFormatter={n=>'₦'+(n/100>=1000?(n/100000).toFixed(0)+'k':(n/100).toFixed(0))}/><Tooltip contentStyle={{background:'#151b17',border:'1px solid #303b30',borderRadius:10,color:'#eef2eb'}} formatter={(v:any,name:any)=>[formatNaira(Number(v)),name]} labelFormatter={(_,items)=>{const row=items[0]?.payload;return row?`${row.date} / previous ${row.previousDate}`:'';}}/><Area name="This period" type="monotone" dataKey="revenueKobo" stroke="#acd98b" strokeWidth={2.5} fill="url(#vnRevenueFade)" isAnimationActive={false}/><Line name="Previous period" type="monotone" dataKey="previousRevenueKobo" stroke="#73836a" strokeDasharray="5 6" dot={false} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div><p className="vn-ref-footnote">Includes delivery. Excludes unpaid and cancelled orders. Refunds are reported separately in Sales reports.</p></section>
 <section className="vn-ref-card"><div className="vn-ref-card-head"><h2>Best sellers</h2><button onClick={()=>onNavigate({section:'products'})}>View products <ArrowUpRight size={15}/></button></div>{best.length?best.map(item=>{const product=products.find(p=>p.id===item.productId);return <button className="vn-best-row" key={item.productId} onClick={()=>product?onProduct(product):onNavigate({section:'products'})}>{product&&<StoreImage src={product.imageUrl} alt="" sizes="64px"/>}<div><h3>{item.name}</h3><p>{item.units} units sold</p><div className="vn-best-bar"><span style={{width:`${Math.max(4,item.revenueKobo/Math.max(...best.map(b=>b.revenueKobo),1)*100)}%`}}/></div></div><strong>{formatNaira(item.revenueKobo)}</strong></button>}):<div className="vn-ref-empty"><ShoppingBag size={28}/><h3>No paid sales in this period</h3><p>Choose another period or review your products.</p></div>}<p className="vn-ref-footnote">Ranked by gross item revenue · Selected period · Before discounts and refunds</p></section>
 <section className="vn-ref-card vn-ref-orders"><div className="vn-ref-card-head"><div><h2>Recent orders</h2><p className="vn-ref-muted">Latest activity across all dates.</p></div><button onClick={()=>onNavigate({section:'orders'})}>All orders <ArrowUpRight size={15}/></button></div><div className="vn-ref-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Amount</th><th>Payment</th><th>Fulfilment</th></tr></thead><tbody>{orders.slice(0,4).map(o=><tr key={o.id}><td><button onClick={()=>onNavigate({section:'orders',query:o.reference})}>{o.reference}</button><small>{new Date(o.createdAt).toLocaleDateString('en-NG',{day:'numeric',month:'short',timeZone:'UTC'})}</small></td><td>{o.firstName} {o.lastName}<small>{o.items.reduce((n,i)=>n+i.quantity,0)} items</small></td><td>{formatNaira(o.totalKobo)}</td><td><span className={'vn-status status-'+o.paymentStatus}>{o.paymentStatus.replaceAll('_',' ')}</span></td><td><span className={'vn-status status-'+o.status}>{o.status.replaceAll('_',' ')}</span></td></tr>)}</tbody></table>{!orders.length&&<div className="vn-ref-empty"><Receipt size={28}/><h3>No orders yet</h3><p>New customer orders will appear here.</p></div>}</div><button className="vn-ref-table-footer" onClick={()=>onNavigate({section:'orders'})}>Manage orders <ArrowUpRight size={16}/></button></section>
 <div className="vn-ref-right"><section className="vn-ref-card" id="vn-attention"><div className="vn-ref-card-head"><h2>Needs your attention</h2><span>{[lowStock,fulfil,drafts].filter(Boolean).length} tasks</span></div>{[{Icon:Package,n:lowStock,title:'variants running low',note:'Review stock available to sell.',target:{section:'inventory',stockFilter:'low'} as AdminTarget},{Icon:Truck,n:fulfil,title:'orders to fulfil',note:'Paid and ready for the next step.',target:{section:'orders',status:'fulfil'}},{Icon:Pencil,n:drafts,title:'products in draft',note:'Your next drop is taking shape.',target:{section:'products',productStatus:'draft'}}].map(({Icon,n,title,note,target})=><button className="vn-attention-row" key={title} onClick={()=>onNavigate(target)}><span className="vn-attention-icon"><Icon size={20}/></span><div><strong>{n} {title}</strong><p>{note}</p></div><ArrowUpRight size={16}/></button>)}</section><section><button className="vn-collection-callout" onClick={()=>campaign?onProduct(campaign):onNavigate({section:'collections'})}><div><small>THE NEXT CHAPTER</small><h2>Make your<br/>presence felt.</h2><span>{campaign?campaign.name:'Explore your collection'} <ArrowUpRight size={16}/></span></div>{campaign&&<StoreImage src={campaign.imageUrl} alt={campaign.name} sizes="180px"/>}</button><button className="vn-artwork-edit" onClick={()=>setEditing(!editing)}>Choose dashboard artwork</button>{editing&&<label>Product image<select aria-label="Dashboard artwork product" disabled={saving} value={campaignProductId} onChange={e=>void saveCampaign(e.target.value)}><option value="">No garment image</option>{products.filter(p=>p.status!=='archived').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}{feedback&&<p role="status">{feedback}</p>}</section></div>
 </div>
 {conversion?.status==='connected'&&<p className="vn-report-period">{conversion.message} GA4 timezone: {conversion.timeZone||'property timezone'}. This is measured purchase-session conversion, not paid orders divided by all visitors.</p>}
 <footer className="vn-control-footer"><span>PRESENCE. POWER. PRECISION.</span><p>Figures from this workspace’s database.</p></footer>
 </>;
}
