'use client';
import {useState,useRef,useEffect} from 'react';
import {Area,ComposedChart,CartesianGrid,XAxis,YAxis,ResponsiveContainer,Tooltip} from 'recharts';
import {Wallet,ShoppingCart,ChartNoAxesCombined,Tag,ArrowRight,ChevronRight,Package,Truck,Pencil,Download,CheckCircle2,Users,Image,FileText,Ruler,RefreshCw} from 'lucide-react';
import {formatNaira} from '@/lib/catalog';
import {comparison} from '@/lib/admin-reporting';
import type {AdminAnalytics,AdminOrder,AdminProduct} from '@/lib/store-db';
import type {AdminTarget} from './management-tools';
import StoreImage from '@/components/store-image';
import {useUnsavedChanges} from './unsaved-changes';
import {DashboardInfo} from './dashboard-info';
export type ConnectionSummary={paymentsConfigured:boolean;emailConfigured:boolean;ga4Configured:boolean};
export type FulfilmentCounts={status:string;count:number}[];
export function ReportControls({analytics,loading,onRange}:{analytics:AdminAnalytics;loading:boolean;onRange:(params:URLSearchParams)=>void}){
 const [period,setPeriod]=useState('30'),[from,setFrom]=useState(analytics.range?.from||''),[to,setTo]=useState(analytics.range?.to||'');
 function exportReport(){const csv='Date UTC,Paid orders,Collected NGN,Previous date UTC,Previous paid orders,Previous collected NGN\n'+analytics.trend.map(p=>[p.date,p.orders,p.revenueKobo/100,p.previousDate,p.previousOrders,(p.previousRevenueKobo||0)/100].join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=`vanta-noir-revenue-${analytics.range?.from}-${analytics.range?.to}.csv`;a.click();URL.revokeObjectURL(u);}
 return <div className="vn-report-controls"><label><span className="sr-only">Reporting period</span><select aria-label="Reporting period" value={period} disabled={loading} onChange={e=>{setPeriod(e.target.value);if(e.target.value!=='custom')onRange(new URLSearchParams({days:e.target.value}));}}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="custom">Custom dates</option></select></label>{period==='custom'&&<form onSubmit={e=>{e.preventDefault();onRange(new URLSearchParams({from,to}));}}><input aria-label="Report from" type="date" required value={from} max={to||new Date().toISOString().slice(0,10)} onChange={e=>setFrom(e.target.value)}/><input aria-label="Report through" type="date" required value={to} min={from} max={new Date().toISOString().slice(0,10)} onChange={e=>setTo(e.target.value)}/><button disabled={loading}>Apply</button></form>}<button disabled={loading} onClick={exportReport}><Download size={16}/> Export report</button></div>;
}

export function OverviewPanel({analytics,orders,products,lowStock,onNavigate,onProduct,campaignProductId,onCampaignSaved,fulfilment,connections,paymentsMode,emailPanel,onRefresh,loading}:{analytics:AdminAnalytics;orders:AdminOrder[];products:AdminProduct[];lowStock:number;onNavigate:(target:AdminTarget)=>void;onProduct:(product:AdminProduct)=>void;campaignProductId:string;onCampaignSaved:(id:string)=>void;fulfilment:FulfilmentCounts|null;connections:ConnectionSummary|null;paymentsMode:string;emailPanel:React.ReactNode;onRefresh:()=>void;loading:boolean}){
 const revenue=analytics.trend.reduce((s,p)=>s+p.revenueKobo,0),paid=analytics.trend.reduce((s,p)=>s+p.orders,0),previousRevenue=analytics.trend.reduce((s,p)=>s+(p.previousRevenueKobo||0),0),previousPaid=analytics.trend.reduce((s,p)=>s+(p.previousOrders||0),0),average=paid?revenue/paid:0;
 const conversion=analytics.conversion,best=analytics.bestSellers||[],drafts=products.filter(p=>p.status==='draft').length,fulfil=analytics.fulfilmentCount||0;
 const [chart,setChart]=useState<'orders'|'ga4'>('orders'),[orderTab,setOrderTab]=useState('recent');
 const [editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState('');const campaignLock=useRef(false);
 const [draftCampaign,setDraftCampaign]=useState(campaignProductId);
 useEffect(()=>{if(!editing)setDraftCampaign(campaignProductId);},[campaignProductId,editing]);
 useUnsavedChanges({name:'Dashboard artwork',dirty:editing&&draftCampaign!==campaignProductId,busy:saving,save:()=>saveCampaign(draftCampaign),discard:()=>{setDraftCampaign(campaignProductId);setEditing(false);}});
 const campaign=products.find(p=>p.id===campaignProductId&&p.status!=='archived');
 async function saveCampaign(id:string){if(campaignLock.current)return false;campaignLock.current=true;setSaving(true);setFeedback('');try{const r=await fetch('/api/admin/management',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaignProductId:id}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('Artwork could not be saved.');onCampaignSaved(id);setEditing(false);setFeedback('Artwork saved ✓');return true;}catch(e){setFeedback((e as Error).message);return false;}finally{campaignLock.current=false;setSaving(false);}}
 const metricMoney=(kobo:number)=>kobo>=100000000?"₦"+new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:2}).format(kobo/100):formatNaira(kobo);
 const metrics=[{label:'Collected revenue',value:metricMoney(revenue),help:formatNaira(revenue)+'. Paid, non-cancelled orders, including delivery. '+comparison(revenue,previousRevenue)+' versus the previous period. Refunds are reported separately in Sales reports.',Icon:Wallet},{label:'Paid orders',value:String(paid),help:'Paid, non-cancelled orders by creation date in the selected period. '+comparison(paid,previousPaid)+' versus the previous period.',Icon:ShoppingCart},{label:'Purchase conversion',value:conversion?.current!=null?conversion.current.toFixed(2)+'%':'—',note:conversion?.status==='connected'?`${conversion.sessions.toLocaleString()} measured sessions · GA4`:conversion?.message||'Connect Google Analytics',help:'Measured purchase-session conversion from GA4, not paid orders divided by all visitors. '+(conversion?.message||''),Icon:ChartNoAxesCombined},{label:'Average order value',value:paid?metricMoney(Math.round(average)):'—',help:formatNaira(Math.round(average))+'. Collected revenue, including delivery, divided by paid orders in the selected period.',Icon:Tag}];
 const stages=[{status:'processing',label:'Processing',Icon:Package,color:'#a6ee64',count:fulfilment?fulfilment.filter(x=>['paid','processing','paid_stock_review'].includes(x.status)).reduce((n,x)=>n+Number(x.count),0):null},{status:'shipped',label:'Shipped',Icon:Truck,color:'#73ca61',count:fulfilment?Number(fulfilment.find(x=>x.status==='shipped')?.count||0):null},{status:'delivered',label:'Delivered',Icon:CheckCircle2,color:'#d6f6ae',count:fulfilment?Number(fulfilment.find(x=>x.status==='delivered')?.count||0):null}];
 const total=stages.reduce((n,x)=>n+(x.count||0),0);let offset=0;
 const shown=orders.filter(o=>orderTab==='recent'||(orderTab==='processing'?['paid','processing','paid_stock_review'].includes(o.status):o.status===orderTab)).slice(0,3);
 function exportChart(){const rows=analytics.trend.map(p=>[p.date,chart==='orders'?p.revenueKobo/100:conversion?.daily?.[p.date||'']??0]);const a=document.createElement('a'),url=URL.createObjectURL(new Blob(['Date UTC,'+(chart==='orders'?'Collected NGN':'Purchase conversion percent')+'\n'+rows.map(r=>r.join(',')).join('\n')],{type:'text/csv;charset=utf-8'}));a.href=url;a.download='vanta-noir-'+chart+'-report.csv';a.click();URL.revokeObjectURL(url);}
 return <>
 <section className="vn-exact-metrics" aria-label="Store summary">{metrics.map(({label,value,note,help,Icon})=><article key={label}><span className="vn-metric-icon"><Icon size={25}/></span><div><div className="vn-exact-metric-title">{label}<DashboardInfo title={label}>{help}</DashboardInfo></div><strong>{value}</strong>{note&&<p>{note}</p>}</div></article>)}</section>
 <div className="vn-exact-grid">
 <section className="vn-glass vn-exact-revenue"><div className="vn-exact-card-head"><h2>Revenue overview <DashboardInfo title="Revenue overview">{analytics.range?.from} to {analytics.range?.to}, UTC order dates. Paid orders include delivery; unpaid and cancelled orders are excluded. Today may be incomplete. GA4 uses its property timezone.</DashboardInfo></h2><div className="vn-segments" aria-label="Chart source">{(['orders','ga4'] as const).map(v=><button key={v} aria-pressed={chart===v} onClick={()=>setChart(v)}>{v==='orders'?'Orders':'GA4'}</button>)}</div><div className="vn-chart-mobile-actions"><button aria-label="Change chart source" onClick={()=>setChart(chart==='orders'?'ga4':'orders')}>{chart==='orders'?'Orders':'GA4'}</button><button aria-label="Export chart" onClick={exportChart}><Download size={18}/></button><button aria-label="Refresh chart" disabled={loading} onClick={onRefresh}><RefreshCw size={18}/></button></div></div>
 <p className="vn-revenue-description">{chart==='orders'?'Sales performance':'Purchase conversion'} · {analytics.range?.from&&analytics.range?.to?`${analytics.range.from} — ${analytics.range.to}`:'Selected reporting period'}</p>
 {chart==='ga4'&&conversion?.status!=='connected'?<div className="vn-exact-empty"><p>{conversion?.message||'Connect Google Analytics to display measured conversion.'}</p><button onClick={()=>onNavigate({section:'settings'})}>Open connections <ArrowRight size={16}/></button></div>:<div className="vn-exact-chart"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:600,height:190}}><ComposedChart data={analytics.trend.map(p=>({...p,chartValue:chart==='orders'?p.revenueKobo/100:conversion?.daily?.[p.date||'']||0}))} margin={{top:15,right:8,bottom:0,left:0}}><defs><linearGradient id="vnExactRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a7d959" stopOpacity={.65}/><stop offset="100%" stopColor="#a7d959" stopOpacity={.08}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#171a1c0a"/><XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={35} tick={{fill:'#626866',fontSize:11}}/><YAxis width={58} axisLine={false} tickLine={false} tick={{fill:'#626866',fontSize:11}} tickFormatter={v=>chart==='ga4'?v+'%':Number(v).toLocaleString()}/><Tooltip contentStyle={{background:'#ffffff',border:'1px solid #e3e8e1',borderRadius:10,color:'#171a1c'}} formatter={(v:any)=>[chart==='orders'?formatNaira(Number(v)*100):Number(v).toFixed(2)+'%',chart==='orders'?'Collected revenue':'Conversion']}/><Area type="monotone" dataKey="chartValue" stroke="#8cc63f" strokeWidth={2.5} fill="url(#vnExactRevenue)" dot={false} activeDot={{r:4,fill:'#8cc63f',stroke:'#fff',strokeWidth:2}} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div>}
 </section>
 <section className="vn-glass vn-exact-fulfilment"><div className="vn-exact-card-head"><h2>Order fulfilment <DashboardInfo title="Order fulfilment">All paid, non-cancelled orders across all dates. Processing includes newly paid orders and orders needing stock review. Select a stage to open its orders.</DashboardInfo></h2><button className="vn-lime-link" onClick={()=>onNavigate({section:'orders',status:'fulfil'})}>View orders <ArrowRight size={14}/></button></div><div className="vn-fulfilment-visual"><div className="vn-donut"><svg viewBox="0 0 120 120" role="img" aria-label={fulfilment?`${total} paid orders across fulfilment stages`:'Loading fulfilment counts'}><circle cx="60" cy="60" r="49" fill="none" stroke="#282d2c" strokeWidth="10"/>{stages.map(s=>{const amount=total?(s.count||0)/total*307.876:0;const start=offset;offset+=amount;return <circle key={s.status} cx="60" cy="60" r="49" fill="none" stroke={s.color} strokeWidth="10" strokeDasharray={`${amount} 307.876`} strokeDashoffset={-start} transform="rotate(-90 60 60)"/>;})}</svg><div><strong>{fulfilment?total:'—'}</strong><span>paid orders</span></div></div><div className="vn-stage-list">{stages.map(s=><button key={s.status} onClick={()=>onNavigate({section:'orders',status:s.status==='processing'?'fulfil':s.status})}><s.Icon size={23}/><span className="vn-stage-name"><i style={{background:s.color}}/>{s.label}</span><strong>{s.count??'—'}</strong></button>)}</div></div></section>
 <section className="vn-glass vn-exact-orders"><div className="vn-exact-card-head"><h2>Recent orders <DashboardInfo title="Recent orders">Latest orders across all dates. These filters apply to the loaded recent orders. View all opens the complete searchable order list.</DashboardInfo></h2><div className="vn-order-tabs" aria-label="Recent order filters">{['recent','processing','shipped','delivered'].map(v=><button key={v} aria-pressed={orderTab===v} onClick={()=>setOrderTab(v)}>{v==='recent'?'All':v[0].toUpperCase()+v.slice(1)}</button>)}</div><button className="vn-lime-link vn-mobile-view-all" onClick={()=>onNavigate({section:'orders'})}>View all <ArrowRight size={15}/></button></div><div className="vn-exact-order-table"><table><thead><tr><th>Order</th><th>Payment</th><th>Fulfilment</th><th>Total</th><th>Action</th></tr></thead><tbody>{shown.map(o=><tr key={o.id}><td><button title={o.reference} onClick={()=>onNavigate({section:'orders',query:o.reference})}>{o.reference}</button><span className="vn-mobile-order-total">{formatNaira(o.totalKobo)}</span></td><td><span className={'vn-order-status status-'+o.paymentStatus}>{o.paymentStatus.replaceAll('_',' ')}</span></td><td><span className={'vn-order-status status-'+o.status}>{o.status==='paid'?'Awaiting processing':o.status.replaceAll('_',' ')}</span></td><td>{formatNaira(o.totalKobo)}</td><td><button className="vn-small-button" aria-label={'View order '+o.reference} onClick={()=>onNavigate({section:'orders',query:o.reference})}>View <ArrowRight size={14}/></button></td></tr>)}</tbody></table>{!shown.length&&<div className="vn-exact-empty">No recent orders in this filter. <button onClick={()=>onNavigate({section:'orders',status:orderTab==='recent'?'all':orderTab==='processing'?'fulfil':orderTab})}>View all orders <ArrowRight size={14}/></button></div>}</div></section>
 <section className="vn-glass vn-owner-approvals"><div className="vn-exact-card-head"><h2>Owner approvals <DashboardInfo title="Owner approvals">Staff changes remain pending until you review and approve them. Rejected changes do not affect the live store.</DashboardInfo></h2></div><div className="vn-approval-summary"><span className="vn-round-icon"><Users size={24}/></span><div>Review staff changes<small>Only approved changes go live.</small></div><button className="vn-small-button" onClick={()=>onNavigate({section:'approvals'})}>Review changes <ArrowRight size={15}/></button></div></section>
 <div className="vn-exact-email">{emailPanel}</div>
 </div>
 <section className="vn-glass vn-exact-catalogue"><div className="vn-exact-card-head"><h2>Catalogue controls <DashboardInfo title="Catalogue controls">Select a control to open the existing editor. Product changes are saved explicitly; publishing and archiving remain under your control.</DashboardInfo></h2><button className="vn-small-button" onClick={()=>onNavigate({section:'products'})}>Edit products <ArrowRight size={15}/></button></div><div className="vn-catalogue-grid">{[{Icon:Tag,title:'Prices & stock',note:'Manage pricing and inventory',target:{section:'operations',resource:'bulk'}},{Icon:Package,title:'Sizes & colours',note:'Manage variants',target:{section:'collections'}},{Icon:Image,title:'Front / Back / Side views',note:'Upload product images',target:{section:'media'}},{Icon:Ruler,title:'Measurements & care',note:'Size guide and product care',target:{section:'products'}},{Icon:FileText,title:'Draft / Publish / Archive',note:'Control visibility',target:{section:'products'}}].map(({Icon,title,note,target})=><button key={title} onClick={()=>onNavigate(target)}><Icon size={23}/><span>{title}<small>{note}</small></span><ChevronRight size={15}/></button>)}</div></section>
 <section className="vn-glass vn-exact-connections"><h2>Connections <DashboardInfo title="Connections">These statuses reflect configured credentials and the latest analytics response. Open Manage connections for details; configuration does not guarantee a provider is reachable.</DashboardInfo></h2>{[{label:'Paystack',symbol:'▰',kind:'paystack',state:paymentsMode==='live'?'Live':paymentsMode==='test'?'Test mode':'Not configured',ok:paymentsMode==='live'},{label:'Google Analytics',symbol:'▥',kind:'google',state:conversion?.status==='connected'?'Connected':connections?.ga4Configured?'Configured':connections?'Not connected':'Open to check',ok:conversion?.status==='connected'},{label:'Resend',symbol:'R',kind:'resend',state:connections?(connections.emailConfigured?'Configured':'Not configured'):'Open to check',ok:connections?.emailConfigured}].map(c=><button className="vn-connection-tile" key={c.label} onClick={()=>onNavigate({section:'settings'})}><b className={'vn-provider-'+c.kind}>{c.symbol}</b><span>{c.label}<small><i className={c.ok?'is-ok':''}/>{c.state}</small></span><ChevronRight size={15}/></button>)}<button className="vn-small-button" onClick={()=>onNavigate({section:'settings'})}>Manage connections <ArrowRight size={15}/></button></section>
 <details className="vn-extended-reports"><summary>More insights</summary><div className="vn-extended-grid"> <section className="vn-ref-card vn-best-sellers"><div className="vn-ref-card-head"><h2>Best sellers</h2><button onClick={()=>onNavigate({section:'products'})}>View products <ArrowRight size={15}/></button></div>{best.length?best.map(item=>{const product=products.find(p=>p.id===item.productId);return <button className="vn-best-row" key={item.productId} onClick={()=>product?onProduct(product):onNavigate({section:'products'})}>{product&&<StoreImage src={product.imageUrl} alt="" sizes="64px"/>}<div><h3>{item.name}</h3><p>{item.units} units sold</p><div className="vn-best-bar"><span style={{width:`${Math.max(4,item.revenueKobo/Math.max(...best.map(b=>b.revenueKobo),1)*100)}%`}}/></div></div><strong>{formatNaira(item.revenueKobo)}</strong></button>}):<div className="vn-ref-empty"><ShoppingCart size={28}/><h3>No paid sales in this period</h3><p>Choose another period or review your products.</p></div>}<p className="vn-ref-footnote">Ranked by gross item revenue · Selected period · Before discounts and refunds</p></section>
 <div className="vn-ref-right"><section className="vn-ref-card" id="vn-attention"><div className="vn-ref-card-head"><h2>Needs your attention</h2><span>{[lowStock,fulfil,drafts].filter(Boolean).length} tasks</span></div>{[{Icon:Package,n:lowStock,title:'variants running low',note:'Review stock available to sell.',target:{section:'inventory',stockFilter:'low'} as AdminTarget},{Icon:Truck,n:fulfil,title:'orders to fulfil',note:'Paid and ready for the next step.',target:{section:'orders',status:'fulfil'}},{Icon:Pencil,n:drafts,title:'products in draft',note:'Your next drop is taking shape.',target:{section:'products',productStatus:'draft'}}].map(({Icon,n,title,note,target})=><button className="vn-attention-row" key={title} onClick={()=>onNavigate(target)}><span className="vn-attention-icon"><Icon size={20}/></span><div><strong>{n} {title}</strong><p>{note}</p></div><ArrowRight size={16}/></button>)}</section></div></div></details>
 <details className="vn-extended-reports"><summary>Dashboard artwork</summary><section><button className="vn-collection-callout" onClick={()=>campaign?onProduct(campaign):onNavigate({section:'collections'})}><div><small>THE NEXT CHAPTER</small><h2>Make your<br/>presence felt.</h2><span>{campaign?campaign.name:'Explore your collection'} <ArrowRight size={16}/></span></div>{campaign&&<StoreImage src={campaign.imageUrl} alt={campaign.name} sizes="180px"/>}</button><button className="vn-artwork-edit" disabled={saving} onClick={()=>{if(editing)void saveCampaign(draftCampaign);else{setDraftCampaign(campaignProductId);setEditing(true);}}}>{saving?'Saving…':editing?'Save':'Edit dashboard artwork'}</button>{editing&&<label>Product image<select aria-label="Dashboard artwork product" disabled={saving} value={draftCampaign} onChange={e=>setDraftCampaign(e.target.value)}><option value="">No garment image</option>{products.filter(p=>p.status!=='archived').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}{feedback&&<p role="status">{feedback}</p>}</section></details>
 </>;
}
