"use client";
import {Area,AreaChart,CartesianGrid,XAxis,YAxis,ResponsiveContainer,Tooltip} from 'recharts';
import {Wallet,ShoppingBag,ChartNoAxesCombined,Receipt,ArrowUpRight,Package,Truck,Pencil,Download} from 'lucide-react';
import {formatNaira} from '@/lib/catalog';
import type {AdminAnalytics,AdminOrder,AdminProduct} from '@/lib/store-db';
import StoreImage from '@/components/store-image';
export function OverviewPanel({analytics,orders,products,lowStock,onNavigate,onProduct}:{analytics:AdminAnalytics;orders:AdminOrder[];products:AdminProduct[];lowStock:number;onNavigate:(section:string)=>void;onProduct:(product:AdminProduct)=>void}){
 const revenue=analytics.trend.reduce((sum,p)=>sum+p.revenueKobo,0),paid=analytics.trend.reduce((sum,p)=>sum+p.orders,0);
 const best=analytics.bestSellers||[],drafts=products.filter(p=>p.status==='draft').length,fulfil=analytics.fulfilmentCount||0;
 function exportReport(){const csv='Date,Paid orders,Revenue NGN\n'+analytics.trend.map(p=>`${p.label},${p.orders},${p.revenueKobo/100}`).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='vanta-noir-revenue-30-days.csv';a.click();URL.revokeObjectURL(u);}
 return <>
  <div className="vn-overview-tools"><span>Last 30 days · UTC</span><button onClick={exportReport}><Download size={16}/> Export report</button></div>
  <section className="vn-ref-metrics" aria-label="Store summary">{[{label:'Total revenue',value:formatNaira(revenue),note:'Paid, non-cancelled orders',Icon:Wallet},{label:'Paid orders',value:String(paid),note:'Orders placed in the last 30 days',Icon:ShoppingBag},{label:'Conversion rate',value:'—',note:'Visitor analytics not connected',Icon:ChartNoAxesCombined},{label:'Average order value',value:paid?formatNaira(Math.round(revenue/paid)):'—',note:paid?'Revenue divided by paid orders':'Awaiting your first paid order',Icon:Receipt}].map(({label,value,note,Icon})=><article key={label}><div className="vn-ref-metric-label"><Icon size={17}/>{label}<span/></div><strong>{value}</strong><p>{note}</p></article>)}</section>
  <div className="vn-ref-grid">
   <section className="vn-ref-card vn-revenue"><div className="vn-ref-card-head"><h2>Revenue overview</h2><span className="vn-chart-legend">Paid revenue</span></div><strong className="vn-revenue-total">{formatNaira(revenue)}</strong><p className="vn-ref-muted">From {paid} paid orders · NGN</p><div className="vn-revenue-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={analytics.trend} margin={{top:24,right:10,bottom:0,left:0}}><defs><linearGradient id="vnRevenueFade" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a8d785" stopOpacity={0.24}/><stop offset="100%" stopColor="#a8d785" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#293128" strokeDasharray="3 7"/><XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={40} tick={{fill:'#929d93',fontSize:12}}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#929d93',fontSize:12}} tickFormatter={n=>'₦'+(n/100>=1000?(n/100000).toFixed(0)+'k':(n/100).toFixed(0))}/><Tooltip contentStyle={{background:'#151b17',border:'1px solid #303b30',borderRadius:10,color:'#eef2eb'}} formatter={(v:any)=>[formatNaira(Number(v)),'Paid revenue']}/><Area type="monotone" dataKey="revenueKobo" stroke="#acd98b" strokeWidth={2.5} fill="url(#vnRevenueFade)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><p className="vn-ref-footnote">{paid?'Includes delivery. Excludes unpaid and cancelled orders.':'Your revenue trend will appear after the first paid order.'}</p></section>
   <section className="vn-ref-card"><div className="vn-ref-card-head"><h2>Best sellers</h2><button onClick={()=>onNavigate('products')}>View products <ArrowUpRight size={15}/></button></div>{best.length?best.map(item=>{const product=products.find(p=>p.id===item.productId);return <button className="vn-best-row" key={item.productId} onClick={()=>product?onProduct(product):onNavigate('products')}>{product&&<StoreImage src={product.imageUrl} alt="" sizes="64px"/>}<div><h3>{item.name}</h3><p>{item.units} units sold</p><div className="vn-best-bar"><span style={{width:`${Math.max(4,item.revenueKobo/Math.max(...best.map(b=>b.revenueKobo),1)*100)}%`}}/></div></div><strong>{formatNaira(item.revenueKobo)}</strong></button>}):<div className="vn-ref-empty"><ShoppingBag size={28}/><h3>Your first best seller starts here</h3><p>Products will be ranked when paid orders arrive.</p><button onClick={()=>onNavigate('products')}>Review your products <ArrowUpRight size={15}/></button></div>}<p className="vn-ref-footnote">Ranked by gross item revenue · Last 30 days</p></section>
   <section className="vn-ref-card vn-ref-orders"><div className="vn-ref-card-head"><div><h2>Recent orders</h2><p className="vn-ref-muted">A closer look at your latest activity.</p></div><button onClick={()=>onNavigate('orders')}>All orders <ArrowUpRight size={15}/></button></div><div className="vn-ref-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Amount</th><th>Payment</th><th>Fulfilment</th></tr></thead><tbody>{orders.slice(0,4).map(o=><tr key={o.id}><td>{o.reference}<small>{new Date(o.createdAt).toLocaleDateString('en-NG',{day:'numeric',month:'short'})}</small></td><td>{o.firstName} {o.lastName}<small>{o.items.length} items</small></td><td>{formatNaira(o.totalKobo)}</td><td><span className={'vn-status '+(o.paymentStatus==='paid'?'is-paid':'')}>{o.paymentStatus.replaceAll('_',' ')}</span></td><td><span className="vn-status is-fulfilment">{o.status.replaceAll('_',' ')}</span></td></tr>)}</tbody></table>{!orders.length&&<div className="vn-ref-empty"><Receipt size={28}/><h3>No orders yet</h3><p>New customer orders will appear here.</p></div>}</div><button className="vn-ref-table-footer" onClick={()=>onNavigate('orders')}>Manage orders <ArrowUpRight size={15}/></button></section>
   <div className="vn-ref-right"><section className="vn-ref-card" id="vn-attention"><div className="vn-ref-card-head"><h2>Needs your attention</h2><span>{[lowStock,fulfil,drafts].filter(Boolean).length} tasks</span></div>{[{Icon:Package,n:lowStock,title:'variants running low',note:'Review physical stock and availability.',section:'inventory'},{Icon:Truck,n:fulfil,title:'orders to fulfil',note:'Paid and ready for the next step.',section:'orders'},{Icon:Pencil,n:drafts,title:'products in draft',note:'Your next drop is taking shape.',section:'products'}].map(({Icon,n,title,note,section})=><button className="vn-attention-row" key={title} onClick={()=>onNavigate(section)}><span className="vn-attention-icon"><Icon size={20}/></span><div><strong>{n} {title}</strong><p>{note}</p></div><ArrowUpRight size={16}/></button>)}</section><button className="vn-collection-callout" onClick={()=>onNavigate('collections')}><div><small>THE NEXT CHAPTER</small><h2>Make your<br/>presence felt.</h2><span>Explore your collection <ArrowUpRight size={16}/></span></div>{products[0]&&<StoreImage src={products[0].imageUrl} alt="" sizes="180px"/>}</button></div>
  </div><footer className="vn-ref-footer"><span>Presence. Power. Precision.</span><span>Figures from this workspace’s database</span></footer>
 </>;
}
