'use client';
import {useUnsavedChanges} from './unsaved-changes';
import {useState} from 'react';
import type {ItemParcel,Packaging} from '@/lib/parcel-estimates';
const fields={weightGrams:'Item weight (grams)',lengthCm:'Folded length (cm)',widthCm:'Folded width (cm)',heightCm:'Folded height (cm)'};
async function api(url:string,body?:unknown){const r=await fetch(url,body?{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const v=await r.json() as any;if(!r.ok)throw Error(v.error||'Request failed.');return v;}
export function ParcelProfiles(){
 const [open,setOpen]=useState(false),[q,setQ]=useState(''),[page,setPage]=useState(0),[data,setData]=useState<any>(null),[item,setItem]=useState<any>(null),[packs,setPacks]=useState<Packaging[]>([]),[packRevision,setPackRevision]=useState<string|null>(null),[dirty,setDirty]=useState(false),[packDirty,setPackDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useUnsavedChanges({name:'Weights and packaging',dirty:dirty||packDirty,busy,discard:()=>{setItem(null);setPacks(data?.packaging?.data||[]);setDirty(false);setPackDirty(false);}});
 const discard=()=>!(dirty||packDirty)||window.confirm('Discard unsaved parcel profile edits?');
 async function load(next=0){if(!discard())return;setBusy(true);setMessage('');try{const v=await api('/api/admin/parcel-profiles?q='+encodeURIComponent(q)+'&page='+next);setData(v);setPacks(v.packaging.data);setPackRevision(v.packaging.revision);setPage(next);setItem(null);setDirty(false);setPackDirty(false);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function choose(productId:string,size:string){if(dirty&&!window.confirm('Discard unsaved item measurements?'))return;setBusy(true);setMessage('');try{setItem(await api('/api/admin/parcel-profiles?productId='+encodeURIComponent(productId)+'&size='+encodeURIComponent(size)));setDirty(false);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function save(kind:'product'|'packaging'){if(busy)return;setBusy(true);setMessage('');try{const v=await api('/api/admin/parcel-profiles',kind==='packaging'?{kind,data:packs,revision:packRevision}:{kind,productId:item.productId,size:item.size,data:item.parcel,revision:item.revision});if(kind==='packaging'){setPacks(v.saved.data);setPackRevision(v.saved.revision);setPackDirty(false);}else{setItem({...item,parcel:v.saved.data,revision:v.saved.revision,basis:'Saved product/size profile.'});setDirty(false);}setMessage('Parcel profile saved ✓');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function editItem(key:string,value:unknown){setItem({...item,parcel:{weightGrams:0,lengthCm:0,widthCm:0,heightCm:0,measured:false,...item.parcel,[key]:value,...(key==='measured'?{}:{measured:false})}});setDirty(true);}
 function editPack(i:number,key:string,value:unknown){setPacks(packs.map((p,j)=>j===i?{...p,[key]:value,...(key==='measured'?{}:{measured:false})}:p));setPackDirty(true);}
 return <section className="vn-product-disclosure" style={{minWidth:0}}><h3>Product weights &amp; packaging</h3><p>Estimates are preparation aids, not measured shipping specifications. Save a sample measurement once per product and size; the profile applies to colours with the same construction. Physically different colourways need a final packing check.</p><button className="vn-pill" disabled={busy} onClick={()=>{if(open){if(discard())setOpen(false);}else{setOpen(true);void load();}}}>{open?'Close parcel profiles':'Manage weights & packaging'}</button>{open&&<div>
 <form onSubmit={e=>{e.preventDefault();void load(0);}}><label>Find product<input value={q} onChange={e=>setQ(e.target.value)} maxLength={100}/></label><button className="vn-pill" disabled={busy}>Search products</button></form>
 {data?.products.map((p:any)=><div key={p.id} style={{marginBlock:12}}><strong>{p.name}</strong><div>{p.sizes.map((s:string)=><button className="vn-pill" disabled={busy} key={s} onClick={()=>void choose(p.id,s)}>{s}</button>)}</div></div>)}{data&&!data.products.length&&<p>No matching products.</p>}
 <button className="vn-pill" disabled={busy||page===0} onClick={()=>void load(page-1)}>Previous products</button> <button className="vn-pill" disabled={busy||!data?.hasMore} onClick={()=>void load(page+1)}>Next products</button>
 {item&&<fieldset disabled={busy} style={{minWidth:0,marginBlock:16}}><legend>{item.name} — {item.size}</legend><p>{item.basis}</p><strong>{item.parcel?.measured?'Measured sample':'Estimated / unverified'}</strong><div className="vn-admin-fields">{Object.entries(fields).map(([k,label])=><label key={k}>{label}<input type="number" min="1" step={k==='weightGrams'?'1':'0.1'} value={item.parcel?.[k]||''} onChange={e=>editItem(k,Number(e.target.value))}/></label>)}</div><label><input type="checkbox" checked={item.parcel?.measured||false} onChange={e=>editItem('measured',e.target.checked)}/> I weighed and measured this finished sample, excluding shipping packaging.</label><p>Fabric GSM is not garment weight. Enter the item's physical weight in grams.</p><button className="vn-pill" disabled={!item.parcel} onClick={()=>void save('product')}>Save item measurements</button>{dirty&&<p>Unsaved item changes</p>}</fieldset>}
 <h4>Packaging presets</h4><p>Starter sizes are estimates. Replace them with your actual packaging. Dimensions describe the filled outer parcel; empty packaging weight is added separately. Preset selection estimates fit and still needs a packing check.</p>
 {packs.map((p,i)=><fieldset key={p.id} disabled={busy} style={{minWidth:0,marginBlock:12}}><legend>{p.name}</legend><div className="vn-admin-fields"><label>Packaging name<input value={p.name} onChange={e=>editPack(i,'name',e.target.value)}/></label>{Object.entries({lengthCm:'Outer length (cm)',widthCm:'Outer width (cm)',heightCm:'Filled outer height (cm)',tareGrams:'Empty packaging weight (grams)',maxWeightGrams:'Maximum packed weight (grams)'}).map(([k,label])=><label key={k}>{label}<input type="number" min="1" step="0.1" value={(p as any)[k]||''} onChange={e=>editPack(i,k,Number(e.target.value))}/></label>)}</div><label><input type="checkbox" checked={p.measured} onChange={e=>editPack(i,'measured',e.target.checked)}/> I checked these dimensions, empty weight and weight limit.</label><button className="vn-pill" disabled={packs.length===1} onClick={()=>{setPacks(packs.filter((_,j)=>j!==i));setPackDirty(true);}}>Remove preset</button></fieldset>)}
 <button className="vn-pill" disabled={busy||packs.length>=20} onClick={()=>{setPacks([...packs,{id:crypto.randomUUID(),name:'New packaging',lengthCm:0,widthCm:0,heightCm:0,tareGrams:0,maxWeightGrams:0,measured:false}]);setPackDirty(true);}}>Add packaging preset</button> <button className="vn-pill" disabled={busy||!packDirty} onClick={()=>void save('packaging')}>Save packaging presets</button>{packDirty&&<p>Unsaved packaging changes</p>}
 {message&&<p role="status">{message}</p>}{busy&&<p role="status">Working…</p>}
 </div>}</section>;
}
export function OrderParcel({reference,onUse}:{reference:string;onUse?:(parcel:{weightKg:number;lengthCm:number;widthCm:number;heightCm:number})=>void}){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setBusy(true);setError('');try{setData(await api('/api/admin/parcel-profiles?reference='+encodeURIComponent(reference)));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section style={{minWidth:0,marginBlock:12}}><button type="button" className="vn-pill" disabled={busy} onClick={()=>void load()}>{busy?'Calculating…':'Calculate parcel from order items'}</button>{error&&<p role="alert">{error}</p>}{data&&<><ul>{data.items.map((i:any,n:number)=><li key={n}>{i.name} · {i.size} × {i.quantity}: {i.parcel?`${i.parcel.weightGrams} g each (${i.parcel.measured?'measured sample':'estimate'})`:'measurement needed'}</li>)}</ul><p>{data.reason}</p>{data.suggestion&&<><p><strong>{data.suggestion.estimated?'Estimated parcel':'Sample-based parcel estimate'}</strong>: {data.suggestion.weightKg} kg · {data.suggestion.lengthCm} × {data.suggestion.widthCm} × {data.suggestion.heightCm} cm · {data.suggestion.packagingName}</p>{onUse&&<button className="vn-pill" type="button" onClick={()=>onUse(data.suggestion)}>Use suggestion for sandbox quote</button>}</>}<p>Live booking is disabled. Verify the actual packed parcel before any future paid booking.</p></>}</section>;
}
