'use client';
import {RecordEditor} from './record-editor';
import {useAdminNavigation} from './unsaved-changes';
import {useState} from 'react';
import type {ItemParcel,Packaging} from '@/lib/parcel-estimates';
const fields={weightGrams:'Item weight (grams)',lengthCm:'Folded length (cm)',widthCm:'Folded width (cm)',heightCm:'Folded height (cm)'};
async function api(url:string,body?:unknown){const r=await fetch(url,body?{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const v=await r.json() as any;if(!r.ok)throw Error(v.error||'Request failed.');return v;}
export function ParcelProfiles(){
 const [open,setOpen]=useState(false),[q,setQ]=useState(''),[page,setPage]=useState(0),[data,setData]=useState<any>(null),[item,setItem]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const navigate=useAdminNavigation();
 async function load(next=0){setBusy(true);setMessage('');try{const v=await api('/api/admin/parcel-profiles?q='+encodeURIComponent(q)+'&page='+next);setData(v);setPage(next);setItem(null);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function choose(productId:string,size:string){setBusy(true);setMessage('');try{setItem(await api('/api/admin/parcel-profiles?productId='+encodeURIComponent(productId)+'&size='+encodeURIComponent(size)));}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="vn-product-disclosure" style={{minWidth:0}}><h3>Product weights &amp; packaging</h3><p>Save your approved shipping weights for each product and size. Changes apply to new delivery quotes.</p><button className="vn-pill" disabled={busy} onClick={()=>navigate(()=>{setOpen(!open);if(!open)void load();})}>{open?'Close parcel profiles':'Manage weights & packaging'}</button>{open&&<div>
 <form onSubmit={e=>{e.preventDefault();navigate(()=>void load(0));}}><label>Find product<input value={q} onChange={e=>setQ(e.target.value)} maxLength={100}/></label><button className="vn-pill" disabled={busy}>Search products</button></form>
 <div className="vn-pagination"><button className="vn-pill" disabled={busy||page===0} onClick={()=>navigate(()=>void load(page-1))}>Previous products</button><span>Page {page+1}</span><button className="vn-pill" disabled={busy||!data?.hasMore} onClick={()=>navigate(()=>void load(page+1))}>Next products</button></div>
 {data?.products.map((p:any)=><div key={p.id} style={{marginBlock:12}}><strong>{p.name}</strong><div>{p.sizes.map((size:string)=><button className="vn-pill" disabled={busy} key={size} onClick={()=>navigate(()=>void choose(p.id,size))}>{size}</button>)}</div></div>)}{data&&!data.products.length&&<p>No matching products.</p>}
 {item&&<RecordEditor key={item.productId+':'+item.size} name={item.name+' — '+item.size} busy={busy} initialValue={{revision:item.revision,parcel:{weightGrams:0,lengthCm:0,widthCm:0,heightCm:0,measured:false,...item.parcel} as ItemParcel}} onSave={async v=>{const result=await api('/api/admin/parcel-profiles',{kind:'product',productId:item.productId,size:item.size,data:v.parcel,revision:v.revision});setItem({...item,parcel:result.saved.data,revision:result.saved.revision,basis:'Saved product/size profile.'});return true;}}>{(v,set)=><><p>{item.basis}</p><div className="vn-admin-fields">{Object.entries(fields).map(([k,label])=><label key={k}>{label}<input required type="number" min="1" step={k==='weightGrams'?'1':'0.1'} value={v.parcel[k as keyof ItemParcel] as number||''} onChange={e=>set({...v,parcel:{...v.parcel,[k]:Number(e.target.value),measured:false}})}/></label>)}</div><label><input type="checkbox" checked={v.parcel.measured} onChange={e=>set({...v,parcel:{...v.parcel,measured:e.target.checked}})}/> I weighed and measured this finished sample, excluding shipping packaging.</label><p>Saving approves this weight for checkout. Mark it measured only when checked against a physical sample.</p></>}</RecordEditor>}
 {data&&<RecordEditor name="Packaging presets" busy={busy} initialValue={{revision:data.packaging.revision as string|null,packs:data.packaging.data as Packaging[]}} onSave={async v=>{const result=await api('/api/admin/parcel-profiles',{kind:'packaging',data:v.packs,revision:v.revision});setData((current:any)=>({...current,packaging:result.saved}));return true;}}>{(v,set)=><><p>Use filled outer parcel dimensions and empty packaging weight. Confirm the actual packed parcel before booking.</p>{v.packs.map((p,i)=><fieldset key={p.id} style={{minWidth:0,marginBlock:12}}><legend>{p.name}</legend><div className="vn-admin-fields"><label>Packaging name<input required value={p.name} onChange={e=>set({...v,packs:v.packs.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/></label>{Object.entries({lengthCm:'Outer length (cm)',widthCm:'Outer width (cm)',heightCm:'Filled outer height (cm)',tareGrams:'Box + tissue/tape weight (grams)',maxWeightGrams:'Maximum packed weight (grams)'}).map(([k,label])=><label key={k}>{label}<input required type="number" min="1" step="0.1" value={(p as any)[k]||''} onChange={e=>set({...v,packs:v.packs.map((x,j)=>j===i?{...x,[k]:Number(e.target.value),measured:false}:x)})}/></label>)}</div><label><input type="checkbox" checked={p.measured} onChange={e=>set({...v,packs:v.packs.map((x,j)=>j===i?{...x,measured:e.target.checked}:x)})}/> I checked these dimensions, empty weight and weight limit.</label><button type="button" className="vn-pill" disabled={v.packs.length===1} onClick={()=>set({...v,packs:v.packs.filter((_,j)=>j!==i)})}>Remove preset</button></fieldset>)}<button type="button" className="vn-pill" disabled={v.packs.length>=20} onClick={()=>set({...v,packs:[...v.packs,{...v.packs[0],id:crypto.randomUUID(),name:'New packaging — review dimensions',measured:false}]})}>Add packaging preset</button></>}</RecordEditor>}
 {message&&<p role="alert">{message}</p>}{busy&&<p role="status">Working…</p>}
 </div>}</section>;
}
export function OrderParcel({reference,onUse}:{reference:string;onUse?:(parcel:{weightKg:number;lengthCm:number;widthCm:number;heightCm:number})=>void}){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setBusy(true);setError('');try{setData(await api('/api/admin/parcel-profiles?reference='+encodeURIComponent(reference)));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section style={{minWidth:0,marginBlock:12}}><button type="button" className="vn-pill" disabled={busy} onClick={()=>void load()}>{busy?'Calculating…':'Calculate parcel from order items'}</button>{error&&<p role="alert">{error}</p>}{data&&<>{data.selectedDelivery&&<p><strong>Customer selected: {data.selectedDelivery.carrier} via {data.selectedDelivery.provider}</strong> · ₦{(data.selectedDelivery.amountKobo/100).toLocaleString()} before rewards · {data.selectedDelivery.delivery}. Booking must be confirmed manually after payment; this quote is not a shipping label.</p>}<ul>{data.items.map((i:any,n:number)=><li key={n}>{i.name} · {i.size} × {i.quantity}: {i.parcel?`${i.parcel.weightGrams} g each (${i.parcel.measured?'measured sample':i.parcel.approvedForCheckout?'approved standard':'unapproved estimate'})`:'measurement needed'}</li>)}</ul><p>{data.reason}</p>{data.suggestion&&<><p><strong>{data.suggestion.estimated?'Estimated parcel':'Sample-based parcel estimate'}</strong>: {data.suggestion.weightKg} kg · {data.suggestion.lengthCm} × {data.suggestion.widthCm} × {data.suggestion.heightCm} cm · {data.suggestion.packagingName}</p>{onUse&&<button className="vn-pill" type="button" onClick={()=>onUse(data.suggestion)}>Use suggestion for sandbox quote</button>}</>}<p>Live booking is disabled. Verify the actual packed parcel before any future paid booking.</p></>}</section>;
}
