'use client';
import {useEffect,useRef,useState} from 'react';
import {formatNaira} from '@/lib/catalog';
import {adminRead} from '@/lib/admin-read';
import {useUnsavedChanges} from './unsaved-changes';
import './sales-desk.css';
type Variant={id:string;name:string;sku:string;color:string;size:string;priceKobo:number;stock:number;reserved:number;available:number};
type Item={variant:Variant;quantity:number};
type Sale={reference:string;totalKobo:number;createdAt:string;actor:string;status:string;reviewNote:string;details:{items:Array<{productName:string;color:string;size:string;quantity:number}>}};
type Data={variants:Variant[];sales:Sale[];hasMore:boolean;moreVariants:boolean;pending:number};
export function SalesDesk({owner=false,onChanged}:{owner?:boolean;onChanged?:()=>Promise<void>}){
 const [data,setData]=useState<Data>({variants:[],sales:[],hasMore:false,moreVariants:false,pending:0}),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[view,setView]=useState('sale'),[selected,setSelected]=useState(''),[quantity,setQuantity]=useState('1'),[items,setItems]=useState<Item[]>([]),[method,setMethod]=useState('cash'),[reference,setReference]=useState(''),[customer,setCustomer]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0),[retryPending,setRetryPending]=useState(false);
 const serial=useRef(0),lock=useRef(false),submission=useRef<{clientId:string;items:Array<{variantId:string;quantity:number;expectedPriceKobo:number}>;paymentMethod:string;paymentReference:string;customer:string}|null>(null);
 const chosen=data.variants.find(v=>v.id===selected),total=items.reduce((s,i)=>s+i.quantity*i.variant.priceKobo,0),units=items.reduce((s,i)=>s+i.quantity,0);
 useUnsavedChanges({name:'Walk-in sale',dirty:items.length>0||!!reference||!!customer,busy,discard:()=>{setItems([]);setReference('');setCustomer('');submission.current=null;setRetryPending(false);}});
 async function load(){const n=++serial.current;setLoading(true);try{const d=await adminRead<Data>('/api/admin/sales?'+new URLSearchParams({q:search,page:String(page)}),v=>!!v&&typeof v==='object'&&Array.isArray((v as Data).variants)&&Array.isArray((v as Data).sales));if(n===serial.current)setData(d);}catch(e){if(n===serial.current)setError((e as Error).message);}finally{if(n===serial.current)setLoading(false);}}
 useEffect(()=>{void load();return()=>{serial.current++;};},[search,page,attempt]);
 function add(){if(!chosen||!/^\d+$/.test(quantity)||Number(quantity)<1)return;const qty=Number(quantity)+(items.find(i=>i.variant.id===chosen.id)?.quantity||0);if(qty>Math.min(100,chosen.available)){setError('Choose a quantity within the available stock.');return;}if(items.length>=20&&!items.some(i=>i.variant.id===chosen.id)){setError('Record up to 20 different variations per sale.');return;}setItems([...items.filter(i=>i.variant.id!==chosen.id),{variant:chosen,quantity:qty}]);setQuantity('1');setError('');setNotice('');}
 async function submit(){
  if(lock.current||!items.length)return;lock.current=true;setBusy(true);setError('');setNotice('');
  submission.current??={clientId:crypto.randomUUID(),items:items.map(i=>({variantId:i.variant.id,quantity:i.quantity,expectedPriceKobo:i.variant.priceKobo})),paymentMethod:method,paymentReference:reference,customer};
  try{const r=await fetch('/api/admin/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(submission.current),signal:AbortSignal.timeout(30000)});const result=await r.json() as {reference:string;status:string;error?:string};if(!r.ok){if(r.status<500){submission.current=null;setRetryPending(false);}throw new Error(result.error||'Sale could not be submitted.');}
   submission.current=null;setRetryPending(false);setItems([]);setReference('');setCustomer('');setNotice(`${result.reference} · ${result.status==='pending'?'Stock reserved. Waiting for owner approval.':result.status+'. This sale was already recorded.'}`);await load();try{await onChanged?.();}catch{setNotice('Sale recorded. Refresh the dashboard to update its stock figures.');}
  }catch(e){if(submission.current)setRetryPending(true);setError((e as Error).message+(submission.current?' Use Retry submission to check the same sale safely.':''));}finally{lock.current=false;setBusy(false);}
 }
 return <section className="vn-sales-desk" aria-label="Sales desk"><header className="vn-sales-heading"><div><h2>Sales desk</h2><p>Record a walk-in sale. Keep online stock up to date.</p></div><span className="vn-sales-badge">Shared inventory · {data.pending} pending</span></header>
 <nav className="vn-sales-tabs" aria-label="Sales desk views">{[['sale','New sale'],['history','Sales history'],['stock','Available stock']].map(([id,label])=><button key={id} type="button" aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}<button type="button" disabled={loading||busy} onClick={()=>setAttempt(a=>a+1)}>Refresh</button></nav>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading&&<p role="status">Loading current stock and sales…</p>}
 {view!=='history'&&<form className="vn-sales-search" onSubmit={e=>{e.preventDefault();setSearch(query);setAttempt(a=>a+1);}}><label>Search product name or SKU<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Product name, SKU or barcode scanner input" maxLength={100}/></label><button type="submit">Search</button></form>}
 {view==='sale'&&<div className="vn-sales-grid"><div className="vn-sales-card"><h3>New walk-in sale</h3><fieldset disabled={busy||retryPending}><div className="vn-sales-fields"><label>Garment · colour · size<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a variation</option>{data.variants.map(v=><option key={v.id} value={v.id} disabled={v.available<1}>{v.name} · {v.color} / {v.size} · {v.available} available</option>)}</select></label><label>Quantity<input type="number" min="1" max="100" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><button type="button" onClick={add} disabled={!chosen||loading}>Add item</button></div>{data.moreVariants&&<p>Narrow your search to find more variations.</p>}
 <div className="vn-sales-table"><table><thead><tr><th>Item</th><th>Qty</th><th>Unit price</th><th>Total</th><th/></tr></thead><tbody>{items.map(i=><tr key={i.variant.id}><td>{i.variant.name}<small>{i.variant.color} / {i.variant.size}</small></td><td>{i.quantity}</td><td>{formatNaira(i.variant.priceKobo)}</td><td>{formatNaira(i.variant.priceKobo*i.quantity)}</td><td><button type="button" aria-label={'Remove '+i.variant.name+' '+i.variant.color+' '+i.variant.size} onClick={()=>setItems(items.filter(x=>x!==i))}>Remove</button></td></tr>)}</tbody></table></div>{!items.length&&<p>Add the garments sold to this customer.</p>}
 <div className="vn-sales-fields"><label>Payment method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="transfer">Bank transfer</option><option value="card">Card terminal</option></select></label><label>{method==='cash'?'Receipt reference (optional)':'Transfer / terminal reference'}<input maxLength={160} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Customer name or phone (optional)<input maxLength={200} value={customer} onChange={e=>setCustomer(e.target.value)}/></label></div></fieldset>
 <p>Record a payment you have received. This form does not charge a card or verify a bank transfer.</p><button className="vn-sales-submit" disabled={busy||!items.length||(method!=='cash'&&!reference.trim())} onClick={()=>void submit()}>{busy?'Submitting…':retryPending?'Retry submission':'Submit for approval'}</button><p>Submission reserves stock immediately. Owner approval finalizes the sale; rejection releases it. Prices are fixed to the catalogue. Price changes and refunds remain owner-controlled.</p></div>
 <aside><div className="vn-sales-card"><h3>Stock impact</h3>{items.length?items.map(i=>{const current=data.variants.find(v=>v.id===i.variant.id)||i.variant;return <div key={i.variant.id} className="vn-sales-impact"><strong>{i.variant.name}</strong><small>{i.variant.color} · {i.variant.size}</small><dl><div><dt>Available now</dt><dd>{current.available}</dd></div><div><dt>This sale</dt><dd>{i.quantity}</dd></div><div><dt>After submission</dt><dd>{Math.max(0,current.available-i.quantity)}</dd></div></dl>{i.quantity>current.available&&<p role="alert">Refresh this item: not enough stock.</p>}</div>}):<p>Select an item to see its stock impact.</p>}<p>Units are reserved while approval is pending.</p></div><div className="vn-sales-card"><h3>Sale summary</h3><dl><div><dt>Items</dt><dd>{units}</dd></div><div><dt>Total</dt><dd>{formatNaira(total)}</dd></div><div><dt>Payment</dt><dd>{method}</dd></div></dl><p>Awaiting submission</p></div></aside></div>}
 {view==='stock'&&<div className="vn-sales-card vn-sales-table"><h3>Available stock</h3><table><thead><tr><th>Product / SKU</th><th>Colour</th><th>Size</th><th>On hand</th><th>Reserved</th><th>Available</th></tr></thead><tbody>{data.variants.map(v=><tr key={v.id}><td>{v.name}<small>{v.sku}</small></td><td>{v.color}</td><td>{v.size}</td><td>{v.stock}</td><td>{v.reserved}</td><td>{v.available}</td></tr>)}</tbody></table>{data.moreVariants&&<p>Search for a product to narrow these results.</p>}</div>}
 {(view==='history'||view==='sale')&&<div className="vn-sales-card"><h3>{view==='sale'?'Recent sales':'Sales history'}</h3>{!data.sales.length&&!loading&&<p>No walk-in sales recorded yet.</p>}{data.sales.map(s=><details key={s.reference}><summary>{s.reference} · {formatNaira(s.totalKobo)} · {s.status}</summary><p>{s.createdAt} UTC · {s.actor}</p>{s.details.items.map((i,n)=><p key={n}>{i.quantity} × {i.productName} · {i.color} / {i.size}</p>)}{s.reviewNote&&<p>{s.reviewNote}</p>}</details>)}{owner&&<p>Review pending sales in Staff approvals.</p>}{view==='history'&&<div className="vn-sales-tabs"><button disabled={page===1||loading} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page}</span><button disabled={!data.hasMore||loading} onClick={()=>setPage(page+1)}>Next</button></div>}</div>}
 </section>;
}
