'use client';
import {useEffect,useRef,useState} from 'react';
import {adminRead} from '@/lib/admin-read';
import {formatNaira} from '@/lib/catalog-runtime';
import type {ComparisonRate} from '@/lib/shipping-comparison';
type Status={mode:'sandbox';configured:{terminal:boolean;shipbubble:boolean};job?:{status:string;error?:string;results?:Array<{destination:string;partial:boolean;rates:ComparisonRate[];providers:Array<{provider:string;status:string}>}>}};
export function ShippingComparison(){
 const [data,setData]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);
 async function load(){try{setData(await adminRead('/api/admin/shipping-comparison',v=>v?.mode==='sandbox'));setError('');}catch{setError('Comparison status could not load. Retry.');}}
 useEffect(()=>{void load();},[]);
 const pending=['queued','running'].includes(data?.job?.status||'');
 useEffect(()=>{if(!pending)return;const timer=setInterval(()=>{void load();},15000);return()=>clearInterval(timer);},[pending]);
 async function run(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const r=await fetch('/api/admin/shipping-comparison',{method:'POST',credentials:'same-origin'});const body=await r.json() as Status&{error?:string};if(!r.ok)throw Error(body.error||'Could not queue comparison.');setData(body);}catch(e){setError(e instanceof Error?e.message:'Could not queue comparison.');}finally{lock.current=false;setBusy(false);}}
 return <section className="vn-product-disclosure"><h3>Shipbubble + Terminal — test comparison</h3><p>Test mode only. Customer checkout and live bookings are disabled for this comparison.</p><p>Both providers receive the same synthetic 5 kg parcel, external dimensions and test addresses. Rates are sorted by customer price. Sandbox results do not establish real coverage or delivery prices.</p><p>Shipbubble test key: {data?.configured.shipbubble?'saved':'not confirmed'}. Terminal test key: {data?.configured.terminal?'saved':'not confirmed'}.</p><button type="button" className="vn-pill" onClick={run} disabled={busy||pending||!data?.configured.shipbubble||!data.configured.terminal}>{busy||pending?'Comparison queued / running…':'Compare test rates'}</button> <button type="button" className="vn-pill" onClick={load}>Refresh comparison</button><p>Queued tests run on the next scheduled backend check.</p>{(error||data?.job?.error)&&<p role="alert">{error||data?.job?.error}</p>}{data?.job?.results?.map(result=><div key={result.destination}><h4>{result.destination}</h4><p>{result.providers.map(p=>`${p.provider}: ${p.status}`).join(' · ')}</p>{result.partial&&<p>One provider failed. These results are incomplete.</p>}{!result.rates.length?<p>No supported door-to-door test quotes. This is not free delivery.</p>:result.rates.map((rate,i)=><p key={rate.provider+':'+rate.id}><strong>{i===0?'Lowest returned test price · ':''}{rate.carrier}</strong> · {rate.provider} · {formatNaira(rate.amountKobo)} · {rate.delivery}</p>)}</div>)}</section>;
}
