"use client";
import { MeasurementLibrary } from "./measurement-library";
import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { compareSizes, STORE_SIZES, SECTION_FIELDS, measurementLabel, resolveSizeGuide, sizeGuideSchema, type GarmentSizeGuide, type SizeSection, type MeasurementKey } from "@/lib/sizing";
import { adminRead, hasArray } from "@/lib/admin-read";
import type { ProductDetails } from "@/lib/product-details";

type Chart = {id:string;name:string;guide:GarmentSizeGuide};
const help:Record<MeasurementKey,string>={chest:"Measure straight across from armpit to armpit with the garment laid flat. This is half the garment circumference.",waist:"Measure straight across the waistband, laid flat and relaxed. Do not enter the full circumference.",waistStretched:"Measure across the waistband gently stretched to its intended wearing width, without distorting the fabric.",hip:"Measure straight across the widest hip point, laid flat. This is half the garment circumference.",shoulder:"Measure across the back from shoulder seam to shoulder seam.",sleeve:"Measure from the shoulder seam to the end of the sleeve. Use the same method for every size.",length:"Measure from the agreed highest garment point to the hem; for trousers, use the outer waistband to hem.",inseam:"Measure along the inside leg seam from the crotch seam to the hem."};
export function SizeGuideEditor({productId,value,onChange,sizes=[]}:{sizes?:string[];productId?:string;value:ProductDetails;onChange:(value:ProductDetails)=>void}){
 const guide=resolveSizeGuide({id:productId??"",details:value})??{status:"reference",notes:"",sections:[]};
 const chartSizes=[...new Set([...sizes,...guide.sections.flatMap(s=>s.rows.map(r=>r.size))])].filter(s=>s!=="Size pending").sort(compareSizes);
 const labels=chartSizes.length?chartSizes:[...STORE_SIZES];
 const [unit,setUnit]=useState<"cm"|"in">("cm"),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [mode,setMode]=useState<"saved"|"copy"|null>(null),[charts,setCharts]=useState<Chart[]>([]),[loading,setLoading]=useState(false),[selected,setSelected]=useState("");
 const [preview,setPreview]=useState(false),[measure,setMeasure]=useState<MeasurementKey|null>(null),[templateName,setTemplateName]=useState(""),[saving,setSaving]=useState(false);
 const save=(next:GarmentSizeGuide)=>{setError("");onChange({...value,sizeGuide:next});};
 const replace=(next:GarmentSizeGuide)=>{if(guide.sections.length&&!window.confirm("Replace the current chart? Product sizes, prices and stock will stay unchanged."))return;save({...next,status:"reference"});setMode(null);setMessage("Chart copied as provisional. Review it, then Save product.");};
 const change=(index:number,next:SizeSection)=>save({...guide,status:"reference",sections:guide.sections.map((s,i)=>i===index?next:s)});
 async function load(kind:"saved"|"copy") {setMode(kind);setLoading(true);setError("");setCharts([]);setSelected("");try{if(kind==="saved"){const data=await adminRead<{templates:Chart[]}>("/api/admin/size-templates",hasArray("templates"));setCharts(data.templates);}else{const data=await adminRead<{products:{id:string;name:string;details:ProductDetails}[]}>("/api/admin/products",hasArray("products"));setCharts(data.products.filter(p=>p.id!==productId).flatMap(p=>{const g=resolveSizeGuide(p);return g?.sections.length?[{id:p.id,name:p.name,guide:g}]:[];}));}}catch(e){setError(e instanceof Error?e.message:"Charts could not load.");}finally{setLoading(false);}}
 async function saveTemplate(){setError("");const parsed=sizeGuideSchema.safeParse(guide);if(!templateName.trim()||!parsed.success||!guide.sections.length){setError("Enter a chart name and add a valid measurement section first.");return;}setSaving(true);try{const r=await fetch("/api/admin/size-templates",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:templateName,guide:parsed.data}),signal:AbortSignal.timeout(15000)});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error||"Chart could not save.");setMessage("Reusable chart saved. Save product separately to publish this product’s changes.");setTemplateName("");}catch(e){setError(e instanceof Error?e.message:"Chart could not save.");}finally{setSaving(false);}}
 const display=(v:number|null|undefined)=>v==null?"":unit==="cm"?v:Math.round(v/2.54*100)/100;
 return <section className="vn-product-disclosure vn-guided-editor">
  <div className="vn-guide-heading"><h3>Sizes &amp; measurements</h3><span>{guide.status==="confirmed"?"Sample measurements confirmed":"Provisional · sample approval pending"}</span></div>
  <div className="vn-guide-steps" aria-label="Chart editing steps"><span className="vn-guide-step"><b>1</b>Garment</span><span className="vn-guide-step"><b>2</b>Sizes</span><span className="vn-guide-step"><b>3</b>Measurements</span></div>
  <label>Garment type<input value={value.garmentType} maxLength={240} placeholder="For example: tracksuit set" onChange={e=>onChange({...value,garmentType:e.target.value})}/></label>
  <p>Product sizes</p><div className="vn-guide-sizes">{labels.map(size=><span key={size}>{size}</span>)}</div><p>Manage sellable sizes and stock in Variations. Charts never change your inventory.</p><button type="button" className="vn-pill" onClick={()=>{const field=document.querySelector<HTMLInputElement>('[aria-label="New size label"]');field?.scrollIntoView({block:"center"});field?.focus();}}>Edit sizes &amp; stock</button>
  <div className="vn-guide-toolbar"><button type="button" onClick={()=>void load("saved")}>Saved charts</button><button type="button" onClick={()=>void load("copy")}>Copy product chart</button><button type="button" onClick={()=>replace({status:"reference",notes:"",sections:[]})}>New chart</button><span style={{marginLeft:"auto"}}>Units</span>{(["cm","in"] as const).map(u=><button type="button" key={u} aria-pressed={unit===u} onClick={()=>setUnit(u)}>{u}</button>)}</div>
  {mode&&<div className="vn-admin-fields"><label>{mode==="saved"?"Choose a saved chart":"Choose a product"}<select disabled={loading} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{loading?"Loading…":charts.length?"Select a chart":"No charts available"}</option>{charts.map(chart=><option key={chart.id} value={chart.id}>{chart.name}</option>)}</select></label><button type="button" disabled={!selected||loading} onClick={()=>{const chart=charts.find(c=>c.id===selected);if(chart)replace(chart.guide);}}>Use selected chart</button><button type="button" onClick={()=>setMode(null)}>Cancel</button></div>}
  {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
  {!!guide.sections.length&&<Tabs key={guide.sections.map(s=>s.kind).join()} defaultValue={guide.sections[0].kind}><TabsList aria-label="Edit garment measurements">{guide.sections.map(s=><TabsTrigger value={s.kind} key={s.kind}>{s.title}</TabsTrigger>)}</TabsList>{guide.sections.map((section,index)=><TabsContent value={section.kind} key={section.kind}><label>Garment label<input maxLength={60} value={section.title} onChange={e=>change(index,{...section,title:e.target.value})}/></label><div className="overflow-x-auto"><table className="vn-data-table"><caption className="sr-only">{section.title}, flat garment measurements in {unit}</caption><thead><tr><th>Size</th>{SECTION_FIELDS[section.kind].map(key=><th key={key}>{measurementLabel(key,section.kind)} ({unit}) <button type="button" aria-label={`How to measure ${measurementLabel(key,section.kind)}`} onClick={()=>setMeasure(key)}>ⓘ</button></th>)}</tr></thead><tbody>{labels.map(size=><tr key={size}><th scope="row">{size}</th>{SECTION_FIELDS[section.kind].map(key=><td key={key}><input className="w-24 border p-2" type="number" min={unit==="cm"?.1:.04} max={unit==="cm"?400:157.48} step="any" aria-label={`${section.title} ${size} ${measurementLabel(key,section.kind)} in ${unit}`} value={display(section.rows.find(row=>row.size===size)?.[key])} onChange={e=>{const number=e.target.value?Number(e.target.value):null;change(index,{...section,rows:labels.map(label=>({...section.rows.find(r=>r.size===label),size:label,...(label===size?{[key]:number===null?null:Math.round(number*(unit==="in"?2.54:1)*1000)/1000}:{})}))});}}/></td>)}</tr>)}</tbody></table></div><button className="vn-pill" type="button" onClick={()=>{if(window.confirm(`Remove the ${section.title} chart?`))save({...guide,status:"reference",sections:guide.sections.filter((_,i)=>i!==index)});}}>Remove {section.title} chart</button></TabsContent>)}</Tabs>}
  <div className="vn-guide-toolbar">{(["top","bottom","onepiece"] as const).filter(kind=>!guide.sections.some(s=>s.kind===kind)).map(kind=><button type="button" key={kind} onClick={()=>save({...guide,status:"reference",sections:[...guide.sections,{kind,title:{top:"Top",bottom:"Bottom",onepiece:"Dress / one-piece"}[kind],rows:labels.map(size=>({size}))}]})}>Add {kind==="onepiece"?"dress / one-piece":kind} chart</button>)}</div>
  <details><summary>Fit notes</summary><label>What should customers know about the fit?<textarea rows={3} maxLength={1500} value={guide.notes} onChange={e=>save({...guide,notes:e.target.value})}/></label></details>
  <details><summary>Advanced options &amp; reference library</summary><p>Use centimetres internally; unit switching converts the display. Chest, waist and hip are flat widths, not full circumferences. Leave unknown measurements blank.</p><label>Measurement approval<select value={guide.status} onChange={e=>{const parsed=sizeGuideSchema.safeParse({...guide,status:e.target.value});if(parsed.success)save(parsed.data);else setError(parsed.error.issues[0].message);}}><option value="reference">Provisional — sample approval pending</option><option value="confirmed">Confirmed against physical samples</option></select></label><MeasurementLibrary onApply={replace}/></details>
  <details><summary>Save as a reusable template</summary><label>Chart name<input value={templateName} maxLength={80} onChange={e=>setTemplateName(e.target.value)} placeholder="For example: approved relaxed tee pattern"/></label><button type="button" disabled={saving} onClick={()=>void saveTemplate()}>{saving?"Saving chart…":"Save reusable chart"}</button></details>
  <div className="vn-guide-toolbar"><button type="button" disabled={!guide.sections.length} onClick={()=>setPreview(true)}>Preview customer chart</button></div><p>Use <strong>Save product</strong> to save all changes. Only confirm measurements after checking physical samples.</p>
  <Dialog open={preview||!!measure} onOpenChange={open=>{if(!open){setPreview(false);setMeasure(null);}}}><DialogContent style={{maxWidth:760,maxHeight:"85dvh",overflow:"auto"}}><DialogTitle>{measure?`How to measure ${measurementLabel(measure,"top")}`:"Customer chart preview"}</DialogTitle><DialogDescription>{measure?help[measure]:`${guide.status==="reference"?"Provisional size guide · ":""}Flat garment measurements in ${unit}. ${guide.notes}`}</DialogDescription>{measure?<svg viewBox="0 0 240 180" role="img" aria-label="Lay the garment flat before measuring" style={{width:240,margin:"auto"}}><path d="M85 20 45 40 20 80 55 100 70 80V160H170V80L185 100 220 80 195 40 155 20Q120 50 85 20Z" fill="#e8efdc" stroke="#5a7341" strokeWidth="2"/><path d={{chest:"M75 85H165",waist:"M75 115H165",waistStretched:"M65 115H175",hip:"M75 145H165",shoulder:"M85 25H155",sleeve:"M155 25L211 80",length:"M120 45V160",inseam:"M120 100V160"}[measure]} stroke="#7d9f32" strokeWidth="3"/><text x="120" y="115" textAnchor="middle" fontSize="10">Follow the measurement instructions above</text></svg>:guide.sections.map(s=><div key={s.kind}><h4>{s.title}</h4><div className="overflow-x-auto"><table className="vn-data-table"><thead><tr><th>Size</th>{SECTION_FIELDS[s.kind].filter(k=>s.rows.some(r=>r[k]!=null)).map(k=><th key={k}>{measurementLabel(k,s.kind)} ({unit})</th>)}</tr></thead><tbody>{labels.map(size=><tr key={size}><th>{size}</th>{SECTION_FIELDS[s.kind].filter(k=>s.rows.some(r=>r[k]!=null)).map(k=><td key={k}>{display(s.rows.find(r=>r.size===size)?.[k])||"—"}</td>)}</tr>)}</tbody></table></div></div>)}</DialogContent></Dialog>
 </section>;
}
