'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import './staff-chat.css';
import './portal-theme.css';
import {WorkspaceHelp} from './workspace-help';
import {SupportOrderLookup} from './support-order-lookup';
import {adminRead} from '@/lib/admin-read';
import './support-dashboard.css';
import type {StaffRole} from '@/lib/operations-permissions';
type Message={seq:number;id:string;author:string;role:string;body:string;created_at:string};
const channels=[['all','All staff'],['sales','Sales'],['support','Support'],['fulfilment','Fulfilment'],['catalogue','Catalogue'],['analyst','Analytics']];
export function StaffChat({role='support',email=''}:{role?:StaffRole;email?:string}){
 const [view,setView]=useState<'chat'|'help'|'lookup'|'enquiry'>('chat'),[guide,setGuide]=useState<'admin'|'sales'|'support'>(role==='owner'?'admin':role==='sales'?'sales':'support'),[lookup,setLookup]=useState(''),[enquiry,setEnquiry]=useState('');
 const canLookup=role==='owner'||role==='support';
 const [drafts,setDrafts]=useState<Record<string,string>>({});
 function changeChannel(next:string){setDrafts(old=>({...old,[channel]:body}));setBody(drafts[next]||'');setChannel(next);setView('chat');}

 const [open,setOpen]=useState(false),[channel,setChannel]=useState('all'),[messages,setMessages]=useState<Message[]>([]),[unread,setUnread]=useState(0),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[intro,setIntro]=useState(false),[retry,setRetry]=useState(0);const sent=useRef<{id:string;body:string;channel:string}|null>(null),seenIntro=useRef(false),cursor=useRef(0),feed=useRef<HTMLDivElement>(null),generation=useRef(0);
 useEffect(()=>{if(open&&!seenIntro.current){seenIntro.current=true;setIntro(!matchMedia('(prefers-reduced-motion: reduce)').matches);const t=setTimeout(()=>setIntro(false),1400);return()=>clearTimeout(t);}setIntro(false);},[open]);
 useEffect(()=>{const g=++generation.current;cursor.current=0;setMessages([]);setError('');let stopped=false,timer:ReturnType<typeof setTimeout>,controller:AbortController|null=null;
 const poll=async()=>{if(stopped)return;if(document.hidden){timer=setTimeout(poll,15000);return;}controller=new AbortController();const timeout=setTimeout(()=>controller?.abort(),15000);try{const response=await fetch(`/api/admin/chat?channel=${channel}&after=${cursor.current}${open&&view==='chat'?'':'&summary=1'}`,{signal:controller.signal,cache:'no-store'});const result=await response.json() as {error?:string;unread:number;messages:Message[]};if(!response.ok)throw new Error(result.error||'Chat unavailable');if(stopped||generation.current!==g)return;setUnread(result.unread);setError('');if(open&&view==='chat'&&Array.isArray(result.messages)&&result.messages.length){const nearBottom=!feed.current||feed.current.scrollHeight-feed.current.scrollTop-feed.current.clientHeight<90;cursor.current=Math.max(cursor.current,...result.messages.map((m:Message)=>m.seq));setMessages(old=>[...old,...result.messages.filter((m:Message)=>!old.some(x=>x.id===m.id))].slice(-200));if(nearBottom)requestAnimationFrame(()=>feed.current?.scrollTo({top:feed.current.scrollHeight}));await fetch('/api/admin/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'read',channel,seq:cursor.current}),signal:controller.signal});}}
 catch(e){if(!stopped)setError(e instanceof Error?e.message:'Chat unavailable');}finally{clearTimeout(timeout);if(!stopped)timer=setTimeout(poll,open?6000:60000);}};void poll();return()=>{stopped=true;clearTimeout(timer);controller?.abort();};},[open,channel,retry,view]);
 async function send(){if(busy||!body.trim())return;setBusy(true);setError('');const message=sent.current?.body===body&&sent.current.channel===channel?sent.current:{id:crypto.randomUUID(),body,channel};sent.current=message;try{const r=await fetch('/api/admin/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'send',...message}),signal:AbortSignal.timeout(15000)});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Could not send.');setBody('');setDrafts(old=>({...old,[channel]:''}));sent.current=null;setRetry(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Could not send.');}finally{setBusy(false);}}
 return <><button className="vn-chat-launch" onClick={()=>setOpen(true)} aria-label={`Team chat${unread?`, ${unread} unread`:''}`}><MessageCircle size={20}/><span>Staff portal</span>{unread>0&&<b>{unread>99?'99+':unread}</b>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="vn-team-chat vn-staff-portal" aria-label="Staff communication portal">
 <header className="vn-portal-heading"><img src="/images/vanta-spire-light.svg" alt="Vanta Noir"/><div><DialogTitle>Staff communication portal</DialogTitle><DialogDescription>One workspace for the whole team</DialogDescription></div><span className="vn-portal-role">{role}</span></header>
 {intro&&<div className="vn-chat-intro" aria-hidden="true"><img className="vn-chat-intro-hero" src="/images/vanta-hero-960.webp" alt=""/><img className="vn-chat-intro-emblem" src="/images/vanta-emblem.svg" alt=""/></div>}
 <div className="vn-portal-layout"><aside className="vn-portal-sidebar"><p className="vn-portal-eyebrow">TEAM CHANNELS</p><nav aria-label="Chat channels">{channels.map(([id,label])=><button key={id} disabled={busy} aria-pressed={view==='chat'&&channel===id} onClick={()=>changeChannel(id)}><span aria-hidden="true">#</span> {label}</button>)}</nav><p className="vn-portal-eyebrow">WORKSPACE TOOLS</p><nav aria-label="Portal tools"><button aria-pressed={view==='help'} onClick={()=>setView('help')}>Help &amp; how to use</button>{canLookup&&<button aria-pressed={view==='lookup'} onClick={()=>setView('lookup')}>Order &amp; delivery lookup</button>}</nav><div className="vn-portal-guidance"><strong>Keep the team informed</strong><p>Share the order reference, verified facts, the next action and who will follow up. Never share passwords or payment details.</p><p>Messages are internal. Store changes still need owner approval.</p></div>{email&&<small className="vn-portal-account">{email}</small>}</aside>
 <section className="vn-portal-main">{view==='chat'?<><header className="vn-portal-channel"><div><h2>{channels.find(c=>c[0]===channel)?.[1]}</h2><p>Shared with all authorised staff · Updates every few seconds</p></div><span>{unread} unread</span></header><div className="vn-chat-feed" ref={feed} role="log" aria-live="polite">{messages.length?messages.map(m=><article key={m.id} data-own={m.author===email}><header><strong>{m.author}</strong><small>{m.role} · {new Date(m.created_at.replace(' ','T')+'Z').toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</small></header><p>{m.body}</p>{canLookup&&m.body.match(/\bVN-[A-Z0-9-]+\b/i)&&<button className="vn-message-order" onClick={()=>{setLookup(m.body.match(/\bVN-[A-Z0-9-]+\b/i)![0]);setView('lookup');}}>Look up referenced order</button>}</article>):<div className="vn-chat-empty"><MessageCircle size={36}/><h3>Start the conversation</h3><p>Use All staff for shared updates, or choose a team channel for a focused discussion.</p><p>For an order issue: share its reference, explain what you checked and ask for the next action.</p></div>}</div>
 {error&&<p className="vn-portal-error" role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>Retry</button></p>}
 <form onSubmit={e=>{e.preventDefault();void send();}}><label className="vn-chat-compose"><span>Message {channels.find(c=>c[0]===channel)?.[1]}</span><textarea aria-label="Message the team" placeholder="Write an update or ask the team for help…" maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} disabled={busy}/><small>{body.length}/2000 · Internal team message</small></label><button disabled={busy||!body.trim()}>{busy?'Sending…':'Send'}</button></form></>:view==='help'?<div className="vn-portal-tool"><h2>Help &amp; how to use</h2><p>Choose a guide for the task you need. Your access and approval rules still apply.</p><nav aria-label="Workspace guides">{(['sales','support','admin'] as const).map(g=><button key={g} aria-pressed={guide===g} onClick={()=>setGuide(g)}>{g==='admin'?'Admin':g==='sales'?'Sales guide':'Support guide'}</button>)}</nav><WorkspaceHelp role={guide}/></div>:view==='lookup'&&canLookup?<div className="vn-portal-tool"><SupportOrderLookup key={lookup} initialQuery={lookup} onEnquiry={id=>{setEnquiry(id);setView('enquiry');}}/></div>:view==='enquiry'&&canLookup?<div className="vn-portal-tool"><PortalEnquiry id={enquiry}/></div>:null}</section></div></DialogContent></Dialog></>;
}

function PortalEnquiry({id}:{id:string}){
 const [data,setData]=useState<{ticket:{subject:string;public_reference:string;status:string;priority:string;order_reference:string};notes:Array<{author:string;body:string;created_at:string}>}|null>(null),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');adminRead<NonNullable<typeof data>>('/api/admin/support?id='+encodeURIComponent(id),v=>!!v?.ticket&&Array.isArray(v?.notes),{signal:controller.signal}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[id]);
 return <section className="vn-portal-enquiry"><h2>Related enquiry</h2>{error?<p role="alert">{error}</p>:!data?<p role="status">Loading enquiry…</p>:<><h3>{data.ticket.subject}</h3><p>{data.ticket.public_reference} · {data.ticket.status.replaceAll('_',' ')} · {data.ticket.priority}</p><p>Order: {data.ticket.order_reference||'Not linked'}</p>{data.notes.map((note,i)=><article key={i}><strong>{note.author}</strong><small>{note.created_at} UTC</small><p>{note.body}</p></article>)}<p>This is a read-only view. Return to your Support workspace to request changes or add notes.</p></>}</section>;
}
