'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import './staff-chat.css';
type Message={seq:number;id:string;author:string;role:string;body:string;created_at:string};
const channels=[['all','All staff'],['sales','Sales'],['support','Support'],['fulfilment','Fulfilment'],['catalogue','Catalogue'],['analyst','Analytics']];
export function StaffChat(){
 const [open,setOpen]=useState(false),[channel,setChannel]=useState('all'),[messages,setMessages]=useState<Message[]>([]),[unread,setUnread]=useState(0),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[intro,setIntro]=useState(false),[retry,setRetry]=useState(0);const sent=useRef<{id:string;body:string;channel:string}|null>(null),seenIntro=useRef(false),cursor=useRef(0),feed=useRef<HTMLDivElement>(null),generation=useRef(0);
 useEffect(()=>{if(open&&!seenIntro.current){seenIntro.current=true;setIntro(!matchMedia('(prefers-reduced-motion: reduce)').matches);const t=setTimeout(()=>setIntro(false),1400);return()=>clearTimeout(t);}setIntro(false);},[open]);
 useEffect(()=>{const g=++generation.current;cursor.current=0;setMessages([]);setError('');let stopped=false,timer:ReturnType<typeof setTimeout>,controller:AbortController|null=null;
 const poll=async()=>{if(stopped)return;if(document.hidden){timer=setTimeout(poll,15000);return;}controller=new AbortController();const timeout=setTimeout(()=>controller?.abort(),15000);try{const response=await fetch(`/api/admin/chat?channel=${channel}&after=${cursor.current}${open?'':'&summary=1'}`,{signal:controller.signal,cache:'no-store'});const result=await response.json() as {error?:string;unread:number;messages:Message[]};if(!response.ok)throw new Error(result.error||'Chat unavailable');if(stopped||generation.current!==g)return;setUnread(result.unread);setError('');if(open&&Array.isArray(result.messages)&&result.messages.length){const nearBottom=!feed.current||feed.current.scrollHeight-feed.current.scrollTop-feed.current.clientHeight<90;cursor.current=Math.max(cursor.current,...result.messages.map((m:Message)=>m.seq));setMessages(old=>[...old,...result.messages.filter((m:Message)=>!old.some(x=>x.id===m.id))].slice(-200));if(nearBottom)requestAnimationFrame(()=>feed.current?.scrollTo({top:feed.current.scrollHeight}));await fetch('/api/admin/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'read',channel,seq:cursor.current}),signal:controller.signal});}}
 catch(e){if(!stopped)setError(e instanceof Error?e.message:'Chat unavailable');}finally{clearTimeout(timeout);if(!stopped)timer=setTimeout(poll,open?6000:60000);}};void poll();return()=>{stopped=true;clearTimeout(timer);controller?.abort();};},[open,channel,retry]);
 async function send(){if(busy||!body.trim())return;setBusy(true);setError('');const message=sent.current?.body===body&&sent.current.channel===channel?sent.current:{id:crypto.randomUUID(),body,channel};sent.current=message;try{const r=await fetch('/api/admin/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'send',...message}),signal:AbortSignal.timeout(15000)});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Could not send.');setBody('');sent.current=null;setRetry(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Could not send.');}finally{setBusy(false);}}
 return <><button className="vn-chat-launch" onClick={()=>setOpen(true)} aria-label={`Team chat${unread?`, ${unread} unread`:''}`}><MessageCircle size={20}/><span>Team chat</span>{unread>0&&<b>{unread>99?'99+':unread}</b>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="vn-team-chat"><DialogTitle>Team chat</DialogTitle><DialogDescription>Shared across staff workspaces. Business changes still require owner approval.</DialogDescription>
 {intro&&<div className="vn-chat-intro" aria-hidden="true"><img className="vn-chat-intro-hero" src="/images/vanta-hero-960.webp" alt=""/><img className="vn-chat-intro-emblem" src="/images/vanta-emblem.svg" alt=""/></div>}
 <nav aria-label="Chat channels">{channels.map(([id,label])=><button key={id} aria-pressed={channel===id} onClick={()=>setChannel(id)}>{label}</button>)}</nav><div className="vn-chat-feed" ref={feed} role="log" aria-live="polite">{messages.length?messages.map(m=><article key={m.id}><header><strong>{m.author}</strong><small>{m.role} · {new Date(m.created_at.replace(' ','T')+'Z').toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></header><p>{m.body}</p></article>):<p className="vn-chat-empty">Messages for this channel appear here.</p>}</div>
 {error&&<p role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>Retry</button></p>}
 <form onSubmit={e=>{e.preventDefault();void send();}}><textarea aria-label="Message the team" placeholder="Message the team…" maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} disabled={busy}/><button disabled={busy||!body.trim()}>{busy?'Sending…':'Send'}</button></form></DialogContent></Dialog></>;
}
