'use client';
import { useEffect, useRef, useState } from 'react';
import type { CommerceSettings } from '@/lib/commerce-config';
import {EditableFields,useFieldAction} from './record-editor';
import { CollectionNameEditor } from './collection-name-editor';

type Props={settings:CommerceSettings;onChange:(settings:CommerceSettings)=>void;busy:boolean;onUploadChange?:(value:boolean)=>void};
export function StoreDesignFields({settings,onChange,busy,onUploadChange}:Props) {
  const [uploading,setUploading]=useState(false),[error,setError]=useState('');
  const hero=settings.hero;
  const uploadLock=useRef(false);
  const latestSettings=useRef(settings);latestSettings.current=settings;
  async function upload(file:File|undefined,key:'image'|'mobileImage'|'playlist') {
    if(!file||uploadLock.current)return;if(!['image/jpeg','image/png','image/webp','image/avif',...(key==='playlist'?['video/mp4','video/webm']:[])].includes(file.type)||!file.size||file.size>(key==='playlist'?32:12)*1024*1024){setError('Choose an image up to 12 MB, or an MP4/WebM hero video up to 32 MB.');return;}uploadLock.current=true;setUploading(true);onUploadChange?.(true);setError('');
    try {
      const form=new FormData();form.set('file',file);
      const response=await fetch('/api/admin/uploads',{method:'POST',body:form,signal:AbortSignal.timeout(60000)});
      const result=await response.json() as {url?:string;error?:string};
      if(!response.ok||!result.url)throw new Error(result.error||'Image upload failed.');
      onChange(key==='playlist'?{...latestSettings.current,hero:{...latestSettings.current.hero,playlist:[...latestSettings.current.hero.playlist,{url:result.url,type:file.type.startsWith('video/')?'video':'image',alt:latestSettings.current.hero.alt}]}}:{...latestSettings.current,hero:{...latestSettings.current.hero,[key]:result.url}});
    }catch(e){setError(e instanceof Error?e.message:'Upload failed.');}finally{uploadLock.current=false;setUploading(false);onUploadChange?.(false);}
  }
  return <EditableFields><fieldset disabled={busy||uploading} className="vn-product-disclosure"><legend>Store images &amp; collection names</legend>
    <p>Upload campaign artwork, edit the wording and choose its destination. Save each field to publish its change. Use landscape artwork for desktop; an optional mobile image can use a portrait composition. Images are public: never upload customer documents.</p>
    <div className="vn-admin-fields">{(['image','mobileImage'] as const).map(key=><div key={key}><label>{key==='image'?'Main hero image':'Mobile image (optional)'}<input value={hero[key]} maxLength={500} onChange={e=>onChange({...settings,hero:{...hero,[key]:e.target.value}})}/></label><label>Upload {key==='image'?'main':'mobile'} artwork<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>void upload(e.target.files?.[0],key)}/></label>{hero[key]&&<img src={hero[key]} alt={`${key} preview`} style={{width:'100%',maxHeight:240,objectFit:'contain'}}/>}</div>)}</div>
    {uploading&&<p role="status">Uploading image…</p>}{error&&<p role="alert">{error}</p>}
    <div className="vn-admin-fields"><label>Image description<input maxLength={240} value={hero.alt} onChange={e=>onChange({...settings,hero:{...hero,alt:e.target.value}})}/></label><label>Image focal point<select value={hero.focus} onChange={e=>onChange({...settings,hero:{...hero,focus:e.target.value as typeof hero.focus}})}><option>left</option><option>center</option><option>right</option></select></label>
      {(['kicker','title','body','buttonText','buttonLink'] as const).map(key=><label key={key}>{{kicker:'Small heading',title:'Headline',body:'Description',buttonText:'Button / image link label',buttonLink:'Store link (for example /#collection)'}[key]}<textarea value={hero[key]} maxLength={{kicker:100,title:120,body:300,buttonText:50,buttonLink:500}[key]} onChange={e=>onChange({...settings,hero:{...hero,[key]:e.target.value}})}/></label>)}
    </div><label className="vn-launch-check"><input type="checkbox" checked={hero.showText} onChange={e=>onChange({...settings,hero:{...hero,showText:e.target.checked}})}/>Show text and button over the image (turn off for artwork that already includes text).</label>
    <h3>Hero featured products &amp; campaigns</h3><div className="vn-admin-fields"><label>Show in the hero<select value={hero.contentMode} onChange={e=>onChange({...settings,hero:{...hero,contentMode:e.target.value as typeof hero.contentMode}})}><option value="mixed">Featured products and campaigns</option><option value="products">Featured products only</option><option value="campaigns">Campaigns / ads only</option></select></label><label>First slides<select value={hero.productsFirst?'products':'campaigns'} onChange={e=>onChange({...settings,hero:{...hero,productsFirst:e.target.value==='products'}})}><option value="campaigns">Campaigns first</option><option value="products">Products first</option></select></label></div><HeroProductOrder settings={settings} onChange={onChange} busy={busy||uploading}/><h3>Hero playlist &amp; responsive sizing</h3><label>Image fit<select value={hero.fit} onChange={e=>onChange({...settings,hero:{...hero,fit:e.target.value as 'contain'|'cover'}})}><option value="contain">Full image — keep both models visible</option><option value="cover">Fill the frame — edges may be cropped</option></select></label><p>Full image preserves every edge on all screens. A wide image has dark space around it on a narrow phone. For a larger mobile picture, upload a portrait composition that includes both models. Height controls resize the hero; text keeps enough space to remain readable.</p><p>Your approved campaign media and selected featured products share this hero. Leave it empty to use your main hero image. Videos play muted without controls; the main image is the fallback. The logo automatically follows the header size.</p>
    <div className="vn-admin-fields"><label>Add approved image or UGC video<input type="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" disabled={hero.playlist.length>=12} onChange={e=>void upload(e.target.files?.[0],'playlist')}/></label>{(['desktopHeight','mobileHeight','intervalSeconds'] as const).map(key=><label key={key}>{{desktopHeight:'Desktop / tablet height (% of screen)',mobileHeight:'Mobile height (% of screen)',intervalSeconds:'Seconds per hero item'}[key]}<input type="number" min={key==='intervalSeconds'?5:40} max={key==='intervalSeconds'?30:100} value={hero[key]} onChange={e=>onChange({...settings,hero:{...hero,[key]:Number(e.target.value)}})}/></label>)}</div>
    {hero.playlist.map((media,i)=><div className="vn-admin-fields" key={media.url+i}><span>{i+1}. {media.type==='video'?'UGC / video':'Image'}</span><label>Media description<input value={media.alt} maxLength={240} onChange={e=>onChange({...settings,hero:{...hero,playlist:hero.playlist.map((m,n)=>n===i?{...m,alt:e.target.value}:m)}})}/></label><label>Campaign destination<input value={media.link||hero.buttonLink} maxLength={500} onChange={e=>onChange({...settings,hero:{...hero,playlist:hero.playlist.map((m,n)=>n===i?{...m,link:e.target.value}:m)}})}/></label><button type="button" onClick={()=>onChange({...settings,hero:{...hero,playlist:hero.playlist.filter((_,n)=>n!==i)}})}>Remove from hero</button><button type="button" disabled={i===0} onClick={()=>{const playlist=[...hero.playlist];[playlist[i-1],playlist[i]]=[playlist[i],playlist[i-1]];onChange({...settings,hero:{...hero,playlist}});}}>Move earlier</button></div>)}
    <h3>Optional announcement strip</h3><p>Off by default. When enabled, a slim pearl strip appears over the top edge of the hero, above the navigation; never in the bag. Enter your own wording.</p><label><input type="checkbox" checked={settings.announcement.enabled} onChange={e=>onChange({...settings,announcement:{...settings.announcement,enabled:e.target.checked}})}/> Show announcement above hero navigation</label><div className="vn-admin-fields"><label>Announcement text<textarea maxLength={500} value={settings.announcement.text} onChange={e=>onChange({...settings,announcement:{...settings.announcement,text:e.target.value}})}/></label><label>Movement<select value={settings.announcement.mode} onChange={e=>onChange({...settings,announcement:{...settings.announcement,mode:e.target.value as 'left'|'right'|'stationary'}})}><option value="stationary">Stationary</option><option value="left">Scroll left</option><option value="right">Scroll right</option></select></label>{(['startsAt','endsAt'] as const).map(key=><label key={key}>{key==='startsAt'?'Start (optional)':'End (optional)'}<input type="datetime-local" value={settings.announcement[key]?new Date(Date.parse(settings.announcement[key])-new Date(settings.announcement[key]).getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>onChange({...settings,announcement:{...settings.announcement,[key]:e.target.value?new Date(e.target.value).toISOString():''}})}/></label>)}</div>
    <CollectionNameEditor settings={settings} onChange={onChange} busy={busy||uploading}/>
  </fieldset></EditableFields>;
}
export function InternationalShippingFields({settings,onChange,busy}:Props) {
  return <EditableFields><fieldset disabled={busy} className="vn-product-disclosure"><legend>International shipping</legend>
    <label className="vn-launch-check"><input type="checkbox" checked={settings.internationalEnabled} onChange={e=>onChange({...settings,internationalMode:'live',internationalEnabled:e.target.checked,internationalDutiesNote:settings.internationalDutiesNote||'Import duties, taxes and customs clearance charges are payable by the recipient. Courier estimates exclude customs delays.'})}/>Enable worldwide shipping</label>
    <p>All countries and territories are available in checkout. The courier validates the address and returns available services. Checkout offers Express and Standard when estimates support a faster option; destinations without a service cannot proceed to payment. Manage courier availability in Shipbubble.</p>
    <div className="vn-admin-fields"><label>Customs duties and import charges<textarea maxLength={600} value={settings.internationalDutiesNote} onChange={e=>onChange({...settings,internationalDutiesNote:e.target.value})}/></label></div>
  </fieldset></EditableFields>;
}

function HeroProductOrder({settings,onChange,busy}:Props){
 const [products,setProducts]=useState<Array<{id:string;name:string}>>([]),[selected,setSelected]=useState('');const change=useFieldAction();
 useEffect(()=>{const controller=new AbortController();fetch('/api/catalog',{signal:controller.signal}).then(r=>r.json() as Promise<{products?:Array<{id:string;name:string}>}>).then(d=>{if(Array.isArray(d.products))setProducts(d.products);}).catch(()=>{});return()=>controller.abort();},[]);
 const order=settings.hero.productOrder;
 function update(productOrder:string[]){change(()=>onChange({...settings,hero:{...settings.hero,productOrder}}));}
 return <div><p>Leave this list empty to use the featured selection. Choose products here to set an explicit hero order. Product slides link to their product page.</p><label>Choose a product<select value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}><option value="">Select product</option>{products.filter(p=>!order.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button type="button" className="vn-pill" disabled={busy||!selected||order.length>=40} onClick={()=>update([...order,selected])}>Add to hero</button>{order.map((id,i)=><div key={id} className="vn-field-edit"><span>{i+1}. {products.find(p=>p.id===id)?.name||'Unavailable product'}</span><button type="button" className="vn-pill" disabled={busy||i===0} onClick={()=>{const next=[...order];[next[i-1],next[i]]=[next[i],next[i-1]];update(next);}}>Move earlier</button><button type="button" className="vn-pill" disabled={busy} onClick={()=>update(order.filter(p=>p!==id))}>Remove</button></div>)}</div>;
}
