'use client';
import { useRef, useState } from 'react';
import type { CommerceSettings } from '@/lib/commerce-config';
import { SHIPPING_COUNTRIES } from '@/lib/shipping-countries';
import { CollectionNameEditor } from './collection-name-editor';

type Props={settings:CommerceSettings;onChange:(settings:CommerceSettings)=>void;busy:boolean;onUploadChange?:(value:boolean)=>void};
export function StoreDesignFields({settings,onChange,busy,onUploadChange}:Props) {
  const [uploading,setUploading]=useState(false),[error,setError]=useState('');
  const hero=settings.hero;
  const uploadLock=useRef(false);
  const latestSettings=useRef(settings);latestSettings.current=settings;
  async function upload(file:File|undefined,key:'image'|'mobileImage'|'playlist') {
    if(!file||uploadLock.current)return;if(!['image/jpeg','image/png','image/webp','image/avif',...(key==='playlist'?['video/mp4','video/webm']:[])].includes(file.type)||!file.size||file.size>(key==='playlist'?32:12)*1024*1024){setError('Choose an image up to 12 MB, or an MP4/WebM hero video up to 32 MB.');return;}uploadLock.current=true;setUploading(true);onUploadChange?.(true);setError('');
    try {
      const form=new FormData();form.set('file',file);
      const response=await fetch('/api/admin/uploads',{method:'POST',body:form,signal:AbortSignal.timeout(60000)});
      const result=await response.json() as {url?:string;error?:string};
      if(!response.ok||!result.url)throw new Error(result.error||'Image upload failed.');
      onChange(key==='playlist'?{...latestSettings.current,hero:{...latestSettings.current.hero,playlist:[...latestSettings.current.hero.playlist,{url:result.url,type:file.type.startsWith('video/')?'video':'image',alt:latestSettings.current.hero.alt}]}}:{...latestSettings.current,hero:{...latestSettings.current.hero,[key]:result.url}});
    }catch(e){setError(e instanceof Error?e.message:'Upload failed.');}finally{uploadLock.current=false;setUploading(false);onUploadChange?.(false);}
  }
  return <fieldset disabled={busy||uploading} className="vn-product-disclosure"><legend>Store images &amp; collection names</legend>
    <p>Upload campaign artwork, edit the wording and choose its destination. Changes go live after Save settings. Use landscape artwork for desktop; an optional mobile image can use a portrait composition. Images are public: never upload customer documents.</p>
    <div className="vn-admin-fields">{(['image','mobileImage'] as const).map(key=><div key={key}><label>{key==='image'?'Main hero image':'Mobile image (optional)'}<input value={hero[key]} maxLength={500} onChange={e=>onChange({...settings,hero:{...hero,[key]:e.target.value}})}/></label><label>Upload {key==='image'?'main':'mobile'} artwork<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>void upload(e.target.files?.[0],key)}/></label>{hero[key]&&<img src={hero[key]} alt={`${key} preview`} style={{width:'100%',maxHeight:240,objectFit:'contain'}}/>}</div>)}</div>
    {uploading&&<p role="status">Uploading image…</p>}{error&&<p role="alert">{error}</p>}
    <div className="vn-admin-fields"><label>Image description<input maxLength={240} value={hero.alt} onChange={e=>onChange({...settings,hero:{...hero,alt:e.target.value}})}/></label><label>Image focal point<select value={hero.focus} onChange={e=>onChange({...settings,hero:{...hero,focus:e.target.value as typeof hero.focus}})}><option>left</option><option>center</option><option>right</option></select></label>
      {(['kicker','title','body','buttonText','buttonLink'] as const).map(key=><label key={key}>{{kicker:'Small heading',title:'Headline',body:'Description',buttonText:'Button / image link label',buttonLink:'Store link (for example /#collection)'}[key]}<textarea value={hero[key]} maxLength={{kicker:100,title:120,body:300,buttonText:50,buttonLink:500}[key]} onChange={e=>onChange({...settings,hero:{...hero,[key]:e.target.value}})}/></label>)}
    </div><label className="vn-launch-check"><input type="checkbox" checked={hero.showText} onChange={e=>onChange({...settings,hero:{...hero,showText:e.target.checked}})}/>Show text and button over the image (turn off for artwork that already includes text).</label>
    <h3>Hero playlist &amp; responsive sizing</h3><label>Image fit<select value={hero.fit} onChange={e=>onChange({...settings,hero:{...hero,fit:e.target.value as 'contain'|'cover'}})}><option value="contain">Full image — keep both models visible</option><option value="cover">Fill the frame — edges may be cropped</option></select></label><p>Full image preserves every edge on all screens. A wide image has dark space around it on a narrow phone. For a larger mobile picture, upload a portrait composition that includes both models. Height controls resize the hero; text keeps enough space to remain readable.</p><p>Only media in this approved playlist will cycle. Leave it empty to use your main hero image. Videos play muted without controls; the main image is the fallback. The logo automatically follows the header size.</p>
    <div className="vn-admin-fields"><label>Add approved image or UGC video<input type="file" accept="image/jpeg,image/png,image/webp,image/avif,video/mp4,video/webm" disabled={hero.playlist.length>=12} onChange={e=>void upload(e.target.files?.[0],'playlist')}/></label>{(['desktopHeight','mobileHeight','intervalSeconds'] as const).map(key=><label key={key}>{{desktopHeight:'Desktop / tablet height (% of screen)',mobileHeight:'Mobile height (% of screen)',intervalSeconds:'Seconds per hero item'}[key]}<input type="number" min={key==='intervalSeconds'?5:40} max={key==='intervalSeconds'?30:100} value={hero[key]} onChange={e=>onChange({...settings,hero:{...hero,[key]:Number(e.target.value)}})}/></label>)}</div>
    {hero.playlist.map((media,i)=><div className="vn-admin-fields" key={media.url+i}><span>{i+1}. {media.type==='video'?'UGC / video':'Image'}</span><label>Media description<input value={media.alt} maxLength={240} onChange={e=>onChange({...settings,hero:{...hero,playlist:hero.playlist.map((m,n)=>n===i?{...m,alt:e.target.value}:m)}})}/></label><button type="button" onClick={()=>onChange({...settings,hero:{...hero,playlist:hero.playlist.filter((_,n)=>n!==i)}})}>Remove from hero</button><button type="button" disabled={i===0} onClick={()=>{const playlist=[...hero.playlist];[playlist[i-1],playlist[i]]=[playlist[i],playlist[i-1]];onChange({...settings,hero:{...hero,playlist}});}}>Move earlier</button></div>)}
    <h3>Optional announcement strip</h3><p>Off by default. When enabled, a slim pearl strip appears over the top edge of the hero, above the navigation; never in the bag. Enter your own wording.</p><label><input type="checkbox" checked={settings.announcement.enabled} onChange={e=>onChange({...settings,announcement:{...settings.announcement,enabled:e.target.checked}})}/> Show announcement above hero navigation</label><div className="vn-admin-fields"><label>Announcement text<textarea maxLength={500} value={settings.announcement.text} onChange={e=>onChange({...settings,announcement:{...settings.announcement,text:e.target.value}})}/></label><label>Movement<select value={settings.announcement.mode} onChange={e=>onChange({...settings,announcement:{...settings.announcement,mode:e.target.value as 'left'|'right'|'stationary'}})}><option value="stationary">Stationary</option><option value="left">Scroll left</option><option value="right">Scroll right</option></select></label>{(['startsAt','endsAt'] as const).map(key=><label key={key}>{key==='startsAt'?'Start (optional)':'End (optional)'}<input type="datetime-local" value={settings.announcement[key]?new Date(Date.parse(settings.announcement[key])-new Date(settings.announcement[key]).getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>onChange({...settings,announcement:{...settings.announcement,[key]:e.target.value?new Date(e.target.value).toISOString():''}})}/></label>)}</div>
    <CollectionNameEditor settings={settings} onChange={onChange} busy={busy||uploading}/>
  </fieldset>;
}
export function InternationalShippingFields({settings,onChange,busy}:Props) {
  return <fieldset disabled={busy} className="vn-product-disclosure"><legend>International shipping — staged rollout</legend>
    <p>Off by default. While off, these countries, rates and customs notes are not published, and international checkout is rejected. Rates are flat fees per order, charged in NGN; confirm courier pricing, package limits and import requirements before enabling.</p>
    <label className="vn-launch-check"><input type="checkbox" checked={settings.internationalEnabled} onChange={e=>onChange({...settings,internationalEnabled:e.target.checked})}/>Show international shipping on the website and allow checkout to the configured countries</label>
    {settings.internationalZones.map((zone,i)=><div className="vn-admin-fields" key={i}><label>Destination<select value={zone.countryCode} onChange={e=>onChange({...settings,internationalZones:settings.internationalZones.map((z,n)=>n===i?{...z,countryCode:e.target.value}:z)})}>{SHIPPING_COUNTRIES.filter(c=>c[0]!=='NG').map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><label>Flat delivery fee (₦)<input type="number" min={0} max={1000000} step="0.01" value={zone.feeKobo/100} onChange={e=>onChange({...settings,internationalZones:settings.internationalZones.map((z,n)=>n===i?{...z,feeKobo:Math.round(Number(e.target.value)*100)}:z)})}/></label><label>Full estimated delivery window<input maxLength={160} value={zone.estimate} onChange={e=>onChange({...settings,internationalZones:settings.internationalZones.map((z,n)=>n===i?{...z,estimate:e.target.value}:z)})}/></label><button type="button" onClick={()=>onChange({...settings,internationalZones:settings.internationalZones.filter((_,n)=>n!==i)})}>Remove destination</button></div>)}
    <button type="button" className="vn-pill" disabled={settings.internationalZones.length>=23} onClick={()=>{const country=SHIPPING_COUNTRIES.find(c=>c[0]!=='NG'&&!settings.internationalZones.some(z=>z.countryCode===c[0]));if(country)onChange({...settings,internationalZones:[...settings.internationalZones,{countryCode:country[0],feeKobo:0,estimate:''}]});}}>Add destination</button>
    <div className="vn-admin-fields"><label>Customs duties, import taxes and charges<textarea maxLength={600} value={settings.internationalDutiesNote} placeholder="State clearly who pays import charges and whether they are included. Confirm this with your courier." onChange={e=>onChange({...settings,internationalDutiesNote:e.target.value})}/></label></div>
  </fieldset>;
}
