"use client";
import {useState} from 'react';
import {ImagePlus,Upload,Plus} from 'lucide-react';
import StoreImage from '@/components/store-image';
type ImageDraft={id?:string;color:string;imageUrl:string;imageAlt:string};
export function StudioImagery({name,images,colors,onChange,upload,busy}:{name:string;images:ImageDraft[];colors:string[];onChange:(images:ImageDraft[])=>void;upload:(index:number,file:File|undefined)=>Promise<void>;busy:boolean}){
 const choices=Array.from(new Set([...colors,...images.map(i=>i.color)].filter(Boolean)));
 const [selected,setSelected]=useState(choices[0]||''),[view,setView]=useState('Front');
 const color=choices.includes(selected)?selected:choices[0]||'';
 const matching=images.map((image,index)=>({image,index})).filter(x=>x.image.color===color);
 const found=matching.find(x=>new RegExp('\\b'+view+'\\b','i').test(x.image.imageAlt));
 const current=found||(view==='Front'?matching.find(x=>!/\b(back|side|detail)\b/i.test(x.image.imageAlt)):undefined);
 function prepare(){if(current)return current.index;const index=images.length;onChange([...images,{color,imageUrl:'',imageAlt:`${name} — ${color} — ${view.toLowerCase()} view`}]);return index;}
 return <section className="vn-studio-imagery"><div className="vn-studio-preview">{current?.image.imageUrl?<StoreImage src={current.image.imageUrl} alt={current.image.imageAlt} sizes="400px"/>:<div><ImagePlus size={32}/><p>No {view.toLowerCase()} image supplied</p></div>}<span>{view} / {color||'Select a colourway'}</span></div><div className="vn-studio-controls"><label>Colourway imagery<select value={color} onChange={e=>setSelected(e.target.value)}>{!choices.length&&<option value="">Add a colour below</option>}{choices.map(c=><option key={c}>{c}</option>)}</select></label><div className="vn-studio-tabs">{['Front','Back','Side'].map(v=><button type="button" key={v} aria-pressed={v===view} onClick={()=>setView(v)}>{v}</button>)}</div><div className="vn-studio-thumbs">{['Front','Back','Side'].map(v=>{const item=matching.find(x=>new RegExp('\\b'+v+'\\b','i').test(x.image.imageAlt))||(v==='Front'?matching.find(x=>!/\b(back|side|detail)\b/i.test(x.image.imageAlt)):undefined);return <button type="button" key={v} aria-label={`${v} image`} onClick={()=>setView(v)}>{item?.image.imageUrl?<StoreImage src={item.image.imageUrl} alt={v} sizes="60px"/>:'·'}</button>})}</div><label className="vn-studio-upload"><Upload size={22}/><div>{busy?'Uploading…':`Upload ${view} image`}<small>JPG, PNG, WebP or AVIF · up to 12 MB</small></div><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(prepare(),file);e.currentTarget.value='';}}/></label><div className="vn-studio-buttons"><button type="button" onClick={()=>{onChange([...images,{color,imageUrl:'',imageAlt:`${name} — ${color} — detail`}]);document.getElementById('vn-gallery')?.scrollIntoView({behavior:'smooth'});}}><Plus size={16}/> Add detail images</button><button type="button" disabled={!current||busy} onClick={()=>onChange(images.filter((_,i)=>i!==current?.index))}>Remove view</button></div><p className="vn-studio-note">Only supplied views are shown. A dot marks a missing view. Save changes to publish your image edits.</p></div></section>;
}
