'use client';
import {useEffect,useRef,useState} from 'react';
import {Headphones,Inbox,ShoppingBag,RotateCcw,ShieldCheck,Plus,Search,ArrowUpRight,Clock3,UserRound,RefreshCw,LogOut} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {adminRead} from '@/lib/admin-read';
import {OperationsPanel} from './operations-panel';
import {ApprovalsPanel} from './approvals-panel';
import {useAdminNavigation,useUnsavedChanges} from './unsaved-changes';
import './support-dashboard.css';
import {WorkspaceHelp} from './workspace-help';
import {SupportAlerts} from './support-alerts';
import {SupportOrderLookup} from './support-order-lookup';

type Ticket={public_reference?:string;source?:string;unread?:number;id:string;subject:string;customer_name:string;contact:string;channel:string;order_reference:string;category:string;priority:string;status:string;assigned_to:string;version:number;created_at:string;updated_at:string};
type Note={author:string;body:string;created_at:string};
type Data={tickets:Ticket[];hasMore:boolean;counts:{total:number;active:number;waiting:number;mine:number};returns:{count:number};pending:{count:number};team:Array<{email:string}>};
const names:Record<string,string>={help:'Help & how to use',lookup:'Order lookup',website:'Website form',payment:'Payment',privacy:'Privacy',active:'Active enquiries',overview:'Overview',enquiries:'Enquiries',orders:'Orders',returns:'Returns & exchanges',requests:'Approval requests',open:'Open',in_progress:'In progress',waiting_customer:'Waiting for customer',resolved:'Resolved',normal:'Normal',high:'High',urgent:'Urgent',walk_in:'Walk-in',email:'Email',phone:'Phone',instagram:'Instagram',other:'Other',order:'Order',delivery:'Delivery',return:'Return',sizing:'Sizing',product:'Product'};
const label=(v:string)=>names[v]||v;
function time(v:string){return new Date(v.replace(' ','T')+'Z').toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});}
const navigation=[['overview','Overview',Headphones],['enquiries','Enquiries',Inbox],['lookup','Order lookup',Search],['orders','Order updates',ShoppingBag],['returns','Returns & exchanges',RotateCcw],['requests','Approval requests',ShieldCheck],['help','Help & how to use',Headphones]] as const;

export function SupportDashboard({email,owner=false,signOutPath}:{email:string;owner?:boolean;signOutPath?:string}){
 const [section,setSection]=useState('overview'),[data,setData]=useState<Data|null>(null),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[mine,setMine]=useState(false),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[lookup,setLookup]=useState('');
 const serial=useRef(0),navigate=useAdminNavigation();
 useEffect(()=>{const n=++serial.current,controller=new AbortController();setLoading(true);setError('');adminRead<Data>('/api/admin/support?'+new URLSearchParams({q:search,status,mine:mine?'1':'0',page:String(page)}),v=>Array.isArray(v?.tickets)&&!!v.counts,{signal:controller.signal}).then(v=>{if(n===serial.current)setData(v);}).catch(e=>{if(!controller.signal.aborted&&n===serial.current)setError(e.message);}).finally(()=>{if(n===serial.current)setLoading(false);});return()=>{serial.current++;controller.abort();};},[search,status,mine,page,attempt]);
 useEffect(()=>{const read=(event:Event)=>{const detail=(event as CustomEvent<{id:string;version:number}>).detail;if(detail)setData(old=>old?{...old,tickets:old.tickets.map(t=>t.id===detail.id&&t.version===detail.version?{...t,unread:0}:t)}:old);};window.addEventListener('vn-support-read',read);return()=>window.removeEventListener('vn-support-read',read);},[]);
 const change=(s:string)=>navigate(()=>{setSection(s);setSelected('');setNotice('');});
 const refresh=()=>{setAttempt(n=>n+1);};
 async function save(action:string,value:unknown){const r=await fetch('/api/admin/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data:value}),signal:AbortSignal.timeout(30000)});const v=await r.json() as {error?:string;pending?:boolean};if(!r.ok)throw Error(v.error||'Could not save.');setNotice(v.pending?'Sent for owner approval. Track the decision in Approval requests.':'Enquiry saved.');refresh();return v;}
 const stats=[{title:'Active enquiries',value:data?.counts.active,caption:'Open and ongoing',icon:Inbox,go:'enquiries'},{title:'Assigned to me',value:data?.counts.mine,caption:'Your active follow-ups',icon:UserRound,go:'enquiries'},{title:'Waiting for customer',value:data?.counts.waiting,caption:'Awaiting a response',icon:Clock3,go:'enquiries'},{title:'Open returns',value:data?.returns.count,caption:'Returns and exchanges',icon:RotateCcw,go:'returns'}];
 return <div className={'vn-support'+(owner?' vn-support-embedded':'')}><aside className="vn-support-sidebar"><div className="vn-support-brand"><span>VANTA NOIR</span><small>CUSTOMER CARE</small></div><div className="vn-support-space"><span><Headphones size={20}/></span><div><strong>Support workspace</strong><small>Presence. Power. Precision.</small></div></div><nav aria-label="Support navigation">{navigation.map(([id,title,Icon])=><button type="button" key={id} aria-current={section===id?'page':undefined} onClick={()=>change(id)}><Icon size={18}/>{title}{id==='requests'&&!!data?.pending.count&&<b>{data.pending.count}</b>}</button>)}</nav><div className="vn-support-access"><ShieldCheck size={19}/><strong>{owner?'Owner access':'Owner approval protected'}</strong><p>{owner?'Review customer enquiries and your team’s proposed updates.':'Your updates are reviewed before they take effect.'}</p></div><footer><UserRound size={17}/><div><strong>{owner?'Store owner':'Support staff'}</strong><small>{email}</small></div>{signOutPath&&<a aria-label="Sign out" href={signOutPath}><LogOut size={17}/></a>}</footer></aside>
 <div className="vn-support-main"><header className="vn-support-top"><span>Workspace <span>/</span> Support</span>{!owner&&<SupportAlerts onOpen={()=>navigate(()=>{setSection('enquiries');setSelected('');refresh();})}/>}<button type="button" disabled={loading} onClick={()=>navigate(refresh)}><RefreshCw size={15}/>{loading?'Refreshing…':'Refresh'}</button></header><div className="vn-support-content"><div className="vn-support-title"><div><p>CUSTOMER EXPERIENCE</p><h1>{section==='overview'?'Support dashboard':label(section)}</h1><span>{section==='overview'?'A clear view of every customer follow-up.':section==='enquiries'?'Keep customer enquiries, notes and next steps together.':section==='orders'?'Find an order and request a delivery or status update.':section==='returns'?'Review return requests and guide the next step.':section==='lookup'?'Find customer orders and their delivery information.':section==='help'?'Practical guidance for customer care.':'Track proposed changes and their decisions.'}</span></div><button className="vn-support-primary" type="button" onClick={()=>navigate(()=>{setSelected('');setCreating(true);})}><Plus size={17}/>New enquiry</button></div>
 {error&&<p role="alert" className="vn-support-alert">{error} <button onClick={refresh}>Retry</button></p>}{notice&&<p role="status" className="vn-support-notice">{notice}</p>}
 {section==='overview'&&<><div className="vn-support-stats">{stats.map((s,index)=><button key={s.title} onClick={()=>navigate(()=>{setSection(s.go);setStatus(index===2?'waiting_customer':'active');setMine(index===1);setPage(1);setSelected('');})}><div><span>{s.title}</span><s.icon size={18}/></div><strong>{data?s.value||0:'—'}</strong><small>{s.caption}<ArrowUpRight size={15}/></small></button>)}</div><div className="vn-support-overview-note"><ShieldCheck size={20}/><div><strong>{data?data.pending.count: '—'} {owner?'support changes awaiting review':'of your changes awaiting approval'}</strong><p>Keep helping customers while the owner reviews submitted changes.</p></div><button onClick={()=>change('requests')}>View requests <ArrowUpRight size={15}/></button></div></>}
 {(section==='overview'||section==='enquiries')&&<section className="vn-support-inbox"><div className="vn-support-card-heading"><div><h2>Enquiry log</h2><p>Website enquiries arrive here automatically. You can also record other conversations.</p></div><span className="vn-support-tag">Internal workspace</span></div><form className="vn-support-filters" onSubmit={e=>{e.preventDefault();navigate(()=>{setSearch(query);setPage(1);setSelected('');});}}><label className="vn-support-search"><Search size={17}/><input aria-label="Search customer enquiries" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customer, subject or order…" maxLength={120}/></label><button type="submit">Search</button><select aria-label="Enquiry status filter" value={status} onChange={e=>navigate(()=>{setStatus(e.target.value);setPage(1);setSelected('');})}>{['all','active','open','in_progress','waiting_customer','resolved'].map(v=><option key={v} value={v}>{v==='all'?'All statuses':label(v)}</option>)}</select><button type="button" aria-pressed={mine} onClick={()=>navigate(()=>{setMine(!mine);setPage(1);setSelected('');})}>Assigned to me</button></form>
 <div className={'vn-support-inbox-grid'+(selected?' has-detail':'')}><div>{loading&&<p className="vn-support-loading" role="status">Loading enquiries…</p>}{!loading&&!error&&!data?.tickets.length&&<div className="vn-support-empty"><Inbox size={32}/><h3>No enquiries here yet</h3><p>{search||status!=='all'||mine?'Try a different search or filter.':'Website enquiries will appear here. Use New enquiry to record a phone, email or in-store conversation.'}</p><button className="vn-support-primary" onClick={()=>navigate(()=>{setSelected('');setCreating(true);})}><Plus size={16}/>Record an enquiry</button></div>}
 {data?.tickets.map(t=><button type="button" className="vn-support-ticket" key={t.id} aria-pressed={selected===t.id} onClick={()=>navigate(()=>setSelected(t.id))}><span className="vn-support-avatar">{t.customer_name.slice(0,1).toUpperCase()}</span><div><div><strong>{t.subject}{!!t.unread&&<span className="vn-support-unread"> · Unread</span>}</strong><span className={'vn-support-status status-'+t.status}>{label(t.status)}</span></div><p>{t.public_reference?t.public_reference+' · ':''}{t.customer_name} · {label(t.channel)}{t.order_reference?' · '+t.order_reference:''}</p><small><span className={'priority-'+t.priority}>{label(t.priority)} priority</span><span>{t.assigned_to||'Unassigned'}</span><span>{time(t.updated_at)}</span></small></div><ArrowUpRight size={16}/></button>)}<div className="vn-support-pager"><button disabled={loading||page===1} onClick={()=>navigate(()=>{setPage(page-1);setSelected('');})}>Previous</button><span>Page {page}</span><button disabled={loading||!data?.hasMore} onClick={()=>navigate(()=>{setPage(page+1);setSelected('');})}>Next</button></div></div>
 {selected&&<TicketDetail key={selected+'-'+attempt} id={selected} team={data?.team||[]} owner={owner} save={save} onLookup={q=>navigate(()=>{setLookup(q);setSection('lookup');setSelected('');})} close={saved=>saved?setSelected(''):navigate(()=>setSelected(''))}/>}
 </div></section>}
 {section==='help'&&<WorkspaceHelp role="support"/>}
 {section==='lookup'&&<SupportOrderLookup key={lookup} initialQuery={lookup} onEnquiry={id=>{setSection('enquiries');setSelected(id);}}/>}
 {section==='orders'&&<OperationsPanel role={owner?'owner':'support'} initialSection="orders" dedicated supportWorkspace/>}
 {section==='returns'&&<OperationsPanel role={owner?'owner':'support'} initialSection="returns" dedicated supportWorkspace/>}
 {section==='requests'&&<ApprovalsPanel owner={owner} onChanged={async()=>refresh()}/>}
 <p className="vn-support-footnote"><ShieldCheck size={14}/>Customer details stay in the private workspace. Internal notes do not send messages to customers.</p>
 </div></div>
 <NewEnquiry open={creating} close={()=>setCreating(false)} team={data?.team||[]} email={owner?'':email} owner={owner} save={save}/>
 </div>;
}
type Save=(action:string,value:unknown)=>Promise<{pending?:boolean}>;
function Assign({value,set,team}:{value:string;set:(v:string)=>void;team:Array<{email:string}>}){return <label>Assigned to<select value={value} onChange={e=>set(e.target.value)}><option value="">Unassigned</option>{[...new Set([...team.map(t=>t.email),...(value?[value]:[])])].map(email=><option key={email} value={email}>{email}</option>)}</select></label>;}
function NewEnquiry({open,close,team,email,owner,save}:{open:boolean;close:()=>void;team:Array<{email:string}>;email:string;owner:boolean;save:Save}){
 const [id,setId]=useState(''),[subject,setSubject]=useState(''),[name,setName]=useState(''),[contact,setContact]=useState(''),[channel,setChannel]=useState('email'),[order,setOrder]=useState(''),[category,setCategory]=useState('order'),[priority,setPriority]=useState('normal'),[assignee,setAssignee]=useState(email),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false),form=useRef<HTMLFormElement>(null);const navigate=useAdminNavigation();
 const dirty=!!(subject||name||contact||order||note);useUnsavedChanges({name:'New support enquiry',dirty:open&&dirty,busy,save:commit,discard:()=>{setSubject('');setName('');setContact('');setOrder('');setNote('');setId('');close();}});
 useEffect(()=>{if(open&&!id)setId(crypto.randomUUID());},[open,id]);
 const dismiss=()=>{if(!busy)navigate(()=>close());};
 async function commit(){if(lock.current||!form.current?.reportValidity())return false;lock.current=true;setBusy(true);setError('');try{await save('support:create',{id,subject,customerName:name,contact,channel,orderReference:order,category,priority,assignedTo:assignee,note});setSubject('');setName('');setContact('');setOrder('');setNote('');setId('');close();return true;}catch(e){setError((e as Error).message);return false;}finally{lock.current=false;setBusy(false);}}
 return <Dialog open={open} onOpenChange={v=>{if(!v)dismiss();}}><DialogContent className="vn-support-modal"><DialogTitle>New customer enquiry</DialogTitle><DialogDescription>Record the conversation and the next step. This is an internal record.</DialogDescription><form ref={form} onSubmit={e=>{e.preventDefault();void commit();}}><fieldset disabled={busy}><div className="vn-support-form-grid"><label>Customer name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Email or phone (optional)<input maxLength={200} value={contact} onChange={e=>setContact(e.target.value)}/></label><label>Received through<select value={channel} onChange={e=>setChannel(e.target.value)}>{['email','phone','instagram','walk_in','other'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Order reference (optional)<input maxLength={120} value={order} onChange={e=>setOrder(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['order','delivery','payment','return','sizing','product','privacy','other'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}>{['normal','high','urgent'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><Assign value={assignee} set={setAssignee} team={team}/></div><label>Subject<input required minLength={3} maxLength={160} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What does the customer need help with?"/></label><label>Conversation summary / next step<textarea required minLength={3} maxLength={4000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record the enquiry and what needs to happen next."/></label>{error&&<p role="alert">{error}</p>}<button type="submit" className="vn-support-primary" disabled={!id||busy}>{busy?'Submitting…':owner?'Create enquiry':'Submit for owner approval'}</button></fieldset></form></DialogContent></Dialog>;
}
function TicketDetail({id,team,owner,save,close,onLookup}:{id:string;team:Array<{email:string}>;owner:boolean;save:Save;close:(saved?:boolean)=>void;onLookup:(q:string)=>void}){
 const [record,setRecord]=useState<{ticket:Ticket;notes:Note[]}|null>(null),[error,setError]=useState(''),[status,setStatus]=useState('open'),[priority,setPriority]=useState('normal'),[assignee,setAssignee]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false),form=useRef<HTMLFormElement>(null);const [editing,setEditing]=useState(false);
 useEffect(()=>{const c=new AbortController();adminRead<{ticket:Ticket;notes:Note[]}>('/api/admin/support?id='+encodeURIComponent(id),v=>!!v.ticket&&Array.isArray(v.notes),{signal:c.signal}).then(v=>{setRecord(v);void fetch('/api/admin/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'support:seen',id:v.ticket.id,version:v.ticket.version})}).then(r=>{if(r.ok)window.dispatchEvent(new CustomEvent('vn-support-read',{detail:{id:v.ticket.id,version:v.ticket.version}}));}).catch(()=>{});setStatus(v.ticket.status);setPriority(v.ticket.priority);setAssignee(v.ticket.assigned_to);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[id]);
 const dirty=!!record&&(!!note||status!==record.ticket.status||priority!==record.ticket.priority||assignee!==record.ticket.assigned_to);
 useUnsavedChanges({name:'Support follow-up',dirty,busy,save:commit,discard:()=>{setNote('');if(record){setStatus(record.ticket.status);setPriority(record.ticket.priority);setAssignee(record.ticket.assigned_to);}}});
 async function commit(){if(lock.current||!record||!form.current?.reportValidity())return false;if(!dirty){setEditing(false);return true;}lock.current=true;setBusy(true);setError('');try{await save('support:update',{id,version:record.ticket.version,status,priority,assignedTo:assignee,note});setNote('');setEditing(false);close(true);return true;}catch(e){setError((e as Error).message);return false;}finally{lock.current=false;setBusy(false);}}
 return <aside className="vn-support-detail"><div className="vn-support-card-heading"><h3>Enquiry details</h3><button aria-label="Close enquiry details" onClick={()=>close()}>×</button></div>{error&&<p role="alert">{error}</p>}{!record&&!error&&<p>Loading enquiry…</p>}{record&&<><h3>{record.ticket.subject}</h3>{record.ticket.public_reference&&<p>{record.ticket.public_reference}</p>}{record.ticket.source==='website'&&<p>Customer-submitted details. Confirm order ownership before sharing private information.</p>}<p>{record.ticket.customer_name}</p><small>{record.ticket.contact||'No contact recorded'}<br/>{record.ticket.order_reference||'No linked order'} · {label(record.ticket.category)}</small><button className="vn-support-order-result" onClick={()=>onLookup(record.ticket.order_reference||record.ticket.contact||record.ticket.customer_name)}>Look up customer orders →</button><button type="button" className="vn-pill" disabled={busy} onClick={()=>editing?void commit():setEditing(true)}>{editing?'Save':'Edit'}</button><form ref={form} onSubmit={e=>{e.preventDefault();void commit();}}><fieldset disabled={busy||!editing}><div className="vn-support-form-grid"><label>Enquiry status<select value={status} onChange={e=>setStatus(e.target.value)}>{['open','in_progress','waiting_customer','resolved'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}>{['normal','high','urgent'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label></div><Assign value={assignee} set={setAssignee} team={team}/><label>Internal note<textarea maxLength={4000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a follow-up or the resolution…"/></label><button className="vn-support-primary" disabled={busy||!dirty}>{busy?'Submitting…':owner?'Save follow-up':'Request update'}</button></fieldset></form><h4><Clock3 size={15}/>Conversation notes</h4>{record.notes.map((n,i)=><article className="vn-support-note" key={i}><p>{n.body}</p><small>{n.author}<br/>{time(n.created_at)}</small></article>)}{!record.notes.length&&<p>No notes recorded.</p>}</>}</aside>;
}
