"use client";
import {useEffect,useState} from 'react';
import {adminRead} from '@/lib/admin-read';
type Entry={id:string;name:string;category:string;status:string;updated_at:string};
type Result={products:Entry[];total:number;page:number;pageSize:number};
export function TechPackArchive(){
  const [query,setQuery]=useState(''),[page,setPage]=useState(1),[data,setData]=useState<Result|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');const timer=setTimeout(async()=>{try{const payload=await adminRead<Result>(`/api/admin/tech-packs?q=${encodeURIComponent(query)}&page=${page}`,v=>Array.isArray(v?.products)&&typeof v?.total==='number'&&typeof v?.pageSize==='number',{signal:controller.signal});setData(payload);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Unable to load archive');}finally{if(!controller.signal.aborted)setLoading(false);}},250);return()=>{controller.abort();clearTimeout(timer);};},[query,page]);
  return <section className="space-y-5"><div><h2 className="text-2xl font-semibold">Tech-pack archive</h2><p className="mt-2 text-sm text-muted-foreground">A garment-matched sampling pack for every catalogue record. Two wide sheets with saved views, construction, materials and XS–XXL measurements. UK, US and China (CN/CH) size schedule included.</p><p className="mt-2 text-sm">Pending fields and unverified artwork require manufacturer approval before bulk production.</p></div><a className="inline-flex rounded-lg border px-4 py-2" href="/api/admin/tech-packs?standard=1" target="_blank" rel="noreferrer">Open manufacturer sizing standard PDF ↗</a><label className="block text-sm">Search garment, product ID, SKU or category<input className="mt-2 w-full rounded-xl border bg-background p-3" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="Find a specific garment…" /></label><div aria-live="polite">{loading?'Loading archive…':error||`${data?.total||0} matching garments`}</div>{!loading&&!error&&data&&<><div className="grid gap-3 md:grid-cols-2">{data.products.map(p=><article key={p.id} className="rounded-xl border p-4"><h3 className="font-semibold">{p.name}</h3><p className="text-sm text-muted-foreground">{p.category} · {p.status}</p><p className="mt-1 break-all text-xs">{p.id}</p><a className="mt-3 inline-flex rounded-lg border px-4 py-2 text-sm font-medium" href={`/api/admin/tech-packs?id=${encodeURIComponent(p.id)}`} target="_blank" rel="noreferrer">Open tech pack / Save PDF ↗</a></article>)}</div><div className="flex items-center gap-4"><button className="rounded-lg border px-3 py-2 disabled:opacity-40" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} / {Math.max(1,Math.ceil(data.total/data.pageSize))}</span><button className="rounded-lg border px-3 py-2 disabled:opacity-40" disabled={page*data.pageSize>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}</section>;
}
