'use client';
import {useState} from 'react';
import './workspace-help.css';
type Role='sales'|'support'|'admin';
type Article={title:string;steps:string[]};
const guides:Record<Role,Article[]>={
sales:[
{title:'First sale: start here',steps:['Open New sale. Search the garment name or SKU, then check its colour and size against the actual item.','Enter the quantity and add each item. Check the basket and total with the customer.','Confirm payment has actually been received. Choose cash, bank transfer or card terminal; include the transfer or terminal reference. This screen does not charge cards or verify bank transfers.','Submit once. Keep the sale reference and check Sales history. The submission reserves the units immediately so they are not offered online.','Owner approval finalizes the sale. Rejection releases the reservation; read the review note before correcting and resubmitting.']},
{title:'Understand available stock',steps:['On hand is recorded stock. Reserved units are held by pending sales or orders. Available is what remains to sell.','Never sell a variation showing no availability or substitute a different colour/size in the record. Ask the owner to investigate discrepancies.','If a price or stock value changed while you were working, refresh, review the new figures and try again. Staff cannot override catalogue prices.']},
{title:'A submission timed out or looks duplicated',steps:['Use Retry submission on the same screen. It reuses the same sale identifier.','Check Sales history for the reference before starting a new sale. Do not record the same payment twice.','If the outcome remains unclear, ask the owner to check Staff approvals and the sale reference.']},
{title:'Wrong item, rejected sale or refund request',steps:['Before submission, remove the incorrect line and choose the correct variation.','After submission, give the owner the sale reference and the correction needed. Do not submit a second sale to cancel the first.','Only the owner controls prices, refunds and approval decisions. A rejected sale does not refund money automatically.']}
],
support:[
{title:'First shift: triage the queue',steps:['Check unread enquiries and urgent concerns. Alerts refresh every minute while the workspace is visible; email alerts also go to active support staff and the owner.','Open each enquiry and read the customer message. Opening marks that version as read for you; it does not resolve the issue.','A serious concern is a customer-reported priority, not a verified conclusion. Check the facts and escalate safety, privacy, disputed payment or repeated delivery failures to the owner promptly.','Request an assignment and set In progress with a clear next step. Your changes take effect after owner approval.']},
{title:'Find the correct customer and order',steps:['Use Order lookup with the order reference, customer name, checkout email, phone or tracking number. A name can match several people: confirm the correct order.','Before sharing private details, ask the customer to confirm the order reference and checkout contact details. Do not reveal another customer’s address or full order history.','Review purchased items, payment status, delivery address, courier and tracking details. Check related returns, enquiries and your pending requests.','A reference entered in a public enquiry is customer supplied. It does not prove ownership of the order.']},
{title:'Delivery late, tracking missing or marked delivered',steps:['Check the recorded order status and published delivery policy. Processing, dispatch and delivery are different stages.','If tracking is missing, ask the owner or fulfilment team to confirm dispatch. Do not invent a tracking number or mark an unshipped parcel as shipped.','If tracking says delivered but the customer has no parcel, confirm the address privately, ask about reception or an authorised recipient, and escalate for a courier investigation.','Record the latest verified information and next action. Delivery information shown is the latest stored update; it may not be live courier data. Never guarantee a date that has not been confirmed.']},
{title:'Customer paid but order is pending',steps:['Find the correct order and compare its payment status with the customer’s concern. A screenshot alone does not establish a verified payment.','Ask for the transaction reference and approximate payment time, never card numbers, passwords or OTPs.','Escalate to the owner for payment reconciliation. Do not mark it paid or advise paying again until the owner has checked.']},
{title:'Wrong, damaged or missing item; return or exchange',steps:['Confirm the order, affected item, size, colour, quantity and what happened. Ask for appropriate evidence through the agreed customer-care channel if needed.','Check the current delivery and returns policy using the link below. Do not invent eligibility periods or promise a refund.','Review any existing return or exchange before opening another. Direct customers to Help centre → Track order to request a return, or ask the owner for assistance.','Wait for approved instructions before asking a customer to send goods back. Receiving a return, refunding money and restocking are separate actions. Only the owner controls refunds.']},
{title:'Sizing and product enquiries',steps:['Open the exact product and colourway. Use its garment measurements, fabric and care information.','Compare the customer’s measurements with the published chart; explain when a chart is provisional. Avoid promising a fit or fabric detail that is not confirmed.','If information is missing, record the question and request confirmation from the owner.']},
{title:'Notes, follow-ups, escalation and resolution',steps:['Internal notes are private and do not send customer replies. Use them to record facts, actions, the responsible person and the agreed next check.','Use Waiting for customer only when a response is actually needed. Use In progress when the team still has work to do.','For escalation, request Urgent priority and assign the owner; explain why and what decision is needed. Contact the owner promptly for time-sensitive concerns.','Reply using your authorised customer-care email channel. Record the reply summary in an internal note. Keep requests factual, polite and free of other customers’ information.','Request Resolved only after the issue is settled and the outcome has been explained. Resolution is not automatic when an enquiry is read.']},
{title:'Reply templates: adapt only after checking facts',steps:['Acknowledgement: “Thank you for contacting Vanta Noir. We have received your concern under [enquiry reference]. We are checking the details and will follow up.”','Delivery check: “We are checking order [reference]. The latest confirmed update is [verified update]. Our next step is [action].”','Need information: “To locate the right order, please confirm your order reference and the email or phone used at checkout. Please do not send passwords, card details or login codes.”','Escalation: “We have referred this concern to the store owner for review. We will share the confirmed outcome once available.”','Resolution: “We have completed [confirmed action]. Please let us know if the issue is still unresolved.”']}
],
admin:[
{title:'First visit: what each workspace does',steps:['Overview shows current orders, stock and sales. Use the notification bell for work needing attention.','Products manages catalogue information and visibility; Inventory manages quantities. Orders, Delivery and Returns handle fulfilment and aftercare.','Support collects customer enquiries. More tools includes the Sales desk for walk-in sales. Staff access controls who can use each staff workspace.','Use Staff approvals to review proposed changes. Help is also available inside Sales and Support.']},
{title:'Create or edit a product safely',steps:['Open Products and add or edit a product. Check name, collection/category, product type, price, colourways, sizes, SKUs and stock.','Add the correct Front, Back, Left and Right images for each colourway. Check labels, garment colours and logos.','Review the size chart, material, care and weight details. Use the field information buttons when unsure.','Save as Draft until ready. Publish makes it available subject to store settings; unpublishing or archiving hides it. Preview the result and check the save outcome.']},
{title:'Prices, stock and walk-in sales',steps:['Save a price change and verify the displayed result. Do not treat editing a field as saving.','Open Stock & deliveries in the sidebar. Search for the product, then find its exact colour and size. Choose Receive stock and enter only the quantity just delivered, or Correct count and enter your full physical count. Press Save stock and check the saved total. Drafts remain hidden; adding stock does not publish them.','Sales desk submissions reserve units. Approval finalizes the sale; rejection releases the hold. Do not manually deduct the same sale again.','A stock conflict means the figures changed. Reload and check the new state before proceeding.']},
{title:'Review staff requests',steps:['Open Staff approvals, read the proposed change, its requester and the current record.','Approve only when the details are correct. Reject with a useful reason when a correction is needed.','A conflict requires a fresh request because the record changed. A review/applying state needs investigation before retrying; do not repeat a potentially completed action.','Removing or disabling a staff email revokes its access. Review outstanding work before assigning a replacement.']},
{title:'Orders, delivery, returns and refunds',steps:['Confirm the order’s verified payment status before fulfilment. Investigate paid stock-review orders and payment discrepancies before dispatch.','Confirm the real parcel contents, address, weight and courier details. Add tracking only after it is available.','Follow the currently published delivery and returns policy. A cancelled order is not proof of a completed refund.','Review refund details separately from return status and restocking. Confirm the actual payment-provider outcome before recording a refund as completed.']},
{title:'Customer enquiries and email alerts',steps:['Open Support or the Support alert button. Read new and urgent enquiries, then review staff follow-ups in Staff approvals.','Website enquiries arrive automatically and customers receive a queued receipt. Active support staff and the owner receive a queued email alert. Delivery depends on the configured email service.','Internal notes do not send replies. Use your authorised customer-care channel for responses and keep the enquiry updated.','If alerts are missing, check spam, active staff access and your email connection. Do not assume an email was delivered simply because it was queued.']},
{title:'Store settings, policies and reporting',steps:['Keep contact, delivery, returns, checkout and payment settings accurate. Read field help and save deliberately.','Analytics uses its selected dates and connected services; no activity is different from an unavailable connection.','Keep unpublished products and unfinished policies out of the public launch. Confirm the customer-facing result after a storefront update.']}
]};
export function WorkspaceHelp({role}:{role:Role}){const [query,setQuery]=useState('');const entries=guides[role].filter(a=>(a.title+' '+a.steps.join(' ')).toLowerCase().includes(query.toLowerCase()));return <section className="vn-workspace-help"><header><p>VANTA NOIR · WORKSPACE GUIDE</p><h2>{role==='admin'?'Admin':role==='sales'?'Sales desk':'Support'} help & how to use</h2><p>Start with the first guide, or search for the task you need.</p></header><label>Search this guide<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try payment, stock, delivery or approval"/></label><div className="vn-help-principle">{role==='admin'?'Check the facts, review staff proposals and confirm each saved result.':'Looking up information is allowed. Changes to store records require owner approval.'}</div>{entries.map((a,i)=><details key={a.title} open={query?true:undefined}><summary>{a.title}</summary><ol>{a.steps.map(step=><li key={step}>{step}</li>)}</ol></details>)}{!entries.length&&<p>No matching guide. Try another word.</p>}<footer><a href="https://vantanoir.store/shipping-returns" target="_blank" rel="noreferrer">Current delivery & returns policy ↗</a><a href="https://vantanoir.store/help-center" target="_blank" rel="noreferrer">Customer help centre ↗</a></footer></section>;}
