import {actionResource,executeOperation} from '@/lib/operation-actions';
import {submitApproval,pendingResponse} from '@/lib/approvals';
import {z} from 'zod';
import {adminAuthStateFromRequest} from '@/lib/admin-auth';
import {permits,operationsData} from '@/lib/operations';
export const dynamic='force-dynamic';
export async function GET(request:Request){const auth=await adminAuthStateFromRequest(request);if(!auth.ok)return Response.json({error:auth.error},{status:auth.status});const p=new URL(request.url).searchParams,resource=p.get('resource')||'orders';if(!permits(auth.role,resource))return Response.json({error:'Access denied.'},{status:403});try{return Response.json(await operationsData(resource,p),{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'This section could not load. Try again.'},{status:503});}}
export async function POST(request:Request){const auth=await adminAuthStateFromRequest(request);if(!auth.ok)return Response.json({error:auth.error},{status:auth.status});if(Number(request.headers.get('content-length'))>1000000)return Response.json({error:'Upload at most 25 products per batch.'},{status:413});const raw=await request.text();if(raw.length>1000000)return Response.json({error:'Upload at most 25 products per batch.'},{status:413});let body:{action:string;data?:unknown};try{body=z.object({action:z.string(),data:z.unknown()}).parse(JSON.parse(raw));}catch{return Response.json({error:'Invalid request.'},{status:400});}const resource=actionResource[body.action];if(!resource||!permits(auth.role,resource))return Response.json({error:'Access denied.'},{status:403});try{if(auth.role!=='owner')return pendingResponse(await submitApproval(auth,'operation:'+body.action,body.data));const result=await executeOperation(body.action,body.data,auth.email,auth.role);
 return Response.json({result});}catch(e){return Response.json({error:e instanceof z.ZodError?e.issues[0]?.message:e instanceof Error?e.message:'Changes could not be saved.'},{status:400});}}
