import {JSDOM,VirtualConsole} from 'jsdom';
import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {Miniflare} from './miniflare.mjs';
test('Bulk dispatch preserves courier/destination, locks paid bookings, links automatically and blocks ambiguous retries',async t=>{
 await build({entryPoints:['tests/bulk-dispatch-worker.ts'],outfile:'work/bulk-dispatch-test.mjs',bundle:true,format:'esm',platform:'neutral',target:'es2022',external:['cloudflare:workers'],conditions:['workerd','browser']});
 let bookingCalls=0,quoteCalls=0,balance=100000,throwBooking=false,wrongCourier=false,lastRateBody,lastBookBody;const addresses=[];
 const mf=new Miniflare({modules:true,scriptPath:'work/bulk-dispatch-test.mjs',compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{SHIPBUBBLE_API_KEY:'sb_prod_fixture'},outboundService:async r=>{
  assert.equal(r.headers.get('Authorization'),'Bearer sb_prod_fixture');
  if(r.url.endsWith('/wallet/balance'))return Response.json({status:'success',data:{balance,currency:'NGN'}});
  if(r.url.endsWith('/address/validate')){addresses.push(await r.json());return Response.json({status:'success',data:{address_code:123}});}
  if(r.url.endsWith('/labels/categories'))return Response.json({status:'success',data:[{category:'Fashion wears',category_id:1}]});
  if(r.url.endsWith('/fetch_rates')){lastRateBody=await r.json();quoteCalls++;return Response.json({status:'success',data:{request_token:'fresh-token-'+quoteCalls,couriers:[{service_code:wrongCourier?'different':'selected',courier_id:7,courier_name:'Selected courier',total:5000,rate_card_amount:5500,currency:'NGN',service_type:'pickup',delivery_eta:'3 days'},{service_code:'cheap',courier_id:'cheaper',courier_name:'Cheaper courier',total:2000,currency:'NGN',service_type:'pickup'}]}});}
  assert.ok(r.url.endsWith('/shipping/labels'));bookingCalls++;lastBookBody=await r.json();if(throwBooking)return new Response('Ambiguous upstream error',{status:503});
  return Response.json({status:'success',data:{order_id:'SB-FIXTURE-'+bookingCalls,status:'pending',courier:{name:'Selected courier'},ship_to:{email:'buyer@example.com'},payment:{shipping_fee:5000,currency:'NGN',status:'completed'},tracking_url:'https://app.shipbubble.com/tracking/SB-FIXTURE-'+bookingCalls}});
 }});
 try{
 const db=await mf.getD1Database('DB');await db.exec("CREATE TABLE store_meta(key TEXT PRIMARY KEY,value TEXT); CREATE TABLE admin_audit(actor TEXT,action TEXT,entity TEXT,detail TEXT); CREATE TABLE products(id TEXT PRIMARY KEY,name TEXT,category TEXT,details_json TEXT); CREATE TABLE product_variants(id TEXT PRIMARY KEY,product_id TEXT,size TEXT); CREATE TABLE order_items(id INTEGER PRIMARY KEY,order_id TEXT,product_id TEXT,size TEXT,product_name TEXT,quantity INTEGER); CREATE TABLE orders(id TEXT PRIMARY KEY,reference TEXT,payment_status TEXT,status TEXT,email TEXT,first_name TEXT,last_name TEXT,phone TEXT,address_line_1 TEXT,address_line_2 TEXT,city TEXT,state TEXT,country TEXT,subtotal_kobo INTEGER,shipping_kobo INTEGER,carrier TEXT,tracking_number TEXT,tracking_url TEXT,created_at TEXT,updated_at TEXT);");
 const meta=async(k,v)=>db.prepare('INSERT OR REPLACE INTO store_meta VALUES(?,?)').bind(k,JSON.stringify(v)).run();
 await db.prepare("INSERT INTO products VALUES('tee','Tee','Tees','{}')").run();await db.prepare("INSERT INTO product_variants VALUES('tee-l','tee','L')").run();
 await meta('parcel-item:tee:L',{revision:'profile-1',data:{weightGrams:400,lengthCm:28,widthCm:23,heightCm:3,measured:false,approvedForCheckout:true}});
 await meta('parcel-packaging',{revision:'box-1',data:[{id:'box',name:'Approved box',boxGrams:2000,wrapGrams:60,tareGrams:2060,lengthCm:36,widthCm:25,heightCm:15,maxWeightGrams:8000,measured:false,approvedForCheckout:true}]});
 await meta('terminal_business_pickup',{revision:'pickup-1',details:{first_name:'Test',last_name:'Shop',email:'shop@example.com',phone:'+2348000000000',line1:'20 Pickup Street',line2:'',city:'Kaduna',state:'Kaduna',country:'NG',zip:'800001'}});
 for(const ref of ['VN-ONE','VN-TWO','VN-STALE','VN-NOFUNDS','VN-UNKNOWN','VN-MISSING','VN-WRONG','VN-UNPAID']){await db.prepare("INSERT INTO orders(id,reference,payment_status,status,email,first_name,last_name,phone,address_line_1,address_line_2,city,state,country,subtotal_kobo,shipping_kobo,created_at) VALUES(?,?,'paid','paid','buyer@example.com','Test','Buyer','08000000000','10 Recipient Street','','Ikeja','Lagos','Nigeria',3500000,450000,'2026-10-09')").bind(ref,ref).run();await db.prepare("INSERT INTO order_items(order_id,product_id,size,product_name,quantity) VALUES(?,'tee','L','Tee',1)").bind(ref).run();if(ref!=='VN-MISSING')await meta('order-shipping:'+ref,{rate:{provider:'shipbubble',carrier:'Selected courier',service:'selected',id:'old-token:selected',amountKobo:450000,walletKobo:400000,currency:'NGN'},parcel:{weightKg:2.16,lengthCm:36,widthCm:25,heightCm:15}});}
 await db.prepare("UPDATE orders SET payment_status='pending' WHERE reference='VN-UNPAID'").run();
 const rpc=async(action,...args)=>{const r=await mf.dispatchFetch('https://test/rpc',{method:'POST',body:JSON.stringify({action,args})});const data=await r.json();if(!r.ok)throw Error(data.error);return data;};
 const row=async(ref)=>(await rpc('dispatchOrders')).rows.find(r=>r.reference===ref);
 const review=async(ref)=>{const r=await row(ref);return rpc('reviewDispatch',{reference:ref,fingerprint:r.fingerprint,parcel:r.defaults,pickupDate:new Date(Date.now()+86400000).toISOString().slice(0,10),packed:true},'owner@example.com');};
 await t.test('prefills current approved parcel and preserves exact courier even when cheaper options exist',async()=>{const r=await row('VN-ONE');assert.equal(r.defaults.weightKg,2.46);assert.equal(r.carrier,'Selected courier');const q=await review('VN-ONE');assert.equal(q.chargeKobo,500000);assert.equal(q.extraKobo,50000);assert.equal(lastRateBody.package_items[0].unit_weight,2.46);assert.ok(addresses.some(a=>a.address.includes('10 Recipient Street')));assert.equal(bookingCalls,0);assert.ok(!JSON.stringify(q).includes('fresh-token'));});
 await t.test('bulk screen reviews multiple rows, totals wallet charges and requires explicit booking approval',async()=>{
 const html=await(await mf.dispatchFetch('https://test/preview')).text();const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
 const dom=new JSDOM(html,{url:'https://test/api/admin/bulk-dispatch',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.fetch=async(url,opts)=>{const body=JSON.parse(opts.body);try{const result=body.action==='review'?await rpc('reviewDispatch',body,'owner@example.com'):await rpc('bookDispatch',body.id,'owner@example.com');return {ok:true,json:async()=>result};}catch(e){return {ok:false,json:async()=>({error:e.message})};}};}});
 try{const d=dom.window.document;assert.deepEqual(errors,[]);for(const ref of ['VN-ONE','VN-TWO'])d.querySelector('[data-reference="'+ref+'"] .selected').checked=true;d.getElementById('packed').checked=true;d.getElementById('review').click();
 for(let i=0;i<200&&d.getElementById('review-panel').hidden;i++)await new Promise(r=>setTimeout(r,10));assert.equal(d.querySelectorAll('#review-list article').length,2);assert.match(d.getElementById('total').textContent,/10,000/);assert.ok(dom.window.location.search.includes('reviews='));d.getElementById('book').click();assert.match(d.getElementById('progress').textContent,/approval/);assert.equal(bookingCalls,0);assert.deepEqual(errors,[]);
 }finally{dom.window.close();}
 });
 await t.test('paid booking uses fresh provider IDs, is idempotent under concurrent clicks, and links tracking',async()=>{const q=await review('VN-ONE');const results=await Promise.all([rpc('bookDispatch',q.id,'owner@example.com'),rpc('bookDispatch',q.id,'owner@example.com')]);assert.equal(bookingCalls,1);assert.ok(results.some(r=>r.state==='booked'));assert.equal(lastBookBody.courier_id,'7');assert.equal(lastBookBody.service_code,'selected');assert.match(lastBookBody.request_token,/^fresh-token/);assert.equal((await rpc('bookDispatch',q.id,'owner@example.com')).state,'booked');assert.equal(bookingCalls,1);const o=await db.prepare("SELECT * FROM orders WHERE reference='VN-ONE'").first();assert.equal(o.shipping_kobo,450000);assert.equal(o.status,'processing');assert.equal(o.tracking_number,'SB-FIXTURE-1');assert.equal((await db.prepare("SELECT value FROM store_meta WHERE key='shipbubble-order:VN-ONE'").first()).value,'SB-FIXTURE-1');});
 await t.test('failed order does not stop another order from succeeding',async()=>{const q=await review('VN-TWO');assert.equal((await rpc('bookDispatch',q.id,'owner@example.com')).state,'booked');assert.equal(bookingCalls,2);});
 await t.test('stale pickup and parcel changes cannot be booked',async()=>{const q=await review('VN-STALE');await meta('parcel-item:tee:L',{revision:'profile-2',data:{weightGrams:500,lengthCm:28,widthCm:23,heightCm:3,measured:false,approvedForCheckout:true}});await assert.rejects(rpc('bookDispatch',q.id,'owner@example.com'),/changed/);assert.equal(bookingCalls,2);const next=await review('VN-STALE');await db.prepare("UPDATE orders SET address_line_1='Changed address' WHERE reference='VN-STALE'").run();await assert.rejects(rpc('bookDispatch',next.id,'owner@example.com'),/changed/);});
 await t.test('insufficient funds do not submit or claim a booking',async()=>{const q=await review('VN-NOFUNDS');balance=1;await assert.rejects(rpc('bookDispatch',q.id,'owner@example.com'),/funding/);assert.equal(await db.prepare("SELECT value FROM store_meta WHERE key='dispatch-booking:VN-NOFUNDS'").first(),null);balance=100000;});
 await t.test('ambiguous provider results never automatically retry',async()=>{const q=await review('VN-UNKNOWN');throwBooking=true;const r=await rpc('bookDispatch',q.id,'owner@example.com');assert.equal(r.state,'needs_review');const count=bookingCalls;await rpc('bookDispatch',q.id,'owner@example.com');assert.equal(bookingCalls,count);await assert.rejects(review('VN-UNKNOWN'),/unresolved/);throwBooking=false;});
 await t.test('missing courier, unavailable selected service, unpaid order and wrong owner are blocked',async()=>{await assert.rejects(review('VN-MISSING'));wrongCourier=true;await assert.rejects(review('VN-WRONG'),/unavailable/);wrongCourier=false;assert.equal(await row('VN-UNPAID'),undefined);const q=await review('VN-WRONG');await assert.rejects(rpc('bookDispatch',q.id,'other@example.com'),/not found/);assert.equal((await mf.dispatchFetch('https://test/admin')).status,503);});
 }finally{await mf.dispose();}
});
