import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { Miniflare } from './miniflare.mjs';
import { mkdir, readdir, readFile } from 'node:fs/promises';
import { generateKeyPair, exportJWK, SignJWT } from 'jose';

test('commerce: real product fields, delivery quotes, private care, verified reviews, atomic returns, subscriptions and email retries',async()=>{
 await mkdir('work',{recursive:true});
 await build({entryPoints:['tests/commerce-worker.ts'],outfile:'work/commerce-test-worker.mjs',bundle:true,format:'esm',platform:'neutral',target:'es2022',conditions:['workerd','browser'],external:['cloudflare:workers']});
 const {publicKey,privateKey}=await generateKeyPair('RS256');const issuer='https://commerce-test.cloudflareaccess.com';
 const jwk={...await exportJWK(publicKey),kid:'commerce-test',alg:'RS256',use:'sig'};
 const token=await new SignJWT({email:'owner@example.com'}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuer(issuer).setAudience('commerce-test').setIssuedAt().setExpirationTime('10m').sign(privateKey);
 const sent=[];let failEmail=false;
 const mf=new Miniflare({modules:true,scriptPath:'work/commerce-test-worker.mjs',compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{ADMIN_EMAIL:'owner@example.com',AUTH_PROVIDER:'cloudflare-access',CF_ACCESS_TEAM_DOMAIN:issuer,CF_ACCESS_AUD:'commerce-test',PAYSTACK_SECRET_KEY:'sk_test_local_only',STANDARD_SHIPPING_FEE_KOBO:'200000',RESEND_API_KEY:'re_local_only',EMAIL_FROM:'Vanta Noir <test@example.com>',STOREFRONT_URL:'https://vantanoir.store'},outboundService:async req=>{
  if(req.url===issuer+'/cdn-cgi/access/certs')return Response.json({keys:[jwk]});
  const body=await req.json();
  if(new URL(req.url).hostname==='api.paystack.co')return Response.json({status:true,data:{authorization_url:'https://checkout.paystack.com/local-test',reference:body.reference}});
  assert.equal(req.url,'https://api.resend.com/emails');assert.ok(req.headers.get('Idempotency-Key'));assert.ok(body.html.includes('VANTA NOIR'));assert.ok(body.text);
  if(failEmail)return Response.json({error:'temporary failure'},{status:503});sent.push({body,key:req.headers.get('Idempotency-Key')});return Response.json({id:'local-message'});
 }});
 try{
  const db=await mf.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort()){const sql=(await readFile('drizzle/'+file,'utf8')).replaceAll('--> statement-breakpoint','');await db.batch(sql.split(';').map(s=>s.trim()).filter(Boolean).map(s=>db.prepare(s)));}
  const rpc=async(action,...args)=>{const r=await mf.dispatchFetch('https://commerce-test.chatgpt.site/test',{method:'POST',body:JSON.stringify({action,args})});const p=await r.json();if(!r.ok)throw new Error(p.error);return p;};
  const request=(path,method='GET',body,owner=false)=>mf.dispatchFetch('https://commerce-test.chatgpt.site'+path,{method,headers:{'Content-Type':'application/json',...(method==='GET'?{}:{Origin:'https://commerce-test.chatgpt.site'}),...(owner?{'cf-access-jwt-assertion':token}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const catalog=await rpc('listCatalog');const product=catalog[0],color=product.colorways[0],size=Object.keys(color.stock)[0],variantId=color.variantIds[size];
  const editable=(await rpc('listAdminProducts')).find(p=>p.id===product.id);
  const details={audience:'men',fit:'Sample fit information',fabric:'Confirmed material',care:'Follow the garment label',collection:'Test collection',sizeChart:[{size:'M',chest:60,waist:40}],measurementType:'garment'};
  const save=await request('/api/admin/products','PATCH',{...editable,details,images:[...editable.images,{color:color.name,imageUrl:'/images/detail-test.png',imageAlt:'Test detail'}]},true);assert.equal(save.status,200,JSON.stringify(await save.clone().json()));
  const updated=(await rpc('listCatalog')).find(p=>p.id===product.id);assert.equal(updated.details.audience,'men');assert.equal(updated.details.sizeChart[0].chest,60);assert.ok(updated.images.some(i=>i.imageAlt==='Test detail'));
  // Publishing is visibility only, even if an editor submits approved sale flags.
  const preview = await rpc('saveAdminProduct',{...editable,id:undefined,slug:'publication-guard-test',name:'Publication guard test',status:'published',details:{...details,availability:'in_stock',priceStatus:'approved',suggestedPriceNgn:12345},images:editable.images.map(i=>({...i,id:undefined})),variants:editable.variants.map((v,i)=>({...v,id:undefined,sku:'PREVIEW-GUARD-'+i,stock:2,expectedStock:undefined}))});
  assert.equal(preview.details.availability,'preview');assert.equal(preview.details.priceStatus,'proposed');assert.equal(preview.priceKobo,editable.priceKobo);
  const publicPreview=(await rpc('listCatalog')).find(p=>p.id===preview.id);
  assert.equal(publicPreview.priceKobo,0);assert.equal(publicPreview.details.suggestedPriceNgn,0);
  const resaved=await rpc('saveAdminProduct',{...preview,details:{...preview.details,availability:'in_stock',priceStatus:'approved'}});
  assert.equal(resaved.details.availability,'preview');
  await rpc('setAdminProductStatus',preview.id,'draft');
  assert.equal((await rpc('listCatalog')).some(p=>p.id===preview.id),false);
  const republished=await rpc('setAdminProductStatus',preview.id,'published');assert.equal(republished.details.priceStatus,'proposed');
  // Saving a stale editor must roll back all changes, not restore sold units.
  const beforeRace=(await rpc('listAdminProducts')).find(p=>p.id===product.id);
  await rpc('sql','UPDATE product_variants SET stock=3 WHERE id=?',variantId);
  const stale=await request('/api/admin/products','PATCH',{...beforeRace,name:'Must not save stale edit'},true);
  assert.equal(stale.status,400);
  assert.match((await stale.json()).error,/Stock changed|reserved/);
  assert.equal((await rpc('listAdminProducts')).find(p=>p.id===product.id).name,beforeRace.name);
  assert.equal((await rpc('sql','SELECT stock FROM product_variants WHERE id=?',variantId)).results[0].stock,3);
  const settings={supportEmail:'care@example.com',supportPhone:'+234 800 123 4567',processingNote:'Orders are accepted all day; processing starts the next business day.',acceptingOrders:true,inventoryConfirmed:true,dispatchNote:'Confirmed dispatch',returnPolicy:'Confirmed test return policy',shippingZones:[{state:'Lagos',feeKobo:300000,estimate:'Confirmed test window'},{state:'Ogun',feeKobo:500000,estimate:'Other test window'}]};await rpc('saveCommerceSettings',settings);
  const publicSettings=await (await request('/api/store-settings')).json();assert.equal(publicSettings.supportPhone,settings.supportPhone);assert.equal(publicSettings.processingNote,settings.processingNote);
  const customer={email:'buyer@example.com',firstName:'Test',lastName:'Buyer',phone:'08000000000',addressLine1:'10 Test Street',addressLine2:'',city:'Ikeja',state:'Lagos'};
  await rpc('saveCommerceSettings',{...settings,acceptingOrders:false});
  assert.equal((await request('/api/checkout','POST',{customer,cart:[{variantId,quantity:1}],expectedTotalKobo:product.priceKobo+300000})).status,503,'A paused store cannot create an order even when Paystack is configured');
  await rpc('saveCommerceSettings',settings);
  let response=await request('/api/checkout','POST',{customer,cart:[{variantId,quantity:1}],expectedTotalKobo:product.priceKobo+200000});assert.equal(response.status,400,'Client cannot choose the old shipping fee');
  response=await request('/api/checkout','POST',{customer:{...customer,state:'Kano'},cart:[{variantId,quantity:1}],expectedTotalKobo:product.priceKobo+300000});assert.equal(response.status,400,'Unsupported state cannot checkout');
  await rpc('sql','UPDATE product_variants SET stock=5 WHERE id=?',variantId);
  await assert.rejects(rpc('createPendingOrder',{customer,cart:[{variantId:preview.variants[0].id,quantity:1}],shippingKobo:300000,expectedTotalKobo:preview.priceKobo+300000}),/available|preview|purchas|order/i);
  const order=await rpc('createPendingOrder',{customer,cart:[{variantId,quantity:1}],shippingKobo:300000,expectedTotalKobo:product.priceKobo+300000});
  await rpc('queueOrderEmail',order.reference,'payment');
  assert.equal((await rpc('sql',"SELECT COUNT(*) AS n FROM email_outbox WHERE event_key=?",`order:${order.reference}:payment`)).results[0].n,0,'Unpaid orders cannot queue payment confirmations');
  await rpc('markOrderPaid',{reference:order.reference,amountKobo:order.totalKobo,eventKey:'test-payment',eventType:'test'});
  await rpc('markOrderPaid',{reference:order.reference,amountKobo:order.totalKobo,eventKey:'repeat-payment',eventType:'test'});
  assert.equal((await rpc('sql',"SELECT COUNT(*) AS n FROM email_outbox WHERE event_key=?",`order:${order.reference}:payment`)).results[0].n,1,'Duplicate payment queues one receipt');
  const receipt=(await rpc('sql',"SELECT body,subject FROM email_outbox WHERE event_key=?",`order:${order.reference}:payment`)).results[0];
  assert.match(receipt.subject,/Order confirmation/);
  for(const detail of ['YOUR ITEMS','Subtotal:','Delivery:','Order total:','10 Test Street','Ikeja','Presence. Power. Precision.']) assert.ok(receipt.body.includes(detail),detail);
  await rpc('updateOrderStatus',order.reference,'processing');await rpc('updateOrderStatus',order.reference,'shipped');await rpc('updateOrderStatus',order.reference,'delivered');
  await rpc('updateOrderTracking',order.reference,{carrier:'Test courier',trackingNumber:'LOCAL-123',trackingUrl:'https://courier.example/LOCAL-123',deliveryEstimate:'Test delivery window'});
  const guest=await rpc('getGuestOrder',order.reference,customer.email,'');assert.equal(guest.trackingNumber,'LOCAL-123');assert.ok(guest.items[0].id);assert.equal(await rpc('getGuestOrder',order.reference,'wrong@example.com',''),null);
  assert.equal((await request('/api/admin/commerce')).status,403);assert.equal((await request('/api/admin/orders')).status,403);
  const filtered=await request('/api/admin/orders?query='+order.reference,'GET',undefined,true);const filterData=await filtered.json();assert.equal(filterData.orders.length,1);assert.equal(filterData.total,1);
  const review={productId:product.id,reference:order.reference,email:customer.email,displayName:'Test buyer',rating:4,fit:'true_to_size',body:'The fit and finish worked well for me.'};
  assert.equal((await request('/api/reviews','POST',{...review,email:'wrong@example.com'})).status,400);
  assert.equal((await request('/api/reviews','POST',review)).status,201);
  assert.equal((await (await request('/api/reviews?productId='+product.id)).json()).reviews.length,0,'Unmoderated reviews are private');
  const reviewId=(await rpc('sql','SELECT id FROM product_reviews')).results[0].id;
  assert.equal((await request('/api/admin/commerce','POST',{action:'review',data:{id:reviewId,status:'published'}},true)).status,200);
  const publicReview=(await (await request('/api/reviews?productId='+product.id)).json()).reviews[0];assert.equal(publicReview.rating,4);assert.equal(publicReview.orderId,undefined);assert.equal(publicReview.email,undefined);
  assert.equal((await request('/api/reviews','POST',review)).status,400,'One review per purchased product/order');
  const returnBody={reference:order.reference,email:customer.email,kind:'return',reason:'I would like to return this unworn item.',items:[{id:guest.items[0].id,quantity:1}]};
  assert.equal((await request('/api/returns','POST',{...returnBody,items:[{id:99999,quantity:1}]})).status,400);
  const returned=await request('/api/returns','POST',returnBody);assert.equal(returned.status,201);const {id:returnId}=await returned.json();
  await rpc('updateReturn',{id:returnId,version:0,status:'approved',notes:'Please follow the return instructions.',refundKobo:0,refundReference:'',refundStatus:'none',restock:false},'owner@example.com');
  const before=(await rpc('sql','SELECT stock FROM product_variants WHERE id=?',variantId)).results[0].stock;
  const input={id:returnId,version:1,status:'received',notes:'Received and inspected.',refundKobo:0,refundReference:'',refundStatus:'none',restock:true};
  const race=await Promise.allSettled([rpc('updateReturn',input,'owner@example.com'),rpc('updateReturn',input,'owner@example.com')]);assert.equal(race.filter(r=>r.status==='fulfilled').length,1);
  assert.equal((await rpc('sql','SELECT stock FROM product_variants WHERE id=?',variantId)).results[0].stock,before+1,'Return stock added once');
  assert.equal((await rpc('sql','SELECT COUNT(*) AS n FROM stock_adjustments WHERE reason=?',`Return ${returnId}`)).results[0].n,1);
  await assert.rejects(rpc('updateReturn',{...input,version:2,status:'resolved',restock:false,refundStatus:'completed'},'owner@example.com'),/refund reference/);
  assert.equal((await rpc('getGuestOrder',order.reference,customer.email,'')).returnRequest.status,'received');
  const subscription={email:'restock@example.com',kind:'restock',variantId,consent:true};
  assert.equal((await request('/api/subscriptions','POST',{...subscription,consent:false})).status,400);
  assert.equal((await request('/api/subscriptions','POST',subscription)).status,200);
  let subscriber=(await rpc('sql','SELECT * FROM subscribers WHERE email=?',subscription.email)).results[0];assert.equal(subscriber.status,'pending');
  await rpc('queueRestockAlerts');assert.equal((await rpc('sql',"SELECT COUNT(*) AS n FROM email_outbox WHERE event_key LIKE '%:restock:%'")).results[0].n,0,'No restock mail before confirmation');
  await request('/api/subscriptions','POST',{action:'confirm',token:subscriber.token});
  await rpc('saveCommerceSettings',{...settings,acceptingOrders:false});
  await rpc('queueRestockAlerts');
  assert.equal((await rpc('sql',"SELECT COUNT(*) AS n FROM email_outbox WHERE event_key LIKE '%:restock:%'")).results[0].n,0,'Paused checkout cannot announce restocks');
  await rpc('saveCommerceSettings',settings);
  const storedDetails=(await rpc('sql','SELECT details_json FROM products WHERE id=?',product.id)).results[0].details_json;
  await rpc('sql',"UPDATE products SET details_json=json_set(details_json,'$.availability','preview') WHERE id=?",product.id);
  await rpc('queueRestockAlerts');
  assert.equal((await rpc('sql',"SELECT COUNT(*) AS n FROM email_outbox WHERE event_key LIKE '%:restock:%'")).results[0].n,0,'Preview product cannot announce a restock');
  await rpc('sql','UPDATE products SET details_json=? WHERE id=?',storedDetails,product.id);
  await rpc('queueRestockAlerts');
  await rpc('sql','UPDATE product_variants SET stock=0 WHERE id=?',variantId);
  await rpc('processEmailOutbox',100);
  assert.equal(sent.filter(s=>s.body.subject.includes('is back')).length,0,'Exact size selling out holds an already queued restock email');
  await rpc('sql','UPDATE product_variants SET stock=5 WHERE id=?',variantId);
  await rpc('sql',"UPDATE email_outbox SET next_attempt_at=CURRENT_TIMESTAMP WHERE event_key LIKE '%:restock:%'");

  assert.equal((await rpc('sql',"SELECT COUNT(*) AS n FROM email_outbox WHERE event_key LIKE '%:restock:%'")).results[0].n,1);
  const sentBeforeUnsubscribe=sent.filter(s=>s.body.to.includes(subscription.email)).length;
  await request('/api/subscriptions','POST',{action:'unsubscribe',token:subscriber.token});
  await rpc('processEmailOutbox',100);assert.equal(sent.filter(s=>s.body.to.includes(subscription.email)).length,sentBeforeUnsubscribe,'Unsubscribe cancels queued mail without further delivery');
  await request('/api/subscriptions','POST',subscription);
  subscriber=(await rpc('sql','SELECT * FROM subscribers WHERE email=?',subscription.email)).results[0];
  await request('/api/subscriptions','POST',{action:'confirm',token:subscriber.token});
  await rpc('queueRestockAlerts');
  await rpc('saveCommerceSettings',{...settings,acceptingOrders:false});
  await rpc('processEmailOutbox',100);
  assert.equal(sent.filter(s=>s.body.subject.includes('is back')).length,0,'Pausing checkout also holds queued restock mail');
  await rpc('saveCommerceSettings',settings);
  await rpc('sql',"UPDATE email_outbox SET next_attempt_at=CURRENT_TIMESTAMP WHERE status='pending'");
  await rpc('processEmailOutbox',100);
  assert.equal(sent.filter(s=>s.body.subject.includes('is back')).length,1,'Eligible restock sends once after reopening');
  await rpc('queueEmail','retry-test','retry@example.com','Test retry','Test only');failEmail=true;await rpc('processEmailOutbox');const pending=(await rpc('sql',"SELECT * FROM email_outbox WHERE event_key='retry-test'")).results[0];assert.equal(pending.status,'pending');assert.equal(pending.attempts,1);
  await rpc('sql',"UPDATE email_outbox SET next_attempt_at=CURRENT_TIMESTAMP WHERE event_key='retry-test'");failEmail=false;
  await Promise.all([rpc('processEmailOutbox'),rpc('processEmailOutbox')]);assert.equal(sent.filter(s=>s.key===pending.id).length,1,'Concurrent workers claim one email');
  await rpc('queueEmail','retry-test','retry@example.com','Test retry','Test only');await rpc('processEmailOutbox');assert.equal(sent.filter(s=>s.key===pending.id).length,1,'An event is not queued twice');
 }finally{await mf.dispose();}
});

