import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {Miniflare} from './miniflare.mjs';
test('parcel profiles retain estimated provenance, multiply quantities, include packaging, reject stale/invalid saves and unknown items',async()=>{
 await build({entryPoints:['tests/parcel-profiles-worker.ts'],outfile:'work/parcel-profiles.mjs',bundle:true,format:'esm',platform:'neutral',target:'es2022',external:['cloudflare:workers']});const mf=new Miniflare({modules:true,scriptPath:'work/parcel-profiles.mjs',compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{AUTH_PROVIDER:'cloudflare-access',ADMIN_EMAIL:'owner@example.com'},outboundService:()=>{throw Error('Parcel preparation must not call couriers');}});
 try{const db=await mf.getD1Database('DB');await db.exec("CREATE TABLE store_meta(key TEXT PRIMARY KEY,value TEXT); CREATE TABLE products(id TEXT,name TEXT,category TEXT,details_json TEXT); CREATE TABLE product_variants(product_id TEXT,size TEXT); CREATE TABLE orders(id TEXT,reference TEXT,payment_status TEXT,status TEXT); CREATE TABLE order_items(id INTEGER,order_id TEXT,product_id TEXT,size TEXT,product_name TEXT,quantity INTEGER);");await db.prepare("INSERT INTO products VALUES('p','Stealth hoodie set','Streetwear','{}')").run();await db.prepare("INSERT INTO product_variants VALUES('p','L')").run();await db.prepare("INSERT INTO orders VALUES('o','VN-TEST','paid','processing')").run();await db.prepare("INSERT INTO order_items VALUES(1,'o','p','L','Stealth hoodie set',2)").run();
 const get=async p=>await(await mf.dispatchFetch('https://test.local'+p)).json();const save=async(p,data,revision)=>{const r=await mf.dispatchFetch('https://test.local'+p,{method:'POST',body:JSON.stringify({data,revision})});return {status:r.status,value:await r.json()};};
 for(const method of ['GET','PUT'])assert.equal((await mf.dispatchFetch('https://test.local/api/admin/parcel-profiles',{method})).status,403);
 const first=await get('/item');assert.equal(first.parcel.measured,false);assert.equal(first.parcel.weightGrams,1400);let order=await get('/order');assert.equal(order.suggestion.weightKg,3.3);assert.equal(order.suggestion.estimated,true);assert.equal(order.liveBookingEnabled,false);
 const measured={weightGrams:1300,lengthCm:32,widthCm:25,heightCm:8,measured:true};const saved=await save('/item',measured,null);assert.equal(saved.status,200);assert.equal((await get('/item')).parcel.measured,true);assert.equal((await save('/item',measured,null)).status,400);for(const bad of [{weightGrams:-1},{lengthCm:0},{weightGrams:Infinity},{measured:'yes'}])assert.equal((await save('/item',{...measured,...bad},saved.value.revision)).status,400);
 const packs=await get('/packs');assert.equal(packs.data.length,3);assert.equal((await save('/packs',[],null)).status,400);const box={id:'measured-box',name:'Measured box',lengthCm:50,widthCm:40,heightCm:25,tareGrams:300,maxWeightGrams:10000,measured:true};assert.equal((await save('/packs',[box],null)).status,200);order=await get('/order');assert.equal(order.suggestion.weightKg,2.9);assert.equal(order.suggestion.estimated,false);assert.equal(order.suggestion.requiresPackingCheck,true);
 await db.prepare('UPDATE order_items SET quantity=100').run();assert.equal((await get('/order')).suggestion,null);await db.prepare("UPDATE order_items SET product_id='unknown'").run();assert.equal((await get('/order')).suggestion,null);
 }finally{await mf.dispose();}
});
