import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
const dom=new JSDOM('<div id="root"></div>',{url:'https://vantanoir.store',pretendToBeVisual:true});
for(const name of ['window','document','HTMLElement','HTMLInputElement','Element','Node','NodeFilter','MutationObserver','getComputedStyle','CustomEvent'])globalThis[name]=dom.window[name];
globalThis.MessageChannel=undefined;
globalThis.matchMedia=()=>({matches:true,addEventListener(){},removeEventListener(){}});globalThis.IntersectionObserver=class {observe(){} disconnect(){}};
globalThis.requestAnimationFrame=fn=>{fn();return 1};globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const output=await build({stdin:{contents:"export {ProductGallery} from './components/product-gallery';export {createRoot} from 'react-dom/client';export {act,createElement} from 'react';",resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'esm',platform:'browser',loader:{'.css':'empty'},define:{'process.env.NODE_ENV':'"development"'}});
const {ProductGallery,createRoot,act,createElement}=await import('data:text/javascript;base64,'+Buffer.from(output.outputFiles[0].text).toString('base64'));
test('direct view selection and gallery navigation stay synchronized across colour changes',()=>{
 const root=createRoot(document.getElementById('root'));
 const images=['front','back','left','right'].map(view=>({imageUrl:`/images/test-${view}.webp`,imageAlt:`Test garment ${view} view`,color:'Black'}));
 const product={name:'Test garment',images};
 const render=(key,color,mainImage)=>act(()=>root.render(createElement(ProductGallery,{key,product,color,mainImage})));
 render('black',{name:'Black',imageAlt:'Front view'},images[0].imageUrl);
 const buttons=()=>[...document.querySelectorAll('.dn-thumbnails button')];
 assert.deepEqual(buttons().map(b=>b.textContent),['Front','Back','Left','Right']);
 act(()=>buttons()[2].click());
 assert.equal(buttons()[2].getAttribute('aria-pressed'),'true');
 assert.match(document.querySelector('.vn-independent-frame[aria-hidden="false"] img').src,/test-left/);
 act(()=>document.querySelector('.dn-detail-photo').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true})));
 assert.equal(buttons()[3].getAttribute('aria-pressed'),'true');
 act(()=>buttons()[0].click());
 assert.match(document.querySelector('.vn-independent-frame[aria-hidden="false"] img').src,/test-front/);
 render('red',{name:'Red',imageAlt:'Red front view'},'/images/red-front.webp');
 assert.equal(buttons().length,1);assert.equal(buttons()[0].getAttribute('aria-pressed'),'true');
 act(()=>root.unmount());dom.window.close();
});
