import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {Miniflare} from './miniflare.mjs';
import {mkdir,readdir,readFile} from 'node:fs/promises';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import {createHmac} from 'node:crypto';
test('owner approval is required at every staff write boundary; payment verification remains automatic',async()=>{
 await mkdir('work',{recursive:true});await build({entryPoints:['tests/commerce-worker.ts'],outfile:'work/approval-test-worker.mjs',bundle:true,format:'esm',platform:'neutral',target:'es2022',conditions:['workerd','browser'],external:['cloudflare:workers']});
 const {publicKey,privateKey}=await generateKeyPair('RS256',{extractable:true}),issuer='https://approval-test.cloudflareaccess.com',jwk={...await exportJWK(publicKey),kid:'approval',alg:'RS256',use:'sig'};
 const jwt=email=>new SignJWT({email}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuer(issuer).setAudience('approval').setIssuedAt().setExpirationTime('10m').sign(privateKey);
 const paystack=new Map();let verifies=0;
 const mf=new Miniflare({modules:true,scriptPath:'work/approval-test-worker.mjs',compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{ADMIN_EMAIL:'owner@example.com',AUTH_PROVIDER:'cloudflare-access',CF_ACCESS_TEAM_DOMAIN:issuer,CF_ACCESS_AUD:'approval',PAYSTACK_SECRET_KEY:'sk_test_fixture',ACCESS_EVALUATION_SIGNING_JWK:JSON.stringify({...await exportJWK(privateKey),kid:'evaluation'})},outboundService:async req=>{if(req.url===issuer+'/cdn-cgi/access/certs')return Response.json({keys:[jwk]});assert.equal(req.method,'GET');assert.match(req.url,/^https:\/\/api.paystack.co\/transaction\/verify\//);verifies++;return Response.json({status:true,data:paystack.get(decodeURIComponent(req.url.split('/').pop()))||{status:'pending'}});}});
 try{
  const db=await mf.getD1Database('DB');for(const f of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())await db.batch((await readFile('drizzle/'+f,'utf8')).replaceAll('--> statement-breakpoint','').split(';').map(s=>s.trim()).filter(Boolean).map(s=>db.prepare(s)));
  const rpc=async(action,...args)=>{const r=await mf.dispatchFetch('https://api.example.com/test',{method:'POST',body:JSON.stringify({action,args})});const p=await r.json();assert.equal(r.status,200,p?.error);return p;};
  const tokens={};for(const role of ['owner','catalogue','fulfilment','support','analyst','other']){tokens[role]=await jwt(role+'@example.com');if(role!=='owner')await rpc('saveStaff',{email:role+'@example.com',role:role==='other'?'catalogue':role,active:true},'owner@example.com');}
  const request=async(role,path,method='GET',body)=>{const req=new Request('https://api.example.com/api/admin/'+path,{method,headers:{'cf-access-jwt-assertion':tokens[role],Origin:'https://api.example.com',...(body instanceof FormData?{}:{'Content-Type':'application/json'})},...(body?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});return mf.dispatchFetch(req.url,{method,headers:Object.fromEntries(req.headers),...(body?{body:new Uint8Array(await req.arrayBuffer())}:{})});};
  const queue=async(role,path,method,body)=>{const r=await request(role,path,method,body);const v=await r.json();assert.equal(r.status,202,JSON.stringify(v));assert.equal(v.pending,true);return v.requestId;};
  const review=(id,decision='approve')=>request('owner','approvals','POST',{id,decision});
  const stock=async id=>(await db.prepare('SELECT stock FROM product_variants WHERE id=?').bind(id).first()).stock;
  const products=await rpc('listCatalog'),p=products[0],variantId=p.colorways[0].variantIds.S;
  await db.prepare('UPDATE product_variants SET stock=10 WHERE product_id=?').bind(p.id).run();
  // Every staff role sees only its assigned resources, even via a direct API URL.
  const resources=['orders','bulk','inventory','returns','promotions','reports','courier','staff','activity'];
  const permissions={catalogue:['bulk','inventory'],fulfilment:['orders','courier'],support:['orders','returns'],analyst:['reports']};
  for(const [role,allowed] of Object.entries(permissions))for(const resource of resources){const response=await request(role,'operations?resource='+resource);assert.equal(response.status,allowed.includes(resource)?200:403,role+': '+resource);}
  const publicKeys=await (await mf.dispatchFetch('https://api.example.com/api/access/keys')).json();assert.equal(publicKeys.keys[0].d,undefined);
  const evaluate=async(email,expiry='1m')=>{const token=await new SignJWT({identity:{email},nonce:'test-nonce'}).setProtectedHeader({alg:'RS256',kid:jwk.kid}).setIssuedAt().setExpirationTime(expiry).sign(privateKey);return mf.dispatchFetch('https://api.example.com/api/access/evaluate',{method:'POST',body:JSON.stringify({token})});};
  const {jwtVerify}=await import('jose');
  const decision=async email=>{const r=await evaluate(email);assert.equal(r.status,200);return (await jwtVerify((await r.json()).token,publicKey)).payload;};
  assert.equal((await decision('catalogue@example.com')).success,true);
  assert.equal((await decision('unknown@example.com')).success,false);
  assert.equal((await decision('owner@example.com')).success,true);
  assert.equal((await evaluate('catalogue@example.com','-1m')).status,403);
  assert.equal((await mf.dispatchFetch('https://api.example.com/api/access/evaluate',{method:'POST',body:JSON.stringify({token:'forged'})})).status,403);
  const patch={variantId,expectedStock:10,stock:12};
  const simultaneous=await Promise.all([queue('catalogue','inventory','PATCH',patch),queue('catalogue','inventory','PATCH',patch)]);assert.equal(simultaneous[0],simultaneous[1]);const first=simultaneous[0];assert.equal(await stock(variantId),10);
  assert.equal(await queue('catalogue','inventory','PATCH',patch),first,'Duplicate pending submissions are reused');
  assert.equal((await request('catalogue','approvals','POST',{id:first,decision:'approve'})).status,403);
  assert.equal((await request('other','approvals?status=all').then(r=>r.json())).requests.length,0);
  const two=await Promise.all([review(first),review(first)]);assert.deepEqual(two.map(r=>r.status).sort(),[200,409]);assert.equal(await stock(variantId),12);
  assert.equal((await review(first)).status,409);assert.equal(await stock(variantId),12);
  const rejected=await queue('catalogue','operations','POST',{action:'stock',data:{variantId,expectedStock:12,stock:20,reason:'Incoming stock'}});assert.equal(await stock(variantId),12);assert.equal((await review(rejected,'reject')).status,200);assert.equal(await stock(variantId),12);
  const stale=await queue('catalogue','inventory','PATCH',{...patch,expectedStock:12,stock:15});await db.prepare('UPDATE product_variants SET stock=11 WHERE id=?').bind(variantId).run();assert.equal((await (await review(stale)).json()).status,'conflict');assert.equal(await stock(variantId),11);
  const price=await queue('catalogue','operations','POST',{action:'prices',data:[{id:p.id,expectedPrice:p.priceKobo,priceKobo:p.priceKobo+100}]});assert.equal((await db.prepare('SELECT price_kobo AS price FROM products WHERE id=?').bind(p.id).first()).price,p.priceKobo);assert.equal((await (await review(price)).json()).status,'approved');
  const status=await queue('catalogue','products','PATCH',{productId:p.id,status:'draft'});assert.equal((await db.prepare('SELECT status FROM products WHERE id=?').bind(p.id).first()).status,'published');await review(status,'reject');
  const freshProduct={name:'Approval fixture tee',category:'Tops',description:'A fixture product for approval tests.',priceKobo:100000,images:[{imageUrl:'/images/fixture.png',imageAlt:'Fixture'}],variants:[{sku:'APPROVAL-NEW',size:'M',color:'Black',colorHex:'#000000',stock:3}]};
  const count=await db.prepare('SELECT COUNT(*) AS n FROM products').first();
  const create=await queue('catalogue','products','POST',freshProduct);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM products').first()).n,count.n);const created=await (await review(create)).json();assert.equal(created.status,'approved');
  const importId=await queue('catalogue','operations','POST',{action:'import',data:[{...freshProduct,name:'Another fixture',variants:[{...freshProduct.variants[0],sku:'APPROVAL-IMPORT'}]}]});assert.equal((await (await review(importId)).json()).status,'approved');
  const newId=created.result.id;const adminProduct=(await rpc('listAdminProducts')).find(x=>x.id===newId);
  const edit=await queue('catalogue','products','PATCH',{...adminProduct,name:'Renamed only after approval',variants:adminProduct.variants.filter(v=>v.active).map(v=>({...v,expectedStock:v.stock}))});assert.equal((await db.prepare('SELECT name FROM products WHERE id=?').bind(newId).first()).name,freshProduct.name);assert.equal((await (await review(edit)).json()).status,'approved');
  const imageForm=new FormData();imageForm.set('file',new File([new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,0])],'fixture.png',{type:'image/png'}));
  const imageId=await queue('catalogue','uploads','POST',imageForm);const imageRow=await db.prepare('SELECT payload_json FROM admin_approvals WHERE id=?').bind(imageId).first();const key=JSON.parse(imageRow.payload_json).key,bucket=await mf.getR2Bucket('BUCKET');assert.ok(await bucket.get(key));assert.equal(await bucket.get(key.replace('approval-staging/','products/')),null);assert.equal((await request('other','approvals?image='+imageId)).status,404);assert.equal((await request('owner','approvals?image='+imageId)).status,200);assert.equal((await (await review(imageId)).json()).status,'approved');assert.ok(await bucket.get(key.replace('approval-staging/','products/')));
  assert.equal((await request('analyst','operations','POST',{action:'stock',data:{...patch,reason:'Not allowed'}})).status,403);
  assert.equal((await request('catalogue','products','DELETE',{productId:p.id})).status,403);
  assert.equal((await request('catalogue','operations','POST',{action:'staff',data:{email:'other@example.com',role:'owner',active:true}})).status,403);
  const revoked=await queue('catalogue','inventory','PATCH',{...patch,expectedStock:11});await rpc('saveStaff',{email:'catalogue@example.com',role:'catalogue',active:false},'owner@example.com');assert.equal((await review(revoked)).status,409);assert.equal(await stock(variantId),11);
  const customer={email:'buyer@example.com',firstName:'Fixture',lastName:'Customer',phone:'08000000000',addressLine1:'Test address',addressLine2:'',city:'Lagos',state:'Lagos'};
  const order=await rpc('createPendingOrder',{customer,cart:[{variantId,quantity:1}],shippingKobo:0,expectedTotalKobo:p.priceKobo+100});
  paystack.set(order.reference,{status:'success',reference:order.reference,currency:'NGN',amount:order.totalKobo+1,domain:'test'});
  await rpc('reconcilePendingPayments');assert.equal((await rpc('getOrderByReference',order.reference)).paymentStatus,'pending','Mismatched amount cannot mark paid');
  await db.prepare("DELETE FROM store_meta WHERE key='payment-reconciliation'").run();paystack.get(order.reference).amount=order.totalKobo;
  assert.equal((await rpc('reconcilePendingPayments')).confirmed,1);const paid=await rpc('getOrderByReference',order.reference);assert.equal(paid.paymentStatus,'paid');assert.equal(paid.status,'paid');const afterPaid=await stock(variantId);
  const beforeVerify=verifies;await rpc('reconcilePendingPayments');assert.equal(verifies,beforeVerify,'Cron cooldown prevents repeated provider calls');
  const raw=JSON.stringify({event:'charge.success',data:{id:999,...paystack.get(order.reference)}}),signature=createHmac('sha512','sk_test_fixture').update(raw).digest('hex');
  assert.equal((await mf.dispatchFetch('https://api.example.com/api/payments/webhook',{method:'POST',headers:{'x-paystack-signature':'0'.repeat(128)},body:raw})).status,401);
  assert.equal((await mf.dispatchFetch('https://api.example.com/api/payments/webhook',{method:'POST',headers:{'x-paystack-signature':signature},body:raw})).status,200);assert.equal(await stock(variantId),afterPaid,'Webhook plus reconciliation cannot allocate stock twice');
  const orderProposal=await queue('fulfilment','operations','POST',{action:'order',data:{reference:order.reference,status:'processing'}});assert.equal((await rpc('getOrderByReference',order.reference)).status,'paid');assert.equal((await (await review(orderProposal)).json()).status,'approved');
  const trackingId=await queue('fulfilment','operations','POST',{action:'tracking',data:{reference:order.reference,carrier:'Fixture courier',trackingNumber:'TRACK-1',trackingUrl:'',deliveryEstimate:'Tomorrow'}});assert.equal((await db.prepare('SELECT tracking_number FROM orders WHERE reference=?').bind(order.reference).first()).tracking_number,'');assert.equal((await (await review(trackingId)).json()).status,'approved');
  assert.equal((await request('support','operations','POST',{action:'order',data:{reference:order.reference,status:'paid'}})).status,400);
  await rpc('updateOrderStatus',order.reference,'shipped');await rpc('updateOrderStatus',order.reference,'delivered');const guest=await rpc('getGuestOrder',order.reference,customer.email,'');const returned=await rpc('requestReturn',{reference:order.reference,email:customer.email,kind:'return',reason:'Fixture return for testing.',items:[{id:guest.items[0].id,quantity:1}]});
  const returnData={id:returned.id,version:0,status:'approved',notes:'Please return your item.',refundKobo:0,refundReference:'',refundStatus:'none',restock:false};
  const returnId=await queue('support','operations','POST',{action:'return',data:returnData});assert.equal((await db.prepare('SELECT status FROM return_requests WHERE id=?').bind(returned.id).first()).status,'requested');assert.equal((await (await review(returnId)).json()).status,'approved');
  assert.equal((await request('support','operations','POST',{action:'return',data:{...returnData,version:1,refundKobo:100,refundStatus:'completed'}})).status,400);
  await rpc('saveStaff',{email:'catalogue@example.com',role:'catalogue',active:true},'owner@example.com');
  const removedRequest=await queue('catalogue','inventory','PATCH',{variantId,expectedStock:await stock(variantId),stock:30});
  assert.equal((await request('catalogue','operations','POST',{action:'staff-delete',data:{email:'other@example.com'}})).status,403);
  assert.equal((await request('owner','operations','POST',{action:'staff-delete',data:{email:'owner@example.com'}})).status,400);
  assert.equal((await request('owner','operations','POST',{action:'staff-delete',data:{email:'catalogue@example.com'}})).status,200);
  assert.equal((await request('catalogue','operations?resource=bulk')).status,403,'Existing JWT is denied immediately after deletion');
  assert.equal((await decision('catalogue@example.com')).success,false,'Cloudflare evaluation denies removed staff');
  assert.equal((await db.prepare('SELECT status FROM admin_approvals WHERE id=?').bind(removedRequest).first()).status,'rejected');
  await rpc('saveStaff',{email:'new-staff@example.com',role:'catalogue',active:true},'owner@example.com');assert.equal((await decision('new-staff@example.com')).success,true,'New email is automatically eligible for sign-in');
  console.log('Verified pending, approve, reject, concurrent review, stale records, private images, product/import boundaries, role revocation, orders, tracking, returns and payment reconciliation.');
 }finally{await mf.dispose();}
});
