import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
const dom=new JSDOM('<div id="root"></div>',{url:'https://vantanoir.store',pretendToBeVisual:true});
for(const name of ['window','document','HTMLElement','HTMLInputElement','Element','Node','MutationObserver','getComputedStyle','CustomEvent'])globalThis[name]=dom.window[name];
globalThis.MessageChannel=undefined;
globalThis.requestAnimationFrame=fn=>{fn();return 1};globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const output=await build({stdin:{contents:"export {StoreHeader} from './components/store-header';export {createRoot} from 'react-dom/client';export {act,createElement} from 'react';",resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,format:'esm',platform:'browser',loader:{'.css':'empty'},define:{'process.env.NODE_ENV':'"development"'}});
const {StoreHeader,createRoot,act,createElement}=await import('data:text/javascript;base64,'+Buffer.from(output.outputFiles[0].text).toString('base64'));
test('one inline search opens, submits, closes and preserves the query',()=>{
 const root=createRoot(document.getElementById('root'));let searches=0;
 act(()=>root.render(createElement(StoreHeader,{query:'tracksuit',onQuery(){},onSearch(){searches++},onSaved(){},onBag(){}})));
 const button=name=>document.querySelector(`[aria-label="${name}"]`);
 assert.equal(document.querySelectorAll('header').length,1);
 assert.equal(button('Open search').className,'vn-liquid-search-toggle');
 const css=readFileSync('app/globals.css','utf8');
 assert.doesNotMatch(css,/\.(?:vn-search-toggle|vn-floating-controls|vn-theme-toggle|vn-cart-sheet|vn-light)(?![\w-])/);
 assert.match(css,/--background: #f5f7f7/);
 assert.equal(document.querySelector('form').hidden,true);
 act(()=>button('Open search').click());
 assert.equal(document.querySelector('form').hidden,false);
 assert.equal(button('Search the collection').value,'tracksuit');
 assert.equal(button('Search the collection').closest('.vn-liquid-top'),document.querySelector('.vn-liquid-logo').parentElement);
 act(()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));
 assert.equal(searches,1);
 act(()=>button('Close search').click());assert.equal(document.querySelector('form').hidden,true);
 act(()=>button('Open search').click());
 act(()=>button('Search the collection').dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Escape',bubbles:true})));
 assert.equal(document.querySelector('form').hidden,true);assert.equal(button('Search the collection').value,'tracksuit');
 assert.ok(button('Saved items'));assert.ok(button('Bag 0'));assert.ok(button('Open menu'));
 act(()=>root.unmount());dom.window.close();
});
