import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Modal,Pressable,ScrollView,StyleSheet,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Text,Icon,useTheme} from '../theme';
import {Customer,Order} from '../types';
import {api,money} from '../api';
import {useReducedMotion} from './Motion';
export type OrderGroup='All'|'To pay'|'To ship'|'Shipped'|'Delivered'|'Expired'|'Returns';
export function inOrderGroup(order:Order,group:OrderGroup){
 if(group==='Returns')return ['returned','return_requested','refunded','partially_refunded'].includes(order.status)||['refunded','partially_refunded'].includes(order.paymentStatus);
 if(group==='Expired')return order.status==='expired'||order.status==='cancelled';
 if(group==='To pay')return order.paymentStatus!=='paid'&&order.status==='pending_payment';
 if(group==='To ship')return order.paymentStatus==='paid'&&['paid','processing','preparing','ready_to_ship'].includes(order.status);
 if(group==='Shipped')return ['shipped','in_transit','out_for_delivery'].includes(order.status);
 if(group==='Delivered')return order.status==='delivered';
 return true;
}
type ReviewItem={reference:string;productId:string;productName:string};
type Coupon={id:string;title:string;code:string;expiresAt:string;countries:string[];states:string[];shippingMinimumKobo:number|null;giftMinimumKobo:number|null};
type Center={toReview:ReviewItem[];coupons:Coupon[]};
type Panel='Notifications'|'Coupons'|'To review'|'Country & currency'|null;
export function YouPage({customer,orders,wishlistCount,onOrders,onWishlist,onSettings,onCoupon,onHelp,countries,country,onCountry}:{countries:readonly (readonly [string,string])[];country:string;onCountry:(code:string)=>void;customer:Customer;orders:Order[];wishlistCount:number;onOrders:(group:OrderGroup)=>void;onWishlist:()=>void;onSettings:()=>void;onCoupon:(code:string)=>void;onHelp:()=>void}){
 const {colors}=useTheme(),reduce=useReducedMotion();
 const [countrySearch,setCountrySearch]=useState('');
 const [panel,setPanel]=useState<Panel>(null),[data,setData]=useState<Center|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [seen,setSeen]=useState<string[]|null>(null),[review,setReview]=useState<ReviewItem|null>(null),[rating,setRating]=useState(5),[fit,setFit]=useState('true_to_size'),[body,setBody]=useState(''),[displayName,setDisplayName]=useState(customer.name),[message,setMessage]=useState('');
 const seenKey='vanta-order-updates:'+customer.email;
 const updates=orders.map(o=>({key:[o.reference,o.status,o.paymentStatus,o.trackingNumber||''].join(':'),order:o}));
 const unread=seen===null?0:updates.filter(u=>!seen.includes(u.key)).length;
 useEffect(()=>{let active=true;api<Center>('/api/customer/center').then(v=>{if(active)setData(v);}).catch(()=>{if(active)setError('Coupons and review requests could not load. Try again.');}).finally(()=>{if(active)setLoading(false);});AsyncStorage.getItem(seenKey).then(v=>{if(active)setSeen(v?JSON.parse(v):[]);}).catch(()=>{if(active)setSeen([]);});return()=>{active=false;};},[seenKey]);
 const card={backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:18,padding:14,gap:10};
 const button=(title:string,action:()=>void,secondary=false,disabled=false)=><Pressable accessibilityRole="button" disabled={disabled} onPress={action} style={{padding:15,borderRadius:24,backgroundColor:secondary?colors.secondary:colors.accent,opacity:disabled?.5:1}}><Text style={{fontWeight:'700',textAlign:'center',color:secondary?colors.text:'#182214'}}>{title}</Text></Pressable>;
 const open=(next:Panel)=>{setPanel(next);setMessage('');setReview(null);};
 const field=(label:string,value:string,onChange:(v:string)=>void,multiline=false)=><View style={{gap:8}}><Text>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} multiline={multiline} maxLength={multiline?2000:60} style={{backgroundColor:colors.input,color:colors.text,borderWidth:1,borderColor:colors.border,borderRadius:14,padding:14,minHeight:multiline?110:48}}/></View>;
 return <View style={{gap:18}}>
  <View style={s.row}><View style={{width:40,height:40,borderRadius:20,backgroundColor:colors.secondary,alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:18,fontWeight:'700'}}>{(customer.name||customer.email).slice(0,1).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={{fontSize:18,fontWeight:'700'}}>{customer.name||'Vanta Noir member'}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Country and currency" onPress={()=>open('Country & currency')} style={{padding:8}}><Text>{country}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Open Settings" onPress={onSettings} style={{padding:8}}><Icon name="settings-outline" size={24}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Notifications, ${unread} unread`} onPress={()=>open('Notifications')} style={{padding:8}}><Icon name="notifications-outline" size={24}/>{unread>0&&<Text style={{position:'absolute',top:-4,right:0,fontSize:10}}>{unread}</Text>}</Pressable></View>
  <View style={card}><View style={s.row}><Text style={s.title}>Your orders</Text><Pressable accessibilityRole="button" accessibilityLabel="View all orders" onPress={()=>onOrders('All')} style={{padding:8}}><Text>View all →</Text></Pressable></View><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>
   {(['To pay','To ship','Shipped','To review','Returns'] as const).map((label,i)=><Pressable key={label} accessibilityRole="button" accessibilityLabel={label} onPress={()=>label==='To review'?open('To review'):onOrders(label)} style={{flex:1,alignItems:'center',gap:6,paddingVertical:8}}><Icon name={(['wallet-outline','cube-outline','airplane-outline','chatbubble-outline','return-down-back-outline'] as const)[i]} size={24}/><Text style={{fontSize:11}}>{label}</Text></Pressable>)}
  </View></View>
  <View style={{flexDirection:'row',flexWrap:'wrap',gap:12}}>
   {([{label:'Wishlist',icon:'heart-outline',value:wishlistCount,action:onWishlist},{label:'Coupons',icon:'ticket-outline',value:data?.coupons.length,action:()=>open('Coupons')},{label:'To review',icon:'star-outline',value:data?.toReview.length,action:()=>open('To review')}] as const).map(item=><Pressable key={item.label} accessibilityRole="button" accessibilityLabel={item.label} onPress={item.action} style={[card,{flexGrow:1,flexBasis:'28%',padding:14,alignItems:'center'}]}><Icon name={item.icon} size={26}/><Text style={{fontSize:22,fontWeight:'700'}}>{item.value??'—'}</Text><Text style={{fontSize:12}}>{item.label}</Text></Pressable>)}
  </View>
  {error!==''&&<View style={{gap:10}}><Text accessibilityRole="alert">{error}</Text>{button('Retry account extras',()=>{setLoading(true);api<Center>('/api/customer/center').then(v=>{setData(v);setError('');}).catch(()=>setError('Coupons and review requests could not load. Try again.')).finally(()=>setLoading(false));},true,loading)}</View>}
  <Pressable accessibilityRole="button" onPress={onHelp} style={[s.row,{paddingVertical:12}]}><Icon name="headset-outline" size={22}/><Text style={{flex:1}}>Help & support</Text><Icon name="chevron-forward" size={18}/></Pressable>
  <Modal visible={panel!==null} animationType={reduce?'none':'slide'} presentationStyle="pageSheet" onRequestClose={()=>setPanel(null)}>
   <SafeAreaView style={{flex:1,backgroundColor:colors.page}}><View style={[s.row,{padding:18}]}><Text style={s.title}>{panel}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Close ${panel}`} onPress={()=>setPanel(null)} style={{padding:10}}><Icon name="close" size={26}/></Pressable></View>
    <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:20,gap:18,maxWidth:680,width:'100%',alignSelf:'center'}}>
     {message!==''&&<Text accessibilityLiveRegion="polite">{message}</Text>}
     {panel==='Country & currency'&&<View style={card}><Icon name="globe-outline" size={32}/><Text style={s.title}>Delivery country</Text><Text>All payments are in Nigerian naira (NGN). Available couriers and shipping prices depend on your full delivery address.</Text>{field('Search countries',countrySearch,setCountrySearch)}{countries.filter(([,name])=>name.toLowerCase().includes(countrySearch.toLowerCase())).map(([code,name])=><Pressable accessibilityRole="radio" accessibilityLabel={name} accessibilityState={{checked:country===code}} key={code} onPress={()=>{onCountry(code);setPanel(null);}} style={[s.row,{paddingVertical:10}]}><Text>{name}</Text><Icon name={country===code?'radio-button-on':'radio-button-off'} size={22}/></Pressable>)}<Text style={{color:colors.muted}}>Changing country clears the delivery region and postcode. Review your address before placing an order.</Text></View>}
     {panel==='Notifications'&&<><Text style={{color:colors.muted}}>Latest updates from your orders. Read status is saved on this device. Phone push notifications are not enabled.</Text>{updates.length===0?<Text>No order updates yet.</Text>:<>{button('Mark all as read',()=>{const keys=updates.map(u=>u.key).slice(0,200);void AsyncStorage.setItem(seenKey,JSON.stringify(keys)).then(()=>setSeen(keys)).catch(()=>setMessage('Could not save read status. Please try again.'));},true)}{updates.map(({key,order})=><Pressable key={key} accessibilityRole="button" accessibilityLabel={`Order update ${order.reference}`} onPress={()=>{setPanel(null);onOrders('All');}} style={card}><View style={s.row}><Text style={s.title}>{order.status.replaceAll('_',' ')}</Text>{seen&&!seen.includes(key)&&<Text style={{color:colors.muted}}>New</Text>}</View><Text>{order.reference}</Text><Text>Payment: {order.paymentStatus}</Text>{!!order.trackingNumber&&<Text>{order.carrier} · {order.trackingNumber}</Text>}</Pressable>)}</>}</>}
     {(panel==='Coupons'||panel==='To review')&&loading&&<ActivityIndicator color={colors.text}/>}
     {(panel==='Coupons'||panel==='To review')&&error!==''&&<Text accessibilityRole="alert">{error}</Text>}
     {panel==='Coupons'&&data&&<><Text style={{color:colors.muted}}>Offers assigned to your account and automatic store rewards. Eligibility is checked against your bag and delivery address at checkout.</Text>{data.coupons.length===0&&<Text>No available coupons or rewards right now.</Text>}{data.coupons.map(c=><View key={c.id} style={card}><Icon name="ticket-outline" size={28}/><Text style={s.title}>{c.title}</Text>{c.code!==''&&<Text selectable>{c.code}</Text>}{c.shippingMinimumKobo!==null&&<Text>Free delivery from {money(c.shippingMinimumKobo)} in eligible locations.</Text>}{c.giftMinimumKobo!==null&&<Text>Gift from {money(c.giftMinimumKobo)}, while eligible stock lasts.</Text>}<Text>{c.countries.join(', ')}{c.states.length?' · '+c.states.join(', '):''}</Text><Text style={{color:colors.muted}}>Expires {new Date(c.expiresAt).toLocaleDateString()}</Text>{button(c.code?'Use coupon':'Shop with this reward',()=>{setPanel(null);onCoupon(c.code);})}</View>)}</>}
     {panel==='To review'&&data&&!review&&<><Text style={{color:colors.muted}}>Review garments from delivered orders. Submitted reviews go through moderation before appearing publicly.</Text>{data.toReview.length===0&&<Text>You’re all caught up. Delivered garments awaiting a review will appear here.</Text>}{data.toReview.map(item=><View key={item.reference+item.productId} style={card}><Text style={s.title}>{item.productName}</Text><Text>{item.reference}</Text>{button('Write a review',()=>{setReview(item);setBody('');setRating(5);setFit('true_to_size');setMessage('');})}</View>)}</>}
     {panel==='To review'&&review&&<View style={card}><Text style={s.title}>{review.productName}</Text>{field('Public display name',displayName,setDisplayName)}<Text>Rating</Text><View style={s.row}>{[1,2,3,4,5].map(n=><Pressable key={n} accessibilityRole="radio" accessibilityLabel={`${n} stars`} accessibilityState={{checked:rating===n}} onPress={()=>setRating(n)} style={{padding:8}}><Icon name={n<=rating?'star':'star-outline'} size={25}/></Pressable>)}</View><Text>Fit</Text>{[['small','Runs small'],['true_to_size','True to size'],['large','Runs large']].map(([value,label])=><Pressable key={value} accessibilityRole="radio" accessibilityLabel={label} accessibilityState={{checked:fit===value}} onPress={()=>setFit(value)} style={s.row}><Icon name={fit===value?'radio-button-on':'radio-button-off'} size={22}/><Text>{label}</Text></Pressable>)}{field('Your review',body,setBody,true)}{button(busy?'Submitting…':'Submit review',()=>{setBusy(true);setMessage('');void api('/api/customer/reviews',{reference:review.reference,productId:review.productId,displayName:displayName.trim(),rating,fit,body:body.trim()}).then(()=>{setData(current=>current?{...current,toReview:current.toReview.filter(i=>i.reference!==review.reference||i.productId!==review.productId)}:current);setReview(null);setMessage('Thank you. Your review is awaiting moderation.');}).catch(e=>setMessage(e instanceof Error?e.message:'Could not submit your review.')).finally(()=>setBusy(false));},false,busy||body.trim().length<10||displayName.trim().length<2)}</View>}
    </ScrollView>
   </SafeAreaView>
  </Modal>
 </View>;
}
const s=StyleSheet.create({row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,flexWrap:'wrap'},title:{fontSize:17,fontWeight:'700'}});
