"use client";
import {ArrowRight,Minus,Plus,ShoppingBag,Trash2,X} from 'lucide-react';
import {Sheet,SheetContent,SheetDescription,SheetTitle} from './ui/sheet';
import {BagGarment} from './bag-garment';
import {BagRewards} from './reward-progress';
import type {CartItem} from '@/lib/cart';
type Props={bagOpen:boolean;setBagOpen:(open:boolean)=>void;cart:CartItem[];catalogError:boolean;catalogLoaded:boolean;inventory:Map<string,{available:number}>;displayCurrency:{format:(kobo:number)=>string};onRetry:()=>void;onQuantity:(id:string,delta:number)=>void;onRemove:(item:CartItem)=>void;onExplore:()=>void};
export function BagDrawer({bagOpen,setBagOpen,cart,catalogError,catalogLoaded,inventory,displayCurrency,onRetry,onQuantity,onRemove,onExplore}:Props){
 const count=cart.reduce((sum,item)=>sum+item.quantity,0),subtotal=cart.reduce((sum,item)=>sum+item.quantity*item.priceKobo,0);
 return <Sheet open={bagOpen} onOpenChange={setBagOpen}><SheetContent className="dn-bag vn-approved-bag" overlayClassName="vn-liquid-overlay" showCloseButton={false}><header className="vn-bag-header"><a href="/" aria-label="Vanta Noir home"><img src="/images/vanta-spire-light.svg" alt="Vanta Noir"/></a><button aria-label="Close bag" onClick={()=>setBagOpen(false)}><X size={22}/></button></header><div className="vn-bag-layout"><div className="vn-bag-content"><div className="dn-bag-heading"><SheetTitle>Your bag <span>({count})</span></SheetTitle><SheetDescription>Your next everyday uniform.</SheetDescription></div>{catalogError ? <div role="alert"><p>Your bag is saved, but current prices and stock could not be loaded.</p><button className="dn-primary" onClick={()=>onRetry()}>Retry bag</button></div> : !catalogLoaded ? <p role="status">Loading your bag…</p> : cart.length ? <><div className="dn-bag-items">{cart.map(item => <div className="dn-bag-item" key={item.variantId}><BagGarment src={item.imageUrl} alt={`${item.name} in ${item.color}`}/><div><h3>{item.name.replace(/^\d+\s+/, "")}</h3><p>{item.color} · {item.size}</p><strong>{displayCurrency.format(item.priceKobo)}</strong><div className="dn-quantity"><button onClick={() => onQuantity(item.variantId, -1)} aria-label={`Decrease ${item.name} quantity`}><Minus size={13} /></button><span>{item.quantity}</span><button disabled={item.quantity >= (inventory.get(item.variantId)?.available ?? 0)} onClick={() => onQuantity(item.variantId, 1)} aria-label={`Increase ${item.name} quantity`}><Plus size={13} /></button></div></div><button className="dn-remove" aria-label={`Remove ${item.name}`} onClick={() => { onRemove(item); }}><Trash2 size={16} /></button></div>)}</div><div className="dn-bag-summary"><BagRewards cart={cart} open={bagOpen}/><div><span>Subtotal</span><strong>{displayCurrency.format(subtotal)}</strong></div><p>Delivery is calculated at checkout. Apply an eligible delivery code there.</p><a className="dn-primary" href="/checkout">Continue to checkout <ArrowRight size={16}/></a><button className="dn-continue" onClick={() => setBagOpen(false)}>Continue exploring <ArrowRight size={15} /></button><small>Review your delivery fee and total before payment.</small></div></> : <div className="dn-empty dn-bag-empty"><ShoppingBag size={42} /><h3>Make it yours.</h3><p>Your bag is waiting for your next favourite.</p><button className="dn-primary" onClick={() => { setBagOpen(false); onExplore(); }}>Explore the collection <ArrowRight size={16} /></button></div>}</div></div></SheetContent></Sheet>;
}
