"use client";
import { useState, type FormEvent } from "react";
import { ArrowRight, Mail, PackageSearch } from "lucide-react";
import { StoreShell } from "./store-shell";
import { AnalyticsPreferences } from "./analytics-consent";
import { ProductReviews } from "./product-reviews";
import { OrderAftercare, type TrackedOrder } from "./order-aftercare";
import { useStoreSettings } from "@/lib/store-settings";
import { apiUrl } from "@/lib/api-client";
import { formatNaira } from "@/lib/catalog";

function Intro({label,title,description}:{label:string;title:string;description:string}){return <div className="dn-page-intro"><span className="dn-eyebrow">{label}</span><h1>{title}</h1><p>{description}</p></div>;}
export function ContactContent(){const settings=useStoreSettings();return <StoreShell><Intro label="HERE TO HELP" title="Let’s talk." description="Questions about your fit, the collection or an order? Get in touch."/><div className="dn-care-grid">
  <section className="dn-panel"><Mail size={26}/><h2>Customer care</h2>{settings.supportEmail?<><p>Include your order reference if you have one. Please never send card numbers, security codes or passwords.</p><a className="dn-text-link" href={`mailto:${settings.supportEmail}`}>{settings.supportEmail} <ArrowRight size={16}/></a></>:<><p>For product and sizing enquiries, message our official Instagram account.</p><a className="dn-primary" href="https://www.instagram.com/the_vanta_noir" target="_blank" rel="noreferrer">Message Vanta Noir <ArrowRight size={16}/></a></>}</section>
  <section className="dn-panel"><PackageSearch size={26}/><h2>Your order, at a glance</h2><p>Use your order reference and checkout email or phone number. No account needed.</p><a className="dn-primary" href="/help-center#track-order">Track your order <ArrowRight size={16}/></a></section>
  </div><section className="dn-panel"><h2>Find us</h2><div className="dn-inline-links"><a href="https://www.instagram.com/the_vanta_noir" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.tiktok.com/@the_vanta_noir" target="_blank" rel="noreferrer">TikTok ↗</a><a href="https://x.com/vanta_noir72" target="_blank" rel="noreferrer">X ↗</a></div></section></StoreShell>;}
export function AboutContent(){return <StoreShell><Intro label="THE VANTA NOIR IDENTITY" title="Presence. Power. Precision." description="Distinctive fashion. Quiet confidence. An athletic influence."/><div className="dn-about-grid"><img src="/images/vanta-hero.png" alt="Vanta Noir campaign — technical streetwear in motion"/><div className="dn-prose"><p>Vanta Noir is a technical streetwear and athletics brand built for people who move with intention. We combine performance-focused function with elevated, distinctive silhouettes to create clothing that feels powerful in motion and refined beyond it.</p><p>From denim, knitwear and tailored trousers to oversized sets, performance tracksuits, outerwear and accessories, our collections bring purposeful details and distinctive silhouettes into everyday dressing.</p><p>Vanta Noir represents quiet confidence, disciplined movement, and the freedom to stand apart.</p><h2>Presence. Power. Precision.</h2><p>Presence in the impression you make. Power in the confidence you carry. Precision in the details we design. One expression across our streetwear, everyday fashion and athletic collections.</p><a className="dn-primary" href="/#collection">Discover the collection <ArrowRight size={16}/></a></div></div></StoreShell>;}

export function HelpContent(){const [reference,setReference]=useState(""),[contact,setContact]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[order,setOrder]=useState<TrackedOrder|null>(null),[lookupContact,setLookupContact]=useState("");
  async function track(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setOrder(null);try{const r=await fetch(apiUrl("/api/orders/track"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reference:reference.trim(),...(contact.includes("@")?{email:contact.trim()}:{phone:contact.trim()})}),signal:AbortSignal.timeout(15000)});const data=await r.json() as {order?:TrackedOrder;error?:string};if(!r.ok||!data.order)throw new Error(data.error||"The order could not be found. Check your reference and contact details.");setOrder(data.order);setLookupContact(contact.trim());}catch(e){setError(e instanceof Error&&e.name!=="TimeoutError"?e.message:"The request timed out. Please try again.");}finally{setBusy(false);}}
  const faqs=[
    ["How do I choose my size?","Open a product and choose Size & fit guide. Compare the separate top and trouser charts in cm or inches. All styles use S, M, L, XL and XXL, with garment-specific fits. Follow the flat-measuring instructions and check whether the chart is provisional. Contact customer care if a measurement is missing or you need help."],
    ["Where do you deliver?","Online checkout supports the Nigerian states listed in our delivery policy. Choose your state at checkout to see the applicable fee and estimate. Contact care about other destinations before ordering."],
    ["Can I return or exchange an item?","Read the current delivery and returns policy, then look up your order below to request a return or exchange. Customer care will review your request and provide instructions before you send anything back."],
    ["My payment is still pending. Should I pay again?","Please do not pay twice. Keep your reference and use Check payment again on your payment confirmation page, or contact care with the reference. An order is marked paid only after payment is verified."],
    ["Can I change or cancel my order?","Contact care as soon as possible with your order reference. We will check what is possible at the current fulfilment stage. Cancelling an order does not automatically issue a refund."],
  ];
  return <StoreShell><Intro label="CUSTOMER CARE" title="A little help, clearly." description="Track your order, find your fit and get the details you need."/>
    <section id="track-order" className="dn-panel dn-track"><h2>Track your order</h2><p>No account needed. Use the details from checkout.</p><form className="dn-form" onSubmit={track}><div className="dn-field-grid"><label>Order reference<input value={reference} onChange={e=>setReference(e.target.value)} required maxLength={120} autoCapitalize="none"/></label><label>Order email or phone<input value={contact} onChange={e=>setContact(e.target.value)} required maxLength={200} autoCapitalize="none"/></label></div><button className="dn-primary" disabled={busy}>{busy?"Finding your order…":"Find my order"}<ArrowRight size={16}/></button>{error&&<p className="dn-error" role="alert">{error}</p>}</form>
    {order&&<div className="dn-order-result" aria-live="polite"><h3>{order.reference}</h3><dl className="dn-totals"><div><dt>Order</dt><dd>{order.status.replaceAll("_"," ")}</dd></div><div><dt>Payment</dt><dd>{order.paymentStatus.replaceAll("_"," ")}</dd></div><div><dt>Total</dt><dd>{formatNaira(order.totalKobo)}</dd></div></dl><ul>{order.items.map(i=><li key={i.id}>{i.quantity} × {i.productName} · {i.color} · {i.size}</li>)}</ul><OrderAftercare key={`${order.reference}-${lookupContact}`} order={order} contact={lookupContact}/></div>}</section>
    <section className="dn-faq dn-prose" id="sizing"><h2>Good to know</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}<div className="dn-inline-links"><a href="/shipping-returns">Delivery & returns <ArrowRight size={15}/></a><a href="/contact">Contact customer care <ArrowRight size={15}/></a></div></section>
  </StoreShell>;
}
export function ReviewsContent(){return <StoreShell><Intro label="CUSTOMER VOICES" title="Your experience matters." description="Reviews from customers with verified, delivered orders."/><ProductReviews/></StoreShell>;}

export function PolicyContent({document}:{document:"shipping-returns"|"terms"|"privacy"|"privacy-choices"}){const s=useStoreSettings();const titles={"shipping-returns":"Delivery & returns",terms:"Shopping with Vanta Noir",privacy:"Your privacy", "privacy-choices":"Your privacy choices"};
  return <StoreShell><Intro label="THE DETAILS" title={titles[document]} description={document==="shipping-returns"?"Know what to expect before you order.":"Clear information, whenever you need it."}/><article className="dn-prose dn-policy">
  {document==="shipping-returns"?<><h2>Delivery within Nigeria</h2>{s.dispatchNote?<p><strong>Dispatch:</strong> {s.dispatchNote}</p>:<p>Dispatch timing has not been published yet. Online orders remain closed until delivery details are confirmed.</p>}{s.deliveryNote&&<p className="dn-preserve-lines">{s.deliveryNote}</p>}{s.shippingZones.length?<div className="dn-table-scroll"><table><thead><tr><th>Destination</th><th>Delivery fee</th><th>Estimated delivery</th></tr></thead><tbody>{s.shippingZones.map(z=><tr key={z.state}><td>{z.state==="*"?"All other Nigerian states":z.state}</td><td>{z.feeKobo===0?"Free":formatNaira(z.feeKobo)}</td><td>{z.estimate}</td></tr>)}</tbody></table></div>:<p>Choose your state at checkout to see whether delivery is available and the confirmed fee. For destinations outside Nigeria, contact care before ordering.</p>}<h2>Returns, exchanges & refunds</h2>{s.returnPolicy?<p className="dn-preserve-lines">{s.returnPolicy}</p>:<p>The store’s returns and exchange policy has not been published yet. Online orders remain closed until it is confirmed.</p>}<p>To request help with a purchased item, <a href="/help-center#track-order">track your order</a> and select the items concerned. Wait for return instructions before sending anything back. For a damaged, defective or incorrect item, contact care with your reference and details of the issue.</p><p>Applicable consumer rights continue to apply.</p></>:
  document==="terms"?<><h2>Products & pricing</h2><p>Prices are shown in Nigerian naira. Your selected colour, size, quantity and applicable delivery charge are shown before payment. Availability and totals are checked again by the store when checkout starts. Photographs show the collection; screen settings can affect how colours appear. Check the individual product’s fabric, fit and measurements.</p><h2>Orders & payment</h2><p>Guest checkout is available when the store is accepting orders. Provide accurate contact and delivery details. Payments are handled through Paystack and confirmed by the store before an order moves into fulfilment. Keep the reference shown after payment. If an order needs a stock review, customer care will contact you before fulfilment.</p><h2>Delivery & aftercare</h2><p>The <a href="/shipping-returns">delivery and returns policy</a> explains the available destinations, rates, estimates and return conditions. Contact care promptly for changes, cancellations, damaged goods or payment questions. Refund requests are reviewed by customer care; a cancellation alone does not confirm a refund.</p><h2>Using this website</h2><p>Use the store lawfully and do not attempt to access another customer’s information, disrupt the service or misrepresent a payment. Brand content and product imagery belong to their respective rights holders. Ask permission before using them commercially.</p><h2>Questions or concerns</h2><p><a href="/contact">Contact customer care</a> for clarification before placing an order. These terms do not limit rights that cannot be excluded under applicable consumer law.</p></>:
  document==="privacy"?<><h2>Information used by the store</h2><p>When you check out, Vanta Noir receives your name, email, phone number, delivery address, purchased items, payment reference and payment status. We use this information to process and deliver orders, answer enquiries, handle returns and maintain transaction records. Order details are stored even if payment is not completed.</p><h2>Service providers</h2><p>Hosting and storage services support the website and order system. Paystack processes payments; the store does not receive or store full card details. Order contact and delivery details are shared with service providers when needed for fulfilment. An email delivery provider sends order and subscription messages when configured. Providers may process information in other countries.</p><h2>Browser storage & analytics</h2><p>Your bag, saved items, preferred measurement unit, consent choice and purchase-event deduplication markers can be stored in this browser. We do not save your checkout address or contact details in browser storage. Optional Google Analytics measures page visits and shopping activity only when you allow it. Advertising personalisation and Google signals are disabled. Checkout contact details are not included in our analytics events.</p><p><a href="/privacy-choices">Change your analytics choice</a> at any time. Declining analytics does not prevent shopping.</p><h2>Reviews & subscriptions</h2><p>Published reviews show the display name, rating, fit feedback and review text. The email and order reference used to verify a review remain private. Email subscriptions require confirmation; use the preference link in a subscription email to unsubscribe.</p><h2>Retention & requests</h2><p>Order and support records are retained for fulfilment, accounting, disputes and applicable record-keeping requirements. Access is restricted to authorised store administrators. Contact customer care to request access, correction or deletion of your information or to raise a privacy concern. Some records may need to be retained for legal or transaction purposes.</p></>:
  <><AnalyticsPreferences/><h2>Essential browser storage</h2><p>Your bag and saved pieces stay on this device. The store also remembers your cm/inches preference, your analytics choice and whether a confirmed purchase has already been recorded. Clear this website’s browser data to reset these choices; this also clears your saved bag and favourites.</p><h2>Optional measurement</h2><p>Allowing analytics helps measure which products customers explore and where checkout needs improvement. Declining it keeps optional Google Analytics disabled. A browser blocker may prevent measurement even when you allow it.</p><p><a href="/privacy-policy">Read the privacy policy</a></p></>}
  {document!=="privacy-choices"&&<div className="dn-policy-contact"><h2>Need help?</h2><p>{s.supportEmail?<a href={`mailto:${s.supportEmail}`}>{s.supportEmail}</a>:<a href="/contact">Contact Vanta Noir customer care</a>}</p></div>}
  </article></StoreShell>;
}
