"use client";
import {useEffect,useState} from 'react';
import type {TransferInstructions} from '@/lib/custom-transfer';
import {apiUrl} from '@/lib/api-client';
export function CustomTransferPayment({transfer,receiptToken,onPaid}:{transfer:TransferInstructions;receiptToken:string;onPaid:()=>void}){
 const [message,setMessage]=useState('Waiting for your transfer.'),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 async function check(){if(busy)return;setBusy(true);try{const r=await fetch(apiUrl('/api/payments/verify?reference='+encodeURIComponent(transfer.reference)),{headers:{'X-Receipt-Token':receiptToken},signal:AbortSignal.timeout(15000)});const p=await r.json() as {order?:{paymentStatus:string}};if(!r.ok)throw Error('Confirmation is temporarily unavailable. Do not pay twice.');if(p.order?.paymentStatus==='paid')onPaid();else setMessage('Payment has not been confirmed yet. Do not pay twice.')}catch{setMessage('Confirmation is temporarily unavailable. Your reference is saved; do not pay twice.')}finally{setBusy(false)}}
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')void check()},20000);return()=>clearInterval(timer)},[busy]);
 const expired=now>=Date.parse(transfer.expiresAt);
 return <section className="dn-panel" aria-labelledby="transfer-title"><span className="dn-eyebrow">VANTA NOIR / PAYMENT</span><h1 id="transfer-title">Pay by bank transfer</h1><p>Transfer exactly <strong>{new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(transfer.amountKobo/100)}</strong> to this order’s temporary account.</p><dl className="dn-totals"><div><dt>Bank</dt><dd>{transfer.bankName}</dd></div><div><dt>Account name</dt><dd>{transfer.accountName}</dd></div><div><dt>Account number</dt><dd style={{fontSize:26,letterSpacing:2}}>{transfer.accountNumber}</dd></div></dl><button type="button" className="dn-primary" onClick={()=>navigator.clipboard.writeText(transfer.accountNumber).then(()=>setMessage('Account number copied.')).catch(()=>setMessage('Select the account number to copy it.'))}>Copy account number</button><p>{expired?'This account has expired. Do not send money to it. Contact customer care if you have not paid.':'Account expires '+new Date(transfer.expiresAt).toLocaleString()+'.'}</p><p role="status">{message}</p><button type="button" className="dn-primary" disabled={busy} onClick={()=>void check()}>{busy?'Checking…':'I have transferred — check payment'}</button><p className="dn-small">We verify receipt of the funds before confirming your order. This button does not mark an order paid. Your bank may open separately.</p><p>Reference: {transfer.reference}</p><a href="/contact">Contact customer care</a></section>
}
