"use client";
import { useState, type FormEvent } from "react";
import { apiUrl } from "@/lib/api-client";
import { formatNaira } from "@/lib/catalog";
export type TrackedOrder = {reference:string;totalKobo:number;status:string;paymentStatus:string;createdAt:string;carrier:string;trackingNumber:string;trackingUrl:string;deliveryEstimate:string;items:Array<{id:number;productId:string;productName:string;size:string;color:string;quantity:number}>;returnRequest?:{id:string;kind:string;status:string;notes:string;refundKobo:number;refundStatus:string;exchangeStatus?:string;exchangeCarrier?:string;exchangeTracking?:string}|null};
export function OrderAftercare({order,contact}:{order:TrackedOrder;contact:string}){
  const [selected,setSelected]=useState<Record<number,number>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[submitted,setSubmitted]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const fields=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch(apiUrl("/api/returns"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...fields,reference:order.reference,items:Object.entries(selected).filter(([,q])=>q>0).map(([id,quantity])=>({id:Number(id),quantity}))})});const p=await r.json() as {error?:string};if(!r.ok)throw new Error(p.error||"Please try again.");setSubmitted(true);setMessage("Your request is saved. Wait for customer care to approve it and provide return instructions. Track this order again to see updates.");}catch(e){setMessage(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
  return <div className="mt-6">
    {order.deliveryEstimate&&<p>Estimated delivery: {order.deliveryEstimate}</p>}
    {order.carrier&&<p className="my-3">{order.carrier}{order.trackingNumber?` · ${order.trackingNumber}`:""}</p>}
    {order.trackingUrl&&/^https:\/\//.test(order.trackingUrl)&&<a className="vn-pill" href={order.trackingUrl} target="_blank" rel="noopener noreferrer">Track with courier</a>}
    {order.returnRequest?<div className="vn-product-disclosure mt-5"><h3 className="text-xl">Your {order.returnRequest.kind} request</h3><p className="capitalize">{order.returnRequest.status}</p>{order.returnRequest.notes&&<p className="whitespace-pre-line">{order.returnRequest.notes}</p>}{order.returnRequest.exchangeStatus&&<p>Replacement: {order.returnRequest.exchangeStatus} · {order.returnRequest.exchangeCarrier} {order.returnRequest.exchangeTracking}</p>}{order.returnRequest.refundStatus!=="none"&&<p>Refund: {order.returnRequest.refundStatus} · {formatNaira(order.returnRequest.refundKobo)}</p>}</div>:order.paymentStatus==="paid"&&["shipped","delivered"].includes(order.status)&&<details className="vn-product-disclosure mt-5"><summary>Request a return or exchange</summary><p>Read the <a href="/shipping-returns">returns and exchange policy</a> before requesting. Customer care will confirm eligibility and return instructions before you send anything back.</p>{!submitted&&<form className="vn-commerce-form" onSubmit={submit}><label>Order email<input type="email" name="email" required defaultValue={contact.includes("@")?contact:""}/></label><label>Request type<select name="kind"><option value="return">Return</option><option value="exchange">Exchange</option></select></label><fieldset><legend className="mb-3">Select quantities to return</legend>{order.items.map(item=><label key={item.id} className="mb-4">{item.productName} · {item.color} · {item.size}<select value={selected[item.id]||0} onChange={e=>setSelected(s=>({...s,[item.id]:Number(e.target.value)}))}>{Array.from({length:item.quantity+1},(_,n)=><option key={n} value={n}>{n===0?"Keep this item":`Return ${n}`}</option>)}</select></label>)}</fieldset><label>Reason / requested exchange<textarea name="reason" required minLength={10} maxLength={2000} rows={4}/></label><button className="vn-pill" disabled={busy||!Object.values(selected).some(n=>n>0)}>{busy?"Sending…":"Submit request"}</button></form>}{message&&<p role={submitted?"status":"alert"}>{message}</p>}</details>}
  </div>;
}
