import {adminThemeHead, adminThemeToolbar} from "./admin-theme-html";
import {adminAuthStateFromRequest} from './admin-auth';
import {rateLimit} from './rate-limit';
import {readWebhookBody} from './shipbubble-webhook';
import {dispatchAlternatives,DispatchError,checkDispatchFunds,dispatchOrders,reviewDispatch,bookDispatch,dispatchReviews,markDispatchPacked,readyDispatchOrders,startDispatchBatch,appendDispatchReview,dispatchBatchReviews} from './bulk-dispatch';
import {z} from 'zod';
import {terminalDispatchReady} from './terminal-dispatch';
import {getPickupDetails} from './terminal-pickup';
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(v:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(v/100);
const json=(value:unknown)=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
export async function bulkDispatchAdmin(request:Request){
 const auth=await adminAuthStateFromRequest(request);if(!auth.ok)return Response.json({error:auth.error},{status:auth.status});
 if(auth.role!=='owner')return Response.json({error:'Owner access required.'},{status:403});
 const url=new URL(request.url);
 if(request.method==='POST'){
  if(request.headers.get('origin')!==url.origin)return Response.json({error:'Open the owner dispatch page.'},{status:403});
  if(!await rateLimit(request,'bulk-dispatch',4000,3600))return Response.json({error:'Please wait before trying again.'},{status:429});
  try{
   const body=JSON.parse(new TextDecoder().decode(await readWebhookBody(request)));
   if(body.action==='alternatives')return Response.json(await dispatchAlternatives(body,auth.email));
   if(body.action==='packed')return Response.json(await markDispatchPacked(body,auth.email));
   if(body.action==='ready')return Response.json(await readyDispatchOrders(body.provider||'all',body.after||''));
   if(body.action==='start-batch')return Response.json(await startDispatchBatch(auth.email));
   if(body.action==='review'){const review=await reviewDispatch({...body,requirePacked:!!body.batchId},auth.email);if(body.batchId)await appendDispatchReview(body.batchId,review.id,auth.email);return Response.json(review);}
   if(body.action==='check-funds')return Response.json(await checkDispatchFunds(body.ids,auth.email));
   if(body.action==='book'){
    const b=z.object({id:z.string().uuid(),confirmed:z.literal(true)}).parse(body);return Response.json(await bookDispatch(b.id,auth.email));
   }
   return Response.json({error:'Unknown action.'},{status:400});
  }catch(e){return Response.json({error:e instanceof DispatchError?e.message:e instanceof z.ZodError?'Check the parcel dimensions, weight and selection.':'Could not complete this request. Reload to check booking status before trying again.'},{status:400});}
 }
 if(request.method!=='GET')return new Response('Method not allowed',{status:405});
 const page=Math.min(10000,Math.max(0,Number.parseInt(url.searchParams.get('page')||'0')||0));
 const ids=(url.searchParams.get('reviews')||'').split(',').filter(id=>z.string().uuid().safeParse(id).success).slice(0,20);
 const batch=url.searchParams.get('batch');
 const [orders,reviews,terminalReady,pickup]=await Promise.all([dispatchOrders(page),batch?dispatchBatchReviews(batch,auth.email):dispatchReviews(ids,auth.email),terminalDispatchReady(),getPickupDetails()]);
 return bulkDispatchPage(orders,reviews,page,{terminalReady,pickupAddress:pickup?[pickup.details.line1,pickup.details.line2,pickup.details.city,pickup.details.state].filter(Boolean).join(', '):'Save your business pickup address before dispatching.'});
}
export function bulkDispatchPage(orders:Awaited<ReturnType<typeof dispatchOrders>>,reviews:Awaited<ReturnType<typeof dispatchReviews>>,page=0,options={terminalReady:false,pickupAddress:'Your saved business pickup address is checked during review.'}){
 const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10),latest=new Date(Date.now()+14*86400000).toISOString().slice(0,10);
 return new Response(String.raw`<!doctype html><html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><title>Bulk dispatch | Vanta Noir</title><style>
 *{box-sizing:border-box}body{margin:0;background:var(--admin-surface);color:var(--admin-text);font:16px system-ui;line-height:1.5}main{max-width:1120px;margin:auto;padding:24px}h1{font-size:36px;margin:12px 0}h2{font-size:22px}a{color:var(--admin-text)}section,article{background:var(--admin-panel);border:1px solid var(--admin-border);border-radius:20px;padding:22px;margin:18px 0;box-shadow:0 8px 24px var(--admin-shadow)}button,.button{background:var(--admin-accent);border:1px solid var(--admin-border);border-radius:24px;padding:12px 18px;color:var(--admin-text);cursor:pointer;font:inherit;display:inline-block;text-decoration:none}button:disabled{opacity:.5;cursor:default}.secondary{background:var(--admin-surface);border-color:var(--admin-border)}input{font:inherit;border:1px solid var(--admin-border);border-radius:9px;padding:10px;max-width:100%;background:var(--admin-surface);color:var(--admin-text)}input[type=checkbox]{width:21px;height:21px;vertical-align:middle}label{display:block}small,.muted{color:var(--admin-muted)}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.grid input{width:100%}.parcel:disabled{background:var(--admin-surface)}.topline{display:flex;justify-content:space-between;align-items:center;gap:14px;flex-wrap:wrap}.problem,.error{color:var(--admin-danger)}.status{white-space:pre-wrap;overflow-wrap:anywhere}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:18px}fieldset{border:0;margin:0;padding:0}details{margin-top:12px}summary{cursor:pointer}#progress{white-space:pre-wrap}#review-list article{box-shadow:none}nav{display:flex;gap:16px}.review-total{font-size:22px;font-weight:700}@media(max-width:600px){main{padding:16px}h1{font-size:30px}section,article{padding:16px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
 </style>${adminThemeHead}<body class="vn-standalone"><main>${adminThemeToolbar}<nav><a href="/admin">Admin</a><a href="/api/admin/shipbubble">Individual shipping</a><a href="/api/admin/shipping-weights">Approved weights</a></nav><p class="muted">VANTA NOIR · FULFILMENT</p><h1>Bulk dispatch</h1><section><h2>Dispatch all packed orders</h2><p><strong>Business pickup:</strong> ${escape(options.pickupAddress)}</p><p>Shipbubble: available. Terminal Africa: ${options.terminalReady?'wallet ready; only saved Terminal checkout orders are included':'waiting for active live wallet'}.</p><label>Include provider <select id="provider"><option value="all">All available providers — keep checkout choice</option><option value="shipbubble">Shipbubble orders</option><option value="terminal" ${options.terminalReady?'':'disabled'}>Terminal Africa orders</option></select></label><p>Mark orders packed below after sealing and checking their parcels. The button gathers saved ready orders across all pages, up to 1,000 per batch. Unavailable couriers can be replaced with a service you select below.</p><button id="review-all">Review all packed orders</button><p>Both wallets are checked against their own batch totals before any pickup is requested. If funds are insufficient, top up the matching wallet and try again. Review the separate wallet totals, then use one Confirm &amp; request all pickups button. Terminal pickup timing comes from its courier; the requested date below applies to Shipbubble.</p></section><p>Select packed orders. Each keeps its delivery address. You can review an alternative courier if needed. Review current charges, then confirm bookings together.</p><p class="muted">Different couriers may collect separately. Pickup dates are requested, subject to the courier’s confirmation. One sealed parcel per order; split parcels need individual arrangements.</p>
 <section><h2>1. Prepare selected orders</h2><label>Requested pickup date <input id="pickup" type="date" value="${tomorrow}" min="${tomorrow}" max="${latest}"></label><p>Weights include garments, the approved box and packing allowance. Edit the total packed weight or outside dimensions if your parcel differs. The saved box weight is already included—do not add it again.</p><label><input id="select-all" type="checkbox"> Select all available orders on this page</label></section>
 <div id="orders">${orders.rows.map(row=>{
 if(!row.ok)return `<article><strong>${escape(row.reference)}</strong><p>${escape(row.problem)}</p></article>`;
 const disabled=Boolean(row.linked||row.booking||!row.carrier);return `<article class="order" data-reference="${escape(row.reference)}" data-fingerprint="${row.fingerprint}"><div class="topline"><label><input class="selected" type="checkbox" ${disabled?'disabled':''}> <strong>${escape(row.reference)}</strong></label><span>${escape(row.carrier||'Courier not saved')}</span></div><p>${escape(row.recipient)}<br>${escape(row.address)}</p><p>Delivery paid: <strong>${money(row.shippingKobo)}</strong></p>${row.problem?`<p class="problem">${escape(row.problem)}</p>`:''}<p class="packed-status">${row.packed?'Packed and ready':row.packedStale?'Packing details changed — confirm again':'Not marked packed'}</p><button class="mark-packed secondary" type="button" ${disabled?'disabled':''} data-packed="${row.packed?'true':'false'}">${row.packed?'Undo packed':'Mark packed & ready'}</button>${row.booking?`<p class="status">${escape(row.booking.state)} ${escape(row.booking.shipmentId||'')} ${escape(row.booking.message||'')}</p>`:''}<button class="choose-alternative secondary" type="button" ${disabled?'disabled':''}>Choose another courier</button><details><summary>Parcel · ${row.defaults?`${row.defaults.weightKg} kg · ${row.defaults.lengthCm} × ${row.defaults.widthCm} × ${row.defaults.heightCm} cm`:'Enter dimensions'}</summary><p class="muted">${escape(row.source)}</p><button class="edit secondary" type="button" ${disabled?'disabled':''}>Edit parcel</button><div class="grid">${(['weightKg','lengthCm','widthCm','heightCm'] as const).map((k,i)=>`<label>${['Packed weight (kg)','Length (cm)','Width (cm)','Height (cm)'][i]}<input class="parcel" name="${k}" type="number" step="any" min="0.001" max="${i?200:50}" value="${row.defaults?.[k]??''}" disabled></label>`).join('')}</div></details></article>`;}).join('')||'<section><p>No paid orders are awaiting dispatch yet. They will appear here after payment confirmation.</p></section>'}</div>
 <nav>${page?`<a href="?page=${page-1}">Previous orders</a>`:''}${orders.hasMore?`<a href="?page=${page+1}">Next orders</a>`:''}</nav>
 <section><label><input id="packed" type="checkbox"> The selected orders are packed and these whole-parcel weights and dimensions are ready for booking.</label><div class="actions"><button id="review" ${orders.rows.length?'':'disabled'}>Review selected dispatches</button></div><p id="progress" role="status" aria-live="polite"></p></section>
 <section id="fallbacks" hidden><h2>Choose a replacement courier</h2><p>Enable additional couriers in Shipbubble if needed, then refresh. Select a service, review its current charge and confirm the booking below. Customer payment is unchanged.</p></section><section id="review-panel" hidden><h2>2. Review and book</h2><p>These are fresh rates for the saved courier or the replacement you selected. No bookings have been made by reviewing. Confirming below charges the matching provider’s wallet; it does not charge customers again.</p><div id="review-list"></div><p id="total" class="review-total"></p><label><input id="confirm" type="checkbox"> I approve the displayed wallet charges and pickup details for these parcels.</label><div class="actions"><button id="book">Confirm &amp; request all pickups</button><a class="button secondary" href="/api/admin/bulk-dispatch">Refresh orders</a></div><p class="muted">Keep this page open while it processes. After an interruption, reopen this review URL to see results. Uncertain bookings are held for checking, never automatically retried.</p></section></main>
 <script>
 const initial=${json(reviews)};
 const $=id=>document.getElementById(id), money=k=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(k/100);
 let reviews=initial,busy=false;
 function line(parent,text,tag='p'){const el=document.createElement(tag);el.textContent=text;parent.append(el);return el;}
 function statusText(b){return b?b.state==='booked'?'Booked · '+b.shipmentId+(b.message?' · '+b.message:''):b.message||'Booking in progress or interrupted. Check the saved provider before booking again.':'';}
 function render(){
  $('review-panel').hidden=!reviews.length;$('review-list').replaceChildren();let total=0,extra=0,pending=0;const totals={shipbubble:0,terminal:0};
  for(const r of reviews){const el=document.createElement('article');line(el,r.reference+' · '+(r.provider==='terminal'?'Terminal Africa':'Shipbubble')+' · '+r.carrier,'h3');line(el,'To: '+r.recipient+' · '+r.address);line(el,'Pickup: '+r.pickupDate+' · '+r.pickupAddress);line(el,r.parcel.weightKg+' kg · '+r.parcel.lengthCm+' × '+r.parcel.widthCm+' × '+r.parcel.heightCm+' cm');line(el,'Wallet charge: '+money(r.chargeKobo)+' · Customer paid: '+money(r.shippingKobo)+' · Store covers: '+money(r.extraKobo));line(el,'Delivery estimate: '+r.delivery);if(r.booking)line(el,statusText(r.booking));else{pending++;total+=r.chargeKobo;totals[r.provider||'shipbubble']+=r.chargeKobo;extra+=r.extraKobo;if(Date.now()>=r.expiresAt)line(el,'Expired. Reload and review again.');}if(r.error)line(el,r.error).className='error';if(r.booking?.trackingUrl){const a=document.createElement('a');a.href=r.booking.trackingUrl;a.target='_blank';a.rel='noopener noreferrer';a.textContent='View shipment tracking';el.append(a);}$('review-list').append(el);}
  $('total').textContent=pending+' awaiting booking · Wallet total '+money(total)+' · Shipbubble '+money(totals.shipbubble)+' · Terminal Africa '+money(totals.terminal)+' · Store covers '+money(extra);$('book').disabled=busy||!pending;
 }
 async function post(body){const res=await fetch(location.pathname,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data;try{data=await res.json();}catch{throw Error('Session or network interrupted. Reload this page to check status.');}if(!res.ok)throw Error(data.error||'Request failed.');return data;}
 async function showFallback(input){
  $('fallbacks').hidden=false;const box=document.createElement('article');$('fallbacks').append(box);line(box,input.reference,'h3');const provider=document.createElement('select');provider.setAttribute('aria-label','Alternative provider for '+input.reference);for(const [value,label] of [['shipbubble','Shipbubble'],['terminal','Terminal Africa']]){const option=document.createElement('option');option.value=value;option.textContent=label;provider.append(option);}provider.value=input.provider||'shipbubble';box.append(provider);
  const refresh=document.createElement('button');refresh.textContent='Refresh available couriers';box.append(refresh);const status=line(box,'');const choices=document.createElement('div');box.append(choices);
  refresh.onclick=async()=>{if(busy)return;lock(true);status.textContent='Checking available couriers…';choices.replaceChildren();try{const request={...input,provider:provider.value};const data=await post({...request,action:'alternatives'});const select=document.createElement('select');select.setAttribute('aria-label','Replacement courier for '+input.reference);for(const option of data.options){const el=document.createElement('option');el.value=option.id;el.textContent=option.carrier+' · '+money(option.chargeKobo)+' · '+option.delivery;select.append(el);}choices.append(select);const use=document.createElement('button');use.textContent='Review this replacement';choices.append(use);status.textContent='Choose the courier you want to book.';use.onclick=async()=>{if(busy)return;lock(true);try{const review=await post({...request,action:'review',alternativeRateId:select.value});reviews=reviews.filter(r=>r.reference!==review.reference);reviews.push(review);$('confirm').checked=false;box.remove();render();const url=new URL(location.href);url.searchParams.set('reviews',reviews.map(r=>r.id).join(','));history.replaceState(null,'',url);}catch(e){status.textContent=e.message;}finally{lock(false);}};}catch(e){status.textContent=e.message;}finally{lock(false);}};
  refresh.click();
 }
 document.querySelectorAll('.choose-alternative').forEach(button=>button.onclick=()=>{const el=button.closest('.order');void showFallback({reference:el.dataset.reference,fingerprint:el.dataset.fingerprint,parcel:Object.fromEntries(Array.from(el.querySelectorAll('.parcel')).map(f=>[f.name,Number(f.value)])),pickupDate:$('pickup').value,packed:true});});
 function lock(value){busy=value;document.querySelectorAll('#orders button,#orders .selected,#select-all,#pickup,#packed,#review,#review-all,#provider,#confirm').forEach(e=>{if(!e.dataset.initialDisabled)e.dataset.initialDisabled=e.disabled?'yes':'no';e.disabled=value||e.dataset.initialDisabled==='yes';});$('book').disabled=value;}
 document.querySelectorAll('.mark-packed').forEach(b=>b.onclick=async()=>{if(busy)return;const el=b.closest('.order');lock(true);try{const parcel=Object.fromEntries(Array.from(el.querySelectorAll('.parcel')).map(f=>[f.name,Number(f.value)]));const result=await post({action:'packed',reference:el.dataset.reference,fingerprint:el.dataset.fingerprint,parcel,packed:b.dataset.packed!=='true'});b.dataset.packed=String(result.packed);b.textContent=result.packed?'Undo packed':'Mark packed & ready';el.querySelector('.packed-status').textContent=result.packed?'Packed and ready':'Not marked packed';}catch(e){$('progress').textContent=e.message;}finally{lock(false);render();}});
 document.querySelectorAll('.edit').forEach(b=>b.onclick=async()=>{if(busy)return;const el=b.closest('.order'),fields=b.closest('details').querySelectorAll('.parcel'),editing=b.textContent==='Edit parcel';lock(true);try{if(editing&&el.querySelector('.mark-packed').dataset.packed==='true'){await post({action:'packed',reference:el.dataset.reference,fingerprint:el.dataset.fingerprint,parcel:Object.fromEntries(Array.from(fields).map(f=>[f.name,Number(f.value)])),packed:false});const mark=el.querySelector('.mark-packed');mark.dataset.packed='false';mark.textContent='Save parcel & mark packed';el.querySelector('.packed-status').textContent='Edited parcel must be saved before mass dispatch';}fields.forEach(f=>f.disabled=!editing);b.textContent=editing?'Use these parcel details':'Edit parcel';}catch(e){$('progress').textContent=e.message;}finally{lock(false);render();}});
 $('select-all').onchange=e=>document.querySelectorAll('.selected:not(:disabled)').forEach(c=>c.checked=e.target.checked);
 $('review').onclick=async()=>{if(busy)return;
  const rows=Array.from(document.querySelectorAll('.order')).filter(el=>el.querySelector('.selected').checked&&!el.querySelector('.selected').disabled);
  if(!rows.length||!$('packed').checked){$('progress').textContent='Select orders and confirm they are packed first.';return;}
  for(const el of rows){for(const f of el.querySelectorAll('.parcel')){const n=Number(f.value);if(!Number.isFinite(n)||n<=0||n>Number(f.max)){$('progress').textContent='Check parcel fields for '+el.dataset.reference;return;}}}
  lock(true);reviews=[];$('confirm').checked=false;let errors=[];
  try{for(let i=0;i<rows.length;i++){const el=rows[i];$('progress').textContent='Checking '+(i+1)+' of '+rows.length+'…';try{const parcel=Object.fromEntries(Array.from(el.querySelectorAll('.parcel')).map(f=>[f.name,Number(f.value)]));reviews.push(await post({action:'review',reference:el.dataset.reference,fingerprint:el.dataset.fingerprint,parcel,pickupDate:$('pickup').value,packed:true}));const u=new URL(location.href);u.searchParams.set('reviews',reviews.map(r=>r.id).join(','));history.replaceState(null,'',u);}catch(e){errors.push(el.dataset.reference+': '+e.message);void showFallback({reference:el.dataset.reference,fingerprint:el.dataset.fingerprint,parcel:Object.fromEntries(Array.from(el.querySelectorAll('.parcel')).map(f=>[f.name,Number(f.value)])),pickupDate:$('pickup').value,packed:true});}}$('progress').textContent=reviews.length+' ready for your review.'+(errors.length?'\nNot included:\n'+errors.join('\n'):'');}finally{lock(false);render();}
 };
 $('review-all').onclick=async()=>{
  if(busy)return;lock(true);reviews=[];$('confirm').checked=false;
  try{const candidates={ready:[],skipped:[]};let after='';do{const page=await post({action:'ready',provider:$('provider').value,after});candidates.ready.push(...page.ready);candidates.skipped.push(...page.skipped);after=page.next;if(candidates.ready.length>1000)throw Error('More than 1,000 ready orders. Use selected batches.');}while(after);
   if(!candidates.ready.length){$('progress').textContent='No eligible packed orders.'+(candidates.skipped.length?' Check packing details or provider availability.':' Mark sealed parcels packed first.');return;}
   const batch=await post({action:'start-batch'});const url=new URL(location.href);url.searchParams.delete('reviews');url.searchParams.set('batch',batch.id);history.replaceState(null,'',url);const errors=candidates.skipped.map(s=>s.reference+': '+s.reason);
   for(let i=0;i<candidates.ready.length;i++){const row=candidates.ready[i];$('progress').textContent='Reviewing '+(i+1)+' of '+candidates.ready.length+' packed orders…';try{reviews.push(await post({action:'review',...row,packed:true,pickupDate:$('pickup').value,batchId:batch.id}));}catch(e){errors.push(row.reference+': '+e.message);void showFallback({...row,packed:true,pickupDate:$('pickup').value,batchId:batch.id});}}
   $('progress').textContent=reviews.length+' ready. Review charges before requesting pickups.'+(errors.length?'\nNot included:\n'+errors.join('\n'):'');
  }catch(e){$('progress').textContent=e.message;}finally{lock(false);render();}
 };
 $('book').onclick=async()=>{if(busy)return;
  if(!$('confirm').checked){$('progress').textContent='Review the displayed charges and tick the approval box first.';return;}
  if(reviews.some(r=>!r.booking&&Date.now()>=r.expiresAt)){$('progress').textContent='Rates expired. Refresh orders and review again.';return;}
  lock(true);
  try{$('progress').textContent='Checking provider wallet balances…';await post({action:'check-funds',ids:reviews.filter(r=>!r.booking).map(r=>r.id)});for(let i=0;i<reviews.length;i++){const r=reviews[i];if(r.booking)continue;$('progress').textContent='Booking '+(i+1)+' of '+reviews.length+'…';try{r.booking=await post({action:'book',id:r.id,confirmed:true});}catch(e){r.error=e.message;$('progress').textContent='Stopped: '+e.message+' Reload this review to check the saved status.';break;}render();}$('progress').textContent+='\nResults saved below.';}catch(e){$('progress').textContent=e.message;}finally{lock(false);$('confirm').checked=false;render();}
 };
 window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue='';}});render();
 </script></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});
}
