import {STORE_SIZES,type GarmentSizeGuide} from './sizing';
export type MeasurementReference={name:string;fit:string;source:string;kind:'top'|'bottom';fields:('chest'|'length'|'waist'|'hip')[];rows:number[][];note:string};
const source='https://www.lookfly.com/pages/sizing';
export const measurementReferences:MeasurementReference[]=[
 {name:'Windbreaker jacket',fit:'Sports shell; compare layering allowance',source:'https://www.lookfly.com/pages/windbreaker-sizing',kind:'top',fields:['chest','length'],rows:[[54.5,71],[57,72],[59.5,75],[62,77.5],[64.5,79]],note:'Dedicated windbreaker chart used. Sleeve origin is not confirmed, so sleeve values are omitted.'},
 {name:'Training jacket / tracksuit top',fit:'Unisex sports jacket',source,kind:'top',fields:['chest','length'],rows:[[56,70],[59,72],[61.5,74],[65,76],[67.5,78]],note:'Lookfly training jacket. Trousers need a separate chart.'},
 {name:'Football / performance jersey',fit:'Men’s standard short-sleeve sports jersey',source,kind:'top',fields:['chest','length'],rows:[[52.5,68.5],[55,71],[58,74],[60.5,76],[63,78.5]],note:'Pure Jersey chart. Not an oversized cotton tee specification.'},
 {name:'Basketball mesh tank',fit:'Unisex reversible mesh tank',source,kind:'top',fields:['chest','length'],rows:[[50,67],[53,69],[57.5,70],[62,72],[66,74]],note:'Reversible mesh tank chart; compare armhole and shoulder against your sample.'},
 {name:'Women’s performance jersey',fit:'Women’s standard short-sleeve sports jersey',source,kind:'top',fields:['chest','length'],rows:[[44,64],[46.5,66],[49,68],[51.5,70],[54,72]],note:'Pure Jersey women’s chart. Not a fitted cotton tee or dress pattern.'},
 {name:'Women’s sports hoodie',fit:'Women’s hoodie; not cropped or oversized',source,kind:'top',fields:['chest','length'],rows:[[45.5,65.5],[48.5,67],[51.5,68],[54.5,70],[58,73.5]],note:'Women’s Revolution Hoodie chart. Fleece, stretch and shrinkage must match your sample.'},
 {name:'Unisex sports hoodie',fit:'Standard hoodie; not oversized',source,kind:'top',fields:['chest','length'],rows:[[50.25,67.75],[54.75,70.25],[58.25,72.75],[61.75,75.25],[65.25,77.75]],note:'Calculated midpoints of Lookfly’s published unisex Revolution Hoodie ranges; a sampling starting point, not exact manufacturer targets.'},
 {name:'Short sports shorts',fit:'Men’s Shorty Shorts',source,kind:'bottom',fields:['waist','hip','length'],rows:[[34.25,53.25,36],[36.75,56.25,38.5],[39.25,59.25,41],[41.75,62.25,43.5],[44.5,65.25,46]],note:'Source full relaxed waist and hip circumferences divided by two to give flat widths. Inseam is not supplied.'},
];
export function referenceToGuide(r:MeasurementReference):GarmentSizeGuide{return {status:'reference',notes:`External sampling reference only: ${r.fit}. ${r.note} Source: ${r.source}. Not measured from Vanta Noir garments; confirm against physical samples.`,sections:[{kind:r.kind,title:r.name,rows:r.rows.map((values,i)=>({size:STORE_SIZES[i],...Object.fromEntries(r.fields.map((f,j)=>[f,values[j]]))}))}]};}
