import { z } from 'zod';
import { getDbBinding, isAdminEmail, runtimeEnv } from './runtime-env';
import { saveAdminProduct, listAdminProducts, listAdminOrders, updateOrderStatus, updateOrderTracking } from './store-db';
import {queueEmail} from './commerce-db';
import { productSchema } from './product-input';
import {roleResources,type StaffRole} from "./operations-permissions";
export {roleResources,type StaffRole} from "./operations-permissions";
export async function staffRole(email:string):Promise<StaffRole|null>{
 if(isAdminEmail(email))return 'owner';
 const row=await getDbBinding().prepare('SELECT role FROM admin_staff WHERE email=? AND active=1').bind(email.trim().toLowerCase()).first<{role:StaffRole}>();
 return row && ['catalogue','fulfilment','support','analyst'].includes(row.role)?row.role:null;
}
export function permits(role:StaffRole,resource:string){return roleResources[role].includes(resource);}
export function auditStatement(actor:string,action:string,entity:string,detail='') {return getDbBinding().prepare('INSERT INTO admin_audit(actor,action,entity,detail) VALUES(?,?,?,?)').bind(actor,action,entity,detail);}
export async function audit(actor:string,action:string,entity:string,detail=''){await auditStatement(actor,action,entity,detail).run();}
export const stockChangeSchema=z.object({variantId:z.string().min(1).max(160),expectedStock:z.number().int().min(0),stock:z.number().int().min(0).max(100000),reason:z.string().trim().min(3).max(240)});
export async function adjustStock(input:unknown,actor:string){
 const x=stockChangeSchema.parse(input), db=getDbBinding(),token=crypto.randomUUID(),key=`stock:${x.variantId}`;
 const gate='EXISTS(SELECT 1 FROM store_meta WHERE key=? AND value=?)';
 const r=await db.batch([
 db.prepare(`INSERT INTO store_meta(key,value) SELECT ?,? WHERE EXISTS(SELECT 1 FROM product_variants v WHERE id=? AND stock=? AND ? >= COALESCE((SELECT SUM(quantity) FROM stock_reservations WHERE variant_id=v.id AND expires_at>CURRENT_TIMESTAMP),0)) ON CONFLICT(key) DO UPDATE SET value=excluded.value`).bind(key,token,x.variantId,x.expectedStock,x.stock),
 db.prepare(`INSERT INTO stock_adjustments(variant_id,old_stock,new_stock,reason,actor) SELECT id,stock,?,?,? FROM product_variants WHERE id=? AND ${gate}`).bind(x.stock,x.reason,actor,x.variantId,key,token),
 db.prepare(`UPDATE product_variants SET stock=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND ${gate}`).bind(x.stock,x.variantId,key,token),
 db.prepare('DELETE FROM store_meta WHERE key=? AND value=?').bind(key,token)]);
 if(!r[0].meta.changes)throw new Error('Stock changed or is reserved by a checkout. Refresh before adjusting it.');
}
export async function bulkPrices(input:unknown,actor:string){
 const rows=z.array(z.object({id:z.string().min(1),expectedPrice:z.number().int(),priceKobo:z.number().int().min(100).max(100000000000)})).min(1).max(100).parse(input); const out=[];
 for(const row of rows){const db=getDbBinding();const token=crypto.randomUUID(),key=`price:${row.id}`;
 const r=await db.batch([db.prepare('INSERT INTO store_meta(key,value) SELECT ?,? WHERE EXISTS(SELECT 1 FROM products WHERE id=? AND price_kobo=?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,token,row.id,row.expectedPrice),db.prepare('UPDATE products SET price_kobo=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND EXISTS(SELECT 1 FROM store_meta WHERE key=? AND value=?)').bind(row.priceKobo,row.id,key,token),db.prepare('INSERT INTO admin_audit(actor,action,entity,detail) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM store_meta WHERE key=? AND value=?)').bind(actor,'price',row.id,JSON.stringify({before:row.expectedPrice,after:row.priceKobo}),key,token),db.prepare('DELETE FROM store_meta WHERE key=? AND value=?').bind(key,token)]);out.push({id:row.id,ok:!!r[0].meta.changes});}return out;
}
export async function importProducts(input:unknown,actor:string){
 const rows=z.array(productSchema).min(1).max(25).parse(input), result=[];
 for(const row of rows){try{if(row.id)throw new Error('Use the product editor to update existing designs. Imports create drafts.');const product=await saveAdminProduct({...row,status:'draft'},actor);await audit(actor,'product import',product.id);result.push({name:row.name,ok:true,id:product.id});}catch(e){result.push({name:row.name,ok:false,error:e instanceof Error?e.message:'Import failed'});}}return result;
}
export const promotionSchema=z.object({code:z.string().trim().toUpperCase().regex(/^[A-Z0-9_-]{3,32}$/),title:z.string().trim().min(2).max(100),kind:z.enum(['percent','fixed']),value:z.number().int().min(1).max(100000000),minimumKobo:z.number().int().min(0).max(100000000000),minimumQuantity:z.number().int().min(1).max(100),productIds:z.array(z.string().min(1)).max(100),maxUses:z.number().int().min(0).max(1000000),startsAt:z.string().datetime(),endsAt:z.string().datetime(),active:z.boolean(),version:z.number().int().min(0).default(0)}).superRefine((v,c)=>{if(v.kind==='percent'&&v.value>90)c.addIssue({code:'custom',message:'Percentage must be between 1 and 90.'});if(v.endsAt<=v.startsAt)c.addIssue({code:'custom',message:'End date must follow start date.'});});
export async function savePromotion(input:unknown,actor:string){
 const v=promotionSchema.parse(input),db=getDbBinding();
 for(const id of v.productIds){if(!await db.prepare('SELECT id FROM products WHERE id=?').bind(id).first())throw new Error('An eligible product ID does not exist.');}
 const r=await db.prepare(`INSERT INTO promotions(code,title,kind,value,minimum_kobo,minimum_quantity,product_ids,max_uses,starts_at,ends_at,active,version) SELECT ?,?,?,?,?,?,?,?,?,?,?,1 WHERE ?=0 OR EXISTS(SELECT 1 FROM promotions WHERE code=? AND version=?) ON CONFLICT(code) DO UPDATE SET title=excluded.title,kind=excluded.kind,value=excluded.value,minimum_kobo=excluded.minimum_kobo,minimum_quantity=excluded.minimum_quantity,product_ids=excluded.product_ids,max_uses=excluded.max_uses,starts_at=excluded.starts_at,ends_at=excluded.ends_at,active=excluded.active,version=promotions.version+1 WHERE promotions.version=?`).bind(v.code,v.title,v.kind,v.value,v.minimumKobo,v.minimumQuantity,JSON.stringify(v.productIds),v.maxUses,v.startsAt,v.endsAt,v.active?1:0,v.version,v.code,v.version,v.version).run();
 if(!r.meta.changes)throw new Error('Promotion changed. Refresh and retry.');await audit(actor,'promotion saved',v.code);
}
export type PromotionRow={code:string;kind:string;value:number;minimum_kobo:number;minimum_quantity:number;product_ids:string;version:number;max_uses:number};
export async function quotePromotion(code:string,items:Array<{productId:string;lineTotalKobo:number;quantity:number}>){
 if(!code.trim())return {discountKobo:0,promotion:null};
 const db=getDbBinding(),now=new Date().toISOString();
 const p=await db.prepare(`SELECT * FROM promotions p WHERE code=? AND active=1 AND starts_at<=? AND ends_at>? AND (max_uses=0 OR max_uses>(SELECT COUNT(*) FROM orders o WHERE o.promotion_code=p.code AND (o.payment_status='paid' OR (o.status='pending_payment' AND o.created_at>datetime('now','-15 minutes')))))`).bind(code.trim().toUpperCase(),now,now).first<PromotionRow>();
 if(!p)throw new Error('This promotion is unavailable or has expired.');const ids=JSON.parse(p.product_ids) as string[];const eligible=items.filter(i=>!ids.length||ids.includes(i.productId));const subtotal=eligible.reduce((s,i)=>s+i.lineTotalKobo,0),quantity=eligible.reduce((s,i)=>s+i.quantity,0);
 if(subtotal<p.minimum_kobo||quantity<p.minimum_quantity)throw new Error('Your bag does not meet this promotion’s requirements.');
 return {discountKobo:Math.min(Math.max(0,subtotal-100),p.kind==='percent'?Math.floor(subtotal*p.value/100):p.value),promotion:p};
}
export async function allocateExchange(input:unknown,actor:string){
 const v=z.object({returnId:z.string().min(1),items:z.array(z.object({originalVariantId:z.string().min(1),variantId:z.string().min(1),quantity:z.number().int().min(1).max(5)})).min(1).max(20)}).parse(input),db=getDbBinding();
 if(new Set(v.items.map(i=>i.originalVariantId)).size!==v.items.length||new Set(v.items.map(i=>i.variantId)).size!==v.items.length)throw new Error('Choose one replacement per returned variant.');
 const r=await db.prepare(`SELECT r.*,o.reference FROM return_requests r JOIN orders o ON o.id=r.order_id WHERE r.id=? AND r.kind='exchange' AND r.status='received'`).bind(v.returnId).first<{items_json:string;reference:string;version:number}>();
 if(!r)throw new Error('Receive and inspect the exchange before allocating replacements.');const originals=JSON.parse(r.items_json) as Array<{variantId:string;quantity:number}>;
 if(originals.length!==v.items.length||v.items.some(i=>!originals.some(o=>o.variantId===i.originalVariantId&&o.quantity===i.quantity)))throw new Error('Replacement quantities must match the received items.');
 const token=crypto.randomUUID(),key=`exchange:${v.returnId}`;
 const gate='EXISTS(SELECT 1 FROM store_meta WHERE key=? AND value=?)';
 const stmts=[db.prepare(`INSERT INTO store_meta(key,value) SELECT ?,? WHERE EXISTS(SELECT 1 FROM return_requests WHERE id=? AND version=? AND status='received') AND NOT EXISTS(SELECT 1 FROM exchanges WHERE return_id=?) AND NOT EXISTS(SELECT 1 FROM json_each(?) i LEFT JOIN product_variants v ON v.id=json_extract(i.value,'$.variantId') LEFT JOIN product_variants orig ON orig.id=json_extract(i.value,'$.originalVariantId') WHERE v.id IS NULL OR orig.id IS NULL OR v.active<>1 OR v.product_id<>orig.product_id OR v.stock-COALESCE((SELECT SUM(quantity) FROM stock_reservations WHERE variant_id=v.id AND expires_at>CURRENT_TIMESTAMP),0)<json_extract(i.value,'$.quantity')) ON CONFLICT(key) DO UPDATE SET value=excluded.value`).bind(key,token,v.returnId,r.version,v.returnId,JSON.stringify(v.items))];
 for(const i of v.items){stmts.push(db.prepare(`INSERT INTO stock_adjustments(variant_id,old_stock,new_stock,reason,actor) SELECT id,stock,stock-?,?,? FROM product_variants WHERE id=? AND ${gate}`).bind(i.quantity,`Exchange ${r.reference}`,actor,i.variantId,key,token),db.prepare(`UPDATE product_variants SET stock=stock-?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND ${gate}`).bind(i.quantity,i.variantId,key,token));}
 stmts.push(db.prepare(`INSERT INTO exchanges(return_id,items_json,actor) SELECT ?,?,? WHERE ${gate}`).bind(v.returnId,JSON.stringify(v.items),actor,key,token),db.prepare(`UPDATE return_requests SET version=version+1 WHERE id=? AND ${gate}`).bind(v.returnId,key,token),db.prepare('DELETE FROM store_meta WHERE key=? AND value=?').bind(key,token));
 const result=await db.batch(stmts);if(!result[0].meta.changes)throw new Error('Replacement stock is unavailable, this request changed, or replacements were already allocated.');await audit(actor,'exchange allocated',v.returnId);
}
export async function operationsData(resource:string,params:URLSearchParams){
 const db=getDbBinding(),page=Math.max(1,Math.min(10000,Number(params.get('page'))||1)),offset=(page-1)*50;
 if(resource==='bulk')return {products:await listAdminProducts()};
 if(resource==='inventory'){const search=`%${(params.get('q')||'').slice(0,100)}%`;return {rows:(await db.prepare(`SELECT a.*,v.sku,p.name FROM stock_adjustments a LEFT JOIN product_variants v ON v.id=a.variant_id LEFT JOIN products p ON p.id=v.product_id WHERE COALESCE(v.sku,'') LIKE ? OR a.reason LIKE ? ORDER BY a.id DESC LIMIT 51 OFFSET ?`).bind(search,search,offset).all()).results};}
 if(resource==='orders'){return {orders:await listAdminOrders({page,status:params.get('status')||'',query:params.get('q')||''}),counts:(await db.prepare('SELECT status,COUNT(*) AS count FROM orders GROUP BY status').all()).results};}
 if(resource==='returns')return {returns:(await db.prepare('SELECT r.*,o.reference,e.items_json AS replacements,e.status AS exchange_status,e.carrier AS exchange_carrier,e.tracking_number AS exchange_tracking FROM return_requests r JOIN orders o ON o.id=r.order_id LEFT JOIN exchanges e ON e.return_id=r.id ORDER BY r.created_at DESC LIMIT 51 OFFSET ?').bind(offset).all()).results,variants:(await db.prepare('SELECT v.id,v.product_id,v.size,v.color,v.stock,v.active,p.name FROM product_variants v JOIN products p ON p.id=v.product_id').all()).results};
 if(resource==='promotions')return {promotions:(await db.prepare(`SELECT p.*,(SELECT COUNT(*) FROM orders o WHERE o.promotion_code=p.code AND o.payment_status='paid') AS redeemed FROM promotions p ORDER BY starts_at DESC LIMIT 100`).all()).results};
 if(resource==='reports'){const from=params.get('from')||'1970-01-01',to=params.get('to')||'2999-12-31';if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)throw new Error('Choose a valid date range.');
 const [sales,refunds,bestsellers]=await Promise.all([db.prepare(`SELECT COUNT(*) AS orders,COALESCE(SUM(total_kobo),0) AS revenue,COALESCE(SUM(discount_kobo),0) AS discounts,COALESCE(SUM(shipping_kobo),0) AS delivery FROM orders WHERE payment_status='paid' AND date(paid_at) BETWEEN ? AND ?`).bind(from,to).first(),db.prepare(`SELECT COALESCE(SUM(refund_kobo),0) AS amount FROM return_requests WHERE refund_status='completed' AND date(updated_at) BETWEEN ? AND ?`).bind(from,to).first(),db.prepare(`SELECT i.product_name,i.size,i.color,SUM(i.quantity) AS units,SUM(i.line_total_kobo) AS gross FROM order_items i JOIN orders o ON o.id=i.order_id WHERE o.payment_status='paid' AND date(o.paid_at) BETWEEN ? AND ? GROUP BY i.product_id,i.product_name,i.size,i.color ORDER BY units DESC LIMIT 100`).bind(from,to).all()]);return {sales,refunds,bestsellers:bestsellers.results};}
 if(resource==='staff')return {staff:(await db.prepare('SELECT email,role,active FROM admin_staff ORDER BY email').all()).results};
 if(resource==='activity')return {rows:(await db.prepare('SELECT * FROM admin_audit ORDER BY id DESC LIMIT 51 OFFSET ?').bind(offset).all()).results};
 if(resource==='courier')return {connected:!!runtimeEnv().COURIER_WEBHOOK_SECRET,events:(await db.prepare('SELECT * FROM courier_events ORDER BY created_at DESC LIMIT 50').all()).results};
 throw new Error('Unknown section.');
}
export async function saveStaff(input:unknown,actor:string){const v=z.object({email:z.string().trim().toLowerCase().email().max(200),role:z.enum(['catalogue','fulfilment','support','analyst']),active:z.boolean()}).parse(input);if(isAdminEmail(v.email))throw new Error('The owner role cannot be changed here.');await getDbBinding().batch([getDbBinding().prepare('INSERT INTO admin_staff(email,role,active) VALUES(?,?,?) ON CONFLICT(email) DO UPDATE SET role=excluded.role,active=excluded.active,updated_at=CURRENT_TIMESTAMP').bind(v.email,v.role,v.active?1:0),auditStatement(actor,'staff permissions',v.email,JSON.stringify({role:v.role,active:v.active}))]);}
export async function orderAction(input:unknown,actor:string,role:StaffRole){const v=z.object({reference:z.string().min(3).max(120),status:z.enum(['paid','processing','shipped','delivered','cancelled','paid_stock_review'])}).parse(input);if(role!=='owner'&&!['processing','shipped','delivered'].includes(v.status))throw new Error('Only the owner can change payment-review or cancellation status.');await updateOrderStatus(v.reference,v.status);await audit(actor,'order status',v.reference,v.status);}
export async function exchangeTracking(input:unknown,actor:string){const v=z.object({returnId:z.string().min(1),carrier:z.string().trim().min(1).max(100),trackingNumber:z.string().trim().min(1).max(160),status:z.enum(['shipped','delivered'])}).parse(input);const r=await getDbBinding().prepare("UPDATE exchanges SET carrier=?,tracking_number=?,status=? WHERE return_id=? AND (status='allocated' AND ?='shipped' OR status='shipped' AND ? IN ('shipped','delivered'))").bind(v.carrier,v.trackingNumber,v.status,v.returnId,v.status,v.status).run();if(!r.meta.changes)throw new Error('Allocate replacements before dispatch and dispatch before delivery.');await audit(actor,'exchange tracking',v.returnId,v.status);const order=await getDbBinding().prepare('SELECT o.email,o.reference FROM return_requests r JOIN orders o ON o.id=r.order_id WHERE r.id=?').bind(v.returnId).first<{email:string;reference:string}>();if(order)await queueEmail(`exchange:${v.returnId}:${v.status}:${v.trackingNumber}`,order.email,`Replacement ${v.status} · ${order.reference}`,`Your replacements are ${v.status}. Courier: ${v.carrier}. Tracking: ${v.trackingNumber}.`);}
