import {z} from 'zod';
import {getDbBinding} from './runtime-env';
import {estimateItem,initialPackaging,itemParcelSchema,packagingSchema,prepareParcel} from './parcel-estimates';
const id=z.string().min(1).max(150),size=z.string().min(1).max(40);
export class ParcelConflict extends Error{}
async function read(key:string){const r=await getDbBinding().prepare('SELECT value FROM store_meta WHERE key=?').bind(key).first<{value:string}>();return r?JSON.parse(r.value):null;}
async function save(key:string,data:unknown,revision:unknown){const rev=z.string().uuid().nullable().parse(revision),record={revision:crypto.randomUUID(),data,updatedAt:new Date().toISOString()};const db=getDbBinding();const r=rev===null?await db.prepare('INSERT OR IGNORE INTO store_meta(key,value) VALUES(?,?)').bind(key,JSON.stringify(record)).run():await db.prepare("UPDATE store_meta SET value=? WHERE key=? AND json_extract(value,'$.revision')=?").bind(JSON.stringify(record),key,rev).run();if(!r.meta.changes)throw new ParcelConflict('Saved details changed. Reload before saving again; your edits have not been overwritten.');return record;}
const profileKey=(p:string,s:string)=>'parcel-item:'+encodeURIComponent(p)+':'+encodeURIComponent(s);
function details(value:string){try{return JSON.parse(value||'{}');}catch{return {};}}
export async function packagingProfiles(){return await read('parcel-packaging')||{revision:null,data:initialPackaging};}
export async function savePackaging(data:unknown,revision:unknown){const presets=z.array(packagingSchema).min(1).max(20).refine(v=>new Set(v.map(p=>p.id)).size===v.length).parse(data);return save('parcel-packaging',presets,revision);}
export async function productParcel(productId:string,selectedSize:string){id.parse(productId);size.parse(selectedSize);const db=getDbBinding();const p=await db.prepare('SELECT id,name,category,details_json FROM products WHERE id=?').bind(productId).first<any>();if(!p)throw Error('Product not found.');const variant=await db.prepare('SELECT 1 AS found FROM product_variants WHERE product_id=? AND size=? LIMIT 1').bind(productId,selectedSize).first();if(!variant)throw Error('Product size not found.');const record=await read(profileKey(productId,selectedSize));const estimate=estimateItem(p.name,p.category,details(p.details_json),selectedSize);return {productId,size:selectedSize,name:p.name,revision:record?.revision||null,parcel:record?.data||estimate.parcel,basis:record?'Saved product/size profile. Applies to colours with the same construction.':estimate.basis};}
export async function saveProductParcel(productId:string,selectedSize:string,data:unknown,revision:unknown){await productParcel(productId,selectedSize);return save(profileKey(productId,selectedSize),itemParcelSchema.parse(data),revision);}
export async function searchParcelProducts(query:string,page:number){const rows=await getDbBinding().prepare("SELECT id,name FROM products WHERE (?='' OR name LIKE ?) ORDER BY name,id LIMIT 11 OFFSET ?").bind(query,'%'+query+'%',page*10).all<{id:string;name:string}>();const products=await Promise.all(rows.results.slice(0,10).map(async p=>({...p,sizes:(await getDbBinding().prepare('SELECT DISTINCT size FROM product_variants WHERE product_id=? ORDER BY size').bind(p.id).all<{size:string}>()).results.map(v=>v.size)})));return {products,hasMore:rows.results.length>10};}
export async function orderParcel(reference:string){z.string().regex(/^VN-[A-Za-z0-9-]{1,100}$/).parse(reference);const db=getDbBinding();const order=await db.prepare('SELECT id,payment_status,status FROM orders WHERE reference=?').bind(reference).first<any>();if(!order)throw Error('Order not found.');const rows=await db.prepare('SELECT product_id,size,product_name,quantity FROM order_items WHERE order_id=? ORDER BY id').bind(order.id).all<any>();const items=await Promise.all(rows.results.map(async r=>{try{const p=await productParcel(r.product_id,r.size);return {name:r.product_name,size:r.size,quantity:r.quantity,parcel:p.parcel,basis:p.basis};}catch{return {name:r.product_name,size:r.size,quantity:r.quantity,parcel:null,basis:'Item shipping profile unavailable.'};}}));const packaging=await packagingProfiles();const selected=await read('order-shipping:'+reference);return {reference,items,selectedDelivery:selected?{provider:selected.rate.provider,carrier:selected.rate.carrier,amountKobo:selected.rate.amountKobo,delivery:selected.rate.delivery,bookingStatus:selected.bookingStatus}:null,...prepareParcel(items,packaging.data),paidUnshipped:order.payment_status==='paid'&&['paid','processing'].includes(order.status),liveBookingEnabled:false};}
