import {adminAuthStateFromRequest} from './admin-auth';
import {rateLimit} from './commerce-db';
import {checkShipbubbleLive,shipbubbleReadiness} from './shipbubble-live';
import {linkShipbubbleShipment,readWebhookBody} from './shipbubble-webhook';
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function shipbubbleAdmin(request:Request){
 const auth=await adminAuthStateFromRequest(request);if(!auth.ok)return Response.json({error:auth.error},{status:auth.status});if(auth.role!=='owner')return new Response('Owner access required',{status:403});
 let message='';
 if(request.method==='POST'){
  if(request.headers.get('origin')!==new URL(request.url).origin)return new Response('Open the owner shipping page',{status:403});
  if(!await rateLimit(request,'shipbubble-live-check',10,3600))return new Response('Please wait before checking again',{status:429});
  try{const form=new URLSearchParams(new TextDecoder().decode(await readWebhookBody(request)));if(form.get('action')==='check'){await checkShipbubbleLive();message='Connection check completed.';}else if(form.get('action')==='link'){await linkShipbubbleShipment(form.get('reference')||'',form.get('shipmentId')||'',auth.email);message='Shipment linked. Verified delivery status synchronized.';}else return new Response('Unknown action',{status:400});}
  catch(e){message=e instanceof Error&&['Choose a paid, uncompleted store order.','Shipment recipient email does not match the store order.','Shipment or order is already linked. Review the existing booking.'].includes(e.message)?e.message:'Could not complete this action. Check the shipment and order references, then retry.';}
 }else if(request.method!=='GET')return new Response('Method not allowed',{status:405});
 const s=await shipbubbleReadiness();if(new URL(request.url).searchParams.get('format')==='json')return Response.json(s);
 const endpoint=new URL(s.webhookPath,request.url).href;
 return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shipbubble setup | Vanta Noir</title><style>body{font:16px system-ui;background:#f2f4f1;color:#141414;margin:0;padding:24px}main{max-width:780px;margin:auto}section{background:white;border:1px solid #dbe1d7;border-radius:20px;padding:24px;margin:20px 0}button{background:#c8ff65;border:0;border-radius:24px;padding:12px 18px;cursor:pointer}input{display:block;padding:12px;margin:8px 0 18px;width:90%;border:1px solid #aaa;border-radius:8px}code{overflow-wrap:anywhere}a{color:#174400}h1{font-size:28px}p{line-height:1.6}</style><main><a href="/admin">Back to admin</a><h1>Shipbubble setup</h1><p role="status">${escape(message)}</p><section><h2>Live connection</h2><p>Production key: ${s.keyConfigured?'saved':'missing or not a live key'}<br>Account check: ${escape(s.connection?.status||'not checked')}<br>${escape(s.connection?.error||'')}<br>Wallet funded: ${s.connection?.walletFunded===true?'yes':s.connection?.walletFunded===false?'no':'not verified'}</p><form method="post"><input type="hidden" name="action" value="check"><button>Check Shipbubble live connection</button></form><p>This reads account status. It does not book or charge for shipping.</p></section><section><h2>Checkout readiness</h2><p>Pickup address: ${s.pickupReady?'saved':'missing'}<br>Measured garment/size profiles: ${s.itemProfiles?.measured||0}<br>Measured packaging presets: ${s.measuredPackaging}<br>Live checkout rates: ${s.checkoutEnabled?'enabled':'not enabled'}</p><p>Enter actual product weights and folded dimensions, and packaging measurements in Admin → Settings → Product weights &amp; packaging. Upload the new Namecheap checkout before enabling customer rates.</p></section><section><h2>Live webhook</h2><p>Enter this in Shipbubble’s Live Webhook URL field:</p><code>${escape(endpoint)}</code><p>Signature verification uses the saved production API key. Last authenticated webhook: ${escape(s.lastWebhook?.receivedAt||'none received')}.</p><p>Shipment booking remains manual. After booking in Shipbubble, link the shipment below so delivery updates reach the correct store order. Sandbox events cannot update live orders.</p></section><section><h2>Link a booked shipment</h2><form method="post"><input type="hidden" name="action" value="link"><label>Vanta Noir order reference<input name="reference" placeholder="VN-…" required maxlength="103"></label><label>Shipbubble shipment ID<input name="shipmentId" placeholder="SB-…" required maxlength="103"></label><button>Verify and link shipment</button></form><p>The store order must be paid and its customer email must match the shipment recipient. This does not create a booking or take a payment.</p></section></main></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});
}
