import {adminAuthStateFromRequest} from './admin-auth';
import {rateLimit} from './rate-limit';
import {checkShipbubbleLive,shipbubbleReadiness} from './shipbubble-live';
import {linkShipbubbleShipment,readWebhookBody} from './shipbubble-webhook';
import {measurementOrders,orderMeasurements,saveOrderMeasurements,quoteMeasuredOrder} from './order-measurements';
const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(kobo:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(kobo/100);
export async function shipbubbleAdmin(request:Request){
 const auth=await adminAuthStateFromRequest(request);
 if(!auth.ok)return Response.json({error:auth.error},{status:auth.status});
 if(auth.role!=='owner')return new Response('Owner access required',{status:403});
 const url=new URL(request.url);let reference=url.searchParams.get('reference')||'',message='',quote:Awaited<ReturnType<typeof quoteMeasuredOrder>>|null=null;
 let attempted:Record<string,string>|null=null;
 if(request.method==='POST'){
  if(request.headers.get('origin')!==url.origin)return new Response('Open the owner shipping page',{status:403});
  try{
   const form=new URLSearchParams(new TextDecoder().decode(await readWebhookBody(request))),action=form.get('action');
   if(!await rateLimit(request,'shipbubble-'+action,action==='measure'?60:10,3600))return new Response('Please wait before trying again',{status:429});
   reference=form.get('reference')||reference;
   if(action==='check'){await checkShipbubbleLive();message='Connection check completed.';}
   else if(action==='link'){await linkShipbubbleShipment(reference,form.get('shipmentId')||'',auth.email);message='Shipment linked. Verified delivery status synchronized.';}
   else if(action==='measure'){
    attempted=Object.fromEntries(['weightKg','lengthCm','widthCm','heightCm'].map(k=>[k,form.get(k)||'']));
    await saveOrderMeasurements(reference,attempted,form.get('revision')||null,auth.email);attempted=null;message='Actual packed measurements saved. You can now request courier rates.';
   }else if(action==='quote'){quote=await quoteMeasuredOrder(reference,form.get('revision')||'');message=quote.rates.length?'Live rates returned. No shipment booked.':'No pickup services returned for this address and parcel.';}
   else return new Response('Unknown action',{status:400});
  }catch(e){
   const safe=['Choose a paid, uncompleted store order.','Shipment recipient email does not match the store order.','Shipment or order is already linked. Review the existing booking.','Measurements were not saved. Reload the order; it may have changed, shipped, or already been linked.','Save and reload the actual packed measurements before requesting rates.','Choose a paid, unshipped Nigerian order.','This order already has a linked shipment.','Save the business pickup address first.','Measurements changed while fetching rates. Reload and request fresh rates.'];
   message=e instanceof Error&&safe.includes(e.message)?e.message:attempted?'Measurements were not saved. Use a packed weight above 0 and at most 50 kg, with each dimension above 0 and at most 200 cm.':'Could not complete this action. Check the live account, order details and shipment reference, then retry.';
  }
 }else if(request.method!=='GET')return new Response('Method not allowed',{status:405});
 const s=await shipbubbleReadiness();if(url.searchParams.get('format')==='json')return Response.json(s);
 const orders=await measurementOrders();
 if(!/^VN-[A-Za-z0-9_-]{1,100}$/.test(reference))reference='';
 const saved=reference?await orderMeasurements(reference):null;
 const selected=orders.find(o=>o.reference===reference),values=attempted||saved?.measurements;
 const endpoint=new URL(s.webhookPath,request.url).href;
 return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Order shipping | Vanta Noir</title><style>body{font:16px system-ui;background:#f2f4f1;color:#141414;margin:0;padding:24px}main{max-width:850px;margin:auto}section{background:white;border:1px solid #dbe1d7;border-radius:20px;padding:24px;margin:20px 0}button{background:#c8ff65;border:0;border-radius:24px;padding:12px 18px;cursor:pointer}input,select{display:block;box-sizing:border-box;padding:12px;margin:8px 0 18px;width:100%;border:1px solid #aaa;border-radius:8px;background:white;color:#141414}input[type=hidden]{display:none}code{overflow-wrap:anywhere}a{color:#174400}h1{font-size:28px}p{line-height:1.6}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:16px}.rates{overflow:auto}table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:10px;border-bottom:1px solid #ddd}small{color:#465341}</style><main><a href="/admin">Back to admin</a><h1>Order shipping</h1><p><a href="/api/admin/shipping-weights">Edit approved garment and box weights</a></p><p>Customer orders and pays the checkout delivery fee → you pack and measure → you choose and book the courier → link the shipment for tracking.</p>${message?`<section role="status">${escape(message)}</section>`:''}
 <section><h2>1. Measure a packed order</h2><p>Enter the total weight including packaging, and the outside length, width and height of the sealed parcel. These are parcel dimensions, not clothing sizes. One parcel per order.</p><form method="get"><label>Paid order awaiting dispatch<select name="reference" required><option value="">Choose an order</option>${orders.map(o=>`<option value="${escape(o.reference)}" ${o.reference===reference?'selected':''}>${escape(o.reference)} · ${escape(o.city)}, ${escape(o.state)}</option>`).join('')}</select></label><button>Open order</button></form>${orders.length?'':'<p>No paid orders are awaiting dispatch yet. New paid orders will appear here.</p>'}
 ${selected?`<h3>${escape(reference)}</h3><p>Delivery fee already paid: ${money(selected.shippingKobo)}. The customer’s payment stays unchanged.</p><form method="post"><input type="hidden" name="action" value="measure"><input type="hidden" name="reference" value="${escape(reference)}"><input type="hidden" name="revision" value="${escape(saved?.revision||'')}"><div class="grid">${(['weightKg','lengthCm','widthCm','heightCm'] as const).map((k,i)=>`<label>${['Packed weight (kg)','Length (cm)','Width (cm)','Height (cm)'][i]}<input type="number" name="${k}" min="0.001" max="${i===0?50:200}" step="any" required value="${escape(values?.[k]??'')}"></label>`).join('')}</div><button>Save actual measurements</button></form>${saved?`<p><small>Saved ${escape(saved.updatedAt)}. Measurements lock after a shipment is linked.</small></p><form method="post"><input type="hidden" name="action" value="quote"><input type="hidden" name="reference" value="${escape(reference)}"><input type="hidden" name="revision" value="${escape(saved.revision)}"><button>Get live courier rates</button></form><p>Uses the saved measurements and order address. Quotes use tomorrow’s pickup date; confirm the date and final price when booking in Shipbubble.</p>`:''}`:reference?'<p>This order is not awaiting dispatch. Select a paid, unshipped order above.</p>':''}
 ${quote?`<div class="rates"><table><thead><tr><th>Courier</th><th>Rate</th><th>Store covers*</th><th>Estimate</th></tr></thead><tbody>${quote.rates.map(r=>`<tr><td>${escape(r.carrier)}</td><td>${money(r.amountKobo)}</td><td>${money(Math.max(0,r.amountKobo-quote!.shippingKobo))}</td><td>${escape(r.delivery)}</td></tr>`).join('')}</tbody></table></div><p>*Quoted rate above the delivery fee already collected. Final wallet charge can differ. Confirm the total before booking. These rates do not create a shipment.</p><a href="https://app.shipbubble.com" target="_blank" rel="noopener noreferrer">Open Shipbubble to book</a>`:''}</section>
 <section><h2>2. Link a booked shipment</h2><form method="post"><input type="hidden" name="action" value="link"><label>Vanta Noir order reference<input name="reference" value="${escape(reference)}" placeholder="VN-…" required maxlength="103"></label><label>Shipbubble shipment ID<input name="shipmentId" placeholder="SB-…" required maxlength="103"></label><button>Verify and link shipment</button></form><p>Book with the saved measurements and customer’s delivery details first. The store order must be paid and its customer email must match the shipment recipient. Linking does not create a booking or take a payment.</p></section>
 <section><h2>Live connection</h2><p>Production key: ${s.keyConfigured?'saved':'missing or not a live key'}<br>Account check: ${escape(s.connection?.status||'not checked')}<br>${escape(s.connection?.error||'')}<br>Wallet funded: ${s.connection?.walletFunded===true?'yes':s.connection?.walletFunded===false?'no':'not verified'}<br>Pickup address: ${s.pickupReady?'saved':'missing'}<br>Automatic checkout courier rates: ${s.checkoutEnabled?'enabled':'not activated'}</p><form method="post"><input type="hidden" name="action" value="check"><button>Check Shipbubble live connection</button></form><p>This reads account status. It does not book or charge for shipping. Approved garment and packaging profiles determine checkout quotes when activated.</p></section>
 <section><h2>Live webhook</h2><p>Enter this in Shipbubble’s Live Webhook URL field:</p><code>${escape(endpoint)}</code><p>Last authenticated webhook: ${escape(s.lastWebhook?.receivedAt||'none received')}.</p><p>Linked shipments update the store’s dispatch and delivery status. Signature verification uses the saved production API key; sandbox events cannot update live orders.</p></section></main></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});
}
