import {adminAuthStateFromRequest} from './admin-auth';
import {rateLimit} from './rate-limit';
import {readWebhookBody} from './shipbubble-webhook';
import {packagingProfiles,productParcel,saveProductParcel,savePackaging,searchParcelProducts} from './parcel-profiles';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function shippingWeightsAdmin(request:Request){
 const auth=await adminAuthStateFromRequest(request);if(!auth.ok)return Response.json({error:auth.error},{status:auth.status});if(auth.role!=='owner')return new Response('Owner access required',{status:403});
 const url=new URL(request.url);let productId=url.searchParams.get('productId')||'',size=url.searchParams.get('size')||'',message='';
 if(request.method==='POST'){
  if(request.headers.get('origin')!==url.origin)return new Response('Open the owner page',{status:403});
  if(!await rateLimit(request,'shipping-weights',60,3600))return new Response('Please wait before saving again',{status:429});
  try{
   const f=new URLSearchParams(new TextDecoder().decode(await readWebhookBody(request))),revision=f.get('revision')||null;
   if(f.get('action')==='product'){
    productId=f.get('productId')||'';size=f.get('size')||'';
    await saveProductParcel(productId,size,{weightGrams:Number(f.get('weightGrams')),lengthCm:Number(f.get('lengthCm')),widthCm:Number(f.get('widthCm')),heightCm:Number(f.get('heightCm')),measured:f.get('measured')==='on'},revision);
   }else if(f.get('action')==='packaging'){
    const current=await packagingProfiles();if(current.revision!==revision)throw Error('Changed');
    const selected=current.data.find((p:{id:string})=>p.id===f.get('id'));if(!selected)throw Error('Missing preset');
    const box=Number(f.get('boxGrams')),wrap=Number(f.get('wrapGrams'));
    if(!Number.isInteger(box)||box<1||!Number.isInteger(wrap)||wrap<0)throw Error('Invalid weight');
    await savePackaging(current.data.map((p:{id:string})=>p.id===selected.id?{...p,tareGrams:box+wrap,boxGrams:box,wrapGrams:wrap,lengthCm:Number(f.get('lengthCm')),widthCm:Number(f.get('widthCm')),heightCm:Number(f.get('heightCm')),maxWeightGrams:Number(f.get('maxWeightGrams')),measured:f.get('measured')==='on'}:p),revision);
   }else return new Response('Unknown action',{status:400});
   message='Approved weights saved. New quotes use these values; older unpaid quotes must be refreshed.';
  }catch{message='Not saved. Check positive weights and dimensions. Reload before editing again if another tab changed this record.';}
 }else if(request.method!=='GET')return new Response('Method not allowed',{status:405});
 const q=(url.searchParams.get('q')||'').slice(0,100),page=Math.max(0,Math.min(1000,Number(url.searchParams.get('page'))||0));
 const [products,packaging]=await Promise.all([searchParcelProducts(q,Math.floor(page)),packagingProfiles()]);
 const item=productId&&size?await productParcel(productId,size):null;
 const input=(name:string,label:string,value:unknown,max=200,min=.1,step='any')=>`<label>${esc(label)}<input required type="number" name="${name}" value="${esc(value)}" min="${min}" max="${max}" step="${step}"></label>`;
 const dimensions=(p:{lengthCm:number;widthCm:number;heightCm:number})=>input('lengthCm','Length (cm)',p.lengthCm)+input('widthCm','Width (cm)',p.widthCm)+input('heightCm','Height (cm)',p.heightCm);
 return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Approved shipping weights | Vanta Noir</title><style>body{font:16px system-ui;background:#f2f4f1;color:#141414;margin:0;padding:24px}main{max-width:850px;margin:auto}section{background:white;border:1px solid #dbe1d7;border-radius:20px;padding:24px;margin:20px 0}button,.pill{display:inline-block;background:#c8ff65;color:#141414;border:0;border-radius:24px;padding:12px 18px;margin:4px;cursor:pointer;text-decoration:none}input{display:block;box-sizing:border-box;padding:12px;margin:8px 0 18px;width:100%;border:1px solid #aaa;border-radius:8px}input[type=checkbox]{display:inline;width:auto}input[type=hidden]{display:none}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:16px}p{line-height:1.5}a{color:#174400}</style><main><a href="/admin">Back to admin</a> · <a href="/api/admin/shipbubble">Order shipping</a><h1>Approved shipping weights</h1><p>These are your standard weights for live delivery quotes. Saving a change approves it for checkout. Physical measurements are optional to record separately.</p><p>Parcel weight = sum of item weights × quantities + one box + tissue/tape. Box dimensions and capacity must also fit. Existing orders keep their agreed charge.</p>${message?`<section role="status">${esc(message)}</section>`:''}<section><h2>Garment weights</h2><form method="get"><label>Find garment<input name="q" value="${esc(q)}" maxlength="100"></label><button>Search</button></form>${products.products.map(p=>`<p><strong>${esc(p.name)}</strong><br>${p.sizes.map(s=>`<a class="pill" href="?productId=${encodeURIComponent(p.id)}&size=${encodeURIComponent(s)}&q=${encodeURIComponent(q)}">${esc(s)}</a>`).join(' ')}</p>`).join('')}<p>${page>0?`<a href="?q=${encodeURIComponent(q)}&page=${page-1}">Previous</a> · `:''}Page ${page+1}${products.hasMore?` · <a href="?q=${encodeURIComponent(q)}&page=${page+1}">Next</a>`:''}</p></section>
 ${item?`<section><h2>${esc(item.name)} · ${esc(size)}</h2><form method="post"><input type="hidden" name="action" value="product"><input type="hidden" name="productId" value="${esc(productId)}"><input type="hidden" name="size" value="${esc(size)}"><input type="hidden" name="revision" value="${esc(item.revision||'')}"><div class="grid">${input('weightGrams','Approved item weight (grams)',item.parcel?.weightGrams,50000,1,'1')}${dimensions(item.parcel||{lengthCm:0,widthCm:0,heightCm:0})}</div><label><input type="checkbox" name="measured" ${item.parcel?.measured?'checked':''}> Physically weighed and measured</label><p>Exclude the outer box and tissue/tape. Existing standard weights include the garment, a planning allowance and tags/inner wrapping.</p><button>Save approved garment weight</button></form></section>`:''}
 <section><h2>Box weights and sizes</h2><p>Your saved standards apply to new quotes. You can change each preset here. Tissue/tape is added once per box.</p>${packaging.data.map((p:{id:string;name:string;tareGrams:number;boxGrams?:number;wrapGrams?:number;lengthCm:number;widthCm:number;heightCm:number;maxWeightGrams:number;measured:boolean})=>`<form method="post"><h3>${esc(p.name)}</h3><input type="hidden" name="action" value="packaging"><input type="hidden" name="id" value="${esc(p.id)}"><input type="hidden" name="revision" value="${esc(packaging.revision||'')}"><div class="grid">${input('boxGrams','Empty box (grams)',p.boxGrams??p.tareGrams-(p.wrapGrams??0),10000,1,'1')}${input('wrapGrams','Tissue/tape (grams)',p.wrapGrams??0,1000,0,'1')}${dimensions(p)}${input('maxWeightGrams','Maximum packed weight (grams)',p.maxWeightGrams,50000,1,'1')}</div><label><input type="checkbox" name="measured" ${p.measured?'checked':''}> Physically checked packaging</label><p>All weights in grams; 1,000 g = 1 kg.</p><button>Save approved box</button></form>`).join('')}</section></main></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});
}
