import { Hono } from 'hono';
import { cors } from 'hono/cors';
const app = new Hono();
app.use('/api/*', cors({ origin: (origin, c) => origin === c.env.STORE_ORIGIN ? origin : c.env.STORE_ORIGIN, allowMethods:['GET','POST','PATCH','DELETE','OPTIONS'], allowHeaders:['Content-Type','Authorization'] }));
app.get('/health', c => c.json({ok:true, service:'vanta-noir-api'}));
app.get('/api/products', async c => { const {results}=await c.env.DB.prepare(`SELECT p.*, COALESCE(SUM(v.stock),0) stock FROM products p LEFT JOIN variants v ON v.product_id=p.id WHERE p.status!='archived' GROUP BY p.id ORDER BY p.updated_at DESC`).all(); return c.json({products:results}); });
app.get('/api/products/:id/variants', async c => { const {results}=await c.env.DB.prepare('SELECT * FROM variants WHERE product_id=? ORDER BY colour,size').bind(c.req.param('id')).all(); return c.json({variants:results}); });
app.post('/api/products', async c => { const b=await c.req.json(); const id=crypto.randomUUID(); await c.env.DB.prepare(`INSERT INTO products(id,name,slug,description,price,category,status,featured) VALUES(?,?,?,?,?,?,?,?)`).bind(id,b.name,b.slug,b.description||'',b.price,b.category,b.status||'draft',b.featured?1:0).run(); return c.json({id},201); });
app.patch('/api/products/:id', async c => { const b=await c.req.json(); await c.env.DB.prepare(`UPDATE products SET name=COALESCE(?,name),description=COALESCE(?,description),price=COALESCE(?,price),category=COALESCE(?,category),status=COALESCE(?,status),featured=COALESCE(?,featured),updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(b.name??null,b.description??null,b.price??null,b.category??null,b.status??null,b.featured==null?null:(b.featured?1:0),c.req.param('id')).run(); return c.json({ok:true}); });
app.post('/api/variants', async c => { const b=await c.req.json(); const id=crypto.randomUUID(); await c.env.DB.prepare(`INSERT INTO variants(id,product_id,sku,colour,size,stock) VALUES(?,?,?,?,?,?)`).bind(id,b.product_id,b.sku,b.colour,b.size,b.stock||0).run(); return c.json({id},201); });
app.patch('/api/variants/:id/stock', async c => { const b=await c.req.json(); await c.env.DB.prepare('UPDATE variants SET stock=?, updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.stock,c.req.param('id')).run(); return c.json({ok:true}); });
app.get('/api/orders', async c => { const {results}=await c.env.DB.prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 100').all(); return c.json({orders:results}); });
app.patch('/api/orders/:id', async c => { const b=await c.req.json(); await c.env.DB.prepare('UPDATE orders SET status=COALESCE(?,status),tracking_number=COALESCE(?,tracking_number),updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.status??null,b.tracking_number??null,c.req.param('id')).run(); return c.json({ok:true}); });
app.post('/api/media/upload-url', async c => c.json({message:'R2 upload endpoint scaffolded; secure admin auth required before enabling direct uploads.'},501));
app.post('/api/paystack/webhook', async c => c.json({ok:true, message:'Webhook route reserved; signature verification must be configured before production.'}));
export default app;
